payload:
  - PROCESS-NAME,air.tv.douyu.android #斗鱼
  - PROCESS-NAME,cmccwm.mobilemusic #咪咕音乐
  - PROCESS-NAME,cn.kuwo.player #酷我音乐
  - PROCESS-NAME,com.achievo.vipshop #唯品会
  - PROCESS-NAME,com.autonavi.minimap #高德地图
  - PROCESS-NAME,com.baidu.appsearch #百度手机助手
  - PROCESS-NAME,com.baidu.haokan #好看视频
  - PROCESS-NAME,com.baidu.homework #作业帮
  - PROCESS-NAME,com.baidu.input #百度输入法
  - PROCESS-NAME,com.baidu.netdisk #百度网盘
  - PROCESS-NAME,com.baidu.searchbox #百度
  - PROCESS-NAME,com.chinamworld.main #中国建设银行
  - PROCESS-NAME,com.cleanmaster.mguard_cn #猎豹清理大师
  - PROCESS-NAME,com.dianping.v1 #大众点评
  - PROCESS-NAME,com.duowan.kiwi #虎牙直播
  - PROCESS-NAME,com.eg.android.AlipayGphone #支付宝
  - PROCESS-NAME,com.handsgo.jiakao.android #驾考宝典
  - PROCESS-NAME,com.huluxia.gametools #葫芦侠
  - PROCESS-NAME,com.hunantv.imgo.activity #芒果TV
  - PROCESS-NAME,com.icbc #中国工商银行
  - PROCESS-NAME,com.immomo.momo #MOMO陌陌
  - PROCESS-NAME,com.jifen.qukan #趣头条
  - PROCESS-NAME,com.jingdong.app.mall #京东
  - PROCESS-NAME,com.jxedt #驾校一点通
  - PROCESS-NAME,com.kuaishou.nebula #快手极速版
  - PROCESS-NAME,com.kugou.android #酷狗音乐
  - PROCESS-NAME,com.meitu.meiyancamera #美颜相机
  - PROCESS-NAME,com.moji.mjweather #墨迹天气
  - PROCESS-NAME,com.mt.mtxx.mtxx #美图秀秀-视频/图片/Live人像精修工具
  - PROCESS-NAME,com.netease.cloudmusic #网易云音乐
  - PROCESS-NAME,com.netease.newsreader.activity #网易新闻
  - PROCESS-NAME,com.pplive.androidphone #PP视频
  - PROCESS-NAME,com.qihoo.appstore #360手机助手
  - PROCESS-NAME,com.qihoo360.mobilesafe #360手机卫士
  - PROCESS-NAME,com.qiyi.video #爱奇艺
  - PROCESS-NAME,com.qq.reader #QQ阅读
  - PROCESS-NAME,com.Qunar #去哪儿旅行
  - PROCESS-NAME,com.qzone #QQ空间
  - PROCESS-NAME,com.sankuai.meituan #美团
  - PROCESS-NAME,com.sdu.didi.psnger #滴滴出行
  - PROCESS-NAME,com.shoujiduoduo.ringtone #铃声多多
  - PROCESS-NAME,com.sina.weibo #微博
  - PROCESS-NAME,com.sinovatech.unicom.ui #中国联通
  - PROCESS-NAME,com.smile.gifmaker #快手
  - PROCESS-NAME,com.snda.wifilocating #WiFi万能钥匙
  - PROCESS-NAME,com.sohu.inputmethod.sogou #搜狗输入法
  - PROCESS-NAME,com.sohu.sohuvideo #搜狐视频
  - PROCESS-NAME,com.ss.android.article.lite #今日头条极速版
  - PROCESS-NAME,com.ss.android.article.news #今日头条
  - PROCESS-NAME,com.ss.android.article.video #西瓜视频
  - PROCESS-NAME,com.ss.android.ugc.aweme #抖音
  - PROCESS-NAME,com.ss.android.ugc.live #抖音火山版
  - PROCESS-NAME,com.storm.smart #暴风影音
  - PROCESS-NAME,com.taobao.idlefish #闲鱼
  - PROCESS-NAME,com.tencent.androidqqmail #QQ邮箱
  - PROCESS-NAME,com.tencent.hunyuan.app.chat #元宝-腾讯旗下AI助手
  - PROCESS-NAME,com.tencent.karaoke #全民K歌
  - PROCESS-NAME,com.tencent.mobileqq #QQ
  - PROCESS-NAME,com.tencent.mtt #QQ浏览器
  - PROCESS-NAME,com.tencent.news #腾讯新闻
  - PROCESS-NAME,com.tencent.qqlive #腾讯视频
  - PROCESS-NAME,com.tencent.qqmusic #QQ音乐
  - PROCESS-NAME,com.tencent.qqpimsecure #腾讯手机管家
  - PROCESS-NAME,com.tencent.weishi #腾讯微视
  - PROCESS-NAME,com.tmall.wireless #天猫
  - PROCESS-NAME,com.UCMobile #UC浏览器
  - PROCESS-NAME,com.wuba #58同城
  - PROCESS-NAME,com.ximalaya.ting.android #喜马拉雅
  - PROCESS-NAME,com.xunmeng.pinduoduo #拼多多
  - PROCESS-NAME,com.youku.phone #优酷视频
  - PROCESS-NAME,ctrip.android.view #携程旅行
  - PROCESS-NAME,tv.danmaku.bili #哔哩哔哩
