{% macro main(rule) %}
PROCESS-NAME,air.tv.douyu.android,{{ rule }} # 斗鱼
PROCESS-NAME,android.zhibo8,{{ rule }} # 直播吧
PROCESS-NAME,bubei.tingshu,{{ rule }} # 懒人听书
PROCESS-NAME,cmb.pb,{{ rule }} # 招商银行
PROCESS-NAME,cmccwm.mobilemusic,{{ rule }} # 咪咕音乐
PROCESS-NAME,cn.buding.martin,{{ rule }} # 微车
PROCESS-NAME,cn.cntv,{{ rule }} # 央视影音
PROCESS-NAME,cn.colorv,{{ rule }} # 彩视
PROCESS-NAME,cn.com.cmbc.newmbank,{{ rule }} # 民生银行
PROCESS-NAME,cn.com.spdb.mobilebank.per,{{ rule }} # 浦发手机银行
PROCESS-NAME,cn.com.tyfon.sun.xhrrac9,{{ rule }} # 泰丰艺术商城
PROCESS-NAME,cn.eclicks.drivingtest,{{ rule }} # 车轮驾考通
PROCESS-NAME,cn.eclicks.wzsearch,{{ rule }} # 车轮
PROCESS-NAME,cn.egame.terminal.cloud5g,{{ rule }} # 天翼云游戏
PROCESS-NAME,cn.emagsoftware.gamehall,{{ rule }} # 咪咕快游
PROCESS-NAME,cn.etouch.ecalendar,{{ rule }} # 中华万年历
PROCESS-NAME,cn.gov.tax.its,{{ rule }} # 个人所得税
PROCESS-NAME,cn.ishansong,{{ rule }} # 闪送
PROCESS-NAME,cn.knet.eqxiu,{{ rule }} # 易企秀
PROCESS-NAME,cn.kuwo.player,{{ rule }} # 酷我音乐
PROCESS-NAME,cn.ledongli.ldl,{{ rule }} # 乐动力
PROCESS-NAME,cn.mucang.android.drivingsimulator,{{ rule }} # 驾考宝典科目一
PROCESS-NAME,cn.mucang.android.jkxt,{{ rule }} # 驾考宝典多语言版
PROCESS-NAME,cn.mucang.android.parallelvehicle,{{ rule }} # 平行之家
PROCESS-NAME,cn.mucang.android.qichetoutiao,{{ rule }} # 车友头条
PROCESS-NAME,cn.net.iwave.zoo,{{ rule }} # 元气开开
PROCESS-NAME,cn.ninegame.gamemanager,{{ rule }} # 九游
PROCESS-NAME,cn.opda.a.phonoalbumshoushou,{{ rule }} # 百度手机卫士
PROCESS-NAME,cn.soulapp.android,{{ rule }} # Soul
PROCESS-NAME,cn.xiaochuankeji.tieba,{{ rule }} # 最右
PROCESS-NAME,cn.xuexi.android,{{ rule }} # 学习强国
PROCESS-NAME,cn.youth.news,{{ rule }} # 中青看点
PROCESS-NAME,com.A17zuoye.mobile.homework,{{ rule }} # 一起作业
PROCESS-NAME,com.acadsoc.learn,{{ rule }} # 阿卡索口语秀
PROCESS-NAME,com.acadsoc.talkshow,{{ rule }} # 阿卡索英语
PROCESS-NAME,com.achievo.vipshop,{{ rule }} # 唯品会
PROCESS-NAME,com.adobe.reader,{{ rule }} # PDF阅读器 Adobe reader
PROCESS-NAME,com.aikan,{{ rule }} # 免费小说大全
PROCESS-NAME,com.airuniversa.control,{{ rule }} # 万能空调遥控器
PROCESS-NAME,com.alibaba.android.rimet,{{ rule }} # 钉钉
PROCESS-NAME,com.alibaba.wireless,{{ rule }} # 阿里巴巴
PROCESS-NAME,com.ancient.calendar,{{ rule }} # 中农老黄历
PROCESS-NAME,com.android.bankabc,{{ rule }} # 农行掌上银行
PROCESS-NAME,com.android.dazhihui,{{ rule }} # 大智慧
PROCESS-NAME,com.android.haitong,{{ rule }} # 国泰海通通财
PROCESS-NAME,com.android.icredit,{{ rule }} # 企查查
PROCESS-NAME,com.androidesk.livewallpaper,{{ rule }} # 安卓动态壁纸
PROCESS-NAME,com.anjuke.android.app,{{ rule }} # 安居客
PROCESS-NAME,com.antutu.ABenchMark,{{ rule }} # 安兔兔评测
PROCESS-NAME,com.anwei.meivliao,{{ rule }} # 美V聊天
PROCESS-NAME,com.appsys.goodname,{{ rule }} # 易经起名取名
PROCESS-NAME,com.artifact.hypnosis,{{ rule }} # 催眠神器
PROCESS-NAME,com.babytree.apps.pregnancy,{{ rule }} # 宝宝树孕育
PROCESS-NAME,com.baidu.appsearch,{{ rule }} # 百度手机助手
PROCESS-NAME,com.baidu.BaiduMap,{{ rule }} # 百度地图
PROCESS-NAME,com.baidu.baidutranslate,{{ rule }} # 百度翻译
PROCESS-NAME,com.baidu.browser.apps,{{ rule }} # 百度浏览器
PROCESS-NAME,com.baidu.haokan,{{ rule }} # 好看视频
PROCESS-NAME,com.baidu.homework,{{ rule }} # 作业帮
PROCESS-NAME,com.baidu.iknow,{{ rule }} # 百度知道
PROCESS-NAME,com.baidu.input,{{ rule }} # 百度输入法
PROCESS-NAME,com.baidu.netdisk,{{ rule }} # 百度网盘
PROCESS-NAME,com.baidu.searchbox,{{ rule }} # 百度
PROCESS-NAME,com.baidu.searchbox.lite,{{ rule }} # 百度极速版
PROCESS-NAME,com.baidu.tieba,{{ rule }} # 百度贴吧
PROCESS-NAME,com.baidu.video,{{ rule }} # 百搜视频
PROCESS-NAME,com.baidu.wenku,{{ rule }} # 百度文库
PROCESS-NAME,com.baidu.yuedu,{{ rule }} # 百度阅读
PROCESS-NAME,com.bankcomm.Bankcomm,{{ rule }} # 交通银行
PROCESS-NAME,com.baojiazhijia.qichebaojia,{{ rule }} # 买车宝典
PROCESS-NAME,com.battery.guard,{{ rule }} # 电池卫士
PROCESS-NAME,com.benqu.wuta,{{ rule }} # 无他相机
PROCESS-NAME,com.bertadata.qxb,{{ rule }} # 启信宝
PROCESS-NAME,com.black.unique,{{ rule }} # 全球购骑士特权
PROCESS-NAME,com.bokecc.dance,{{ rule }} # 糖豆
PROCESS-NAME,com.browser2345,{{ rule }} # 2345浏览器
PROCESS-NAME,com.budejie.www,{{ rule }} # 百思漂流瓶
PROCESS-NAME,com.bullet.subway,{{ rule }} # 掌上地铁
PROCESS-NAME,com.c2vl.kgamebox,{{ rule }} # 狼人杀
PROCESS-NAME,com.cainiao.wireless,{{ rule }} # 菜鸟
PROCESS-NAME,com.cairh.khapp.dbzq.xmlqdl,{{ rule }} # 东北证券股票开户
PROCESS-NAME,com.campmobile.snowcamera,{{ rule }} # B612咔叽
PROCESS-NAME,com.cctv.yangshipin.app.androidp,{{ rule }} # 央视频
PROCESS-NAME,com.cffex.htqh,{{ rule }} # 海通期货期海通行
PROCESS-NAME,com.changba,{{ rule }} # 唱吧
PROCESS-NAME,com.chaozh.iReaderFree,{{ rule }} # 掌阅
PROCESS-NAME,com.chinalife.ebz,{{ rule }} # 中国人寿寿险
PROCESS-NAME,com.chinamworld.bocmbci,{{ rule }} # 中国银行
PROCESS-NAME,com.chinamworld.main,{{ rule }} # 中国建设银行
PROCESS-NAME,com.chinatelecom.bestpayclient,{{ rule }} # 翼支付
PROCESS-NAME,com.ci123.pregnancywap,{{ rule }} # 妈妈社区
PROCESS-NAME,com.citiccard.mobilebank,{{ rule }} # 中信银行动卡空间
PROCESS-NAME,com.cleanmaster.mguard_cn,{{ rule }} # 猎豹清理大师
PROCESS-NAME,com.cmbchina.ccd.pluto.cmbActivity,{{ rule }} # 掌上生活
PROCESS-NAME,com.cmcc.cmvideo,{{ rule }} # 咪咕视频
PROCESS-NAME,com.cmi.jegotrip,{{ rule }} # 无忧行
PROCESS-NAME,com.codoon.gps,{{ rule }} # 咕咚
PROCESS-NAME,com.comic.manhuatai,{{ rule }} # 漫画台
PROCESS-NAME,com.cooker.food,{{ rule }} # 美食
PROCESS-NAME,com.cs_credit_bank,{{ rule }} # 发现精彩
PROCESS-NAME,com.ct.client,{{ rule }} # 中国电信
PROCESS-NAME,com.cubic.autohome,{{ rule }} # 汽车之家
PROCESS-NAME,com.cubic.choosecar,{{ rule }} # 汽车报价
PROCESS-NAME,com.cyp.fm,{{ rule }} # 文件解压管家
PROCESS-NAME,com.dangdang.buy2,{{ rule }} # 当当
PROCESS-NAME,com.dbscgeneral,{{ rule }} # 东北证券融e通
PROCESS-NAME,com.ddyhq.youhuiquan,{{ rule }} # 优惠券
PROCESS-NAME,com.dewmobile.kuaiya,{{ rule }} # 快牙
PROCESS-NAME,com.didago.travel,{{ rule }} # 滴答滴出行
PROCESS-NAME,com.didapinche.booking,{{ rule }} # 嘀嗒出行
PROCESS-NAME,com.dingtai.wxhn.activity,{{ rule }} # 新湖南
PROCESS-NAME,com.dingYZ.dingyzwater,{{ rule }} # 微脉水印相机
PROCESS-NAME,com.douban.frodo,{{ rule }} # 豆瓣
PROCESS-NAME,com.douguo.recipe,{{ rule }} # 豆果美食
PROCESS-NAME,com.doumi.jianzhi,{{ rule }} # 斗米
PROCESS-NAME,com.dp.android.elong,{{ rule }} # 艺龙旅行
PROCESS-NAME,com.dragon.read,{{ rule }} # 番茄免费小说
PROCESS-NAME,com.dragon.ringtone,{{ rule }} # 东方铃声
PROCESS-NAME,com.duokan.phone.remotecontroller,{{ rule }} # 万能遥控
PROCESS-NAME,com.duokan.reader,{{ rule }} # 多看
PROCESS-NAME,com.duowan.kiwi,{{ rule }} # 虎牙直播
PROCESS-NAME,com.dw.btime,{{ rule }} # 亲宝宝
PROCESS-NAME,com.dxbattery.doctor,{{ rule }} # 大象电池医生
PROCESS-NAME,com.dzqh.online11,{{ rule }} # 东方证券期货
PROCESS-NAME,com.dzwww.sd.android,{{ rule }} # 海报新闻
PROCESS-NAME,com.eastmoney.android.berlin,{{ rule }} # 东方财富
PROCESS-NAME,com.easy.subway,{{ rule }} # 地铁查询宝
PROCESS-NAME,com.easy.wallpaper,{{ rule }} # 番茄动态壁纸
PROCESS-NAME,com.ebank.creditcard,{{ rule }} # 阳光惠生活
PROCESS-NAME,com.ecitic.bank.mobile,{{ rule }} # 中信银行
PROCESS-NAME,com.eg.android.AlipayGphone,{{ rule }} # 支付宝
PROCESS-NAME,com.enqualcomm.kids.cyp,{{ rule }} # 西瓜皮
PROCESS-NAME,com.evideo.MobileKTV,{{ rule }} # K米
PROCESS-NAME,com.excelliance.dualaid,{{ rule }} # 双开助手微分身版
PROCESS-NAME,com.ezg.camper,{{ rule }} # 约你游
PROCESS-NAME,com.fanli.android.apps,{{ rule }} # 返利
PROCESS-NAME,com.fanlitaolianmengw,{{ rule }} # 返利淘联盟
PROCESS-NAME,com.fc.management,{{ rule }} # 文件编辑器
PROCESS-NAME,com.fenbi.android.gaozhong,{{ rule }} # 猿题库
PROCESS-NAME,com.fenbi.android.solar,{{ rule }} # 小猿搜题
PROCESS-NAME,com.fenqile.fenqile,{{ rule }} # 分期乐
PROCESS-NAME,com.flightmanager.view,{{ rule }} # 航班管家
PROCESS-NAME,com.foundao.xinhua_android,{{ rule }} # 新华网
PROCESS-NAME,com.funshion.video.mobile,{{ rule }} # 风行视频
PROCESS-NAME,com.ganji.android,{{ rule }} # 赶集招聘
PROCESS-NAME,com.ganji.android.haoche_c,{{ rule }} # 瓜子二手车
PROCESS-NAME,com.goodtech.tq,{{ rule }} # 更云天气预报
PROCESS-NAME,com.gorgeous.lite,{{ rule }} # 轻颜
PROCESS-NAME,com.gotokeep.keep,{{ rule }} # Keep - AI 运动教练
PROCESS-NAME,com.greenpoint.android.mc10086.activity,{{ rule }} # 中国移动
PROCESS-NAME,com.gstarmc.android,{{ rule }} # CAD看图王
PROCESS-NAME,com.gtgj.view,{{ rule }} # 高铁管家
PROCESS-NAME,com.gwsoft.imusic.controller,{{ rule }} # 爱音乐
PROCESS-NAME,com.haixiu.ui,{{ rule }} # 嗨秀直播
PROCESS-NAME,com.handsgo.jiakao.android,{{ rule }} # 驾考宝典
PROCESS-NAME,com.happyteam.dubbingshow,{{ rule }} # 配音秀
PROCESS-NAME,com.hcc.app,{{ rule }} # 京东消费金融
PROCESS-NAME,com.helplove.shbf,{{ rule }} # 社会扶贫
PROCESS-NAME,com.hexin.plat.android,{{ rule }} # 同花顺
PROCESS-NAME,com.hexin.plat.android.CaitongSecurity,{{ rule }} # 财通证券
PROCESS-NAME,com.hexin.plat.android.ZhongyuanSecurity,{{ rule }} # 中原证券
PROCESS-NAME,com.hicorenational.antifraud,{{ rule }} # 国家反诈中心
PROCESS-NAME,com.hipu.yidian,{{ rule }} # 一点资讯
PROCESS-NAME,com.homelink.android,{{ rule }} # 链家
PROCESS-NAME,com.hp.android.printservice,{{ rule }} # HP 打印服务插件
PROCESS-NAME,com.hpplay.happycast,{{ rule }} # 乐播投屏
PROCESS-NAME,com.huajiao,{{ rule }} # 花椒直播
PROCESS-NAME,com.huati,{{ rule }} # 葫芦侠3楼
PROCESS-NAME,com.huawei.fastapp,{{ rule }} # 快应用中心
PROCESS-NAME,com.huawei.hwid,{{ rule }} # HMS Core
PROCESS-NAME,com.huawei.smarthome,{{ rule }} # 智慧生活
PROCESS-NAME,com.huluxia.gametools,{{ rule }} # 葫芦侠
PROCESS-NAME,com.hundsun.stockwinner.cyqh,{{ rule }} # 创元期货
PROCESS-NAME,com.hundsun.stockwinner.yhqh,{{ rule }} # 银河期货专业版
PROCESS-NAME,com.huodao.hdphone,{{ rule }} # 找靓机
PROCESS-NAME,com.hupu.shihuo,{{ rule }} # 识货
PROCESS-NAME,com.i61.draw.live,{{ rule }} # 画啦啦美术课堂
PROCESS-NAME,com.ibox.flashlight,{{ rule }} # 多多手电筒
PROCESS-NAME,com.icbc,{{ rule }} # 中国工商银行
PROCESS-NAME,com.icbc.im,{{ rule }} # 工银融e联
PROCESS-NAME,com.icoolme.android.weather,{{ rule }} # 最美天气
PROCESS-NAME,com.ifeng.news2,{{ rule }} # 凤凰新闻
PROCESS-NAME,com.ifeng.newvideo,{{ rule }} # 凤凰视频
PROCESS-NAME,com.iflytek.elpmobile.smartlearning,{{ rule }} # 智学网
PROCESS-NAME,com.iflytek.ringdiyclient,{{ rule }} # 酷音铃声
PROCESS-NAME,com.ifreetalk.ftalk,{{ rule }} # 派派
PROCESS-NAME,com.imaginer.yunji,{{ rule }} # 云集
PROCESS-NAME,com.immomo.momo,{{ rule }} # MOMO陌陌
PROCESS-NAME,com.imusic.iting,{{ rule }} # 爱听
PROCESS-NAME,com.intsig.BizCardReader,{{ rule }} # 名片全能王
PROCESS-NAME,com.intsig.camscanner,{{ rule }} # 扫描全能王
PROCESS-NAME,com.iqilu.ksd,{{ rule }} # 闪电新闻
PROCESS-NAME,com.iqiyi.qixiu,{{ rule }} # 奇秀
PROCESS-NAME,com.ishowedu.peiyin,{{ rule }} # 英语趣配音
PROCESS-NAME,com.jd.jrapp,{{ rule }} # 京东金融
PROCESS-NAME,com.jf.lkrj,{{ rule }} # 花生日记
PROCESS-NAME,com.jifen.qukan,{{ rule }} # 趣头条
PROCESS-NAME,com.jingdong.app.mall,{{ rule }} # 京东
PROCESS-NAME,com.jingyao.easybike,{{ rule }} # 哈啰
PROCESS-NAME,com.jinxin.namibox,{{ rule }} # 纳米盒
PROCESS-NAME,com.jiongji.andriod.card,{{ rule }} # 百词斩
PROCESS-NAME,com.jiuyan.infashion,{{ rule }} # in
PROCESS-NAME,com.job.android,{{ rule }} # 前程无忧51Job
PROCESS-NAME,com.join.android.app.mgsim.wufun,{{ rule }} # 悟饭游戏厅
PROCESS-NAME,com.jxedt,{{ rule }} # 驾校一点通
PROCESS-NAME,com.jyyx.fuli,{{ rule }} # 九妖游戏
PROCESS-NAME,com.jzyd.coupon,{{ rule }} # 省钱快报
PROCESS-NAME,com.jzzs.ParentsHelper,{{ rule }} # 安全教育平台
PROCESS-NAME,com.kangluoer.tomato,{{ rule }} # 知富美聊
PROCESS-NAME,com.king.weather,{{ rule }} # 天气王
PROCESS-NAME,com.kingsoft,{{ rule }} # 金山词霸
PROCESS-NAME,com.kmxs.reader,{{ rule }} # 七猫免费小说
PROCESS-NAME,com.knowbox.rc.student.pk,{{ rule }} # 小盒学习
PROCESS-NAME,com.koudai.recorder,{{ rule }} # 手机录音管家
PROCESS-NAME,com.koudai.weidian.buyer,{{ rule }} # 微店
PROCESS-NAME,com.koudai.weishop,{{ rule }} # 微店店长版
PROCESS-NAME,com.kuaiduizuoye.scan,{{ rule }} # 快对AI
PROCESS-NAME,com.kuaikan.comic,{{ rule }} # 快看漫画
PROCESS-NAME,com.kuaishou.nebula,{{ rule }} # 快手极速版
PROCESS-NAME,com.kuangxiangciweimao.novel,{{ rule }} # 刺猬猫阅读
PROCESS-NAME,com.kugou.android,{{ rule }} # 酷狗音乐
PROCESS-NAME,com.kugou.android.ktvapp,{{ rule }} # 酷狗唱唱
PROCESS-NAME,com.kugou.android.ringtone,{{ rule }} # 酷狗铃声
PROCESS-NAME,com.kugou.fanxing,{{ rule }} # 酷狗直播
PROCESS-NAME,com.kwai.videoeditor,{{ rule }} # 快影
PROCESS-NAME,com.lalamove.huolala.client,{{ rule }} # 货拉拉
PROCESS-NAME,com.lanjingren.ivwen,{{ rule }} # 美篇
PROCESS-NAME,com.le123.ysdq,{{ rule }} # 影视大全
PROCESS-NAME,com.lechuan.midunovel,{{ rule }} # 米读小说
PROCESS-NAME,com.lehai.ui,{{ rule }} # 乐嗨直播
PROCESS-NAME,com.leixun.taofen8,{{ rule }} # 淘粉吧
PROCESS-NAME,com.lemon.faceu,{{ rule }} # Faceu激萌
PROCESS-NAME,com.lemon.lv,{{ rule }} # 剪映
PROCESS-NAME,com.lenovo.leos.cloud.sync,{{ rule }} # 联想乐云
PROCESS-NAME,com.lianjia.beike,{{ rule }} # 贝壳找房
PROCESS-NAME,com.lingan.seeyou,{{ rule }} # 美柚
PROCESS-NAME,com.lion.market,{{ rule }} # 虫虫助手
PROCESS-NAME,com.liulishuo.engzo,{{ rule }} # 流利说-英语
PROCESS-NAME,com.lltskb.lltskb,{{ rule }} # 路路通
PROCESS-NAME,com.lphtsccft,{{ rule }} # 涨乐财富通
PROCESS-NAME,com.lu.ashionweather,{{ rule }} # 天气预报
PROCESS-NAME,com.lucky.luckyclient,{{ rule }} # 瑞幸咖啡
PROCESS-NAME,com.lvshiguan.app,{{ rule }} # 律师馆法律咨询
PROCESS-NAME,com.m4399.gamecenter,{{ rule }} # 4399游戏盒
PROCESS-NAME,com.maihan.tredian,{{ rule }} # 淘最热点
PROCESS-NAME,com.mampod.ergedd,{{ rule }} # 儿歌点点
PROCESS-NAME,com.market2345,{{ rule }} # 2345手机助手
PROCESS-NAME,com.marryu,{{ rule }} # MarryU相亲交友
PROCESS-NAME,com.master.camera,{{ rule }} # 拍照大咖
PROCESS-NAME,com.master.qrcode,{{ rule }} # 闪电扫码大师
PROCESS-NAME,com.McDullpalm.bus,{{ rule }} # 麦兜掌上公交
PROCESS-NAME,com.meelive.ingkee,{{ rule }} # 映客直播
PROCESS-NAME,com.meitu.meipaimv,{{ rule }} # 美拍
PROCESS-NAME,com.meitu.meiyancamera,{{ rule }} # 美颜相机-AI换装
PROCESS-NAME,com.meitu.wheecam,{{ rule }} # 潮自拍
PROCESS-NAME,com.meta.box,{{ rule }} # 233乐园
PROCESS-NAME,com.mfw.roadbook,{{ rule }} # 马蜂窝
PROCESS-NAME,com.mianfeia.book,{{ rule }} # 爱看书免费小说
PROCESS-NAME,com.mianfeizs.book,{{ rule }} # 免费追书
PROCESS-NAME,com.MobileTicket,{{ rule }} # 铁路12306
PROCESS-NAME,com.mogujie,{{ rule }} # 蘑菇街
PROCESS-NAME,com.moji.mjweather,{{ rule }} # 墨迹天气
PROCESS-NAME,com.monarch.memory,{{ rule }} # 内存清理君
PROCESS-NAME,com.mt.mtxx.mtxx,{{ rule }} # 美图秀秀
PROCESS-NAME,com.mygolbs.mybus,{{ rule }} # 掌上公交
PROCESS-NAME,com.mymoney,{{ rule }} # 随手记
PROCESS-NAME,com.mymoney.sms,{{ rule }} # 卡牛信用管家
PROCESS-NAME,com.myzaker.ZAKER_Phone,{{ rule }} # ZAKER
PROCESS-NAME,com.nanyibang.nomi,{{ rule }} # 男衣邦穿衣搭配
PROCESS-NAME,com.nanyibang.rm,{{ rule }} # 穿衣有品
PROCESS-NAME,com.NationalPhotograpy.weishoot,{{ rule }} # 微摄
PROCESS-NAME,com.nd.android.pandahome2,{{ rule }} # 91桌面
PROCESS-NAME,com.netease.cloudmusic,{{ rule }} # 网易云音乐
PROCESS-NAME,com.netease.mail,{{ rule }} # 网易邮箱大师
PROCESS-NAME,com.netease.newsreader.activity,{{ rule }} # 网易新闻
PROCESS-NAME,com.netease.uu,{{ rule }} # UU加速器
PROCESS-NAME,com.nfdaily.nfplus,{{ rule }} # 南方Plus
PROCESS-NAME,com.nice.main,{{ rule }} # nice
PROCESS-NAME,com.ninexiu.sixninexiu,{{ rule }} # 九秀直播
PROCESS-NAME,com.ophone.reader.ui,{{ rule }} # 咪咕阅读
PROCESS-NAME,com.p1.mobile.putong,{{ rule }} # 探探
PROCESS-NAME,com.paem,{{ rule }} # 平安融易
PROCESS-NAME,com.phoenix.read,{{ rule }} # 红果免费短剧
PROCESS-NAME,com.pingan.carowner,{{ rule }} # 平安好车主
PROCESS-NAME,com.pingan.lifeinsurance,{{ rule }} # 平安金管家
PROCESS-NAME,com.pingan.paces.ccms,{{ rule }} # 平安口袋银行
PROCESS-NAME,com.ppdai.loan,{{ rule }} # 拍拍贷借款
PROCESS-NAME,com.pplive.androidphone,{{ rule }} # PP视频
PROCESS-NAME,com.private.safe,{{ rule }} # 私密保险箱
PROCESS-NAME,com.qclianai.com,{{ rule }} # 全城恋爱
PROCESS-NAME,com.qidian.QDReader,{{ rule }} # 起点读书
PROCESS-NAME,com.qihoo.appstore,{{ rule }} # 360手机助手
PROCESS-NAME,com.qihoo.browser,{{ rule }} # 360浏览器
PROCESS-NAME,com.qihoo.loan,{{ rule }} # 奇富借条
PROCESS-NAME,com.qihoo.magic,{{ rule }} # 分身大师
PROCESS-NAME,com.qihoo360.mobilesafe,{{ rule }} # 360手机卫士
PROCESS-NAME,com.qihuo.changjiang,{{ rule }} # 长江期货开户交易
PROCESS-NAME,com.qihuo.yinhe,{{ rule }} # 银河期货开户交易
PROCESS-NAME,com.qiyi.video,{{ rule }} # 爱奇艺
PROCESS-NAME,com.qiyi.video.pad,{{ rule }} # 爱奇艺PAD
PROCESS-NAME,com.qiyi.video.reader,{{ rule }} # 爱奇艺小说
PROCESS-NAME,com.qq.ac.android,{{ rule }} # 腾讯动漫
PROCESS-NAME,com.qq.qcloud,{{ rule }} # 腾讯微云
PROCESS-NAME,com.qq.reader,{{ rule }} # QQ阅读
PROCESS-NAME,com.quark.browser,{{ rule }} # 夸克
PROCESS-NAME,com.Qunar,{{ rule }} # 去哪儿旅行
PROCESS-NAME,com.qzone,{{ rule }} # QQ空间
PROCESS-NAME,com.renren.mobile.android,{{ rule }} # 人人直播
PROCESS-NAME,com.renrendai.haohuan,{{ rule }} # 好分期
PROCESS-NAME,com.rong360.app,{{ rule }} # 融360
PROCESS-NAME,com.samoyed.credit,{{ rule }} # 省呗
PROCESS-NAME,com.sankuai.meituan.takeoutnew,{{ rule }} # 美团外卖
PROCESS-NAME,com.sankuai.movie,{{ rule }} # 猫眼
PROCESS-NAME,com.sanmu.liaoliaoba,{{ rule }} # 聊聊吧
PROCESS-NAME,com.screeclibinvoke,{{ rule }} # 录屏大师
PROCESS-NAME,com.sdu.didi.gsui,{{ rule }} # 滴滴车主
PROCESS-NAME,com.sdu.didi.psnger,{{ rule }} # 滴滴出行
PROCESS-NAME,com.sec.android.app.shealth,{{ rule }} # 三星健康
PROCESS-NAME,com.seebaby,{{ rule }} # 掌通家园
PROCESS-NAME,com.seewo.easicare.pro,{{ rule }} # 班级优化大师
PROCESS-NAME,com.sf.activity,{{ rule }} # 顺丰速运
PROCESS-NAME,com.shiyue.fensigou,{{ rule }} # 粉丝福利购
PROCESS-NAME,com.shizhuang.duapp,{{ rule }} # 得物
PROCESS-NAME,com.shoujiduoduo.ringtone,{{ rule }} # 铃声多多
PROCESS-NAME,com.shoujiduoduo.wallpaper,{{ rule }} # 壁纸多多
PROCESS-NAME,com.showself.ui,{{ rule }} # 秀色直播
PROCESS-NAME,com.shuhekeji,{{ rule }} # 还呗
PROCESS-NAME,com.shunlian.app,{{ rule }} # 顺联动力
PROCESS-NAME,com.shuqi.controller,{{ rule }} # 书旗小说
PROCESS-NAME,com.shusheng.JoJoRead,{{ rule }} # 叫叫
PROCESS-NAME,com.sina.news,{{ rule }} # 新浪新闻
PROCESS-NAME,com.sina.weibo,{{ rule }} # 微博
PROCESS-NAME,com.sina.weibog3,{{ rule }} # 新浪微博4G版
PROCESS-NAME,com.sina.weibolite,{{ rule }} # 微博极速版
PROCESS-NAME,com.sinovatech.unicom.ui,{{ rule }} # 中国联通
PROCESS-NAME,com.sinyee.babybus.recommendapp,{{ rule }} # 宝宝巴士
PROCESS-NAME,com.sinyee.babybus.shopping,{{ rule }} # 宝宝超市
PROCESS-NAME,com.sinyee.babybus.talk2kiki,{{ rule }} # 宝宝巴士奇妙屋
PROCESS-NAME,com.sjsj.clockapp.clockmaster,{{ rule }} # 即刻闹钟
PROCESS-NAME,com.skyplatanus.crucio,{{ rule }} # 快点阅读
PROCESS-NAME,com.smile.gifmaker,{{ rule }} # 快手
PROCESS-NAME,com.snda.lantern.wifilocating,{{ rule }} # WiFi万能钥匙极速版
PROCESS-NAME,com.snda.wifilocating,{{ rule }} # WiFi万能钥匙
PROCESS-NAME,com.soft.blued,{{ rule }} # Blued
PROCESS-NAME,com.sohu.infonews,{{ rule }} # 搜狐资讯
PROCESS-NAME,com.sohu.inputmethod.sogou,{{ rule }} # 搜狗输入法
PROCESS-NAME,com.sohu.newsclient,{{ rule }} # 搜狐新闻
PROCESS-NAME,com.sohu.sohuvideo,{{ rule }} # 搜狐视频
PROCESS-NAME,com.speed.master,{{ rule }} # 网络测速大师
PROCESS-NAME,com.splingsheng.ringtone,{{ rule }} # 视频铃声来电秀
PROCESS-NAME,com.ss.android.article.lite,{{ rule }} # 今日头条极速版
PROCESS-NAME,com.ss.android.article.news,{{ rule }} # 今日头条
PROCESS-NAME,com.ss.android.article.video,{{ rule }} # 西瓜视频
PROCESS-NAME,com.ss.android.auto,{{ rule }} # 懂车帝
PROCESS-NAME,com.ss.android.ugc.aweme,{{ rule }} # 抖音
PROCESS-NAME,com.ss.android.ugc.aweme.lite,{{ rule }} # 抖音极速版
PROCESS-NAME,com.ss.android.ugc.live,{{ rule }} # 抖音火山版
PROCESS-NAME,com.sskj.flashlight,{{ rule }} # 随手电筒
PROCESS-NAME,com.ssxg.cheers,{{ rule }} # 悦享家生活
PROCESS-NAME,com.storm.smart,{{ rule }} # 暴风影音
PROCESS-NAME,com.suning.mobile.ebuy,{{ rule }} # 苏宁易购
PROCESS-NAME,com.sup.android.superb,{{ rule }} # 皮皮虾
PROCESS-NAME,com.sxm.yiwei,{{ rule }} # 一喂顺风车
PROCESS-NAME,com.talent.food,{{ rule }} # 做菜达人
PROCESS-NAME,com.taobao.etao,{{ rule }} # 一淘
PROCESS-NAME,com.taobao.idlefish,{{ rule }} # 闲鱼
PROCESS-NAME,com.taobao.litetao,{{ rule }} # 淘宝特价版
PROCESS-NAME,com.taobao.qianniu,{{ rule }} # 千牛
PROCESS-NAME,com.taobao.taobao,{{ rule }} # 淘宝
PROCESS-NAME,com.taobao.trip,{{ rule }} # 飞猪旅行
PROCESS-NAME,com.taou.maimai,{{ rule }} # 脉脉
PROCESS-NAME,com.tencent.androidqqmail,{{ rule }} # QQ邮箱
PROCESS-NAME,com.tencent.djcity,{{ rule }} # 掌上道聚城
PROCESS-NAME,com.tencent.gallerymanager,{{ rule }} # 腾讯相册管家
PROCESS-NAME,com.tencent.gamehelper,{{ rule }} # 腾讯游戏助手
PROCESS-NAME,com.tencent.gamehelper.smoba,{{ rule }} # 王者营地
PROCESS-NAME,com.tencent.karaoke,{{ rule }} # 全民K歌
PROCESS-NAME,com.tencent.map,{{ rule }} # 腾讯地图
PROCESS-NAME,com.tencent.mm,{{ rule }} # 微信
PROCESS-NAME,com.tencent.mobileqq,{{ rule }} # QQ
PROCESS-NAME,com.tencent.mtt,{{ rule }} # QQ浏览器
PROCESS-NAME,com.tencent.news,{{ rule }} # 腾讯新闻
PROCESS-NAME,com.tencent.qqgame,{{ rule }} # QQ游戏
PROCESS-NAME,com.tencent.qqlive,{{ rule }} # 腾讯视频
PROCESS-NAME,com.tencent.qqmusic,{{ rule }} # QQ音乐
PROCESS-NAME,com.tencent.qqpim,{{ rule }} # QQ同步助手
PROCESS-NAME,com.tencent.qqpimsecure,{{ rule }} # 腾讯手机管家
PROCESS-NAME,com.tencent.qqsports,{{ rule }} # 腾讯体育
PROCESS-NAME,com.tencent.qt.qtl,{{ rule }} # 掌上英雄联盟
PROCESS-NAME,com.tencent.qt.sns,{{ rule }} # 掌上穿越火线
PROCESS-NAME,com.tencent.tgclub,{{ rule }} # 心悦俱乐部
PROCESS-NAME,com.tencent.tim,{{ rule }} # TIM
PROCESS-NAME,com.tencent.token,{{ rule }} # QQ安全中心
PROCESS-NAME,com.tencent.ttpic,{{ rule }} # 天天P图
PROCESS-NAME,com.tencent.weishi,{{ rule }} # 腾讯微视
PROCESS-NAME,com.tencent.weread,{{ rule }} # 微信读书
PROCESS-NAME,com.tencent.wework,{{ rule }} # 企业微信
PROCESS-NAME,com.tencent.zebra,{{ rule }} # 水印相机
PROCESS-NAME,com.tgelec.aqsh,{{ rule }} # 安全守护2
PROCESS-NAME,com.thestore.main,{{ rule }} # 1号会员店
PROCESS-NAME,com.threegene.yeemiao,{{ rule }} # 小豆苗
PROCESS-NAME,com.tianqi2345,{{ rule }} # 2345天气王
PROCESS-NAME,com.tianqi8.weather,{{ rule }} # 天气吧
PROCESS-NAME,com.tieyou.train.ark,{{ rule }} # 铁友火车票
PROCESS-NAME,com.tinmanarts.JoJoSherlock,{{ rule }} # 叫叫识字
PROCESS-NAME,com.tiqiaa.icontrol,{{ rule }} # 遥控精灵
PROCESS-NAME,com.tmall.wireless,{{ rule }} # 天猫
PROCESS-NAME,com.tmri.app.main,{{ rule }} # 交管12123
PROCESS-NAME,com.tongcheng.android,{{ rule }} # 同程旅行
PROCESS-NAME,com.tongchengpzhl.com,{{ rule }} # 同城品质婚恋
PROCESS-NAME,com.tongzhuo.tongzhuogame,{{ rule }} # 同桌派对
PROCESS-NAME,com.touchtv.touchtv,{{ rule }} # 粤TV
PROCESS-NAME,com.trip.housekeeper,{{ rule }} # 日程管家
PROCESS-NAME,com.tripadvisor.tripadvisor.daodao,{{ rule }} # Tripadvisor猫途鹰
PROCESS-NAME,com.truedian.dragon,{{ rule }} # 微购相册
PROCESS-NAME,com.tudou.android,{{ rule }} # 土豆
PROCESS-NAME,com.UCMobile,{{ rule }} # UC浏览器
PROCESS-NAME,com.ujigu.ytb,{{ rule }} # 优题宝
PROCESS-NAME,com.ume.browser,{{ rule }} # 微米浏览器
PROCESS-NAME,com.unionpay,{{ rule }} # 云闪付
PROCESS-NAME,com.universal.control,{{ rule }} # 万能遥控器+
PROCESS-NAME,com.ushaqi.zhuishushenqi,{{ rule }} # 追书神器
PROCESS-NAME,com.video.clip,{{ rule }} # 视频拼接王
PROCESS-NAME,com.videogo,{{ rule }} # 萤石云视频
PROCESS-NAME,com.vivo.easyshare,{{ rule }} # 互传
PROCESS-NAME,com.wakeup.howear,{{ rule }} # Wearfit Pro
PROCESS-NAME,com.wali.live,{{ rule }} # 白金秀
PROCESS-NAME,com.wandoujia.phoenix2,{{ rule }} # 豌豆荚
PROCESS-NAME,com.wemall.onlineshopping,{{ rule }} # WEMALL
PROCESS-NAME,com.wglianmeng,{{ rule }} # 网购联盟
PROCESS-NAME,com.when.coco,{{ rule }} # 365日历
PROCESS-NAME,com.wifi.reader.free,{{ rule }} # 连尚免费读书
PROCESS-NAME,com.winbaoxian.wybx,{{ rule }} # 保险师
PROCESS-NAME,com.wjkj.loosrun,{{ rule }} # 电子红包
PROCESS-NAME,com.wkscuiphone,{{ rule }} # 五矿证券
PROCESS-NAME,com.wlqq,{{ rule }} # 货车帮司机
PROCESS-NAME,com.wodi.who,{{ rule }} # 玩吧
PROCESS-NAME,com.wondertek.paper,{{ rule }} # 澎湃新闻
PROCESS-NAME,com.work.clock,{{ rule }} # 起床闹铃
PROCESS-NAME,com.wsecar.wsjc,{{ rule }} # 万顺叫车
PROCESS-NAME,com.wuba,{{ rule }} # 58同城
PROCESS-NAME,com.wuba.zhuanzhuan,{{ rule }} # 转转
PROCESS-NAME,com.xfplay.play,{{ rule }} # 影音先锋
PROCESS-NAME,com.xiachufang,{{ rule }} # 下厨房
PROCESS-NAME,com.xiangrikui.sixapp,{{ rule }} # 向日葵保险人
PROCESS-NAME,com.xiaobanlong.main,{{ rule }} # 小伴龙
PROCESS-NAME,com.xiaoenai.app,{{ rule }} # 小恩爱
PROCESS-NAME,com.xiaomi.hm.health,{{ rule }} # Zepp Life
PROCESS-NAME,com.xiaomi.shop,{{ rule }} # 小米商城
PROCESS-NAME,com.xiaomi.smarthome,{{ rule }} # 米家
PROCESS-NAME,com.xiaoshijie.sqb,{{ rule }} # 好省
PROCESS-NAME,com.ximalaya.ting.android,{{ rule }} # 喜马拉雅
PROCESS-NAME,com.xingin.xhs,{{ rule }} # 小红书
PROCESS-NAME,com.xingjiabi.shengsheng,{{ rule }} # 他趣
PROCESS-NAME,com.xingluo.mpa,{{ rule }} # 魔力相册
PROCESS-NAME,com.xinhu.futures,{{ rule }} # 新湖期货开户交易
PROCESS-NAME,com.xiongmaoqiming.quming,{{ rule }} # 熊猫起名
PROCESS-NAME,com.xiwei.logistics,{{ rule }} # 运满满司机
PROCESS-NAME,com.xmcy.hykb,{{ rule }} # 好游快爆
PROCESS-NAME,com.xtc.watch,{{ rule }} # 小天才
PROCESS-NAME,com.xunlei.downloadprovider,{{ rule }} # 迅雷
PROCESS-NAME,com.xunmeng.pinduoduo,{{ rule }} # 拼多多
PROCESS-NAME,com.xvideostudio.videoeditor,{{ rule }} # 乐秀视频剪辑视频编辑
PROCESS-NAME,com.ycwb.android.ycpai,{{ rule }} # 羊城派
PROCESS-NAME,com.yek.android.kfc.activitys,{{ rule }} # 肯德基
PROCESS-NAME,com.ygkj.chelaile.standard,{{ rule }} # 车来了
PROCESS-NAME,com.yiban1413.yiban,{{ rule }} # 一伴婚恋专业版
PROCESS-NAME,com.yibasan.lizhifm,{{ rule }} # 荔枝
PROCESS-NAME,com.yiche.autoeasy,{{ rule }} # 易车
PROCESS-NAME,com.yidian.xiaomi,{{ rule }} # 一点新闻资讯
PROCESS-NAME,com.yingyonghui.market,{{ rule }} # 应用汇
PROCESS-NAME,com.yipiao,{{ rule }} # 智行火车票
PROCESS-NAME,com.yitong.mbank.psbc,{{ rule }} # 邮储银行
PROCESS-NAME,com.yitong.zjrc.mfs.android,{{ rule }} # 丰收互联
PROCESS-NAME,com.yixia.videoeditor,{{ rule }} # 秒拍
PROCESS-NAME,com.yiyou.ga,{{ rule }} # TT语音
PROCESS-NAME,com.yoloho.dayima,{{ rule }} # 大姨妈
PROCESS-NAME,com.youcheyihou.iyoursuv,{{ rule }} # 有车以后
PROCESS-NAME,com.youdao.dict,{{ rule }} # 网易有道词典
PROCESS-NAME,com.youdao.note,{{ rule }} # 有道云笔记
PROCESS-NAME,com.youdao.translator,{{ rule }} # 有道翻译官
PROCESS-NAME,com.youku.phone,{{ rule }} # 优酷视频
PROCESS-NAME,com.youloft.calendar,{{ rule }} # 万年历
PROCESS-NAME,com.ysy.ayy,{{ rule }} # 木鸟民宿
PROCESS-NAME,com.yuedong.sport,{{ rule }} # 悦动圈
PROCESS-NAME,com.yueme.itv,{{ rule }} # 小翼管家
PROCESS-NAME,com.yunxi.bell,{{ rule }} # 闹钟AI
PROCESS-NAME,com.yx,{{ rule }} # 有信
PROCESS-NAME,com.zenmen.palmchat,{{ rule }} # 连信
PROCESS-NAME,com.zhangdan.app,{{ rule }} # 51信用卡管家
PROCESS-NAME,com.zhaopin.social,{{ rule }} # 智联招聘
PROCESS-NAME,com.zhibo.mm,{{ rule }} # 秘密直播
PROCESS-NAME,com.zhihu.android,{{ rule }} # 知乎
PROCESS-NAME,com.zhongdianhuike.app,{{ rule }} # 众点惠客
PROCESS-NAME,com.zl.fqbao,{{ rule }} # 招联金融
PROCESS-NAME,com.zsyj.wallpaper,{{ rule }} # 动态壁纸
PROCESS-NAME,ctrip.android.view,{{ rule }} # 携程旅行
PROCESS-NAME,flipboard.cn,{{ rule }} # 红板报
PROCESS-NAME,fm.qingting.qtradio,{{ rule }} # 蜻蜓FM
PROCESS-NAME,jiakaokeer.app.good,{{ rule }} # 驾考宝典科目二
PROCESS-NAME,jiakaokesan.app.good,{{ rule }} # 驾考宝典科目三
PROCESS-NAME,jiakaokesi.app.good,{{ rule }} # 驾考宝典极速版
PROCESS-NAME,jiakaokeyi.app.good,{{ rule }} # 驾考宝典3D练车
PROCESS-NAME,jiaxiao.app.good,{{ rule }} # 驾照宝典
PROCESS-NAME,jiaxiaobaodian.app.good,{{ rule }} # 驾校宝典
PROCESS-NAME,kehuo.app.good,{{ rule }} # 驾考宝典客货车
PROCESS-NAME,me.chunyu.ChunyuDoctor,{{ rule }} # 春雨医生
PROCESS-NAME,me.yidui,{{ rule }} # 伊对
PROCESS-NAME,moto.app.good,{{ rule }} # 驾考宝典摩托车
PROCESS-NAME,oms.mmc.app.almanac_inland,{{ rule }} # 老黄历万年历顺历
PROCESS-NAME,org.fungo.fungolive,{{ rule }} # 天天电视直播
PROCESS-NAME,org.zywx.wbpalmstar.widgetone.uexaaagg10001,{{ rule }} # 安全守护
PROCESS-NAME,sina.mobile.tianqitong,{{ rule }} # 天气通
PROCESS-NAME,sogou.mobile.explorer,{{ rule }} # 搜狗浏览器极速版
PROCESS-NAME,tv.danmaku.bili,{{ rule }} # 哔哩哔哩
PROCESS-NAME,tv.pps.mobile,{{ rule }} # 爱奇艺随刻
PROCESS-NAME,tv.yilan.howto.app,{{ rule }} # 好兔视频
PROCESS-NAME,tv.yixia.bobo,{{ rule }} # 波波视频
PROCESS-NAME,vStudio.Android.Camera360,{{ rule }} # 相机360
PROCESS-NAME,com.alicom.smartdial,{{ rule }}
PROCESS-NAME,com.bilibili.app.in,{{ rule }}
PROCESS-NAME,me.gfuil.bmap,{{ rule }}
PROCESS-NAME,cn.com.bmac.nfc,{{ rule }}
PROCESS-NAME,com.nowcasting.activity,{{ rule }}
PROCESS-NAME,com.coolapk.market,{{ rule }}
PROCESS-NAME,com.unionpay.tsmservice,{{ rule }}
PROCESS-NAME-REGEX,^com\.(?:heytap|oppo|coloros|oneplus|oplus)\..*,{{ rule }}
PROCESS-NAME-REGEX,^com\.huawei\..*,{{ rule }}
PROCESS-NAME-REGEX,^com\.vivo\..*,{{ rule }}
PROCESS-NAME-REGEX,^com\.(?:xiaomi|miui)\..*,{{ rule }}
PROCESS-NAME-REGEX,^com\.tencent\..*,{{ rule }}
PROCESS-NAME-REGEX,^com\.hypergryph\..*,{{ rule }}
{% endmacro %}