{% macro main(rule) %}
PROCESS-NAME,ai.zuoye.app,{{ rule }} # 爱作业
PROCESS-NAME,air.tv.douyu.android,{{ rule }} # 斗鱼
PROCESS-NAME,all.parttimeguidesystem,{{ rule }} # 兼职猫-同城找工作求职招聘平台
PROCESS-NAME,android.zhibo8,{{ rule }} # 直播吧
PROCESS-NAME,battymole.trainticket,{{ rule }} # 买火车票
PROCESS-NAME,bubei.tingshu,{{ rule }} # 懒人听书
PROCESS-NAME,cc.fotoplace.app,{{ rule }} # 足记
PROCESS-NAME,cc.rs.gc,{{ rule }} # GG租号
PROCESS-NAME,cc.rs.rrzh,{{ rule }} # 人人租号
PROCESS-NAME,cld.navi.mainframe,{{ rule }} # 凯立德导航
PROCESS-NAME,cmb.pb,{{ rule }} # 招商银行
PROCESS-NAME,cmccwm.mobilemusic,{{ rule }} # 咪咕音乐
PROCESS-NAME,cn.amazon.mShop.android,{{ rule }} # 亚马逊购物
PROCESS-NAME,cn.banshenggua.aichang,{{ rule }} # 爱唱
PROCESS-NAME,cn.buding.martin,{{ rule }} # 微车
PROCESS-NAME,cn.caocaokeji.user,{{ rule }} # 曹操出行
PROCESS-NAME,cn.cbct.seefm,{{ rule }} # 听见广播
PROCESS-NAME,cn.chinabus.main,{{ rule }} # 8684实时公交
PROCESS-NAME,cn.cntv,{{ rule }} # 央视影音
PROCESS-NAME,cn.cntvnews,{{ rule }} # 央视新闻
PROCESS-NAME,cn.colorv,{{ rule }} # 彩视
PROCESS-NAME,cn.com.cmbc.newmbank,{{ rule }} # 民生银行
PROCESS-NAME,cn.com.htjc.pay,{{ rule }} # 电e宝
PROCESS-NAME,cn.com.njxmxbank.mbank,{{ rule }} # 南银法巴消金
PROCESS-NAME,cn.com.pansky.sxzgyl,{{ rule }} # 陕西社会保险
PROCESS-NAME,cn.com.qlwb.qiluyidian,{{ rule }} # 齐鲁壹点
PROCESS-NAME,cn.com.spdb.mobilebank.per,{{ rule }} # 浦发手机银行
PROCESS-NAME,cn.com.tyfon.sun.xhrrac9,{{ rule }} # 泰丰艺术商城
PROCESS-NAME,cn.com.zjol,{{ rule }} # 潮新闻
PROCESS-NAME,cn.daje.remoter,{{ rule }} # 空调遥控器万能
PROCESS-NAME,cn.damai,{{ rule }} # 大麦
PROCESS-NAME,cn.dxy.android.aspirin,{{ rule }} # 丁香医生
PROCESS-NAME,cn.eclicks.drivingtest,{{ rule }} # 车轮驾考通
PROCESS-NAME,cn.eclicks.wzsearch,{{ rule }} # 车轮
PROCESS-NAME,cn.egame.terminal.cloud5g,{{ rule }} # 天翼云游戏
PROCESS-NAME,cn.emagsoftware.gamehall,{{ rule }} # 咪咕快游
PROCESS-NAME,cn.etouch.ecalendar,{{ rule }} # 中华万年历
PROCESS-NAME,cn.gov.pbc.dcep,{{ rule }} # 数字人民币
PROCESS-NAME,cn.gov.tax.its,{{ rule }} # 个人所得税
PROCESS-NAME,cn.hsa.app,{{ rule }} # 国家医保服务平台
PROCESS-NAME,cn.huntlaw.android,{{ rule }} # 好律师
PROCESS-NAME,cn.ishansong,{{ rule }} # 闪送
PROCESS-NAME,cn.knet.eqxiu,{{ rule }} # 易企秀
PROCESS-NAME,cn.kuwo.player,{{ rule }} # 酷我音乐
PROCESS-NAME,cn.ledongli.ldl,{{ rule }} # 乐动力
PROCESS-NAME,cn.mama.activity,{{ rule }} # 妈妈网轻聊
PROCESS-NAME,cn.microants.merchants,{{ rule }} # 义采宝义乌小商品批发网
PROCESS-NAME,cn.mimilive.xianyu,{{ rule }} # 爆聊
PROCESS-NAME,cn.mucang.android.drivingsimulator,{{ rule }} # 驾考宝典科目一
PROCESS-NAME,cn.mucang.android.jkxt,{{ rule }} # 驾考宝典多语言版
PROCESS-NAME,cn.mucang.android.parallelvehicle,{{ rule }} # 平行之家
PROCESS-NAME,cn.mucang.android.parallelvehicle.manager,{{ rule }} # 平行之家商家版
PROCESS-NAME,cn.mucang.android.qichetoutiao,{{ rule }} # 车友头条
PROCESS-NAME,cn.mucang.drunkremind.android,{{ rule }} # 小猪二手车
PROCESS-NAME,cn.ninegame.gamemanager,{{ rule }} # 九游
PROCESS-NAME,cn.opda.a.phonoalbumshoushou,{{ rule }} # 百度手机卫士
PROCESS-NAME,cn.rainbow.westore,{{ rule }} # 天虹
PROCESS-NAME,cn.soulapp.android,{{ rule }} # Soul
PROCESS-NAME,cn.TuHu.android,{{ rule }} # 途虎养车
PROCESS-NAME,cn.wangxiao.gwyzhuntiku,{{ rule }} # 公务员准题库
PROCESS-NAME,cn.wps.moffice_eng,{{ rule }} # WPS Office
PROCESS-NAME,cn.xiaochuankeji.tieba,{{ rule }} # 最右
PROCESS-NAME,cn.xiaochuankeji.zuiyouLite,{{ rule }} # 皮皮搞笑
PROCESS-NAME,cn.xuexi.android,{{ rule }} # 学习强国
PROCESS-NAME,cn.yonghui.hyd,{{ rule }} # 永辉生活
PROCESS-NAME,cn.youth.news,{{ rule }} # 中青看点
PROCESS-NAME,co.runner.app,{{ rule }} # 悦跑圈
PROCESS-NAME,co.welab.wolaidai,{{ rule }} # 我来数科
PROCESS-NAME,com.A17zuoye.mobile.homework,{{ rule }} # 一起作业
PROCESS-NAME,com.able.wisdomtree,{{ rule }} # 知到
PROCESS-NAME,com.acadsoc.learn,{{ rule }} # 阿卡索口语秀
PROCESS-NAME,com.acadsoc.talkshow,{{ rule }} # 阿卡索英语
PROCESS-NAME,com.achievo.vipshop,{{ rule }} # 唯品会
PROCESS-NAME,com.adobe.reader,{{ rule }} # PDF阅读器 Adobe reader
PROCESS-NAME,com.aikan,{{ rule }} # 免费小说大全
PROCESS-NAME,com.airbnb.android,{{ rule }} # 爱彼迎
PROCESS-NAME,com.airuniversa.control,{{ rule }} # 万能空调遥控器
PROCESS-NAME,com.alibaba.ailabs.tg,{{ rule }} # 天猫精灵
PROCESS-NAME,com.alibaba.android.rimet,{{ rule }} # 钉钉
PROCESS-NAME,com.alibaba.wireless,{{ rule }} # 阿里巴巴
PROCESS-NAME,com.alpha.lagouapk,{{ rule }} # 拉勾招聘
PROCESS-NAME,com.ancda.parents,{{ rule }} # 掌心宝贝
PROCESS-NAME,com.ancient.calendar,{{ rule }} # 老黄历
PROCESS-NAME,com.android.app.quanmama,{{ rule }} # 券妈妈优惠券
PROCESS-NAME,com.android.bankabc,{{ rule }} # 农行掌上银行
PROCESS-NAME,com.android.chrome,{{ rule }} # 谷歌浏览器Google Chrome
PROCESS-NAME,com.android.dazhihui,{{ rule }} # 大智慧
PROCESS-NAME,com.android.haitong,{{ rule }} # 海通e海通财
PROCESS-NAME,com.android.icredit,{{ rule }} # 企查查
PROCESS-NAME,com.android.tutuerge,{{ rule }} # 兔兔儿歌
PROCESS-NAME,com.android.vending,{{ rule }} # Google Play Store
PROCESS-NAME,com.Android56,{{ rule }} # 56视频
PROCESS-NAME,com.androidesk.livewallpaper,{{ rule }} # 安卓动态壁纸
PROCESS-NAME,com.anjiu.buff.yingyongbao,{{ rule }} # BUFF手游
PROCESS-NAME,com.anjuke.android.app,{{ rule }} # 安居客
PROCESS-NAME,com.antutu.ABenchMark,{{ rule }} # 安兔兔评测
PROCESS-NAME,com.anwei.meivliao,{{ rule }} # 美V聊天
PROCESS-NAME,com.appsys.goodname,{{ rule }} # 易经起名取名
PROCESS-NAME,com.ataaw.tianyi,{{ rule }} # 天翼生活
PROCESS-NAME,com.autohome.usedcar,{{ rule }} # 二手车之家
PROCESS-NAME,com.autonavi.minimap,{{ rule }} # 高德地图
PROCESS-NAME,com.babycloud.hanju,{{ rule }} # 韩小圈
PROCESS-NAME,com.babytree.apps.lama,{{ rule }} # 宝宝树小时光
PROCESS-NAME,com.babytree.apps.pregnancy,{{ rule }} # 宝宝树孕育
PROCESS-NAME,com.baidu.appsearch,{{ rule }} # 百度手机助手
PROCESS-NAME,com.baidu.BaiduMap,{{ rule }} # 百度地图
PROCESS-NAME,com.baidu.baidutranslate,{{ rule }} # 百度翻译
PROCESS-NAME,com.baidu.browser.apps,{{ rule }} # 百度浏览器
PROCESS-NAME,com.baidu.haokan,{{ rule }} # 好看视频
PROCESS-NAME,com.baidu.homework,{{ rule }} # 作业帮
PROCESS-NAME,com.baidu.iknow,{{ rule }} # 百度知道
PROCESS-NAME,com.baidu.input,{{ rule }} # 百度输入法
PROCESS-NAME,com.baidu.netdisk,{{ rule }} # 百度网盘
PROCESS-NAME,com.baidu.searchbox,{{ rule }} # 百度
PROCESS-NAME,com.baidu.searchbox.lite,{{ rule }} # 百度极速版
PROCESS-NAME,com.baidu.tieba,{{ rule }} # 百度贴吧
PROCESS-NAME,com.baidu.video,{{ rule }} # 百搜视频
PROCESS-NAME,com.baidu.wenku,{{ rule }} # 百度文库
PROCESS-NAME,com.baidu.yuedu,{{ rule }} # 百度阅读
PROCESS-NAME,com.baihe,{{ rule }} # 百合网
PROCESS-NAME,com.bananavideo.atqb,{{ rule }} # 香焦视频
PROCESS-NAME,com.bankcomm.Bankcomm,{{ rule }} # 交通银行
PROCESS-NAME,com.baojiazhijia.qichebaojia,{{ rule }} # 买车宝典
PROCESS-NAME,com.baoyun.babycloud,{{ rule }} # 口袋宝宝
PROCESS-NAME,com.benqu.wuta,{{ rule }} # 无他相机
PROCESS-NAME,com.bertadata.qxb,{{ rule }} # 启信宝
PROCESS-NAME,com.bfire.da.nui,{{ rule }} # 微分身双开
PROCESS-NAME,com.bingo.yeliao,{{ rule }} # 十点聊天
PROCESS-NAME,com.bjut.cyl.findnurse,{{ rule }} # 金牌护士
PROCESS-NAME,com.black.unique,{{ rule }} # 全球购骑士特权
PROCESS-NAME,com.bly.dkplat,{{ rule }} # 小X分身
PROCESS-NAME,com.bokecc.dance,{{ rule }} # 糖豆
PROCESS-NAME,com.boniu.saomiaoquannengwang,{{ rule }} # 扫描转文字王
PROCESS-NAME,com.boohee.one,{{ rule }} # 薄荷健康
PROCESS-NAME,com.booking,{{ rule }} # Booking.com缤客
PROCESS-NAME,com.browser2345,{{ rule }} # 2345浏览器
PROCESS-NAME,com.btime.bjtime,{{ rule }} # 北京时间
PROCESS-NAME,com.budejie.www,{{ rule }} # 百思漂流瓶
PROCESS-NAME,com.c2vl.kgamebox,{{ rule }} # 狼人杀
PROCESS-NAME,com.caineng.app,{{ rule }} # 才能网
PROCESS-NAME,com.cainiao.wireless,{{ rule }} # 菜鸟
PROCESS-NAME,com.cainiu.lawyer365,{{ rule }} # 律师365
PROCESS-NAME,com.cairh.khapp.dbzq.xmlqdl,{{ rule }} # 东北证券股票开户
PROCESS-NAME,com.campmobile.snowcamera,{{ rule }} # B612咔叽
PROCESS-NAME,com.ccb.longjiLife,{{ rule }} # 建行生活
PROCESS-NAME,com.cctv.caijing,{{ rule }} # 央视财经
PROCESS-NAME,com.cctv.yangshipin.app.androidp,{{ rule }} # 央视频
PROCESS-NAME,com.cdv.video360,{{ rule }} # 云美摄
PROCESS-NAME,com.cebbank.mobile.cemb,{{ rule }} # 光大银行
PROCESS-NAME,com.cffex.htqh,{{ rule }} # 海通期货期海通行
PROCESS-NAME,com.cfy.xqwxt,{{ rule }} # 象棋微学堂
PROCESS-NAME,com.cgbchina.xpt,{{ rule }} # 广发银行
PROCESS-NAME,com.changba,{{ rule }} # 唱吧
PROCESS-NAME,com.chaoxing.mobile,{{ rule }} # 学习通
PROCESS-NAME,com.chaozh.iReaderFree,{{ rule }} # 掌阅
PROCESS-NAME,com.chebada,{{ rule }} # 巴士管家
PROCESS-NAME,com.chinalife.ebz,{{ rule }} # 中国人寿寿险
PROCESS-NAME,com.chinamobile.contacts.im,{{ rule }} # 和通讯录
PROCESS-NAME,com.chinamobile.mcloud,{{ rule }} # 中国移动云盘
PROCESS-NAME,com.chinamworld.bocmbci,{{ rule }} # 中国银行
PROCESS-NAME,com.chinaso.toutiao,{{ rule }} # 中国搜索
PROCESS-NAME,com.chinatelecom.bestpayclient,{{ rule }} # 翼支付
PROCESS-NAME,com.chineseall.singlebook,{{ rule }} # 中文书城
PROCESS-NAME,com.ci123.pregnancywap,{{ rule }} # 妈妈社区
PROCESS-NAME,com.cib.cibmb,{{ rule }} # 兴业银行
PROCESS-NAME,com.cib.xyk,{{ rule }} # 兴业生活
PROCESS-NAME,com.citiccard.mobilebank,{{ rule }} # 中信银行动卡空间
PROCESS-NAME,com.cleanmaster.mguard_cn,{{ rule }} # 猎豹清理大师
PROCESS-NAME,com.clipzz.media,{{ rule }} # 视频剪辑精灵
PROCESS-NAME,com.cloudpower.netsale.activity,{{ rule }} # 中国人保
PROCESS-NAME,com.cmbc.cc.mbank,{{ rule }} # 全民生活
PROCESS-NAME,com.cmbchina.ccd.pluto.cmbActivity,{{ rule }} # 掌上生活
PROCESS-NAME,com.cmcc.cmvideo,{{ rule }} # 咪咕视频
PROCESS-NAME,com.cmcc.hebao,{{ rule }} # 和包
PROCESS-NAME,com.cmi.jegotrip,{{ rule }} # 无忧行
PROCESS-NAME,com.cmri.universalapp,{{ rule }} # 移动爱家
PROCESS-NAME,com.cmschina.stock,{{ rule }} # 招商证券
PROCESS-NAME,com.cns.mc.activity,{{ rule }} # 中国新闻网
PROCESS-NAME,com.codoon.gps,{{ rule }} # 咕咚
PROCESS-NAME,com.comic.manhuatai,{{ rule }} # 漫画台
PROCESS-NAME,com.cooby.news,{{ rule }} # 华人头条
PROCESS-NAME,com.cpic.sxbxxe,{{ rule }} # 太平洋保险
PROCESS-NAME,com.creditwealth.client,{{ rule }} # 宜人优选
PROCESS-NAME,com.crv.wanjia,{{ rule }} # 华润万家
PROCESS-NAME,com.cs_credit_bank,{{ rule }} # 发现精彩
PROCESS-NAME,com.csii.gdnx.mobilebank,{{ rule }} # 广东农信
PROCESS-NAME,com.ct.client,{{ rule }} # 中国电信
PROCESS-NAME,com.cubic.autohome,{{ rule }} # 汽车之家
PROCESS-NAME,com.cubic.choosecar,{{ rule }} # 汽车报价
PROCESS-NAME,com.cyjh.ddyun,{{ rule }} # 多多云手机
PROCESS-NAME,com.cyp.fm,{{ rule }} # 文件解压管家
PROCESS-NAME,com.dailyyoga.cn,{{ rule }} # 每日瑜伽
PROCESS-NAME,com.dalongtech.cloud,{{ rule }} # 云电脑
PROCESS-NAME,com.dangdang.buy2,{{ rule }} # 当当
PROCESS-NAME,com.daofeng.zuhaowan,{{ rule }} # 租号玩
PROCESS-NAME,com.dazhuanjia.dcloud,{{ rule }} # 大专家
PROCESS-NAME,com.dbscgeneral,{{ rule }} # 东北证券融e通
PROCESS-NAME,com.ddnapalon.calculator.gp,{{ rule }} # 计算器智能计算
PROCESS-NAME,com.ddyhq.youhuiquan,{{ rule }} # 优惠券
PROCESS-NAME,com.devuni.flashlight,{{ rule }} # 超级手电筒
PROCESS-NAME,com.dewmobile.kuaiya,{{ rule }} # 快牙
PROCESS-NAME,com.dianping.v1,{{ rule }} # 大众点评
PROCESS-NAME,com.dida.help,{{ rule }} # 滴答滴顺风车
PROCESS-NAME,com.didago.dida,{{ rule }} # 滴答顺风车
PROCESS-NAME,com.didago.travel,{{ rule }} # 滴答出行
PROCESS-NAME,com.didapinche.booking,{{ rule }} # 嘀嗒出行
PROCESS-NAME,com.digitalgd.dgyss,{{ rule }} # 粤省事
PROCESS-NAME,com.dingchebao,{{ rule }} # 订车宝
PROCESS-NAME,com.dingtai.wxhn.activity,{{ rule }} # 新湖南
PROCESS-NAME,com.dingYZ.dingyzwater,{{ rule }} # 微脉水印相机
PROCESS-NAME,com.diyidan,{{ rule }} # 第一弹
PROCESS-NAME,com.dongqiudi.news,{{ rule }} # 懂球帝
PROCESS-NAME,com.douban.frodo,{{ rule }} # 豆瓣
PROCESS-NAME,com.douguo.recipe,{{ rule }} # 豆果美食
PROCESS-NAME,com.doumi.jianzhi,{{ rule }} # 斗米
PROCESS-NAME,com.doupin.show,{{ rule }} # 来电秀
PROCESS-NAME,com.dp.android.elong,{{ rule }} # 艺龙旅行
PROCESS-NAME,com.dragon.calendar,{{ rule }} # 东方农历
PROCESS-NAME,com.dragon.read,{{ rule }} # 番茄免费小说
PROCESS-NAME,com.dragon.ringtone,{{ rule }} # 东方铃声
PROCESS-NAME,com.droid.credit,{{ rule }} # 移动手机贷
PROCESS-NAME,com.duitang.main,{{ rule }} # 堆糖
PROCESS-NAME,com.duokan.phone.remotecontroller,{{ rule }} # 万能遥控
PROCESS-NAME,com.duokan.reader,{{ rule }} # 多看
PROCESS-NAME,com.duowan.kiwi,{{ rule }} # 虎牙直播
PROCESS-NAME,com.dute.dutenews,{{ rule }} # 读特
PROCESS-NAME,com.duwo.reading,{{ rule }} # 伴鱼绘本
PROCESS-NAME,com.duxiaoman.umoney,{{ rule }} # 有钱花
PROCESS-NAME,com.dw.btime,{{ rule }} # 亲宝宝
PROCESS-NAME,com.dzqh.dzyjcf,{{ rule }} # 东证赢家
PROCESS-NAME,com.dzqh.online11,{{ rule }} # 东方证券期货
PROCESS-NAME,com.dzwww.sd.android,{{ rule }} # 海报新闻
PROCESS-NAME,com.eastmoney.android.berlin,{{ rule }} # 东方财富
PROCESS-NAME,com.eastmoney.android.fund,{{ rule }} # 天天基金
PROCESS-NAME,com.easy.bus,{{ rule }} # 无忧巴士
PROCESS-NAME,com.easy.subway,{{ rule }} # 地铁查询宝
PROCESS-NAME,com.ebank.creditcard,{{ rule }} # 阳光惠生活
PROCESS-NAME,com.ecitic.bank.mobile,{{ rule }} # 中信银行
PROCESS-NAME,com.eg.android.AlipayGphone,{{ rule }} # 支付宝
PROCESS-NAME,com.emperor.flashlight,{{ rule }} # 手电王
PROCESS-NAME,com.eno.android.cj.page,{{ rule }} # 长江e号
PROCESS-NAME,com.enqualcomm.kids.cyp,{{ rule }} # 西瓜皮
PROCESS-NAME,com.evideo.MobileKTV,{{ rule }} # K米
PROCESS-NAME,com.excean.gspace,{{ rule }} # OurPlay加速器
PROCESS-NAME,com.excean.masaid,{{ rule }} # 微分身版
PROCESS-NAME,com.excelliance.dualaid,{{ rule }} # 双开助手微分身版
PROCESS-NAME,com.ezg.camper,{{ rule }} # 约你游
PROCESS-NAME,com.fangdai.fdjsq,{{ rule }} # 房贷计算器
PROCESS-NAME,com.fangdai.fdjszs,{{ rule }} # 房贷计算器
PROCESS-NAME,com.fanli.android.apps,{{ rule }} # 返利
PROCESS-NAME,com.fanlitaolianmengw,{{ rule }} # 返利淘联盟
PROCESS-NAME,com.fanlwgaoylmengw,{{ rule }} # 返利高佣联盟
PROCESS-NAME,com.fc.management,{{ rule }} # 文件编辑器
PROCESS-NAME,com.fenbi.android.gaozhong,{{ rule }} # 猿题库
PROCESS-NAME,com.fenbi.android.leo,{{ rule }} # 小猿口算
PROCESS-NAME,com.fenbi.android.servant,{{ rule }} # 粉笔
PROCESS-NAME,com.fenbi.android.solar,{{ rule }} # 小猿搜题
PROCESS-NAME,com.fenqile.fenqile,{{ rule }} # 分期乐
PROCESS-NAME,com.financial.quantgroup,{{ rule }} # 羊小咩
PROCESS-NAME,com.flash.zhongcao,{{ rule }} # 种草生活
PROCESS-NAME,com.flightmanager.view,{{ rule }} # 航班管家
PROCESS-NAME,com.fm.aiyinsitan,{{ rule }} # 爱音斯坦FM
PROCESS-NAME,com.folder.management,{{ rule }} # 文件夹管家
PROCESS-NAME,com.fombo.wallpaper,{{ rule }} # 高清动态壁纸大全
PROCESS-NAME,com.forms,{{ rule }} # 缤纷生活
PROCESS-NAME,com.foundao.bjnews,{{ rule }} # 新京报
PROCESS-NAME,com.foundao.xinhua_android,{{ rule }} # 新华网
PROCESS-NAME,com.foundersc.app.xf,{{ rule }} # 小方
PROCESS-NAME,com.fqapps.fdsh,{{ rule }} # 福袋生活
PROCESS-NAME,com.free_ride_pin.yiwei,{{ rule }} # 汽车票
PROCESS-NAME,com.free_ride.yiwei,{{ rule }} # 顺风车
PROCESS-NAME,com.free.compass,{{ rule }} # 免费指南针
PROCESS-NAME,com.funshion.video.mobile,{{ rule }} # 风行视频
PROCESS-NAME,com.gameabc.zhanqiAndroid,{{ rule }} # 战旗直播
PROCESS-NAME,com.gamestar.perfectpiano,{{ rule }} # 完美钢琴
PROCESS-NAME,com.ganji.android.haoche_c,{{ rule }} # 瓜子二手车
PROCESS-NAME,com.gaotu100.superclass,{{ rule }} # 高途
PROCESS-NAME,com.gelonghui.glhapp,{{ rule }} # 格隆汇
PROCESS-NAME,com.gfqh.guangfa,{{ rule }} # 广发期货小添财-投资交易软件
PROCESS-NAME,com.gh.gamecenter,{{ rule }} # 光环助手
PROCESS-NAME,com.giiso.jinantimes,{{ rule }} # 新黄河
PROCESS-NAME,com.gioct.weather,{{ rule }} # 天气预报
PROCESS-NAME,com.glodon.drawingexplorer,{{ rule }} # CAD快速看图
PROCESS-NAME,com.gome.eshopnew,{{ rule }} # 国美-电器消费潮人的选择
PROCESS-NAME,com.gomejr.icash,{{ rule }} # 美易借钱
PROCESS-NAME,com.goodtech.tq,{{ rule }} # 天气预报
PROCESS-NAME,com.google.android.apps.translate,{{ rule }} # Google翻译
PROCESS-NAME,com.google.android.googlequicksearchbox,{{ rule }} # Google 搜索
PROCESS-NAME,com.gorgeous.lite,{{ rule }} # 轻颜
PROCESS-NAME,com.gotokeep.keep,{{ rule }} # Keep
PROCESS-NAME,com.greenline.guahao,{{ rule }} # 微医
PROCESS-NAME,com.greenpoint.android.mc10086.activity,{{ rule }} # 中国移动
PROCESS-NAME,com.greentree.android,{{ rule }} # 格林
PROCESS-NAME,com.gstarmc.android,{{ rule }} # CAD看图王
PROCESS-NAME,com.gtgj.view,{{ rule }} # 高铁管家
PROCESS-NAME,com.guosen.android,{{ rule }} # 国信金太阳
PROCESS-NAME,com.guotai.dazhihui,{{ rule }} # 国泰君安君弘
PROCESS-NAME,com.gwsoft.imusic.controller,{{ rule }} # 爱音乐
PROCESS-NAME,com.haier.uhome.uplus,{{ rule }} # 海尔智家
PROCESS-NAME,com.haixiu.ui,{{ rule }} # 嗨秀直播
PROCESS-NAME,com.haizhengqihuo.mhdxh,{{ rule }} # 上海证券期货
PROCESS-NAME,com.handsgo.jiakao.android,{{ rule }} # 驾考宝典
PROCESS-NAME,com.haodf.android,{{ rule }} # 好大夫在线
PROCESS-NAME,com.happyteam.dubbingshow,{{ rule }} # 配音秀
PROCESS-NAME,com.hazq.huiying.android,{{ rule }} # 华安证券
PROCESS-NAME,com.hcc.app,{{ rule }} # 捷信金融
PROCESS-NAME,com.hcyh.scanner,{{ rule }} # 扫描仪全能王
PROCESS-NAME,com.helplove.shbf,{{ rule }} # 社会扶贫
PROCESS-NAME,com.hexin.plat.android,{{ rule }} # 同花顺
PROCESS-NAME,com.hexin.plat.android.CaitongSecurity,{{ rule }} # 财通证券
PROCESS-NAME,com.hexin.plat.android.WanlianSecurity,{{ rule }} # 万联e万通
PROCESS-NAME,com.hexin.plat.android.ZhongyuanSecurity,{{ rule }} # 中原证券
PROCESS-NAME,com.hf,{{ rule }} # 中国天气
PROCESS-NAME,com.hichip,{{ rule }} # CamHi
PROCESS-NAME,com.hicorenational.antifraud,{{ rule }} # 国家反诈中心
PROCESS-NAME,com.hipu.yidian,{{ rule }} # 一点资讯
PROCESS-NAME,com.hlg.daydaytobusiness,{{ rule }} # 稿定设计
PROCESS-NAME,com.holyblade.cloud.platform,{{ rule }} # 蘑菇云游
PROCESS-NAME,com.homelink.android,{{ rule }} # 链家
PROCESS-NAME,com.hong.chenranse,{{ rule }} # 情趣淘成人购物商城
PROCESS-NAME,com.hongju.aishang,{{ rule }} # 情趣店
PROCESS-NAME,com.hongren.ui,{{ rule }} # 红人直播
PROCESS-NAME,com.HotelZhiDing.zhiding365,{{ rule }} # 直订
PROCESS-NAME,com.hp.android.printservice,{{ rule }} # HP 打印服务插件
PROCESS-NAME,com.hpbr.bosszhipin,{{ rule }} # BOSS直聘
PROCESS-NAME,com.hpplay.happycast,{{ rule }} # 乐播投屏
PROCESS-NAME,com.hrz.quick,{{ rule }} # 红人装极速版
PROCESS-NAME,com.htinns,{{ rule }} # 华住会
PROCESS-NAME,com.huajiao,{{ rule }} # 花椒直播
PROCESS-NAME,com.huataiqihuo.mhdxh,{{ rule }} # 华泰期货开户交易软件
PROCESS-NAME,com.huati,{{ rule }} # 葫芦侠3楼
PROCESS-NAME,com.huawei.android.findmyphone,{{ rule }} # 查找设备
PROCESS-NAME,com.huawei.fastapp,{{ rule }} # 快应用中心
PROCESS-NAME,com.huawei.hwid,{{ rule }} # HMS Core
PROCESS-NAME,com.huawei.hwvplayer.youku,{{ rule }} # 优酷经典版
PROCESS-NAME,com.huawei.intelligent,{{ rule }} # 智慧助手·今天
PROCESS-NAME,com.huawei.mycenter,{{ rule }} # 会员中心
PROCESS-NAME,com.huawei.smarthome,{{ rule }} # 智慧生活
PROCESS-NAME,com.huitouche.android.app,{{ rule }} # 省省原省省回头车
PROCESS-NAME,com.huluxia.gametools,{{ rule }} # 葫芦侠
PROCESS-NAME,com.hunantv.imgo.activity,{{ rule }} # 芒果TV
PROCESS-NAME,com.hundsun.stockwinner.cyqh,{{ rule }} # 创元期货
PROCESS-NAME,com.hundsun.stockwinner.gdzq,{{ rule }} # 光大证券金阳光
PROCESS-NAME,com.hundsun.stockwinner.gtjaqh,{{ rule }} # 国泰君安期货经典版
PROCESS-NAME,com.hundsun.stockwinner.haqh,{{ rule }} # 华安期货e通
PROCESS-NAME,com.hundsun.stockwinner.paqh,{{ rule }} # 平安期货
PROCESS-NAME,com.hundsun.stockwinner.yhqh,{{ rule }} # 银河期货专业版
PROCESS-NAME,com.hundsun.winner.pazq,{{ rule }} # 平安证券
PROCESS-NAME,com.huodao.hdphone,{{ rule }} # 找靓机
PROCESS-NAME,com.hupu.games,{{ rule }} # 虎扑
PROCESS-NAME,com.hupu.shihuo,{{ rule }} # 识货
PROCESS-NAME,com.huxiu,{{ rule }} # 虎嗅
PROCESS-NAME,com.huxiupro,{{ rule }} # 妙投
PROCESS-NAME,com.huyun.ybb,{{ rule }} # 运帮帮
PROCESS-NAME,com.hw.okm,{{ rule }} # 二三里
PROCESS-NAME,com.hxak.liangongbao,{{ rule }} # 链工宝
PROCESS-NAME,com.i61.draw.live,{{ rule }} # 画啦啦美术课堂
PROCESS-NAME,com.ibike.publicbicycle.activity,{{ rule }} # 永安行
PROCESS-NAME,com.ibox.calculators,{{ rule }} # 多多计算器
PROCESS-NAME,com.ibox.flashlight,{{ rule }} # 多多手电筒
PROCESS-NAME,com.iboxpay.minicashbox,{{ rule }} # 钱盒商户通
PROCESS-NAME,com.icbc,{{ rule }} # 中国工商银行
PROCESS-NAME,com.icbc.elife,{{ rule }} # 工银e生活
PROCESS-NAME,com.icbc.im,{{ rule }} # 工银融e联
PROCESS-NAME,com.ichinait.gbpassenger,{{ rule }} # 首汽约车
PROCESS-NAME,com.icoolme.android.weather,{{ rule }} # 最美天气
PROCESS-NAME,com.ifeimo.audiorecord,{{ rule }} # 录音大师
PROCESS-NAME,com.ifeimo.videoeditor,{{ rule }} # 视频剪辑大师
PROCESS-NAME,com.ifeng.news2,{{ rule }} # 凤凰新闻
PROCESS-NAME,com.ifeng.newvideo,{{ rule }} # 凤凰视频
PROCESS-NAME,com.iflytek.elpmobile.smartlearning,{{ rule }} # 智学网
PROCESS-NAME,com.iflytek.ringdiyclient,{{ rule }} # 酷音铃声
PROCESS-NAME,com.ifreetalk.ftalk,{{ rule }} # 派派
PROCESS-NAME,com.ihaozhuo.youjiankang,{{ rule }} # 优健康
PROCESS-NAME,com.ihuman.recite,{{ rule }} # 万词王
PROCESS-NAME,com.imaginer.yunji,{{ rule }} # 云集
PROCESS-NAME,com.immomo.momo,{{ rule }} # MOMO陌陌
PROCESS-NAME,com.imusic.iting,{{ rule }} # 爱听
PROCESS-NAME,com.infothinker.gzmetro,{{ rule }} # 广州地铁官方APP
PROCESS-NAME,com.insurance.agency,{{ rule }} # 亲亲小保
PROCESS-NAME,com.intsig.BizCardReader,{{ rule }} # 名片全能王
PROCESS-NAME,com.intsig.camscanner,{{ rule }} # 扫描全能王
PROCESS-NAME,com.iodkols.onekeylockscreen,{{ rule }} # 一键锁屏
PROCESS-NAME,com.iqilu.ksd,{{ rule }} # 闪电新闻
PROCESS-NAME,com.iqiyi.acg,{{ rule }} # 爱奇艺叭嗒
PROCESS-NAME,com.iqiyi.qixiu,{{ rule }} # 奇秀
PROCESS-NAME,com.ishowedu.child.peiyin,{{ rule }} # 少儿趣配音
PROCESS-NAME,com.ishowedu.peiyin,{{ rule }} # 英语趣配音
PROCESS-NAME,com.ishugui,{{ rule }} # 点众快看小说
PROCESS-NAME,com.iznet.thailandtong,{{ rule }} # 三毛游
PROCESS-NAME,com.jd.jrapp,{{ rule }} # 京东金融
PROCESS-NAME,com.jesson.meishi,{{ rule }} # 美食杰家常菜谱大全
PROCESS-NAME,com.jf.lkrj,{{ rule }} # 花生日记
PROCESS-NAME,com.jgkj.mwebview.jjl,{{ rule }} # 迦迦欢
PROCESS-NAME,com.jianshu.haruki,{{ rule }} # 简书
PROCESS-NAME,com.jianyou.swatch,{{ rule }} # 智能守护5
PROCESS-NAME,com.jianzhiku.zhongrenbang,{{ rule }} # 众人帮
PROCESS-NAME,com.jiaoliuqu.peipei,{{ rule }} # 恰聊
PROCESS-NAME,com.jiayuan,{{ rule }} # 世纪佳缘
PROCESS-NAME,com.jifen.qukan,{{ rule }} # 趣头条
PROCESS-NAME,com.jiliguala.niuwa,{{ rule }} # 叽里呱啦
PROCESS-NAME,com.jingdian.tianxiameishi.android,{{ rule }} # 美食天下
PROCESS-NAME,com.jingdong.app.mall,{{ rule }} # 京东
PROCESS-NAME,com.jingdong.pdj,{{ rule }} # 京东到家
PROCESS-NAME,com.jingyao.easybike,{{ rule }} # 哈啰
PROCESS-NAME,com.jinxin.namibox,{{ rule }} # 纳米盒
PROCESS-NAME,com.jiongji.andriod.card,{{ rule }} # 百词斩
PROCESS-NAME,com.jiuyan.infashion,{{ rule }} # in
PROCESS-NAME,com.job.android,{{ rule }} # 前程无忧51Job
PROCESS-NAME,com.johong.jiaxiaobaodian,{{ rule }} # 驾校宝
PROCESS-NAME,com.join.android.app.mgsim.wufun,{{ rule }} # 悟饭游戏厅
PROCESS-NAME,com.jojoread.huiben,{{ rule }} # 叫叫绘本
PROCESS-NAME,com.joyshebao.joy,{{ rule }} # 查悦社保
PROCESS-NAME,com.juejinchain.android,{{ rule }} # 掘金宝
PROCESS-NAME,com.julanling.app,{{ rule }} # 安心记加班
PROCESS-NAME,com.jurong.carok,{{ rule }} # 车车佳
PROCESS-NAME,com.jxedt,{{ rule }} # 驾校一点通
PROCESS-NAME,com.jy.recorder,{{ rule }} # 录屏精灵
PROCESS-NAME,com.jyyx.fuli,{{ rule }} # 九妖游戏
PROCESS-NAME,com.jzyd.coupon,{{ rule }} # 省钱快报
PROCESS-NAME,com.jzzs.ParentsHelper,{{ rule }} # 安全教育平台
PROCESS-NAME,com.kangluoer.tomato,{{ rule }} # 知富美聊
PROCESS-NAME,com.kaola,{{ rule }} # 考拉海购
PROCESS-NAME,com.king.weather,{{ rule }} # 天气王
PROCESS-NAME,com.Kingdee.Express,{{ rule }} # 快递100
PROCESS-NAME,com.kingsoft,{{ rule }} # 金山词霸
PROCESS-NAME,com.kky.picsartpubg,{{ rule }} # 视频剪辑软件
PROCESS-NAME,com.kmxs.reader,{{ rule }} # 七猫免费小说
PROCESS-NAME,com.knowbox.rc.student.pk,{{ rule }} # 小盒学习
PROCESS-NAME,com.komoxo.octopusime,{{ rule }} # 章鱼输入法
PROCESS-NAME,com.koudai.calendar,{{ rule }} # 口袋日历
PROCESS-NAME,com.koudai.recorder,{{ rule }} # 手机录音管家
PROCESS-NAME,com.koudai.weidian.buyer,{{ rule }} # 微店
PROCESS-NAME,com.koudai.weishop,{{ rule }} # 微店店长版
PROCESS-NAME,com.kuaiduizuoye.scan,{{ rule }} # 快对AI
PROCESS-NAME,com.kuaikan.comic,{{ rule }} # 快看漫画
PROCESS-NAME,com.kuaishou.nebula,{{ rule }} # 快手极速版
PROCESS-NAME,com.kuangxiangciweimao.novel,{{ rule }} # 刺猬猫阅读
PROCESS-NAME,com.kugou.android,{{ rule }} # 酷狗音乐
PROCESS-NAME,com.kugou.android.ktvapp,{{ rule }} # 酷狗唱唱
PROCESS-NAME,com.kugou.android.ringtone,{{ rule }} # 酷狗铃声
PROCESS-NAME,com.kugou.fanxing,{{ rule }} # 酷狗直播
PROCESS-NAME,com.kunpeng.babyting,{{ rule }} # 宝贝听听
PROCESS-NAME,com.kwai.livepartner,{{ rule }} # 快手直播伴侣
PROCESS-NAME,com.kwai.m2u,{{ rule }} # 一甜相机
PROCESS-NAME,com.kwai.thanos,{{ rule }} # 噗叽
PROCESS-NAME,com.kwai.videoeditor,{{ rule }} # 快影
PROCESS-NAME,com.laidian.xiu,{{ rule }} # 来电秀秀
PROCESS-NAME,com.lalamove.huolala.client,{{ rule }} # 货拉拉
PROCESS-NAME,com.lanjinger.choiassociatedpress,{{ rule }} # 财联社
PROCESS-NAME,com.lanjingren.ivwen,{{ rule }} # 美篇
PROCESS-NAME,com.laoyuegou.android,{{ rule }} # 捞月狗
PROCESS-NAME,com.le123.ysdq,{{ rule }} # 影视大全
PROCESS-NAME,com.lechuan.mdwz,{{ rule }} # 米读极速版
PROCESS-NAME,com.lechuan.midunovel,{{ rule }} # 米读小说
PROCESS-NAME,com.lehai.ui,{{ rule }} # 乐嗨直播
PROCESS-NAME,com.leixun.taofen8,{{ rule }} # 淘粉吧
PROCESS-NAME,com.leleketang.SchoolFantasy,{{ rule }} # 天天练
PROCESS-NAME,com.lemon.faceu,{{ rule }} # Faceu激萌
PROCESS-NAME,com.lemon.lv,{{ rule }} # 剪映
PROCESS-NAME,com.lenovo.leos.cloud.sync,{{ rule }} # 联想乐云
PROCESS-NAME,com.leqi.idpicture,{{ rule }} # 智能证件照
PROCESS-NAME,com.leqi.ProfessionalIDPhoto,{{ rule }} # 专业证件照
PROCESS-NAME,com.lft.turn,{{ rule }} # 导学号
PROCESS-NAME,com.lianjia.beike,{{ rule }} # 贝壳找房
PROCESS-NAME,com.lietou.mishu,{{ rule }} # 猎聘
PROCESS-NAME,com.lingan.seeyou,{{ rule }} # 美柚
PROCESS-NAME,com.lion.market,{{ rule }} # 虫虫助手
PROCESS-NAME,com.liulishuo.engzo,{{ rule }} # 流利说-英语
PROCESS-NAME,com.lltskb.lltskb,{{ rule }} # 路路通
PROCESS-NAME,com.lofter.android,{{ rule }} # 网易LOFTER
PROCESS-NAME,com.lovebizhi.wallpaper,{{ rule }} # 爱壁纸_桌面锁屏
PROCESS-NAME,com.lphtsccft,{{ rule }} # 涨乐财富通
PROCESS-NAME,com.lt.lighting,{{ rule }} # 来电闪光
PROCESS-NAME,com.lu.ashionweather,{{ rule }} # 天气预报
PROCESS-NAME,com.lucky.luckyclient,{{ rule }} # 瑞幸咖啡
PROCESS-NAME,com.ludashi.benchmark,{{ rule }} # 鲁大师
PROCESS-NAME,com.luojilab.player,{{ rule }} # 得到
PROCESS-NAME,com.luyun.diary,{{ rule }} # 每日记
PROCESS-NAME,com.lvka.mars,{{ rule }} # 火星
PROCESS-NAME,com.lvshiguan.app,{{ rule }} # 律师馆法律咨询
PROCESS-NAME,com.m4399.gamecenter,{{ rule }} # 4399游戏盒
PROCESS-NAME,com.macrovideo.v380,{{ rule }} # V380
PROCESS-NAME,com.magicpoint.mobile.bank,{{ rule }} # 重庆农商行
PROCESS-NAME,com.maihan.tredian,{{ rule }} # 淘最热点
PROCESS-NAME,com.mampod.ergedd,{{ rule }} # 儿歌点点
PROCESS-NAME,com.mandian.android.dongdong,{{ rule }} # 动动计步器
PROCESS-NAME,com.market2345,{{ rule }} # 2345手机助手
PROCESS-NAME,com.marryu,{{ rule }} # MarryU相亲交友
PROCESS-NAME,com.master.qrcode,{{ rule }} # 闪电扫码大师
PROCESS-NAME,com.max.xiaoheihe,{{ rule }} # 小黑盒
PROCESS-NAME,com.maxxipoint.android,{{ rule }} # 集享联盟
PROCESS-NAME,com.McDullpalm.bus,{{ rule }} # 麦兜掌上公交
PROCESS-NAME,com.meelive.ingkee,{{ rule }} # 映客直播
PROCESS-NAME,com.meichu.food.release,{{ rule }} # 烘培厨房
PROCESS-NAME,com.meitu.meipaimv,{{ rule }} # 美拍
PROCESS-NAME,com.meitu.meiyancamera,{{ rule }} # 美颜相机-AI换装
PROCESS-NAME,com.meitu.poster,{{ rule }} # 美图设计室
PROCESS-NAME,com.meitu.wheecam,{{ rule }} # 潮自拍
PROCESS-NAME,com.melot.meshow,{{ rule }} # KK
PROCESS-NAME,com.meta.box,{{ rule }} # 233乐园
PROCESS-NAME,com.mfw.roadbook,{{ rule }} # 马蜂窝
PROCESS-NAME,com.mfyueduqi.book,{{ rule }} # 爱看书极速版
PROCESS-NAME,com.mi.health,{{ rule }} # 小米运动健康
PROCESS-NAME,com.mianfeia.book,{{ rule }} # 爱看书免费小说
PROCESS-NAME,com.mianfeizs.book,{{ rule }} # 免费追书
PROCESS-NAME,com.microsoft.office.excel,{{ rule }} # Microsoft Excel
PROCESS-NAME,com.microsoft.office.onenote,{{ rule }} # OneNote
PROCESS-NAME,com.microsoft.office.outlook,{{ rule }} # Outlook
PROCESS-NAME,com.microsoft.office.powerpoint,{{ rule }} # Microsoft PowerPoint
PROCESS-NAME,com.microsoft.office.word,{{ rule }} # Microsoft Word
PROCESS-NAME,com.midea.ai.appliances,{{ rule }} # 美的美居
PROCESS-NAME,com.midea.vm.washer,{{ rule }} # U净
PROCESS-NAME,com.mini.bill,{{ rule }} # 口袋账本
PROCESS-NAME,com.mm.android.lc,{{ rule }} # 乐橙
PROCESS-NAME,com.MobileTicket,{{ rule }} # 铁路12306
PROCESS-NAME,com.mobivans.onestrokecharge,{{ rule }} # 预记智能账本
PROCESS-NAME,com.mogujie,{{ rule }} # 蘑菇街
PROCESS-NAME,com.moji.mjweather,{{ rule }} # 墨迹天气
PROCESS-NAME,com.monarch.memory,{{ rule }} # 内存清理君
PROCESS-NAME,com.mosheng,{{ rule }} # 爱聊
PROCESS-NAME,com.motoband,{{ rule }} # 摩托邦
PROCESS-NAME,com.moyu.moyu,{{ rule }} # 墨鱼旅行
PROCESS-NAME,com.msxf.ayh,{{ rule }} # 安逸花
PROCESS-NAME,com.msxf.loan,{{ rule }} # 马上金融
PROCESS-NAME,com.mt.mtxx.mtxx,{{ rule }} # 美图秀秀
PROCESS-NAME,com.mybank.android.phone,{{ rule }} # 网商银行
PROCESS-NAME,com.mygolbs.mybus,{{ rule }} # 掌上公交
PROCESS-NAME,com.mymoney,{{ rule }} # 随手记
PROCESS-NAME,com.mymoney.sms,{{ rule }} # 卡牛信用管家
PROCESS-NAME,com.myzaker.ZAKER_Phone,{{ rule }} # ZAKER
PROCESS-NAME,com.n_add.android,{{ rule }} # 粉象生活
PROCESS-NAME,com.nade.ownerride,{{ rule }} # 顺风车司机版
PROCESS-NAME,com.nade.tickowner,{{ rule }} # 滴答出行司机端
PROCESS-NAME,com.nanyibang.nomi,{{ rule }} # 男衣邦穿衣搭配
PROCESS-NAME,com.nanyibang.rm,{{ rule }} # 穿衣有品
PROCESS-NAME,com.NationalPhotograpy.weishoot,{{ rule }} # 微摄
PROCESS-NAME,com.nd.android.pandahome2,{{ rule }} # 91桌面
PROCESS-NAME,com.nd.android.pandareader,{{ rule }} # 熊猫看书
PROCESS-NAME,com.netease.cloudmusic,{{ rule }} # 网易云音乐
PROCESS-NAME,com.netease.edu.ucmooc,{{ rule }} # 中国大学MOOC
PROCESS-NAME,com.netease.gl,{{ rule }} # 网易大神
PROCESS-NAME,com.netease.mail,{{ rule }} # 网易邮箱大师
PROCESS-NAME,com.netease.mkey,{{ rule }} # 网易将军令
PROCESS-NAME,com.netease.mobimail,{{ rule }} # 网易邮箱
PROCESS-NAME,com.netease.newsreader.activity,{{ rule }} # 网易新闻
PROCESS-NAME,com.netease.pris,{{ rule }} # 网易云阅读
PROCESS-NAME,com.netease.uu,{{ rule }} # UU加速器
PROCESS-NAME,com.netease.vopen,{{ rule }} # 网易公开课
PROCESS-NAME,com.neusoft.app.beijingdaily.phone,{{ rule }} # 北京日报
PROCESS-NAME,com.news.shangyounews,{{ rule }} # 上游新闻
PROCESS-NAME,com.nfdaily.nfplus,{{ rule }} # 南方Plus
PROCESS-NAME,com.nice.main,{{ rule }} # nice
PROCESS-NAME,com.ninexiu.sixninexiu,{{ rule }} # 九秀直播
PROCESS-NAME,com.nxy.sc,{{ rule }} # 四川农信手机银行
PROCESS-NAME,com.octinn.birthdayplus,{{ rule }} # 生日管家
PROCESS-NAME,com.ophone.reader.ui,{{ rule }} # 咪咕阅读
PROCESS-NAME,com.oppo.store,{{ rule }} # OPPO商城
PROCESS-NAME,com.oupeng.mini.android,{{ rule }} # 欧朋浏览器
PROCESS-NAME,com.ovital.ovitalMap,{{ rule }} # 奥维互动地图
PROCESS-NAME,com.p1.mobile.putong,{{ rule }} # 探探
PROCESS-NAME,com.paem,{{ rule }} # 平安担保
PROCESS-NAME,com.paic.yl.health,{{ rule }} # 好福利
PROCESS-NAME,com.paic.zhifu.wallet.activity,{{ rule }} # 壹钱包
PROCESS-NAME,com.pdmi.guangzhou.media,{{ rule }} # 广州日报新花城
PROCESS-NAME,com.people.health.doctor,{{ rule }} # 人民好医生
PROCESS-NAME,com.peopledailychina.activity,{{ rule }} # 人民日报
PROCESS-NAME,com.phoenix.read,{{ rule }} # 红果免费短剧
PROCESS-NAME,com.phone.recording,{{ rule }} # 电话录音宝
PROCESS-NAME,com.pingan.carowner,{{ rule }} # 平安好车主
PROCESS-NAME,com.pingan.lifeinsurance,{{ rule }} # 平安金管家
PROCESS-NAME,com.pingan.paces.ccms,{{ rule }} # 平安口袋银行
PROCESS-NAME,com.plan.master,{{ rule }} # 计划大师
PROCESS-NAME,com.ppdai.loan,{{ rule }} # 拍拍贷借款
PROCESS-NAME,com.pplive.androidphone,{{ rule }} # PP视频
PROCESS-NAME,com.pplive.androidphone.sport,{{ rule }} # PP体育
PROCESS-NAME,com.qclianai.com,{{ rule }} # 全城恋爱
PROCESS-NAME,com.qdruotu.app,{{ rule }} # 若途旅行
PROCESS-NAME,com.qidian.QDReader,{{ rule }} # 起点读书
PROCESS-NAME,com.qihoo.appstore,{{ rule }} # 360手机助手
PROCESS-NAME,com.qihoo.browser,{{ rule }} # 360浏览器
PROCESS-NAME,com.qihoo.camera,{{ rule }} # 360摄像机
PROCESS-NAME,com.qihoo.loan,{{ rule }} # 奇富借条(原360借条)
PROCESS-NAME,com.qihoo.magic,{{ rule }} # 分身大师
PROCESS-NAME,com.qihoo360.antilostwatch,{{ rule }} # 360儿童卫士
PROCESS-NAME,com.qihoo360.mobilesafe,{{ rule }} # 360手机卫士
PROCESS-NAME,com.qihuo.changjiang,{{ rule }} # 长江期货开户交易
PROCESS-NAME,com.qihuo.yinhe,{{ rule }} # 银河期货开户交易
PROCESS-NAME,com.qinhe.ispeak,{{ rule }} # IS语音
PROCESS-NAME,com.qiyi.video,{{ rule }} # 爱奇艺
PROCESS-NAME,com.qiyi.video.child,{{ rule }} # 爱奇艺奇巴布
PROCESS-NAME,com.qiyi.video.lite,{{ rule }} # 爱奇艺极速版
PROCESS-NAME,com.qiyi.video.pad,{{ rule }} # 爱奇艺PAD
PROCESS-NAME,com.qiyi.video.reader,{{ rule }} # 爱奇艺小说
PROCESS-NAME,com.qlscupgrade,{{ rule }} # 中泰齐富通
PROCESS-NAME,com.qq.ac.android,{{ rule }} # 腾讯动漫
PROCESS-NAME,com.qq.qcloud,{{ rule }} # 微云
PROCESS-NAME,com.qq.reader,{{ rule }} # QQ阅读
PROCESS-NAME,com.qsmy.walkmonkey,{{ rule }} # 步多多
PROCESS-NAME,com.qtx.qtxty,{{ rule }} # 球天下体育
PROCESS-NAME,com.quanleimu.activity,{{ rule }} # 百姓网
PROCESS-NAME,com.quanmai.findu,{{ rule }} # 饭友
PROCESS-NAME,com.quark.browser,{{ rule }} # 夸克
PROCESS-NAME,com.Qunar,{{ rule }} # 去哪儿旅行
PROCESS-NAME,com.qzone,{{ rule }} # QQ空间
PROCESS-NAME,com.renren.mobile.android,{{ rule }} # 人人直播
PROCESS-NAME,com.renrendai.haohuan,{{ rule }} # 好分期
PROCESS-NAME,com.renxing.xys,{{ rule }} # 性用社
PROCESS-NAME,com.rong.fastloan,{{ rule }} # 时光分期
PROCESS-NAME,com.rong360.app,{{ rule }} # 融360
PROCESS-NAME,com.rosedate.siye,{{ rule }} # 玫瑰约会视频聊天交友
PROCESS-NAME,com.rrh.jdb,{{ rule }} # 借贷宝
PROCESS-NAME,com.runbey.ybjk,{{ rule }} # 元贝驾考
PROCESS-NAME,com.samoyed.credit,{{ rule }} # 省呗
PROCESS-NAME,com.samsung.android.app.watchmanager,{{ rule }} # 三星智能穿戴
PROCESS-NAME,com.sankuai.meituan,{{ rule }} # 美团
PROCESS-NAME,com.sankuai.meituan.meituanwaimaibusiness,{{ rule }} # 美团外卖商家版
PROCESS-NAME,com.sankuai.meituan.merchant,{{ rule }} # 美团开店宝
PROCESS-NAME,com.sankuai.meituan.takeoutnew,{{ rule }} # 美团外卖
PROCESS-NAME,com.sankuai.movie,{{ rule }} # 猫眼
PROCESS-NAME,com.sanmu.liaoliaoba,{{ rule }} # 聊聊吧
PROCESS-NAME,com.sbds.miaoyin,{{ rule }} # 秒音
PROCESS-NAME,com.screeclibinvoke,{{ rule }} # 录屏大师
PROCESS-NAME,com.sdbean.werewolf,{{ rule }} # 天天狼人
PROCESS-NAME,com.sdu.didi.gsui,{{ rule }} # 滴滴车主
PROCESS-NAME,com.sdu.didi.psnger,{{ rule }} # 滴滴出行
PROCESS-NAME,com.sec.android.app.shealth,{{ rule }} # 三星健康
PROCESS-NAME,com.sec.android.easyMover,{{ rule }} # S 换机助手
PROCESS-NAME,com.seebaby,{{ rule }} # 掌通家园
PROCESS-NAME,com.seetong.app.seetong,{{ rule }} # Seetong
PROCESS-NAME,com.seewo.easicare.pro,{{ rule }} # 班级优化大师
PROCESS-NAME,com.sender.yiwei,{{ rule }} # 一喂宠物托运
PROCESS-NAME,com.sevenplus.chinascience,{{ rule }} # 科普中国
PROCESS-NAME,com.sf.activity,{{ rule }} # 顺丰速运
PROCESS-NAME,com.sgcc.wsgw.cn,{{ rule }} # 网上国网
PROCESS-NAME,com.shabro.android.activity,{{ rule }} # 沙师弟司机
PROCESS-NAME,com.shangbiao.activity,{{ rule }} # 尚标商标转让
PROCESS-NAME,com.shangbiao.searchsb86,{{ rule }} # 尚标商标注册查询
PROCESS-NAME,com.shangfang.gylm,{{ rule }} # 高佣联盟
PROCESS-NAME,com.shangshaban.zhaopin.activity,{{ rule }} # 上啥班
PROCESS-NAME,com.shenghuoquan,{{ rule }} # 生活圈
PROCESS-NAME,com.shengqianyxlmw,{{ rule }} # 省钱优选联盟
PROCESS-NAME,com.shfy.voice,{{ rule }} # 和平吃鸡变声器
PROCESS-NAME,com.shiyue.fensigou,{{ rule }} # 粉丝福利购
PROCESS-NAME,com.shizhuang.duapp,{{ rule }} # 得物
PROCESS-NAME,com.shoujiduoduo.dj,{{ rule }} # DJ多多
PROCESS-NAME,com.shoujiduoduo.ringtone,{{ rule }} # 铃声多多
PROCESS-NAME,com.shoujiduoduo.wallpaper,{{ rule }} # 壁纸多多
PROCESS-NAME,com.showself.ui,{{ rule }} # 秀色直播
PROCESS-NAME,com.shsc.gen,{{ rule }} # 上海证券
PROCESS-NAME,com.shuhekeji,{{ rule }} # 还呗
PROCESS-NAME,com.shulantech.video,{{ rule }} # 视频转换压缩
PROCESS-NAME,com.shunlian.app,{{ rule }} # 顺联动力商城
PROCESS-NAME,com.shuqi.controller,{{ rule }} # 书旗小说
PROCESS-NAME,com.shuqu.banyan,{{ rule }} # 榕树贷款
PROCESS-NAME,com.shusheng.JoJoRead,{{ rule }} # 叫叫
PROCESS-NAME,com.shyz.toutiao,{{ rule }} # 清理大师
PROCESS-NAME,com.sina.news,{{ rule }} # 新浪新闻
PROCESS-NAME,com.sina.weibo,{{ rule }} # 微博
PROCESS-NAME,com.sina.weibog3,{{ rule }} # 新浪微博4G版
PROCESS-NAME,com.sina.weibolite,{{ rule }} # 微博极速版
PROCESS-NAME,com.sing.client,{{ rule }} # 5sing音乐
PROCESS-NAME,com.sinovatech.unicom.ui,{{ rule }} # 中国联通
PROCESS-NAME,com.sinyee.babybus.amusement,{{ rule }} # 奇妙科普馆
PROCESS-NAME,com.sinyee.babybus.babyhospital,{{ rule }} # 宝宝医院
PROCESS-NAME,com.sinyee.babybus.chants,{{ rule }} # 宝宝巴士儿歌
PROCESS-NAME,com.sinyee.babybus.chef,{{ rule }} # 宝宝小厨房
PROCESS-NAME,com.sinyee.babybus.drinks,{{ rule }} # 宝宝甜品店
PROCESS-NAME,com.sinyee.babybus.food,{{ rule }} # 中华美食
PROCESS-NAME,com.sinyee.babybus.kindergarten,{{ rule }} # 宝宝欢乐教室
PROCESS-NAME,com.sinyee.babybus.recommendapp,{{ rule }} # 宝宝巴士
PROCESS-NAME,com.sinyee.babybus.shopping,{{ rule }} # 宝宝超市
PROCESS-NAME,com.sinyee.babybus.talk2kiki,{{ rule }} # 宝宝巴士奇妙屋
PROCESS-NAME,com.site.maigoo,{{ rule }} # 买购十大品牌排行榜
PROCESS-NAME,com.sjsj.clockapp.clockmaster,{{ rule }} # 即刻闹钟
PROCESS-NAME,com.skyplatanus.crucio,{{ rule }} # 快点阅读
PROCESS-NAME,com.slanissue.apps.mobile.erge,{{ rule }} # 贝瓦儿歌
PROCESS-NAME,com.smallyin.musiceditor,{{ rule }} # 音乐剪辑助手
PROCESS-NAME,com.smile.gifmaker,{{ rule }} # 快手
PROCESS-NAME,com.smzdm.client.android,{{ rule }} # 什么值得买
PROCESS-NAME,com.snda.lantern.wifilocating,{{ rule }} # WiFi万能钥匙极速版
PROCESS-NAME,com.snda.wifilocating,{{ rule }} # WiFi万能钥匙
PROCESS-NAME,com.soft.blued,{{ rule }} # Blued
PROCESS-NAME,com.sohu.infonews,{{ rule }} # 搜狐资讯
PROCESS-NAME,com.sohu.inputmethod.sogou,{{ rule }} # 搜狗输入法
PROCESS-NAME,com.sohu.newsclient,{{ rule }} # 搜狐新闻
PROCESS-NAME,com.sohu.sohuvideo,{{ rule }} # 搜狐视频
PROCESS-NAME,com.sohu.tv,{{ rule }} # 搜狐视频HD
PROCESS-NAME,com.songguoyhqw,{{ rule }} # 赚钱联盟
PROCESS-NAME,com.spdbccc.app,{{ rule }} # 浦大喜奔
PROCESS-NAME,com.speed.master,{{ rule }} # 网络测速大师
PROCESS-NAME,com.speed.qrcode.release,{{ rule }} # 极速二维码
PROCESS-NAME,com.speedsoftware.rootexplorer,{{ rule }} # RE文件管理器
PROCESS-NAME,com.splingsheng.ringtone,{{ rule }} # 视频铃声来电秀
PROCESS-NAME,com.ss.android.article.lite,{{ rule }} # 今日头条极速版
PROCESS-NAME,com.ss.android.article.news,{{ rule }} # 今日头条
PROCESS-NAME,com.ss.android.article.video,{{ rule }} # 西瓜视频
PROCESS-NAME,com.ss.android.auto,{{ rule }} # 懂车帝
PROCESS-NAME,com.ss.android.ugc.aweme,{{ rule }} # 抖音
PROCESS-NAME,com.ss.android.ugc.aweme.lite,{{ rule }} # 抖音极速版
PROCESS-NAME,com.ss.android.ugc.live,{{ rule }} # 抖音火山版
PROCESS-NAME,com.sskj.flashlight,{{ rule }} # 随手电筒
PROCESS-NAME,com.ssxg.cheers,{{ rule }} # 悦享
PROCESS-NAME,com.starbucks.cn,{{ rule }} # 星巴克
PROCESS-NAME,com.stone.bill,{{ rule }} # 石头记账
PROCESS-NAME,com.storm.smart,{{ rule }} # 暴风影音
PROCESS-NAME,com.student.yuwen.yimilan,{{ rule }} # 一米阅读
PROCESS-NAME,com.suddenfix.customer,{{ rule }} # 闪电修
PROCESS-NAME,com.suning.mobile.ebuy,{{ rule }} # 苏宁易购
PROCESS-NAME,com.suning.mobile.epa,{{ rule }} # 星图金融
PROCESS-NAME,com.suteng.zzss480,{{ rule }} # 趣拿
PROCESS-NAME,com.sxm.farpoolcar,{{ rule }} # 拼车
PROCESS-NAME,com.sxm.yiwei,{{ rule }} # 一喂顺风车
PROCESS-NAME,com.szyy2106.pdfscanner,{{ rule }} # 扫描王PDF
PROCESS-NAME,com.szzc,{{ rule }} # 神州租车
PROCESS-NAME,com.szzc.ucar.pilot,{{ rule }} # 神州专车
PROCESS-NAME,com.talent.food,{{ rule }} # 做菜达人
PROCESS-NAME,com.tanyu.me,{{ rule }} # 探遇漂流瓶
PROCESS-NAME,com.taobao.etao,{{ rule }} # 一淘
PROCESS-NAME,com.taobao.idlefish,{{ rule }} # 闲鱼
PROCESS-NAME,com.taobao.litetao,{{ rule }} # 淘宝特价版
PROCESS-NAME,com.taobao.movie.android,{{ rule }} # 淘票票
PROCESS-NAME,com.taobao.qianniu,{{ rule }} # 千牛
PROCESS-NAME,com.taobao.taobao,{{ rule }} # 淘宝
PROCESS-NAME,com.taobao.trip,{{ rule }} # 飞猪旅行
PROCESS-NAME,com.taou.maimai,{{ rule }} # 脉脉
PROCESS-NAME,com.taowuyou.tbk,{{ rule }} # 淘无忧
PROCESS-NAME,com.teamnet.hula,{{ rule }} # 粤听
PROCESS-NAME,com.tencent.androidqqmail,{{ rule }} # QQ邮箱
PROCESS-NAME,com.tencent.djcity,{{ rule }} # 掌上道聚城
PROCESS-NAME,com.tencent.gallerymanager,{{ rule }} # 腾讯相册管家
PROCESS-NAME,com.tencent.gamehelper,{{ rule }} # 腾讯游戏助手
PROCESS-NAME,com.tencent.gamehelper.dnf,{{ rule }} # DNF助手
PROCESS-NAME,com.tencent.gamehelper.nz,{{ rule }} # 逆战助手
PROCESS-NAME,com.tencent.gamehelper.pg,{{ rule }} # 和平营地
PROCESS-NAME,com.tencent.gamehelper.smoba,{{ rule }} # 王者营地
PROCESS-NAME,com.tencent.gamehelper.speed,{{ rule }} # 掌上飞车
PROCESS-NAME,com.tencent.gamereva,{{ rule }} # 腾讯先锋（云游戏）
PROCESS-NAME,com.tencent.igame,{{ rule }} # 王者人生
PROCESS-NAME,com.tencent.karaoke,{{ rule }} # 全民K歌
PROCESS-NAME,com.tencent.map,{{ rule }} # 腾讯地图
PROCESS-NAME,com.tencent.mm,{{ rule }} # 微信
PROCESS-NAME,com.tencent.mobileqq,{{ rule }} # QQ
PROCESS-NAME,com.tencent.mtt,{{ rule }} # QQ浏览器
PROCESS-NAME,com.tencent.news,{{ rule }} # 腾讯新闻
PROCESS-NAME,com.tencent.portfolio,{{ rule }} # 腾讯自选股
PROCESS-NAME,com.tencent.qqgame,{{ rule }} # QQ游戏
PROCESS-NAME,com.tencent.qqlive,{{ rule }} # 腾讯视频
PROCESS-NAME,com.tencent.qqlivekid,{{ rule }} # 小企鹅乐园
PROCESS-NAME,com.tencent.qqmusic,{{ rule }} # QQ音乐
PROCESS-NAME,com.tencent.qqpim,{{ rule }} # QQ同步助手
PROCESS-NAME,com.tencent.qqpimsecure,{{ rule }} # 腾讯手机管家
PROCESS-NAME,com.tencent.qqsports,{{ rule }} # 腾讯体育
PROCESS-NAME,com.tencent.qt.qtl,{{ rule }} # 掌上英雄联盟
PROCESS-NAME,com.tencent.qt.sns,{{ rule }} # 掌上穿越火线
PROCESS-NAME,com.tencent.tgclub,{{ rule }} # 心悦俱乐部
PROCESS-NAME,com.tencent.tim,{{ rule }} # TIM
PROCESS-NAME,com.tencent.token,{{ rule }} # QQ安全中心
PROCESS-NAME,com.tencent.transfer,{{ rule }} # 换机助手
PROCESS-NAME,com.tencent.ttpic,{{ rule }} # 天天P图
PROCESS-NAME,com.tencent.weishi,{{ rule }} # 腾讯微视
PROCESS-NAME,com.tencent.wemeet.app,{{ rule }} # 腾讯会议
PROCESS-NAME,com.tencent.weread,{{ rule }} # 微信读书
PROCESS-NAME,com.tencent.wework,{{ rule }} # 企业微信
PROCESS-NAME,com.tencent.zebra,{{ rule }} # 水印相机
PROCESS-NAME,com.tgelec.aqsh,{{ rule }} # 安全守护2
PROCESS-NAME,com.thestore.main,{{ rule }} # 1号会员店
PROCESS-NAME,com.thinkive.mobile.open.account.huaan,{{ rule }} # 华安证券手机开户
PROCESS-NAME,com.threegene.yeemiao,{{ rule }} # 小豆苗
PROCESS-NAME,com.tianqi2345,{{ rule }} # 2345天气预报
PROCESS-NAME,com.tianqi8.weather,{{ rule }} # 天气吧
PROCESS-NAME,com.tianqiyubao2345,{{ rule }} # 15日天气预报
PROCESS-NAME,com.tianwen.jjrb,{{ rule }} # 经济日报
PROCESS-NAME,com.tieyou.train.ark,{{ rule }} # 铁友火车票
PROCESS-NAME,com.ting.mp3.android,{{ rule }} # 千千音乐
PROCESS-NAME,com.tingniu.audioclip,{{ rule }} # 音频剪辑大师
PROCESS-NAME,com.tinmanarts.JoJoSherlock,{{ rule }} # 叫叫识字
PROCESS-NAME,com.tiqiaa.icontrol,{{ rule }} # 遥控精灵
PROCESS-NAME,com.tmall.wireless,{{ rule }} # 天猫
PROCESS-NAME,com.tmri.app.main,{{ rule }} # 交管12123
PROCESS-NAME,com.tongcheng.android,{{ rule }} # 同程旅行
PROCESS-NAME,com.tongchengpzhl.com,{{ rule }} # 同城品质婚恋
PROCESS-NAME,com.tonghuashun.stocktrade.gtjaqh,{{ rule }} # 国泰君安掌上期货
PROCESS-NAME,com.tongzhuo.tongzhuogame,{{ rule }} # 同桌派对
PROCESS-NAME,com.touchtv.touchtv,{{ rule }} # 触电新闻
PROCESS-NAME,com.translate.english,{{ rule }} # 英语翻译君
PROCESS-NAME,com.trip.housekeeper,{{ rule }} # 日程管家
PROCESS-NAME,com.tripadvisor.tripadvisor.daodao,{{ rule }} # Tripadvisor猫途鹰
PROCESS-NAME,com.truedian.dragon,{{ rule }} # 微购相册
PROCESS-NAME,com.tttci.tik,{{ rule }} # 提词器
PROCESS-NAME,com.tudou.android,{{ rule }} # 土豆
PROCESS-NAME,com.tujia.hotel,{{ rule }} # 途家民宿
PROCESS-NAME,com.twentyfirstcbh.epaper,{{ rule }} # 21财经
PROCESS-NAME,com.ubestkid.beilehu.android,{{ rule }} # 贝乐虎儿歌
PROCESS-NAME,com.ucar.app,{{ rule }} # 淘车车
PROCESS-NAME,com.UCMobile,{{ rule }} # UC浏览器
PROCESS-NAME,com.ucmobile.lite,{{ rule }} # UC浏览器极速版
PROCESS-NAME,com.ujigu.ytb,{{ rule }} # 优题宝
PROCESS-NAME,com.ume.browser,{{ rule }} # 微米浏览器
PROCESS-NAME,com.umetrip.android.msky.app,{{ rule }} # 航旅纵横
PROCESS-NAME,com.unionpay,{{ rule }} # 云闪付
PROCESS-NAME,com.universal.compass,{{ rule }} # 全能指南针
PROCESS-NAME,com.universal.control,{{ rule }} # 万能遥控器+
PROCESS-NAME,com.ushaqi.zhuishushenqi,{{ rule }} # 追书神器
PROCESS-NAME,com.uxin.usedcar,{{ rule }} # 优信二手车
PROCESS-NAME,com.v2gogo.project,{{ rule }} # 百姓关注
PROCESS-NAME,com.vbill.shoushua.biz,{{ rule }} # 随行付Plus
PROCESS-NAME,com.vcredit.ddcash,{{ rule }} # 豆豆钱
PROCESS-NAME,com.vcredit.kkcredit,{{ rule }} # 维信卡卡贷
PROCESS-NAME,com.video.clip,{{ rule }} # 视频拼接王
PROCESS-NAME,com.videogo,{{ rule }} # 萤石云视频
PROCESS-NAME,com.vivo.easyshare,{{ rule }} # 互传
PROCESS-NAME,com.vivo.space,{{ rule }} # vivo 官网
PROCESS-NAME,com.wacai365,{{ rule }} # 挖财记账
PROCESS-NAME,com.wakeup.howear,{{ rule }} # Wearfit Pro
PROCESS-NAME,com.wakeyoga.wakeyoga,{{ rule }} # Wake瑜伽
PROCESS-NAME,com.wali.live,{{ rule }} # 白金秀
PROCESS-NAME,com.wandafilm.app,{{ rule }} # 万达电影
PROCESS-NAME,com.wandoujia.phoenix2,{{ rule }} # 豌豆荚
PROCESS-NAME,com.we.keyuan,{{ rule }} # 微商码头
PROCESS-NAME,com.webank.wemoney,{{ rule }} # 微众银行
PROCESS-NAME,com.weface.kksocialsecurity,{{ rule }} # 看看生活
PROCESS-NAME,com.welove520.welove,{{ rule }} # 微爱
PROCESS-NAME,com.wemall.onlineshopping,{{ rule }} # WEMALL
PROCESS-NAME,com.wglianmeng,{{ rule }} # 网购联盟
PROCESS-NAME,com.when.coco,{{ rule }} # 365日历
PROCESS-NAME,com.wifi.reader,{{ rule }} # 连尚读书
PROCESS-NAME,com.wifi.reader.free,{{ rule }} # 连尚免费读书
PROCESS-NAME,com.winbaoxian.wybx,{{ rule }} # 保险师
PROCESS-NAME,com.winderinfo.yashanghui,{{ rule }} # 雅商汇荟
PROCESS-NAME,com.wjkj.loosrun,{{ rule }} # 电子红包
PROCESS-NAME,com.wkjyqh.wukuangqihuo,{{ rule }} # 五矿期货
PROCESS-NAME,com.wkscuiphone,{{ rule }} # 五矿证券
PROCESS-NAME,com.wlqq,{{ rule }} # 货车帮司机
PROCESS-NAME,com.wlqq4consignor,{{ rule }} # 货车帮货主
PROCESS-NAME,com.wm.dmall,{{ rule }} # 多点
PROCESS-NAME,com.wodan.xianshijian,{{ rule }} # 兼客兼职
PROCESS-NAME,com.wodi.who,{{ rule }} # 玩吧
PROCESS-NAME,com.wondertek.miguaikan,{{ rule }} # 咪咕视频爱看版
PROCESS-NAME,com.wondertek.paper,{{ rule }} # 澎湃新闻
PROCESS-NAME,com.woqu.attendance,{{ rule }} # 喔趣考勤
PROCESS-NAME,com.words.english,{{ rule }} # 英语单词君
PROCESS-NAME,com.work.clock,{{ rule }} # 起床闹铃
PROCESS-NAME,com.wsecar.wsjc,{{ rule }} # 万顺叫车
PROCESS-NAME,com.wshifu.app.jiedanyi,{{ rule }} # 万师傅师傅版
PROCESS-NAME,com.wuba,{{ rule }} # 58同城
PROCESS-NAME,com.wuba.zhuanzhuan,{{ rule }} # 转转
PROCESS-NAME,com.wudaokou.hippo,{{ rule }} # 盒马
PROCESS-NAME,com.xcsc.tdxapp,{{ rule }} # 湘财证券
PROCESS-NAME,com.xfplay.play,{{ rule }} # 影音先锋
PROCESS-NAME,com.xhey.xcamera,{{ rule }} # 今日水印相机
PROCESS-NAME,com.xhqb.app,{{ rule }} # 小花钱包
PROCESS-NAME,com.xiachufang,{{ rule }} # 下厨房
PROCESS-NAME,com.xiangha,{{ rule }} # 香哈菜谱
PROCESS-NAME,com.xiangrikui.sixapp,{{ rule }} # 向日葵保险人
PROCESS-NAME,com.xiaobanlong.main,{{ rule }} # 小伴龙
PROCESS-NAME,com.xiaodao.jiemeng,{{ rule }} # 复真书法
PROCESS-NAME,com.xiaoenai.app,{{ rule }} # 小恩爱
PROCESS-NAME,com.xiaoji.emulator,{{ rule }} # 小鸡模拟器
PROCESS-NAME,com.xiaomi.hm.health,{{ rule }} # Zepp Life
PROCESS-NAME,com.xiaomi.jr,{{ rule }} # 天星金融
PROCESS-NAME,com.xiaomi.mico,{{ rule }} # 小爱音箱
PROCESS-NAME,com.xiaomi.mitv.phone.tvassistant,{{ rule }} # 小米电视助手
PROCESS-NAME,com.xiaomi.shop,{{ rule }} # 小米商城
PROCESS-NAME,com.xiaomi.smarthome,{{ rule }} # 米家
PROCESS-NAME,com.xiaomi.youpin,{{ rule }} # 小米有品
PROCESS-NAME,com.xiaoshijie.sqb,{{ rule }} # 好省
PROCESS-NAME,com.xiaoying.cardloan,{{ rule }} # 小赢卡贷
PROCESS-NAME,com.xiaozhu.xzdz,{{ rule }} # 小猪民宿
PROCESS-NAME,com.ximalaya.ting.android,{{ rule }} # 喜马拉雅
PROCESS-NAME,com.xingin.xhs,{{ rule }} # 小红书
PROCESS-NAME,com.xingjiabi.shengsheng,{{ rule }} # 他趣
PROCESS-NAME,com.xingluo.mpa,{{ rule }} # 魔力相册
PROCESS-NAME,com.xinhu.futures,{{ rule }} # 新湖期货开户交易
PROCESS-NAME,com.xinyongfei.xyf,{{ rule }} # 信用飞
PROCESS-NAME,com.xiongmaoqiming.quming,{{ rule }} # 熊猫起名
PROCESS-NAME,com.xiuyuan.phonelive,{{ rule }} # 秀员
PROCESS-NAME,com.xiwei.logistics,{{ rule }} # 运满满司机
PROCESS-NAME,com.xiwei.logistics.consignor,{{ rule }} # 运满满货主
PROCESS-NAME,com.xk.span.zutuan,{{ rule }} # 美逛
PROCESS-NAME,com.xs.fm,{{ rule }} # 番茄畅听
PROCESS-NAME,com.xt.retouch,{{ rule }} # 醒图
PROCESS-NAME,com.xtc.watch,{{ rule }} # 小天才
PROCESS-NAME,com.xtuone.android.syllabus,{{ rule }} # 超级课程表
PROCESS-NAME,com.xueersi.parentsmeeting,{{ rule }} # 学而思网校
PROCESS-NAME,com.xueqiu.android,{{ rule }} # 雪球
PROCESS-NAME,com.xunlei.downloadprovider,{{ rule }} # 迅雷
PROCESS-NAME,com.xunmeng.pinduoduo,{{ rule }} # 拼多多
PROCESS-NAME,com.xvideostudio.videoeditor,{{ rule }} # 乐秀视频剪辑视频编辑
PROCESS-NAME,com.yangcong345.android.phone,{{ rule }} # 洋葱学园
PROCESS-NAME,com.yaya.zone,{{ rule }} # 叮咚买菜
PROCESS-NAME,com.ycwb.android.ycpai,{{ rule }} # 羊城派
PROCESS-NAME,com.yek.android.kfc.activitys,{{ rule }} # 肯德基
PROCESS-NAME,com.ygkj.chelaile.standard,{{ rule }} # 车来了
PROCESS-NAME,com.ygxc.student,{{ rule }} # 阳光学车
PROCESS-NAME,com.yiban1413.yiban,{{ rule }} # 一伴婚恋专业版
PROCESS-NAME,com.yibanlu.luck,{{ rule }} # 同城知趣聊天
PROCESS-NAME,com.yibasan.lizhifm,{{ rule }} # 荔枝
PROCESS-NAME,com.yiche.autoeasy,{{ rule }} # 易车
PROCESS-NAME,com.yidian.xiaomi,{{ rule }} # 一点新闻资讯
PROCESS-NAME,com.yingyonghui.market,{{ rule }} # 应用汇
PROCESS-NAME,com.yipiao,{{ rule }} # 智行火车票
PROCESS-NAME,com.yitantech.gaigai,{{ rule }} # 比心
PROCESS-NAME,com.yitong.mbank,{{ rule }} # 江苏·农商行
PROCESS-NAME,com.yitong.mbank.psbc,{{ rule }} # 邮储银行
PROCESS-NAME,com.yitong.zjrc.mfs.android,{{ rule }} # 丰收互联
PROCESS-NAME,com.yiwang,{{ rule }} # 1药网
PROCESS-NAME,com.yixia.videoeditor,{{ rule }} # 秒拍
PROCESS-NAME,com.yiyou.ga,{{ rule }} # TT语音
PROCESS-NAME,com.yjs.android,{{ rule }} # 应届生求职
PROCESS-NAME,com.yoho,{{ rule }} # YohoBuy有货
PROCESS-NAME,com.yoloho.dayima,{{ rule }} # 大姨妈
PROCESS-NAME,com.yoosee,{{ rule }} # 有看头
PROCESS-NAME,com.youcheyihou.iyourautobee,{{ rule }} # 车小蜂
PROCESS-NAME,com.youcheyihou.iyoursuv,{{ rule }} # 有车以后
PROCESS-NAME,com.youdao.dict,{{ rule }} # 网易有道词典
PROCESS-NAME,com.youdao.note,{{ rule }} # 有道云笔记
PROCESS-NAME,com.youdao.translator,{{ rule }} # 有道翻译官
PROCESS-NAME,com.youku.crazytogether,{{ rule }} # 来疯
PROCESS-NAME,com.youku.phone,{{ rule }} # 优酷视频
PROCESS-NAME,com.youloft.calendar,{{ rule }} # 万年历
PROCESS-NAME,com.youxiang.soyoungapp,{{ rule }} # 新氧医美
PROCESS-NAME,com.ysy.ayy,{{ rule }} # 木鸟民宿
PROCESS-NAME,com.yuanli.recordingSoftware,{{ rule }} # 录音软件
PROCESS-NAME,com.yuantiku.tutor,{{ rule }} # 猿辅导
PROCESS-NAME,com.yuedong.sport,{{ rule }} # 悦动圈
PROCESS-NAME,com.yueme.itv,{{ rule }} # 小翼管家
PROCESS-NAME,com.yumc.phsuperapp,{{ rule }} # 必胜客
PROCESS-NAME,com.yunxi.bell,{{ rule }} # 闹钟AI
PROCESS-NAME,com.yunxiao.haofenshu,{{ rule }} # 好分数
PROCESS-NAME,com.yuyuesports.yuyue.android,{{ rule }} # 羽约运动
PROCESS-NAME,com.yx,{{ rule }} # 有信
PROCESS-NAME,com.yy.dreamer,{{ rule }} # Yo交友
PROCESS-NAME,com.yy.huanju,{{ rule }} # Hello
PROCESS-NAME,com.zaxd.loan,{{ rule }} # 众安贷
PROCESS-NAME,com.zbx.ct.tvzhibo,{{ rule }} # 手机电视高清直播
PROCESS-NAME,com.zcbl.bjjj_driving,{{ rule }} # 北京交警
PROCESS-NAME,com.zenmen.palmchat,{{ rule }} # 连信
PROCESS-NAME,com.zhangdan.app,{{ rule }} # 51信用卡管家
PROCESS-NAME,com.zhangxiong.art,{{ rule }} # 张雄艺术
PROCESS-NAME,com.zhaopin.social,{{ rule }} # 智联招聘
PROCESS-NAME,com.zhenai.android,{{ rule }} # 珍爱
PROCESS-NAME,com.zhibo.mm,{{ rule }} # 秘密直播
PROCESS-NAME,com.zhichan.msmds,{{ rule }} # 买什么都省
PROCESS-NAME,com.zhihu.android,{{ rule }} # 知乎
PROCESS-NAME,com.zhinengremote.mohan,{{ rule }} # 空调智能遥控器+
PROCESS-NAME,com.zhiyaolai.playschool,{{ rule }} # 锦鲤宇宙
PROCESS-NAME,com.ziipin.homeinn,{{ rule }} # 首旅如家
PROCESS-NAME,com.zl.fqbao,{{ rule }} # 招联金融
PROCESS-NAME,com.zmlearn.course.am,{{ rule }} # 掌门1对1辅导
PROCESS-NAME,com.zsyj.videomake,{{ rule }} # 趣制作
PROCESS-NAME,com.zsyj.wallpaper,{{ rule }} # 动态壁纸
PROCESS-NAME,com.zuoyebang.airclass,{{ rule }} # 作业帮直播课
PROCESS-NAME,com.zxscnew,{{ rule }} # 中信证券
PROCESS-NAME,com.zybang.parent,{{ rule }} # 作业帮口算
PROCESS-NAME,com.zyhd.voice,{{ rule }} # 语音包变声器
PROCESS-NAME,com.zzw.october,{{ rule }} # 志愿汇
PROCESS-NAME,comm.cchong.BloodAssistant,{{ rule }} # 体检宝手机测血压视力心率
PROCESS-NAME,ctrip.android.view,{{ rule }} # 携程旅行
PROCESS-NAME,fkg.client.side.activity,{{ rule }} # 蜂狂购
PROCESS-NAME,flipboard.cn,{{ rule }} # 红板报
PROCESS-NAME,fm.qingting.qtradio,{{ rule }} # 蜻蜓FM
PROCESS-NAME,gz.lifesense.weidong,{{ rule }} # 乐心健康
PROCESS-NAME,hg.zp.ui,{{ rule }} # 天眼新闻
PROCESS-NAME,howbuy.android.piggy,{{ rule }} # 储蓄罐
PROCESS-NAME,io.dcloud.H5999961F,{{ rule }} # 宝宝云
PROCESS-NAME,io.dushu.fandengreader,{{ rule }} # 帆书
PROCESS-NAME,jiakaokeer.app.good,{{ rule }} # 驾考宝典科目二
PROCESS-NAME,jiakaokesan.app.good,{{ rule }} # 驾考宝典科目三
PROCESS-NAME,jiakaokesi.app.good,{{ rule }} # 驾考宝典极速版
PROCESS-NAME,jiakaokeyi.app.good,{{ rule }} # 驾考宝典3D练车
PROCESS-NAME,jiakaotong.app.good,{{ rule }} # 驾考通
PROCESS-NAME,jiaxiao.app.good,{{ rule }} # 驾照宝典
PROCESS-NAME,jiaxiaobaodian.app.good,{{ rule }} # 驾校宝典
PROCESS-NAME,kehuo.app.good,{{ rule }} # 驾考宝典客货车
PROCESS-NAME,llbt.ccb.lnga,{{ rule }} # 辽事通
PROCESS-NAME,me.chunyu.ChunyuDoctor,{{ rule }} # 春雨医生
PROCESS-NAME,me.ele,{{ rule }} # 饿了么
PROCESS-NAME,me.ele.napos,{{ rule }} # 饿了么商家版
PROCESS-NAME,me.iweek.rili,{{ rule }} # 生活日历
PROCESS-NAME,me.suncloud.marrymemo,{{ rule }} # 婚礼纪
PROCESS-NAME,me.yidui,{{ rule }} # 伊对
PROCESS-NAME,mobi.htjsq.accelerator,{{ rule }} # 海豚加速器
PROCESS-NAME,moto.app.good,{{ rule }} # 驾考宝典摩托车
PROCESS-NAME,net.whty.app.eyu,{{ rule }} # 人人通空间
PROCESS-NAME,net.xinhuamm.mainclient,{{ rule }} # 新华社
PROCESS-NAME,oms.mmc.app.almanac_inland,{{ rule }} # 老黄历万年历顺历
PROCESS-NAME,org.fungo.fungolive,{{ rule }} # 天天电视直播
PROCESS-NAME,org.zywx.wbpalmstar.widgetone.uexaaagg10001,{{ rule }} # 安全守护
PROCESS-NAME,protect.eye,{{ rule }} # 护眼宝
PROCESS-NAME,qzyd.speed.nethelper,{{ rule }} # 中国移动福建
PROCESS-NAME,shengang.szkingdom.android.phone,{{ rule }} # 申港证券
PROCESS-NAME,sina.mobile.tianqitong,{{ rule }} # 天气通
PROCESS-NAME,software.ecenter.study,{{ rule }} # 状元共享课堂
PROCESS-NAME,sogou.mobile.explorer,{{ rule }} # 搜狗浏览器极速版
PROCESS-NAME,tv.acfundanmaku.video,{{ rule }} # AcFun
PROCESS-NAME,tv.danmaku.bili,{{ rule }} # 哔哩哔哩
PROCESS-NAME,tv.pps.mobile,{{ rule }} # 爱奇艺随刻
PROCESS-NAME,tv.yilan.howto.app,{{ rule }} # 好兔视频
PROCESS-NAME,tv.yixia.bobo,{{ rule }} # 波波视频
PROCESS-NAME,vStudio.Android.Camera360,{{ rule }} # 相机360
PROCESS-NAME,vz.com,{{ rule }} # 飞常准
PROCESS-NAME,wshifu.app.android,{{ rule }} # 万师傅企业版
PROCESS-NAME,yiqi.bazi,{{ rule }} # 易奇文化
PROCESS-NAME,zzll.cn.com.trader,{{ rule }} # 彼彼省家
{% endmacro %}