{% macro main(rule) %}
PROCESS-NAME,air.tv.douyu.android,{{ rule }} # 斗鱼
PROCESS-NAME,cmccwm.mobilemusic,{{ rule }} # 咪咕音乐
PROCESS-NAME,cn.kuwo.player,{{ rule }} # 酷我音乐
PROCESS-NAME,com.achievo.vipshop,{{ rule }} # 唯品会
PROCESS-NAME,com.autonavi.minimap,{{ rule }} # 高德地图
PROCESS-NAME,com.baidu.appsearch,{{ rule }} # 百度手机助手
PROCESS-NAME,com.baidu.haokan,{{ rule }} # 好看视频
PROCESS-NAME,com.baidu.homework,{{ rule }} # 作业帮
PROCESS-NAME,com.baidu.input,{{ rule }} # 百度输入法
PROCESS-NAME,com.baidu.netdisk,{{ rule }} # 百度网盘
PROCESS-NAME,com.baidu.searchbox,{{ rule }} # 百度
PROCESS-NAME,com.chinamworld.main,{{ rule }} # 中国建设银行
PROCESS-NAME,com.cleanmaster.mguard_cn,{{ rule }} # 猎豹清理大师
PROCESS-NAME,com.dianping.v1,{{ rule }} # 大众点评
PROCESS-NAME,com.duowan.kiwi,{{ rule }} # 虎牙直播
PROCESS-NAME,com.eg.android.AlipayGphone,{{ rule }} # 支付宝
PROCESS-NAME,com.handsgo.jiakao.android,{{ rule }} # 驾考宝典
PROCESS-NAME,com.huluxia.gametools,{{ rule }} # 葫芦侠
PROCESS-NAME,com.hunantv.imgo.activity,{{ rule }} # 芒果TV
PROCESS-NAME,com.icbc,{{ rule }} # 中国工商银行
PROCESS-NAME,com.immomo.momo,{{ rule }} # MOMO陌陌
PROCESS-NAME,com.jifen.qukan,{{ rule }} # 趣头条
PROCESS-NAME,com.jingdong.app.mall,{{ rule }} # 京东
PROCESS-NAME,com.jxedt,{{ rule }} # 驾校一点通
PROCESS-NAME,com.kuaishou.nebula,{{ rule }} # 快手极速版
PROCESS-NAME,com.kugou.android,{{ rule }} # 酷狗音乐
PROCESS-NAME,com.meitu.meiyancamera,{{ rule }} # 美颜相机
PROCESS-NAME,com.moji.mjweather,{{ rule }} # 墨迹天气
PROCESS-NAME,com.mt.mtxx.mtxx,{{ rule }} # 美图秀秀-视频/图片/Live人像精修工具
PROCESS-NAME,com.netease.cloudmusic,{{ rule }} # 网易云音乐
PROCESS-NAME,com.netease.newsreader.activity,{{ rule }} # 网易新闻
PROCESS-NAME,com.pplive.androidphone,{{ rule }} # PP视频
PROCESS-NAME,com.qihoo.appstore,{{ rule }} # 360手机助手
PROCESS-NAME,com.qihoo360.mobilesafe,{{ rule }} # 360手机卫士
PROCESS-NAME,com.qiyi.video,{{ rule }} # 爱奇艺
PROCESS-NAME,com.qq.reader,{{ rule }} # QQ阅读
PROCESS-NAME,com.Qunar,{{ rule }} # 去哪儿旅行
PROCESS-NAME,com.qzone,{{ rule }} # QQ空间
PROCESS-NAME,com.sankuai.meituan,{{ rule }} # 美团
PROCESS-NAME,com.sdu.didi.psnger,{{ rule }} # 滴滴出行
PROCESS-NAME,com.shoujiduoduo.ringtone,{{ rule }} # 铃声多多
PROCESS-NAME,com.sina.weibo,{{ rule }} # 微博
PROCESS-NAME,com.sinovatech.unicom.ui,{{ rule }} # 中国联通
PROCESS-NAME,com.smile.gifmaker,{{ rule }} # 快手
PROCESS-NAME,com.snda.wifilocating,{{ rule }} # WiFi万能钥匙
PROCESS-NAME,com.sohu.inputmethod.sogou,{{ rule }} # 搜狗输入法
PROCESS-NAME,com.sohu.sohuvideo,{{ rule }} # 搜狐视频
PROCESS-NAME,com.ss.android.article.lite,{{ rule }} # 今日头条极速版
PROCESS-NAME,com.ss.android.article.news,{{ rule }} # 今日头条
PROCESS-NAME,com.ss.android.article.video,{{ rule }} # 西瓜视频
PROCESS-NAME,com.ss.android.ugc.aweme,{{ rule }} # 抖音
PROCESS-NAME,com.ss.android.ugc.live,{{ rule }} # 抖音火山版
PROCESS-NAME,com.storm.smart,{{ rule }} # 暴风影音
PROCESS-NAME,com.taobao.idlefish,{{ rule }} # 闲鱼
PROCESS-NAME,com.tencent.androidqqmail,{{ rule }} # QQ邮箱
PROCESS-NAME,com.tencent.hunyuan.app.chat,{{ rule }} # 元宝-腾讯旗下AI助手
PROCESS-NAME,com.tencent.karaoke,{{ rule }} # 全民K歌
PROCESS-NAME,com.tencent.mobileqq,{{ rule }} # QQ
PROCESS-NAME,com.tencent.mtt,{{ rule }} # QQ浏览器
PROCESS-NAME,com.tencent.news,{{ rule }} # 腾讯新闻
PROCESS-NAME,com.tencent.qqlive,{{ rule }} # 腾讯视频
PROCESS-NAME,com.tencent.qqmusic,{{ rule }} # QQ音乐
PROCESS-NAME,com.tencent.qqpimsecure,{{ rule }} # 腾讯手机管家
PROCESS-NAME,com.tencent.weishi,{{ rule }} # 腾讯微视
PROCESS-NAME,com.tmall.wireless,{{ rule }} # 天猫
PROCESS-NAME,com.UCMobile,{{ rule }} # UC浏览器
PROCESS-NAME,com.wuba,{{ rule }} # 58同城
PROCESS-NAME,com.ximalaya.ting.android,{{ rule }} # 喜马拉雅
PROCESS-NAME,com.xunmeng.pinduoduo,{{ rule }} # 拼多多
PROCESS-NAME,com.youku.phone,{{ rule }} # 优酷视频
PROCESS-NAME,ctrip.android.view,{{ rule }} # 携程旅行
PROCESS-NAME,tv.danmaku.bili,{{ rule }} # 哔哩哔哩
{% endmacro %}