{% macro main(rule) %}
PROCESS-NAME,air.com.miracle.weqi.packqq,{{ rule }} # 少儿围棋教学合集
PROCESS-NAME,bf.sgs.hdexp,{{ rule }} # 三国杀
PROCESS-NAME,cn.flytalk.shudu,{{ rule }} # 全民数独
PROCESS-NAME,cn.izis.mygo.mplat,{{ rule }} # 隐智围棋
PROCESS-NAME,cn.jj,{{ rule }} # JJ斗地主
PROCESS-NAME,cn.ydxh.mario,{{ rule }} # 超级玛丽
PROCESS-NAME,com.airmpoint.ninjump2.yyb,{{ rule }} # 最强忍者
PROCESS-NAME,com.airmpoint.popball.yyb,{{ rule }} # 开心连球球
PROCESS-NAME,com.airmpoint.popstar.yyb,{{ rule }} # 消灭星星经典
PROCESS-NAME,com.airmpoint.spider.yyb,{{ rule }} # 蜘蛛纸牌经典
PROCESS-NAME,com.aswind.libdesktoppet,{{ rule }} # 桌面萌宠
PROCESS-NAME,com.bbqstudio.bbqq.yyb,{{ rule }} # 野蛮人大作战
PROCESS-NAME,com.bdapps.antistressball,{{ rule }} # 快清理粘液模拟器
PROCESS-NAME,com.bftuolaji.yyb,{{ rule }} # 边锋拖拉机精简版
PROCESS-NAME,com.brianbaek.popstar,{{ rule }} # 消灭星星全新版
PROCESS-NAME,com.bruce.bestidiom,{{ rule }} # 成语拼拼拼
PROCESS-NAME,com.c2vl.kgamebox,{{ rule }} # 狼人杀
PROCESS-NAME,com.calf.vr,{{ rule }} # 开飞VR
PROCESS-NAME,com.carrot.carrotfantasy,{{ rule }} # 保卫萝卜
PROCESS-NAME,com.cayer.qiesg,{{ rule }} # 快乐切水果
PROCESS-NAME,com.cchsx.chxc,{{ rule }} # 插花消除
PROCESS-NAME,com.chrysler.ball,{{ rule }} # 七彩五子连珠
PROCESS-NAME,com.deeplusplus.blackmath,{{ rule }} # 黑色数学-挑战高难度问题
PROCESS-NAME,com.dobest.new2048,{{ rule }} # 2048数字方块
PROCESS-NAME,com.draw.color.pixel.digit,{{ rule }} # 指尖涂色
PROCESS-NAME,com.ea.simcitymobile.tx,{{ rule }} # 模拟城市：我是市长
PROCESS-NAME,com.emo.studio.magicparticle,{{ rule }} # 我的粒子世界
PROCESS-NAME,com.fengguo.wpjz.yingyongbao,{{ rule }} # 王牌机战
PROCESS-NAME,com.fengyun.qiqijww,{{ rule }} # 奇奇抓娃娃
PROCESS-NAME,com.find.out.hidden.objects.jrtt,{{ rule }} # 脑洞大侦探
PROCESS-NAME,com.fingersoft.hcr2.cn.tencent,{{ rule }} # 登山赛车2
PROCESS-NAME,com.fingersoft.hillclimb,{{ rule }} # 登山赛车
PROCESS-NAME,com.fingertip.saolei,{{ rule }} # 扫雷世界
PROCESS-NAME,com.fourddz.yyb,{{ rule }} # 边锋四人斗地主精简版
PROCESS-NAME,com.gamebox.king,{{ rule }} # 帝王·三国
PROCESS-NAME,com.gdczu.memory,{{ rule }} # C族记忆宫殿
PROCESS-NAME,com.gof.china,{{ rule }} # 无尽冬日
PROCESS-NAME,com.golaxy.mobile,{{ rule }} # 星阵围棋
PROCESS-NAME,com.guandan.yybtest,{{ rule }} # 掼蛋
PROCESS-NAME,com.happyelements.AndroidAnimal.qq,{{ rule }} # 开心消消乐
PROCESS-NAME,com.happyelements.AndroidClover.www,{{ rule }} # 海滨消消乐
PROCESS-NAME,com.hdhd.cyxxcg,{{ rule }} # 成语消消闯关
PROCESS-NAME,com.htwoplayers.srjjc,{{ rule }} # 双人竞技场
PROCESS-NAME,com.huanshouluhy.book,{{ rule }} # 幻兽录
PROCESS-NAME,com.hytc.hxsg2,{{ rule }} # 汉风幻想三国OL
PROCESS-NAME,com.hzdx.fkzdx,{{ rule }} # 疯狂找东西
PROCESS-NAME,com.imangi.templerun2,{{ rule }} # 神庙逃亡2
PROCESS-NAME,com.indeed.golinks,{{ rule }} # 弈客围棋
PROCESS-NAME,com.iyougao.grandparents,{{ rule }} # 托卡世界夏威夷小镇
PROCESS-NAME,com.jiahui.lymj,{{ rule }} # 南宁老友麻将
PROCESS-NAME,com.joygo,{{ rule }} # 忘忧围棋
PROCESS-NAME,com.joym.armorbear.yyb,{{ rule }} # 熊出没之机甲熊大
PROCESS-NAME,com.joym.bearfarm.yingyongbao,{{ rule }} # 熊出没之熊大农场
PROCESS-NAME,com.joym.legendhero.yyb,{{ rule }} # 奥特曼传奇英雄
PROCESS-NAME,com.joym.xiongdakuaipao.yyb,{{ rule }} # 熊出没之熊大快跑
PROCESS-NAME,com.jucai.happygo,{{ rule }} # 一起学围棋
PROCESS-NAME,com.jy.mj.hzmj,{{ rule }} # 来打红中麻将
PROCESS-NAME,com.kid58.lianyong.agriculturalvehicle,{{ rule }} # 奇妙小镇农场
PROCESS-NAME,com.kiloo.subwaysurf,{{ rule }} # 地铁跑酷
PROCESS-NAME,com.KingOfTank.tkqx,{{ rule }} # 坦克前线
PROCESS-NAME,com.kuniu.mota,{{ rule }} # 魔塔
PROCESS-NAME,com.kurogame.mingchao,{{ rule }} # 鸣潮
PROCESS-NAME,com.lego.supermario,{{ rule }} # LEGO® Super Mario™
PROCESS-NAME,com.leiting.wjcs.android,{{ rule }} # 问剑长生
PROCESS-NAME,com.leiting.xiany,{{ rule }} # 一念逍遥
PROCESS-NAME,com.liaoyanxuan.jeweldropdom,{{ rule }} # 方块宝石滑消消
PROCESS-NAME,com.liaoyanxuan.sudoku,{{ rule }} # 数独玩家
PROCESS-NAME,com.liaoyanxuan.unblockMeKlotski,{{ rule }} # 三国华容道谜题集
PROCESS-NAME,com.lilithgame.igame.android.cn,{{ rule }} # 剑与远征：启程
PROCESS-NAME,com.lilithgame.wgame.android.cn,{{ rule }} # 战火勋章
PROCESS-NAME,com.lilithgames.rok.offical.cn,{{ rule }} # 万国觉醒
PROCESS-NAME,com.lilithgames.samo.android.cn,{{ rule }} # 万龙觉醒
PROCESS-NAME,com.lilithgames.xgame.android.cn,{{ rule }} # 众神派对
PROCESS-NAME,com.longtu.oao,{{ rule }} # 海龟汤
PROCESS-NAME,com.lovejiajiao.my2048,{{ rule }} # 2048并并并
PROCESS-NAME,com.lovejiajiao.twentyfour,{{ rule }} # 24点口算王
PROCESS-NAME,com.lutongnet.brainadventure.plugin,{{ rule }} # 脑力大冒险学习软件
PROCESS-NAME,com.magene.onelapMatch,{{ rule }} # 顽鹿竞技
PROCESS-NAME,com.magic.stkeripc,{{ rule }} # 魔法贴贴
PROCESS-NAME,com.magicflute.renjuworld,{{ rule }} # 五林五子棋
PROCESS-NAME,com.martian.mssl.tx,{{ rule }} # 密室逃脱绝境系列4迷失森林
PROCESS-NAME,com.martian.RoomEscape14.tx,{{ rule }} # 密室逃脱14帝国崛起
PROCESS-NAME,com.martian.RoomEscape18.tx,{{ rule }} # 密室逃脱18移动迷城
PROCESS-NAME,com.martian.RoomEscape23.tx,{{ rule }} # 密室逃脱23迷失俱乐部
PROCESS-NAME,com.martian.RoomEscape9.tx,{{ rule }} # 密室逃脱9太空迷航
PROCESS-NAME,com.mfp.jelly.yingyongbao,{{ rule }} # 宾果消消消
PROCESS-NAME,com.miHoYo.hkrpg,{{ rule }} # 崩坏：星穹铁道
PROCESS-NAME,com.miHoYo.HSoDv22144.tencent,{{ rule }} # 崩坏学园2
PROCESS-NAME,com.miHoYo.Nap,{{ rule }} # 绝区零
PROCESS-NAME,com.mindblocks.blocks.tencent,{{ rule }} # 被尘封的故事
PROCESS-NAME,com.mizhongtech.qief,{{ rule }} # 儿童益智切水果
PROCESS-NAME,com.molehole.zaiwanyiguan.yyb,{{ rule }} # 再玩亿关
PROCESS-NAME,com.mychess.video,{{ rule }} # 将棋
PROCESS-NAME,com.netease.lrs,{{ rule }} # 狼人杀
PROCESS-NAME,com.nhsoft.shopapp3,{{ rule }} # 乐檬零售
PROCESS-NAME,com.og.danjiddz,{{ rule }} # 单机斗地主（开心版）
PROCESS-NAME,com.orangestudio.kenken,{{ rule }} # 算独
PROCESS-NAME,com.orangestudio.sudoku,{{ rule }} # 桔子数独
PROCESS-NAME,com.ourgame.mahjong.danji,{{ rule }} # 单机麻将-开心版
PROCESS-NAME,com.outfit7.mytalkingangelafree,{{ rule }} # 我的安吉拉
PROCESS-NAME,com.outfit7.mytalkingtomfree,{{ rule }} # 我的汤姆猫
PROCESS-NAME,com.outfit7.talkingtompool,{{ rule }} # 汤姆猫水上乐园
PROCESS-NAME,com.papegames.infinitynikki,{{ rule }} # 无限暖暖
PROCESS-NAME,com.papegames.lysk.cn,{{ rule }} # 恋与深空
PROCESS-NAME,com.pdragon.chess,{{ rule }} # 国际象棋
PROCESS-NAME,com.pdragon.junqi,{{ rule }} # 军棋
PROCESS-NAME,com.pdragon.tetris,{{ rule }} # 多牛百变方块
PROCESS-NAME,com.qileyx.ddz.yyb,{{ rule }} # 欢喜斗地主
PROCESS-NAME,com.qqgame.happymj,{{ rule }} # 欢乐麻将
PROCESS-NAME,com.qqgame.hlddz,{{ rule }} # 欢乐斗地主
PROCESS-NAME,com.qqgame.mic,{{ rule }} # 英雄杀
PROCESS-NAME,com.shengji.yyb,{{ rule }} # 升级80分
PROCESS-NAME,com.sincetimes.fknsg,{{ rule }} # 放开那三国
PROCESS-NAME,com.sincetimes.games.worldship,{{ rule }} # 战舰帝国
PROCESS-NAME,com.sinyee.babybus.adventure,{{ rule }} # 奇妙逻辑启蒙
PROCESS-NAME,com.sinyee.babybus.bumpercars,{{ rule }} # 奇妙碰碰车
PROCESS-NAME,com.sinyee.babybus.careII,{{ rule }} # 照顾甜心妹妹
PROCESS-NAME,com.sinyee.babybus.chef,{{ rule }} # 宝宝小厨房
PROCESS-NAME,com.sinyee.babybus.coffee,{{ rule }} # 奇妙咖啡餐厅
PROCESS-NAME,com.sinyee.babybus.cultivation,{{ rule }} # 宝宝小牧场
PROCESS-NAME,com.sinyee.babybus.delicacy,{{ rule }} # 奇妙世界美食
PROCESS-NAME,com.sinyee.babybus.diner,{{ rule }} # 宝宝早餐车
PROCESS-NAME,com.sinyee.babybus.dinosaurIII,{{ rule }} # 奇妙恐龙科普
PROCESS-NAME,com.sinyee.babybus.factory,{{ rule }} # 宝宝冰淇淋工厂
PROCESS-NAME,com.sinyee.babybus.findCha,{{ rule }} # 宝宝来找茬
PROCESS-NAME,com.sinyee.babybus.foodstreetII,{{ rule }} # 奇妙美味日记
PROCESS-NAME,com.sinyee.babybus.foodstuffII,{{ rule }} # 宝宝美食帮帮忙
PROCESS-NAME,com.sinyee.babybus.grove,{{ rule }} # 宝宝森林美食
PROCESS-NAME,com.sinyee.babybus.icecream,{{ rule }} # 雪糕工厂
PROCESS-NAME,com.sinyee.babybus.jurassic,{{ rule }} # 奇妙恐龙世界
PROCESS-NAME,com.sinyee.babybus.kitchen,{{ rule }} # 宝宝神奇厨房
PROCESS-NAME,com.sinyee.babybus.princess,{{ rule }} # 奇妙的专注力
PROCESS-NAME,com.sinyee.babybus.restaurant,{{ rule }} # 奇妙料理餐厅
PROCESS-NAME,com.sinyee.babybus.snacks,{{ rule }} # 宝宝手工零食
PROCESS-NAME,com.sinyee.babybus.soda,{{ rule }} # 宝宝果汁商店
PROCESS-NAME,com.sinyee.babybus.spell,{{ rule }} # 宝宝拼拼乐
PROCESS-NAME,com.sinyee.babybus.splice,{{ rule }} # 奇妙拼图世界
PROCESS-NAME,com.sinyee.babybus.tea,{{ rule }} # 奇妙小茶园
PROCESS-NAME,com.smellymonster.games.make24,{{ rule }} # 算24点
PROCESS-NAME,com.tencent.af,{{ rule }} # 王牌战士
PROCESS-NAME,com.tencent.bsdld,{{ rule }} # 宝石大乱斗
PROCESS-NAME,com.tencent.cookie,{{ rule }} # 冲呀！饼干人：王国
PROCESS-NAME,com.tencent.cqsj,{{ rule }} # 传奇世界
PROCESS-NAME,com.tencent.cqtxsy,{{ rule }} # 传奇天下
PROCESS-NAME,com.tencent.crossworlds,{{ rule }} # 二之国：交错世界
PROCESS-NAME,com.tencent.dm,{{ rule }} # 数码宝贝：新世纪
PROCESS-NAME,com.tencent.dy.planet,{{ rule }} # 创造吧！我们的星球
PROCESS-NAME,com.tencent.egame,{{ rule }} # 英雄联盟电竞经理
PROCESS-NAME,com.tencent.feiji,{{ rule }} # 全民飞机大战
PROCESS-NAME,com.tencent.fifa4m,{{ rule }} # 足球在线4移动版
PROCESS-NAME,com.tencent.fifamobile,{{ rule }} # FC足球世界
PROCESS-NAME,com.tencent.fiftyone.yc,{{ rule }} # 桃源深处有人家
PROCESS-NAME,com.tencent.game.rhythmmaster,{{ rule }} # 节奏大师
PROCESS-NAME,com.tencent.game.VXDGame,{{ rule }} # 天天炫斗
PROCESS-NAME,com.tencent.gamematrix.tmgp.sgame,{{ rule }} # 云•王者荣耀
PROCESS-NAME,com.tencent.gate,{{ rule }} # 白荆回廊——古剑奇谭
PROCESS-NAME,com.tencent.gnyx.putonghua,{{ rule }} # 普通话小镇
PROCESS-NAME,com.tencent.gnyx.tqxs,{{ rule }} # 星火筑梦人
PROCESS-NAME,com.tencent.gris,{{ rule }} # 格莉斯的旅程
PROCESS-NAME,com.tencent.gwgo,{{ rule }} # 一起来捉妖
PROCESS-NAME,com.tencent.hhw,{{ rule }} # 航海王：壮志雄心
PROCESS-NAME,com.tencent.huajing,{{ rule }} # 画境长恨歌
PROCESS-NAME,com.tencent.hxgame,{{ rule }} # QQ华夏手游
PROCESS-NAME,com.tencent.hygd,{{ rule }} # 荒野国度
PROCESS-NAME,com.tencent.hyrzol,{{ rule }} # 火影忍者：忍者新世代
PROCESS-NAME,com.tencent.jgm,{{ rule }} # 家国梦
PROCESS-NAME,com.tencent.jkchess,{{ rule }} # 金铲铲之战
PROCESS-NAME,com.tencent.JWX,{{ rule }} # 傲世西游
PROCESS-NAME,com.tencent.KiHan,{{ rule }} # 火影忍者
PROCESS-NAME,com.tencent.kof,{{ rule }} # 拳皇·命运
PROCESS-NAME,com.tencent.lastblade,{{ rule }} # 末刀
PROCESS-NAME,com.tencent.letsgo,{{ rule }} # 元梦之星
PROCESS-NAME,com.tencent.lolm,{{ rule }} # 英雄联盟手游
PROCESS-NAME,com.tencent.lzhx,{{ rule }} # 龙族幻想
PROCESS-NAME,com.tencent.mergemansion,{{ rule }} # 庄园合合
PROCESS-NAME,com.tencent.mf.uam,{{ rule }} # 暗区突围
PROCESS-NAME,com.tencent.msgame,{{ rule }} # 合金弹头：觉醒
PROCESS-NAME,com.tencent.Mtown,{{ rule }} # 全民小镇
PROCESS-NAME,com.tencent.nfsonline,{{ rule }} # 极品飞车：集结
PROCESS-NAME,com.tencent.pao,{{ rule }} # 天天酷跑
PROCESS-NAME,com.tencent.peng,{{ rule }} # 天天爱消除
PROCESS-NAME,com.tencent.pocket,{{ rule }} # 腾讯桌球
PROCESS-NAME,com.tencent.pokemonunite.cn,{{ rule }} # 宝可梦大集结
PROCESS-NAME,com.tencent.Q108,{{ rule }} # 全民水浒
PROCESS-NAME,com.tencent.Qfarm,{{ rule }} # 全民农场
PROCESS-NAME,com.tencent.qqfarm,{{ rule }} # QQ农场
PROCESS-NAME,com.tencent.qqgame.qqhlupwvga,{{ rule }} # 欢乐升级
PROCESS-NAME,com.tencent.qqgame.xq,{{ rule }} # 天天象棋
PROCESS-NAME,com.tencent.ro,{{ rule }} # 仙境传说：爱如初见
PROCESS-NAME,com.tencent.ryxsg,{{ rule }} # 荣耀新三国
PROCESS-NAME,com.tencent.sevensin,{{ rule }} # 七人传奇：光与暗之交战
PROCESS-NAME,com.tencent.sgwsba,{{ rule }} # 真・三国无双 霸
PROCESS-NAME,com.tencent.shootgame,{{ rule }} # 魂斗罗：归来
PROCESS-NAME,com.tencent.sqsd,{{ rule }} # 石器时代：觉醒
PROCESS-NAME,com.tencent.tig,{{ rule }} # 隐形守护者
PROCESS-NAME,com.tencent.tls2,{{ rule }} # 末剑二
PROCESS-NAME,com.tencent.tmaoe,{{ rule }} # 重返帝国
PROCESS-NAME,com.tencent.tmgp.aceracer,{{ rule }} # 王牌竞速
PROCESS-NAME,com.tencent.tmgp.afshqz,{{ rule }} # 水浒Q传手游
PROCESS-NAME,com.tencent.tmgp.ahlhsyjy,{{ rule }} # 神域纪元
PROCESS-NAME,com.tencent.tmgp.ahlhzmsl,{{ rule }} # 织梦森林
PROCESS-NAME,com.tencent.tmgp.ahzc.shengdu,{{ rule }} # 暗黑之城
PROCESS-NAME,com.tencent.tmgp.aioos.chess,{{ rule }} # 立体围棋
PROCESS-NAME,com.tencent.tmgp.aligames.kybc,{{ rule }} # 狂野飙车9：竞速传奇
PROCESS-NAME,com.tencent.tmgp.aligames.sgzhxdl,{{ rule }} # 三国志幻想大陆
PROCESS-NAME,com.tencent.tmgp.android.ANMP.GloftDLCN,{{ rule }} # 萌龙大乱斗
PROCESS-NAME,com.tencent.tmgp.angellegion,{{ rule }} # 女神星球
PROCESS-NAME,com.tencent.tmgp.aoshilongcheng,{{ rule }} # 傲世龙城
PROCESS-NAME,com.tencent.tmgp.aotu,{{ rule }} # 凹凸世界
PROCESS-NAME,com.tencent.tmgp.aresvirus2,{{ rule }} # 阿瑞斯病毒2
PROCESS-NAME,com.tencent.tmgp.arrowio,{{ rule }} # 弓箭手大作战
PROCESS-NAME,com.tencent.tmgp.atmlegend2,{{ rule }} # 奥特曼传奇英雄2
PROCESS-NAME,com.tencent.tmgp.awlzw,{{ rule }} # 阿瓦隆之王
PROCESS-NAME,com.tencent.tmgp.aygame.xygame,{{ rule }} # 梦幻仙语
PROCESS-NAME,com.tencent.tmgp.bairimeng.dmmdzz,{{ rule }} # 逃跑吧！少年
PROCESS-NAME,com.tencent.tmgp.bairimeng.snake,{{ rule }} # 蛇蛇争霸
PROCESS-NAME,com.tencent.tmgp.baitian.alx,{{ rule }} # 奥拉星
PROCESS-NAME,com.tencent.tmgp.baitian.aobi.czs,{{ rule }} # 奥比岛：梦想国度
PROCESS-NAME,com.tencent.tmgp.baitian.aqcs.aqcssy,{{ rule }} # 奥奇传说
PROCESS-NAME,com.tencent.tmgp.basecity.game.hjd,{{ rule }} # 黄金岛在线游戏软件
PROCESS-NAME,com.tencent.tmgp.bekko.lszjz,{{ rule }} # 乱世终结战
PROCESS-NAME,com.tencent.tmgp.bfdjddzhd,{{ rule }} # 单机斗地主(六月)边锋精简版
PROCESS-NAME,com.tencent.tmgp.bgame,{{ rule }} # 热血街篮
PROCESS-NAME,com.tencent.tmgp.bh.slwz,{{ rule }} # 神陵武装
PROCESS-NAME,com.tencent.tmgp.bh3,{{ rule }} # 崩坏3
PROCESS-NAME,com.tencent.tmgp.bhzz.kuaiyele,{{ rule }} # 八荒主宰
PROCESS-NAME,com.tencent.tmgp.bilibili.asharms,{{ rule }} # 灰烬战线
PROCESS-NAME,com.tencent.tmgp.bilibili.bangdream,{{ rule }} # 梦想协奏曲！少女乐团派对！
PROCESS-NAME,com.tencent.tmgp.bilibili.blhx,{{ rule }} # 碧蓝航线
PROCESS-NAME,com.tencent.tmgp.bilibili.deadcells.mobile,{{ rule }} # 重生细胞
PROCESS-NAME,com.tencent.tmgp.bilibili.excalibur,{{ rule }} # 依露希尔：星晓
PROCESS-NAME,com.tencent.tmgp.bilibili.hunter3,{{ rule }} # 时空猎人3
PROCESS-NAME,com.tencent.tmgp.bilibili.nslg,{{ rule }} # 三国：谋定天下
PROCESS-NAME,com.tencent.tmgp.bilibili.overlord,{{ rule }} # 纳萨力克之王
PROCESS-NAME,com.tencent.tmgp.bilibili.priconne,{{ rule }} # 公主连结
PROCESS-NAME,com.tencent.tmgp.bilibili.snake,{{ rule }} # 坎特伯雷公主与骑士唤醒冠军之剑的奇幻冒险
PROCESS-NAME,com.tencent.tmgp.bilibili.warmsnow,{{ rule }} # 暖雪
PROCESS-NAME,com.tencent.tmgp.bingougame.tgsw,{{ rule }} # 太古神王
PROCESS-NAME,com.tencent.tmgp.bkddz,{{ rule }} # 波克斗地主
PROCESS-NAME,com.tencent.tmgp.blr3,{{ rule }} # 不良人3
PROCESS-NAME,com.tencent.tmgp.brdz67,{{ rule }} # 兵人大战
PROCESS-NAME,com.tencent.tmgp.budapp,{{ rule }} # 碧优蒂的世界
PROCESS-NAME,com.tencent.tmgp.cahxxc,{{ rule }} # 长安幻想
PROCESS-NAME,com.tencent.tmgp.caishen,{{ rule }} # 财神十三张
PROCESS-NAME,com.tencent.tmgp.carrot2,{{ rule }} # 保卫萝卜2
PROCESS-NAME,com.tencent.tmgp.carrot3dj,{{ rule }} # 保卫萝卜3
PROCESS-NAME,com.tencent.tmgp.catstudio.moegirlcafe2,{{ rule }} # 餐厅萌物语
PROCESS-NAME,com.tencent.tmgp.cdfml,{{ rule }} # 伏魔录
PROCESS-NAME,com.tencent.tmgp.cdxhdsg,{{ rule }} # 魂斗三国
PROCESS-NAME,com.tencent.tmgp.cf,{{ rule }} # 穿越火线-枪战王者
PROCESS-NAME,com.tencent.tmgp.cfxf,{{ rule }} # 超凡先锋
PROCESS-NAME,com.tencent.tmgp.cgatts,{{ rule }} # 重构：阿塔提斯
PROCESS-NAME,com.tencent.tmgp.chcyyb,{{ rule }} # 彩虹橙
PROCESS-NAME,com.tencent.tmgp.chd,{{ rule }} # 永恒岛
PROCESS-NAME,com.tencent.tmgp.chengzhu.zcydtz,{{ rule }} # 这城有良田
PROCESS-NAME,com.tencent.tmgp.chudustar.gdmj2,{{ rule }} # 星辰广东麻将
PROCESS-NAME,com.tencent.tmgp.chudustar.herbmj,{{ rule }} # 星辰哈尔滨麻将
PROCESS-NAME,com.tencent.tmgp.chudustar.kwxmj,{{ rule }} # 星辰卡五星
PROCESS-NAME,com.tencent.tmgp.chudustar.sxmj,{{ rule }} # 星辰陕西麻将
PROCESS-NAME,com.tencent.tmgp.cjhwy,{{ rule }} # 超进化物语
PROCESS-NAME,com.tencent.tmgp.cjjd,{{ rule }} # 超级舰队
PROCESS-NAME,com.tencent.tmgp.cjqyz.kkk5,{{ rule }} # 超级群英传
PROCESS-NAME,com.tencent.tmgp.clgame.cs2,{{ rule }} # 火线出击
PROCESS-NAME,com.tencent.tmgp.cmcm.zmjjkillshotbravo,{{ rule }} # 狙神荣耀
PROCESS-NAME,com.tencent.tmgp.cmge.dldllove,{{ rule }} # 斗罗大陆：逆转时空
PROCESS-NAME,com.tencent.tmgp.cmge.gathering,{{ rule }} # 斗罗大陆：史莱克学院
PROCESS-NAME,com.tencent.tmgp.cmge.ssjd,{{ rule }} # 境界-死神激斗
PROCESS-NAME,com.tencent.tmgp.cmge.xxjhjwq,{{ rule }} # 新仙剑奇侠传之挥剑问情
PROCESS-NAME,com.tencent.tmgp.cmswat,{{ rule }} # 正义枪战
PROCESS-NAME,com.tencent.tmgp.cn.jj.chess2,{{ rule }} # JJ象棋
PROCESS-NAME,com.tencent.tmgp.cn.jj.log,{{ rule }} # 曙光英雄
PROCESS-NAME,com.tencent.tmgp.cn.ro,{{ rule }} # 仙境传说：新启航
PROCESS-NAME,com.tencent.tmgp.co.zjhy,{{ rule }} # 创世战车
PROCESS-NAME,com.tencent.tmgp.cocos.sicmj,{{ rule }} # 四川麻将
PROCESS-NAME,com.tencent.tmgp.cod,{{ rule }} # 使命召唤手游
PROCESS-NAME,com.tencent.tmgp.cokqq,{{ rule }} # 列王的纷争
PROCESS-NAME,com.tencent.tmgp.cokutau.jls,{{ rule }} # 将灵说
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.bn.cn,{{ rule }} # 明日边境
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.jsfb.cn,{{ rule }} # 僵尸风暴
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.zfsniper.cn,{{ rule }} # 僵尸前线3D
PROCESS-NAME,com.tencent.tmgp.com.hanjiasongshu.jianghux2,{{ rule }} # 汉家江湖
PROCESS-NAME,com.tencent.tmgp.com.jbdfw.wcssf,{{ rule }} # 金币大富翁
PROCESS-NAME,com.tencent.tmgp.com.kaayou.chongyangmajiang,{{ rule }} # 斗棋麻将
PROCESS-NAME,com.tencent.tmgp.com.outfit7.talkingtomgoldrun,{{ rule }} # 汤姆猫跑酷
PROCESS-NAME,com.tencent.tmgp.com.scMahjong.CTYY,{{ rule }} # 决战血流
PROCESS-NAME,com.tencent.tmgp.com.sdgs.yyb,{{ rule }} # 商道高手
PROCESS-NAME,com.tencent.tmgp.com.shengsheng.huapai,{{ rule }} # 圣盛宜昌花牌安卓版软件V1.0
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.bog2,{{ rule }} # 古魂
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.jsqq.alsp,{{ rule }} # 爱琳诗篇
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.yunbu.pool3,{{ rule }} # 台球风云游戏软件 V1.0.0
PROCESS-NAME,com.tencent.tmgp.combatman,{{ rule }} # 奥特曼之格斗超人
PROCESS-NAME,com.tencent.tmgp.coslegend,{{ rule }} # 英魂之刃
PROCESS-NAME,com.tencent.tmgp.cqwx.cqdzzdj,{{ rule }} # 传奇斗地主单机游戏软件V1.0
PROCESS-NAME,com.tencent.tmgp.cqytj,{{ rule }} # 从前有条街
PROCESS-NAME,com.tencent.tmgp.croak,{{ rule }} # 旅行青蛙·中国之旅
PROCESS-NAME,com.tencent.tmgp.crossgate.ks,{{ rule }} # 魔力宝贝：旅人
PROCESS-NAME,com.tencent.tmgp.cshjphz,{{ rule }} # 喜扣跑胡子
PROCESS-NAME,com.tencent.tmgp.csqcfy2020,{{ rule }} # 球场风云
PROCESS-NAME,com.tencent.tmgp.cszr.cly,{{ rule }} # 侠剑狂歌
PROCESS-NAME,com.tencent.tmgp.ctycj,{{ rule }} # 餐厅养成记
PROCESS-NAME,com.tencent.tmgp.cxswz,{{ rule }} # 潮汐守望者
PROCESS-NAME,com.tencent.tmgp.cyddztwo,{{ rule }} # 禅游斗地主
PROCESS-NAME,com.tencent.tmgp.cykj.kdzz,{{ rule }} # 口袋战争
PROCESS-NAME,com.tencent.tmgp.daluandou,{{ rule }} # 奇葩战斗家
PROCESS-NAME,com.tencent.tmgp.dancingline,{{ rule }} # 跳舞的线
PROCESS-NAME,com.tencent.tmgp.daqing,{{ rule }} # 我在大清当皇帝
PROCESS-NAME,com.tencent.tmgp.darkestcastle,{{ rule }} # 黑暗城堡
PROCESS-NAME,com.tencent.tmgp.dartouPoker,{{ rule }} # 开心十三张
PROCESS-NAME,com.tencent.tmgp.dcrrmj,{{ rule }} # 人人麻将
PROCESS-NAME,com.tencent.tmgp.DDD2,{{ rule }} # 弹弹岛2
PROCESS-NAME,com.tencent.tmgp.ddianle.lovedance,{{ rule }} # 恋舞OL
PROCESS-NAME,com.tencent.tmgp.ddqmmx,{{ rule }} # 弹弹奇妙冒险
PROCESS-NAME,com.tencent.tmgp.ddtank,{{ rule }} # 弹弹堂
PROCESS-NAME,com.tencent.tmgp.ddzbsdj,{{ rule }} # 斗地主比赛
PROCESS-NAME,com.tencent.tmgp.dfjs,{{ rule }} # 巅峰极速
PROCESS-NAME,com.tencent.tmgp.dfm,{{ rule }} # 三角洲行动
PROCESS-NAME,com.tencent.tmgp.dftkzjzg,{{ rule }} # 巅峰坦克
PROCESS-NAME,com.tencent.tmgp.dfzj,{{ rule }} # 巅峰战舰
PROCESS-NAME,com.tencent.tmgp.dhad,{{ rule }} # 放置奇兵
PROCESS-NAME,com.tencent.tmgp.dhbs.swxh,{{ rule }} # 大话白蛇
PROCESS-NAME,com.tencent.tmgp.diyibo.nnz,{{ rule }} # 奶牛镇的小时光
PROCESS-NAME,com.tencent.tmgp.djddzhlbtwo,{{ rule }} # 单机斗地主（欢乐版）
PROCESS-NAME,com.tencent.tmgp.djsy,{{ rule }} # 妄想山海
PROCESS-NAME,com.tencent.tmgp.dldl.qidian,{{ rule }} # 新斗罗大陆（动画合作手游）
PROCESS-NAME,com.tencent.tmgp.dldlhsdjsy,{{ rule }} # 斗罗大陆：魂师对决
PROCESS-NAME,com.tencent.tmgp.dldlwyly,{{ rule }} # 斗罗大陆
PROCESS-NAME,com.tencent.tmgp.dlfsz.shengdu,{{ rule }} # 斗罗封神传
PROCESS-NAME,com.tencent.tmgp.dljh.shlk,{{ rule }} # 斗笠江湖
PROCESS-NAME,com.tencent.tmgp.dmxkl.jiuxing,{{ rule }} # 大明侠客令
PROCESS-NAME,com.tencent.tmgp.dnf,{{ rule }} # 地下城与勇士：起源
PROCESS-NAME,com.tencent.tmgp.dnh,{{ rule }} # 龙与家园：时光
PROCESS-NAME,com.tencent.tmgp.dodjoy.hlwdzz,{{ rule }} # 葫芦娃大作战
PROCESS-NAME,com.tencent.tmgp.douposnzy,{{ rule }} # 斗破苍穹：三年之约
PROCESS-NAME,com.tencent.tmgp.dpcq,{{ rule }} # 斗破苍穹：异火重燃
PROCESS-NAME,com.tencent.tmgp.dpdj,{{ rule }} # 斗破苍穹：巅峰对决
PROCESS-NAME,com.tencent.tmgp.dqdgxxhd,{{ rule }} # 大秦帝国之帝国烽烟
PROCESS-NAME,com.tencent.tmgp.dragonball,{{ rule }} # 龙珠激斗
PROCESS-NAME,com.tencent.tmgp.dreamfarm,{{ rule }} # 梦想农场
PROCESS-NAME,com.tencent.tmgp.dssgame.jianzhong,{{ rule }} # 剑中
PROCESS-NAME,com.tencent.tmgp.dtszj,{{ rule }} # 永恒纪元
PROCESS-NAME,com.tencent.tmgp.dtszjkhd,{{ rule }} # 精灵盛典：黎明
PROCESS-NAME,com.tencent.tmgp.dtszjwd222,{{ rule }} # 大天使之剑H5
PROCESS-NAME,com.tencent.tmgp.duige.hzw,{{ rule }} # 花之舞
PROCESS-NAME,com.tencent.tmgp.duige.xsdgj,{{ rule }} # 消失的轨迹
PROCESS-NAME,com.tencent.tmgp.dungeon22,{{ rule }} # 地下城堡2：黑暗觉醒
PROCESS-NAME,com.tencent.tmgp.duole.duolemjhd,{{ rule }} # 多乐麻将
PROCESS-NAME,com.tencent.tmgp.dustglobal.jianghu,{{ rule }} # 这就是江湖
PROCESS-NAME,com.tencent.tmgp.dwrg,{{ rule }} # 第五人格
PROCESS-NAME,com.tencent.tmgp.dxphzhj,{{ rule }} # 跑胡子（字牌）合集
PROCESS-NAME,com.tencent.tmgp.dyqlb,{{ rule }} # 道友请留步
PROCESS-NAME,com.tencent.tmgp.dzxyzq,{{ rule }} # 队长小翼：最强十一人
PROCESS-NAME,com.tencent.tmgp.eden,{{ rule }} # 世界启元
PROCESS-NAME,com.tencent.tmgp.ef3,{{ rule }} # 现代空战3D
PROCESS-NAME,com.tencent.tmgp.ef5,{{ rule }} # 空战争锋
PROCESS-NAME,com.tencent.tmgp.eight.ball.live,{{ rule }} # 超凡台球
PROCESS-NAME,com.tencent.tmgp.enjoymisgzj,{{ rule }} # 三国战纪
PROCESS-NAME,com.tencent.tmgp.es2boy,{{ rule }} # 偶像梦幻祭2
PROCESS-NAME,com.tencent.tmgp.evol,{{ rule }} # 恋与制作人
PROCESS-NAME,com.tencent.tmgp.ew5s,{{ rule }} # 欧陆战争5：帝国
PROCESS-NAME,com.tencent.tmgp.eyou.eygy,{{ rule }} # 光·遇
PROCESS-NAME,com.tencent.tmgp.eyou.tiyu,{{ rule }} # 天谕
PROCESS-NAME,com.tencent.tmgp.eyou.yjsh,{{ rule }} # 遇见逆水寒
PROCESS-NAME,com.tencent.tmgp.eyou.yqyn,{{ rule }} # 一起优诺
PROCESS-NAME,com.tencent.tmgp.eyou.zzsz,{{ rule }} # 重装上阵
PROCESS-NAME,com.tencent.tmgp.fdcx.cly,{{ rule }} # 釜底抽薪
PROCESS-NAME,com.tencent.tmgp.fengchi.ldjx,{{ rule }} # 雷电：觉醒
PROCESS-NAME,com.tencent.tmgp.ffom,{{ rule }} # 自由幻想
PROCESS-NAME,com.tencent.tmgp.fgcq,{{ rule }} # 热血传说
PROCESS-NAME,com.tencent.tmgp.fgo,{{ rule }} # 命运-冠位指定
PROCESS-NAME,com.tencent.tmgp.fhmj,{{ rule }} # 富豪麻将
PROCESS-NAME,com.tencent.tmgp.fjdz2,{{ rule }} # 飞机大战之全民雷电
PROCESS-NAME,com.tencent.tmgp.fknsg2,{{ rule }} # 放开那三国2
PROCESS-NAME,com.tencent.tmgp.forgame.mmxd,{{ rule }} # 美美小店
PROCESS-NAME,com.tencent.tmgp.frxxzrjp,{{ rule }} # 凡人修仙传：人界篇
PROCESS-NAME,com.tencent.tmgp.fszn2.huiyue,{{ rule }} # 封神之怒
PROCESS-NAME,com.tencent.tmgp.ftf,{{ rule }} # 战就战
PROCESS-NAME,com.tencent.tmgp.funntcp,{{ rule }} # 欢乐南通长牌
PROCESS-NAME,com.tencent.tmgp.fxbp,{{ rule }} # 放学别跑
PROCESS-NAME,com.tencent.tmgp.fyd,{{ rule }} # 枫叶岛
PROCESS-NAME,com.tencent.tmgp.fzdl,{{ rule }} # 风之大陆
PROCESS-NAME,com.tencent.tmgp.fzgd.ssfh,{{ rule }} # 盛世芳华
PROCESS-NAME,com.tencent.tmgp.g12000128,{{ rule }} # 航海王-启航
PROCESS-NAME,com.tencent.tmgp.g13001230,{{ rule }} # 敢达决战
PROCESS-NAME,com.tencent.tmgp.g13002010,{{ rule }} # 灌篮高手 正版授权手游
PROCESS-NAME,com.tencent.tmgp.g67,{{ rule }} # 暗黑破坏神：不朽
PROCESS-NAME,com.tencent.tmgp.galasports.basketball,{{ rule }} # 美职篮篮球大师
PROCESS-NAME,com.tencent.tmgp.galasports.championsfc,{{ rule }} # 最佳11人
PROCESS-NAME,com.tencent.tmgp.galasports.operablebasketball,{{ rule }} # 美职篮巅峰对决
PROCESS-NAME,com.tencent.tmgp.galasports.totalfootball,{{ rule }} # 最佳球会
PROCESS-NAME,com.tencent.tmgp.game.jianwuqk,{{ rule }} # 剑舞乾坤
PROCESS-NAME,com.tencent.tmgp.game.shanggufz.xiaoyz,{{ rule }} # 逍遥志
PROCESS-NAME,com.tencent.tmgp.game.xiaoyaojiugexing,{{ rule }} # 逍遥九歌行
PROCESS-NAME,com.tencent.tmgp.game.xueyizz_q,{{ rule }} # 柱子英雄
PROCESS-NAME,com.tencent.tmgp.gbits.atm,{{ rule }} # 问道
PROCESS-NAME,com.tencent.tmgp.gcsgzh5,{{ rule }} # 攻城三国志
PROCESS-NAME,com.tencent.tmgp.gg.lostword,{{ rule }} # 东方归言录
PROCESS-NAME,com.tencent.tmgp.gg.xrjh,{{ rule }} # 小忍计划
PROCESS-NAME,com.tencent.tmgp.ggdda,{{ rule }} # 哥哥打大A
PROCESS-NAME,com.tencent.tmgp.glkj.lhcx01,{{ rule }} # 灵魂潮汐
PROCESS-NAME,com.tencent.tmgp.glzp,{{ rule }} # 桂林字牌手机版
PROCESS-NAME,com.tencent.tmgp.gm.hs,{{ rule }} # 魂色
PROCESS-NAME,com.tencent.tmgp.gm.hxsy,{{ rule }} # 幻想圣域
PROCESS-NAME,com.tencent.tmgp.gnsbt,{{ rule }} # 高能手办团
PROCESS-NAME,com.tencent.tmgp.gnyx,{{ rule }} # 高能英雄
PROCESS-NAME,com.tencent.tmgp.gtll2,{{ rule }} # 钢铁力量2
PROCESS-NAME,com.tencent.tmgp.gumballs2,{{ rule }} # 不思议迷宫
PROCESS-NAME,com.tencent.tmgp.gundambattle,{{ rule }} # 敢达 争锋对决
PROCESS-NAME,com.tencent.tmgp.gw,{{ rule }} # 口袋进化
PROCESS-NAME,com.tencent.tmgp.gzlll,{{ rule }} # 国战来了
PROCESS-NAME,com.tencent.tmgp.habby.archeroii,{{ rule }} # 弓箭传说2
PROCESS-NAME,com.tencent.tmgp.habby.cnarchero.qq,{{ rule }} # 弓箭传说
PROCESS-NAME,com.tencent.tmgp.habby.danke,{{ rule }} # 弹壳特攻队
PROCESS-NAME,com.tencent.tmgp.habby.punballcn,{{ rule }} # 砰砰法师
PROCESS-NAME,com.tencent.tmgp.harrypotter,{{ rule }} # 哈利波特：魔法觉醒
PROCESS-NAME,com.tencent.tmgp.hchess,{{ rule }} # 全民象棋
PROCESS-NAME,com.tencent.tmgp.hcr2,{{ rule }} # 火柴人联盟2
PROCESS-NAME,com.tencent.tmgp.hcr3.qcjs,{{ rule }} # 火柴人联盟3
PROCESS-NAME,com.tencent.tmgp.hdczjh2,{{ rule }} # 皇帝成长计划2
PROCESS-NAME,com.tencent.tmgp.hdyxnbhx,{{ rule }} # 全民养成之女皇陛下
PROCESS-NAME,com.tencent.tmgp.hengsaoqianjun,{{ rule }} # 横扫千军
PROCESS-NAME,com.tencent.tmgp.hero.lszt,{{ rule }} # 绿色征途
PROCESS-NAME,com.tencent.tmgp.hhw,{{ rule }} # 航海王强者之路
PROCESS-NAME,com.tencent.tmgp.hhwrxhx,{{ rule }} # 航海王热血航线
PROCESS-NAME,com.tencent.tmgp.hhxy,{{ rule }} # 洪荒仙韵
PROCESS-NAME,com.tencent.tmgp.hhz,{{ rule }} # 神雕侠侣2
PROCESS-NAME,com.tencent.tmgp.hjczjh,{{ rule }} # 豪杰成长计划
PROCESS-NAME,com.tencent.tmgp.hjol,{{ rule }} # 红警OL
PROCESS-NAME,com.tencent.tmgp.hldj,{{ rule }} # 欢乐对决
PROCESS-NAME,com.tencent.tmgp.hlsgs,{{ rule }} # 欢乐三国杀
PROCESS-NAME,com.tencent.tmgp.hlxxz,{{ rule }} # 幻灵修仙传
PROCESS-NAME,com.tencent.tmgp.hmzqfy,{{ rule }} # 豪门足球风云
PROCESS-NAME,com.tencent.tmgp.hnjysgfz,{{ rule }} # 上古纷争
PROCESS-NAME,com.tencent.tmgp.hotta,{{ rule }} # 幻塔
PROCESS-NAME,com.tencent.tmgp.hqfytank,{{ rule }} # 华清飞扬全民坦克联盟游戏软件v1.0
PROCESS-NAME,com.tencent.tmgp.hsahc,{{ rule }} # 幻兽爱合成
PROCESS-NAME,com.tencent.tmgp.hse,{{ rule }} # 饥饿鲨：进化
PROCESS-NAME,com.tencent.tmgp.hsw,{{ rule }} # 饥饿鲨：世界
PROCESS-NAME,com.tencent.tmgp.htsk,{{ rule }} # 千变双扣
PROCESS-NAME,com.tencent.tmgp.huahusy,{{ rule }} # 画狐
PROCESS-NAME,com.tencent.tmgp.huanxi.hscq,{{ rule }} # 海蛇传奇（欢乐版）
PROCESS-NAME,com.tencent.tmgp.hungrydragon,{{ rule }} # 饥饿龙
PROCESS-NAME,com.tencent.tmgp.huopinsk,{{ rule }} # 火拼双扣
PROCESS-NAME,com.tencent.tmgp.hxjysy,{{ rule }} # 火线精英
PROCESS-NAME,com.tencent.tmgp.hxmjl,{{ rule }} # 幻想名将录
PROCESS-NAME,com.tencent.tmgp.hy.fmyx,{{ rule }} # 粉末游戏
PROCESS-NAME,com.tencent.tmgp.hy.hcrdj,{{ rule }} # 火柴人对决
PROCESS-NAME,com.tencent.tmgp.hy.hcrzzyc,{{ rule }} # 火柴人战争遗产
PROCESS-NAME,com.tencent.tmgp.hy.kbnn,{{ rule }} # 恐怖奶奶
PROCESS-NAME,com.tencent.tmgp.hymc,{{ rule }} # 荒野迷城
PROCESS-NAME,com.tencent.tmgp.idol2,{{ rule }} # 绝对演绎
PROCESS-NAME,com.tencent.tmgp.ifsanguo,{{ rule }} # 极无双
PROCESS-NAME,com.tencent.tmgp.ikillerss,{{ rule }} # 推理学院
PROCESS-NAME,com.tencent.tmgp.iron,{{ rule }} # 钢铁命令
PROCESS-NAME,com.tencent.tmgp.javgame.lsj,{{ rule }} # 来升级
PROCESS-NAME,com.tencent.tmgp.jdzmj,{{ rule }} # 中至赣牌圈
PROCESS-NAME,com.tencent.tmgp.jielan2,{{ rule }} # 街篮2
PROCESS-NAME,com.tencent.tmgp.jjxm,{{ rule }} # 新仙魔九界
PROCESS-NAME,com.tencent.tmgp.jjzd,{{ rule }} # 机甲战队
PROCESS-NAME,com.tencent.tmgp.jlsyln,{{ rule }} # 九灵神域
PROCESS-NAME,com.tencent.tmgp.jltx,{{ rule }} # 逐鹿三国之君临天下
PROCESS-NAME,com.tencent.tmgp.jlxxljlb,{{ rule }} # 精灵消消乐（精灵版）
PROCESS-NAME,com.tencent.tmgp.jmlzj,{{ rule }} # 姬魔恋战纪
PROCESS-NAME,com.tencent.tmgp.jnbg2,{{ rule }} # 纪念碑谷2
PROCESS-NAME,com.tencent.tmgp.jpzmg,{{ rule }} # 极品芝麻官
PROCESS-NAME,com.tencent.tmgp.jsxwsy,{{ rule }} # 绝世仙王
PROCESS-NAME,com.tencent.tmgp.jszc,{{ rule }} # 巨兽战场
PROCESS-NAME,com.tencent.tmgp.jumpw,{{ rule }} # 300大作战
PROCESS-NAME,com.tencent.tmgp.junhai.shjhxl,{{ rule }} # 山海经幻想录
PROCESS-NAME,com.tencent.tmgp.jwdzg,{{ rule }} # 叫我大掌柜
PROCESS-NAME,com.tencent.tmgp.jwt.zqb,{{ rule }} # 劲舞时代
PROCESS-NAME,com.tencent.tmgp.jx3m,{{ rule }} # 剑网3指尖江湖
PROCESS-NAME,com.tencent.tmgp.jxjhyyh,{{ rule }} # 锦绣江湖
PROCESS-NAME,com.tencent.tmgp.jxqy,{{ rule }} # 新剑侠情缘
PROCESS-NAME,com.tencent.tmgp.kaayou.daye,{{ rule }} # 大冶打拱
PROCESS-NAME,com.tencent.tmgp.kaayou.ezhou,{{ rule }} # 鄂州五十K
PROCESS-NAME,com.tencent.tmgp.kaopu.jzpaj,{{ rule }} # 决战！平安京
PROCESS-NAME,com.tencent.tmgp.kaopu.zdjs,{{ rule }} # 朕的江山
PROCESS-NAME,com.tencent.tmgp.kbxy.kyl,{{ rule }} # 狂暴西游
PROCESS-NAME,com.tencent.tmgp.kdzj,{{ rule }} # 口袋战舰
PROCESS-NAME,com.tencent.tmgp.kgame.catssoup,{{ rule }} # 猫咪和汤
PROCESS-NAME,com.tencent.tmgp.kgame.ppcr,{{ rule }} # 全民泡泡超人
PROCESS-NAME,com.tencent.tmgp.kjfzd,{{ rule }} # 开间服装店
PROCESS-NAME,com.tencent.tmgp.kn.zdfz,{{ rule }} # 战斗法则
PROCESS-NAME,com.tencent.tmgp.kof97,{{ rule }} # 拳皇97OL
PROCESS-NAME,com.tencent.tmgp.kof98,{{ rule }} # 拳皇98终极之战OL
PROCESS-NAME,com.tencent.tmgp.kuangbaochuanqi,{{ rule }} # 狂暴传奇
PROCESS-NAME,com.tencent.tmgp.kurogame.haru,{{ rule }} # 战双帕弥什
PROCESS-NAME,com.tencent.tmgp.kxsgqyzm,{{ rule }} # 三国群英传-争霸
PROCESS-NAME,com.tencent.tmgp.kzfy,{{ rule }} # 空战风云
PROCESS-NAME,com.tencent.tmgp.kzysqh,{{ rule }} # 空之要塞：启航
PROCESS-NAME,com.tencent.tmgp.l10,{{ rule }} # 倩女幽魂
PROCESS-NAME,com.tencent.tmgp.lanjing.yanyu,{{ rule }} # 烟雨江湖
PROCESS-NAME,com.tencent.tmgp.leagueclash,{{ rule }} # 联盟纷争
PROCESS-NAME,com.tencent.tmgp.ledou.mhhy,{{ rule }} # 梦幻花园
PROCESS-NAME,com.tencent.tmgp.ledou.mhjy,{{ rule }} # 梦幻家园
PROCESS-NAME,com.tencent.tmgp.ledou.ryqmx,{{ rule }} # 荣耀全明星
PROCESS-NAME,com.tencent.tmgp.legendstd,{{ rule }} # 帝国守卫战
PROCESS-NAME,com.tencent.tmgp.leiting.bxjz,{{ rule }} # 不朽家族
PROCESS-NAME,com.tencent.tmgp.leiting.chaojinhua,{{ rule }} # 超进化物语2
PROCESS-NAME,com.tencent.tmgp.leiting.dragonraider,{{ rule }} # 飞吧龙骑士
PROCESS-NAME,com.tencent.tmgp.leiting.dungeon3,{{ rule }} # 地下城堡3：魂之诗
PROCESS-NAME,com.tencent.tmgp.leiting.lostcastle,{{ rule }} # 失落城堡
PROCESS-NAME,com.tencent.tmgp.leiting.poi,{{ rule }} # 这个地下城有点怪
PROCESS-NAME,com.tencent.tmgp.leiting.szqsf,{{ rule }} # 神州千食舫
PROCESS-NAME,com.tencent.tmgp.leshu.snakeonline,{{ rule }} # 贪吃蛇在线
PROCESS-NAME,com.tencent.tmgp.leting.picatown,{{ rule }} # 皮卡堂之梦想起源
PROCESS-NAME,com.tencent.tmgp.lewu.lhjx,{{ rule }} # 猎魂觉醒
PROCESS-NAME,com.tencent.tmgp.lhsl,{{ rule }} # 千年血战
PROCESS-NAME,com.tencent.tmgp.lilithgame.sgame,{{ rule }} # 剑与家园
PROCESS-NAME,com.tencent.tmgp.lilithgames.afk,{{ rule }} # 剑与远征
PROCESS-NAME,com.tencent.tmgp.limboworks.honorofcup,{{ rule }} # 足球大师黄金一代
PROCESS-NAME,com.tencent.tmgp.lkhx,{{ rule }} # 蓝空幻想
PROCESS-NAME,com.tencent.tmgp.locojoy,{{ rule }} # 我叫MT
PROCESS-NAME,com.tencent.tmgp.lostinblue,{{ rule }} # 迷失蔚蓝
PROCESS-NAME,com.tencent.tmgp.ltxfd.yyb,{{ rule }} # 雷霆小分队
PROCESS-NAME,com.tencent.tmgp.luobo4,{{ rule }} # 保卫萝卜4
PROCESS-NAME,com.tencent.tmgp.luoliye,{{ rule }} # 叶罗丽
PROCESS-NAME,com.tencent.tmgp.lv,{{ rule }} # 光与夜之恋
PROCESS-NAME,com.tencent.tmgp.lwyqqsqz,{{ rule }} # 元气骑士前传
PROCESS-NAME,com.tencent.tmgp.lxwz,{{ rule }} # 篮下王者
PROCESS-NAME,com.tencent.tmgp.lytx.shengjue,{{ rule }} # 烈焰天下
PROCESS-NAME,com.tencent.tmgp.lywlfrcs,{{ rule }} # 凡人传说
PROCESS-NAME,com.tencent.tmgp.m3gsy,{{ rule }} # 梦三国
PROCESS-NAME,com.tencent.tmgp.madhero,{{ rule }} # 暴走英雄坛
PROCESS-NAME,com.tencent.tmgp.majiangall,{{ rule }} # 全番单机麻将
PROCESS-NAME,com.tencent.tmgp.manggo.xwdsh,{{ rule }} # 向往的生活
PROCESS-NAME,com.tencent.tmgp.maplem,{{ rule }} # 冒险岛：枫之传说
PROCESS-NAME,com.tencent.tmgp.mds,{{ rule }} # 真三国快打
PROCESS-NAME,com.tencent.tmgp.mduel,{{ rule }} # 漫威对决
PROCESS-NAME,com.tencent.tmgp.mecharashi,{{ rule }} # 钢岚
PROCESS-NAME,com.tencent.tmgp.meng,{{ rule }} # 梦王国与沉睡的100王子
PROCESS-NAME,com.tencent.tmgp.mgddz,{{ rule }} # 芒果斗地主
PROCESS-NAME,com.tencent.tmgp.mhmfw,{{ rule }} # 梦幻魔法屋
PROCESS-NAME,com.tencent.tmgp.mhmnz,{{ rule }} # 梦幻模拟战
PROCESS-NAME,com.tencent.tmgp.mhtgame.wxr,{{ rule }} # 走开外星人
PROCESS-NAME,com.tencent.tmgp.mhxy.sqsy,{{ rule }} # 梦幻西游
PROCESS-NAME,com.tencent.tmgp.mhzxsy,{{ rule }} # 梦幻诛仙（哪吒闹海联动）
PROCESS-NAME,com.tencent.tmgp.minitech.miniworld,{{ rule }} # 迷你世界
PROCESS-NAME,com.tencent.tmgp.miniworldroyale,{{ rule }} # 迷你枪战精英
PROCESS-NAME,com.tencent.tmgp.mjwy,{{ rule }} # 魔镜物语
PROCESS-NAME,com.tencent.tmgp.mkqhhw,{{ rule }} # 秦皇汉武
PROCESS-NAME,com.tencent.tmgp.mlahsymx,{{ rule }} # 幻世与冒险
PROCESS-NAME,com.tencent.tmgp.MMHD,{{ rule }} # 魔法门之英雄无敌：王朝
PROCESS-NAME,com.tencent.tmgp.mmsrmlhd,{{ rule }} # 萌萌四人斗地主
PROCESS-NAME,com.tencent.tmgp.molenew,{{ rule }} # 摩尔庄园
PROCESS-NAME,com.tencent.tmgp.mozhigu,{{ rule }} # 魔之谷游戏软件v1.0
PROCESS-NAME,com.tencent.tmgp.mqwgctx,{{ rule }} # 攻城天下
PROCESS-NAME,com.tencent.tmgp.mqwsgzz,{{ rule }} # 三国战争
PROCESS-NAME,com.tencent.tmgp.ms,{{ rule }} # 漫威终极逆转
PROCESS-NAME,com.tencent.tmgp.mt2r,{{ rule }} # 我叫MT2
PROCESS-NAME,com.tencent.tmgp.mt4,{{ rule }} # 我叫MT4
PROCESS-NAME,com.tencent.tmgp.mtlbb,{{ rule }} # 天龙3D
PROCESS-NAME,com.tencent.tmgp.mw5k,{{ rule }} # 小小五千年
PROCESS-NAME,com.tencent.tmgp.mxdlmdyz,{{ rule }} # 冒险岛：联盟的意志
PROCESS-NAME,com.tencent.tmgp.mxtyln,{{ rule }} # 梦想桃源
PROCESS-NAME,com.tencent.tmgp.mxw3ol,{{ rule }} # 冒险王3OL
PROCESS-NAME,com.tencent.tmgp.mxxfd,{{ rule }} # 冒险小分队
PROCESS-NAME,com.tencent.tmgp.my.yyb,{{ rule }} # 魔域口袋版
PROCESS-NAME,com.tencent.tmgp.my.zjfm,{{ rule }} # 仗剑封魔
PROCESS-NAME,com.tencent.tmgp.myhero,{{ rule }} # 我的勇者
PROCESS-NAME,com.tencent.tmgp.myrzx.meizu,{{ rule }} # 牧羊人之心
PROCESS-NAME,com.tencent.tmgp.myshzg,{{ rule }} # 云上城之歌
PROCESS-NAME,com.tencent.tmgp.mytalkingangela2.tencent,{{ rule }} # 我的安吉拉2
PROCESS-NAME,com.tencent.tmgp.mytalkingtom2,{{ rule }} # 我的汤姆猫2
PROCESS-NAME,com.tencent.tmgp.mytalkingtomfriends,{{ rule }} # 汤姆猫总动员
PROCESS-NAME,com.tencent.tmgp.mywar,{{ rule }} # 我的战争
PROCESS-NAME,com.tencent.tmgp.nanningmj,{{ rule }} # 南宁麻将
PROCESS-NAME,com.tencent.tmgp.NBA,{{ rule }} # 最强NBA
PROCESS-NAME,com.tencent.tmgp.netcraftyouyi,{{ rule }} # 奶块
PROCESS-NAME,com.tencent.tmgp.nextjoy.dlamfc,{{ rule }} # 哆啦A梦飞车
PROCESS-NAME,com.tencent.tmgp.ninefun.ark,{{ rule }} # 仙国志
PROCESS-NAME,com.tencent.tmgp.nn4,{{ rule }} # 闪耀暖暖
PROCESS-NAME,com.tencent.tmgp.nomoga.fsandroid,{{ rule }} # 封神幻想世界
PROCESS-NAME,com.tencent.tmgp.nshm,{{ rule }} # 逆水寒
PROCESS-NAME,com.tencent.tmgp.nsn592.bubblefish,{{ rule }} # 萌鱼泡泡
PROCESS-NAME,com.tencent.tmgp.nysgs2,{{ rule }} # 怒焰三国杀
PROCESS-NAME,com.tencent.tmgp.oasis.jlcq,{{ rule }} # 君临传奇
PROCESS-NAME,com.tencent.tmgp.oceantradekings,{{ rule }} # 航海霸业
PROCESS-NAME,com.tencent.tmgp.orangesgamefh,{{ rule }} # 逗趣医院游戏软件V2.1.0
PROCESS-NAME,com.tencent.tmgp.p16s,{{ rule }} # 银河战舰
PROCESS-NAME,com.tencent.tmgp.p2pcncn.hwyad,{{ rule }} # 凌云诺
PROCESS-NAME,com.tencent.tmgp.p31,{{ rule }} # 朕的江山2
PROCESS-NAME,com.tencent.tmgp.p5x,{{ rule }} # 女神异闻录：夜幕魅影
PROCESS-NAME,com.tencent.tmgp.p6cncn.hwyad,{{ rule }} # 浮生忆玲珑
PROCESS-NAME,com.tencent.tmgp.p7mj,{{ rule }} # 开运麻将
PROCESS-NAME,com.tencent.tmgp.PalaceM2cncn,{{ rule }} # 熹妃传
PROCESS-NAME,com.tencent.tmgp.palacem4cncn.hwyad,{{ rule }} # 宫廷计手游
PROCESS-NAME,com.tencent.tmgp.palol,{{ rule }} # 仙剑奇侠传online
PROCESS-NAME,com.tencent.tmgp.pandadastudio.ninja3,{{ rule }} # 忍者必须死3
PROCESS-NAME,com.tencent.tmgp.paoyao33,{{ rule }} # 刨幺
PROCESS-NAME,com.tencent.tmgp.party,{{ rule }} # 蛋仔派对
PROCESS-NAME,com.tencent.tmgp.pdkhj,{{ rule }} # 跑得快合集
PROCESS-NAME,com.tencent.tmgp.pfdmw,{{ rule }} # 票房大卖王
PROCESS-NAME,com.tencent.tmgp.phoenixAnhuiyyb,{{ rule }} # 边锋掼蛋
PROCESS-NAME,com.tencent.tmgp.pisces,{{ rule }} # 桃花源记
PROCESS-NAME,com.tencent.tmgp.pkwan.op,{{ rule }} # 航海王：燃烧意志
PROCESS-NAME,com.tencent.tmgp.playcrab.dazhangmen2,{{ rule }} # 大掌门2
PROCESS-NAME,com.tencent.tmgp.playcrab.kos,{{ rule }} # 一拳超人：最强之男
PROCESS-NAME,com.tencent.tmgp.playrix.township.chukong,{{ rule }} # 梦想城镇
PROCESS-NAME,com.tencent.tmgp.pocketworld,{{ rule }} # 我爱拼模型
PROCESS-NAME,com.tencent.tmgp.pook.foodgame,{{ rule }} # 爆炒江湖
PROCESS-NAME,com.tencent.tmgp.poolmastersl,{{ rule }} # 台球游戏大师
PROCESS-NAME,com.tencent.tmgp.pop.game.dreamhome,{{ rule }} # 梦想家园
PROCESS-NAME,com.tencent.tmgp.projectsnow,{{ rule }} # 尘白禁区
PROCESS-NAME,com.tencent.tmgp.projectt,{{ rule }} # 天龙八部2：飞龙战天
PROCESS-NAME,com.tencent.tmgp.pubgmhd,{{ rule }} # 和平精英
PROCESS-NAME,com.tencent.tmgp.pvz2hdtxyyb,{{ rule }} # 植物大战僵尸2
PROCESS-NAME,com.tencent.tmgp.pygame.zipai,{{ rule }} # 同城字牌
PROCESS-NAME,com.tencent.tmgp.qblykilltext,{{ rule }} # 谁是卧底移动版
PROCESS-NAME,com.tencent.tmgp.qilong.warship,{{ rule }} # 战舰冲突
PROCESS-NAME,com.tencent.tmgp.qinsmoon,{{ rule }} # 秦时明月卡牌版
PROCESS-NAME,com.tencent.tmgp.qiwanhh,{{ rule }} # 航海纷争
PROCESS-NAME,com.tencent.tmgp.qjnn,{{ rule }} # 奇迹暖暖
PROCESS-NAME,com.tencent.tmgp.qjzjkp,{{ rule }} # 奇迹之剑
PROCESS-NAME,com.tencent.tmgp.qlbt.cly,{{ rule }} # 器灵宝塔
PROCESS-NAME,com.tencent.tmgp.qlfhl,{{ rule }} # 青鸾繁华录
PROCESS-NAME,com.tencent.tmgp.qmdgl,{{ rule }} # 全民大灌篮
PROCESS-NAME,com.tencent.tmgp.qmlwesss,{{ rule }} # 全民乐舞
PROCESS-NAME,com.tencent.tmgp.qmqz2022,{{ rule }} # 全民枪战2
PROCESS-NAME,com.tencent.tmgp.qmxb1,{{ rule }} # 全民学霸
PROCESS-NAME,com.tencent.tmgp.qmyxatm,{{ rule }} # 全民奥特曼之银河英雄
PROCESS-NAME,com.tencent.tmgp.qmzg.wszj.yyb,{{ rule }} # 无双战将
PROCESS-NAME,com.tencent.tmgp.qqx5,{{ rule }} # QQ炫舞
PROCESS-NAME,com.tencent.tmgp.qqyx,{{ rule }} # 球球英雄
PROCESS-NAME,com.tencent.tmgp.qsroom1,{{ rule }} # 密室逃脱求生系列1极地冒险
PROCESS-NAME,com.tencent.tmgp.qtdl3d,{{ rule }} # 抢滩登陆3D
PROCESS-NAME,com.tencent.tmgp.qxxy.cookingcity,{{ rule }} # 小镇大厨
PROCESS-NAME,com.tencent.tmgp.qyj,{{ rule }} # 青云诀
PROCESS-NAME,com.tencent.tmgp.qyn,{{ rule }} # 庆余年
PROCESS-NAME,com.tencent.tmgp.qzxy,{{ rule }} # 葫芦兄弟：七子降妖
PROCESS-NAME,com.tencent.tmgp.road7.ddtdmxandroid,{{ rule }} # 弹弹堂大冒险
PROCESS-NAME,com.tencent.tmgp.rollingsky,{{ rule }} # 滚动的天空
PROCESS-NAME,com.tencent.tmgp.rome,{{ rule }} # 帝国军团罗马
PROCESS-NAME,com.tencent.tmgp.room1,{{ rule }} # 密室逃脱1逃离地牢
PROCESS-NAME,com.tencent.tmgp.Room13,{{ rule }} # 密室逃脱13秘密任务
PROCESS-NAME,com.tencent.tmgp.room4,{{ rule }} # 密室逃脱影城之谜4
PROCESS-NAME,com.tencent.tmgp.rshyzncq,{{ rule }} # 真牛传奇
PROCESS-NAME,com.tencent.tmgp.rxcq,{{ rule }} # 热血传奇
PROCESS-NAME,com.tencent.tmgp.rxjhbj,{{ rule }} # 热血江湖手游
PROCESS-NAME,com.tencent.tmgp.rxsjkp,{{ rule }} # 热血神剑
PROCESS-NAME,com.tencent.tmgp.s3.sgzzlb,{{ rule }} # 三国志·战略版
PROCESS-NAME,com.tencent.tmgp.sanguobt,{{ rule }} # 攻城掠地（唯一正版）
PROCESS-NAME,com.tencent.tmgp.sanguosha.mjz,{{ rule }} # 三国杀名将传
PROCESS-NAME,com.tencent.tmgp.sbcsmj,{{ rule }} # 随便玩长沙麻将
PROCESS-NAME,com.tencent.tmgp.sbkcqjlcsmb,{{ rule }} # 戒灵传说
PROCESS-NAME,com.tencent.tmgp.sbphz,{{ rule }} # 随便跑胡子
PROCESS-NAME,com.tencent.tmgp.sbsdh,{{ rule }} # 三打哈
PROCESS-NAME,com.tencent.tmgp.sbwpdk,{{ rule }} # 随便跑得快
PROCESS-NAME,com.tencent.tmgp.sbzp,{{ rule }} # 随便字牌
PROCESS-NAME,com.tencent.tmgp.scmjxzddnew,{{ rule }} # 四川麻将（血战到底）
PROCESS-NAME,com.tencent.tmgp.scqmjhly,{{ rule }} # 全民江湖
PROCESS-NAME,com.tencent.tmgp.sds,{{ rule }} # 圣斗士星矢：重生
PROCESS-NAME,com.tencent.tmgp.sdsbq,{{ rule }} # 射雕
PROCESS-NAME,com.tencent.tmgp.sdsysdk,{{ rule }} # 圣斗士星矢：正义传说
PROCESS-NAME,com.tencent.tmgp.sdxl,{{ rule }} # 神雕侠侣
PROCESS-NAME,com.tencent.tmgp.seal,{{ rule }} # 征途
PROCESS-NAME,com.tencent.tmgp.seasun.jxsj3,{{ rule }} # 剑侠世界3
PROCESS-NAME,com.tencent.tmgp.seasun.jxsjorg,{{ rule }} # 剑侠世界：起源
PROCESS-NAME,com.tencent.tmgp.secret,{{ rule }} # 黑猫奇闻社
PROCESS-NAME,com.tencent.tmgp.SeerInfiniteUniverse,{{ rule }} # 赛尔号星球大战
PROCESS-NAME,com.tencent.tmgp.SevenHegemony,{{ rule }} # 七雄争霸
PROCESS-NAME,com.tencent.tmgp.sf3,{{ rule }} # 暗影格斗3
PROCESS-NAME,com.tencent.tmgp.sg3,{{ rule }} # 放开那三国3
PROCESS-NAME,com.tencent.tmgp.sgame,{{ rule }} # 王者荣耀
PROCESS-NAME,com.tencent.tmgp.sgcs,{{ rule }} # 三国传说
PROCESS-NAME,com.tencent.tmgp.sgfx,{{ rule }} # 曙光防线
PROCESS-NAME,com.tencent.tmgp.sglbcs,{{ rule }} # 三国吕布传说
PROCESS-NAME,com.tencent.tmgp.sgqyz,{{ rule }} # 三国群英传-霸王之业
PROCESS-NAME,com.tencent.tmgp.sgqyzhhby,{{ rule }} # 三国群英传：鸿鹄霸业
PROCESS-NAME,com.tencent.tmgp.sgs.x,{{ rule }} # 三国杀：一将成名
PROCESS-NAME,com.tencent.tmgp.sgspad.yyb,{{ rule }} # 三国杀OL互通版
PROCESS-NAME,com.tencent.tmgp.sgz2017,{{ rule }} # 三国志2017
PROCESS-NAME,com.tencent.tmgp.sgzj2,{{ rule }} # 欢动三国战纪2
PROCESS-NAME,com.tencent.tmgp.sgzr,{{ rule }} # 三国之刃
PROCESS-NAME,com.tencent.tmgp.sgzzqb,{{ rule }} # 三国志·战棋版
PROCESS-NAME,com.tencent.tmgp.sh.cly,{{ rule }} # 山河
PROCESS-NAME,com.tencent.tmgp.shangguxiux,{{ rule }} # 上古修仙
PROCESS-NAME,com.tencent.tmgp.shdlln,{{ rule }} # 神火大陆
PROCESS-NAME,com.tencent.tmgp.shelter,{{ rule }} # 辐射：避难所Online
PROCESS-NAME,com.tencent.tmgp.shenghewzcq,{{ rule }} # 王者传奇
PROCESS-NAME,com.tencent.tmgp.shenghuawc1,{{ rule }} # 生化围城
PROCESS-NAME,com.tencent.tmgp.shyyl,{{ rule }} # 山海与妖灵
PROCESS-NAME,com.tencent.tmgp.sichuan,{{ rule }} # 蜀山四川麻将
PROCESS-NAME,com.tencent.tmgp.sjsgfx,{{ rule }} # 神将三国
PROCESS-NAME,com.tencent.tmgp.sjyxwy,{{ rule }} # 启源女神
PROCESS-NAME,com.tencent.tmgp.sjzt.ingames,{{ rule }} # 圣境之塔
PROCESS-NAME,com.tencent.tmgp.skgame,{{ rule }} # 太空杀
PROCESS-NAME,com.tencent.tmgp.skysgame.xyqy,{{ rule }} # 逍遥情缘
PROCESS-NAME,com.tencent.tmgp.slsmfx,{{ rule }} # 狩猎使命
PROCESS-NAME,com.tencent.tmgp.sm,{{ rule }} # 创造与魔法
PROCESS-NAME,com.tencent.tmgp.smdl.qy,{{ rule }} # 神魔大陆
PROCESS-NAME,com.tencent.tmgp.sniper3dv2,{{ rule }} # 狙击行动：代号猎鹰
PROCESS-NAME,com.tencent.tmgp.snk.kofworld,{{ rule }} # 拳皇世界
PROCESS-NAME,com.tencent.tmgp.snsgz,{{ rule }} # 少年三国志
PROCESS-NAME,com.tencent.tmgp.sparrowkwx2dx.maijie,{{ rule }} # 楚天优游卡五星麻将
PROCESS-NAME,com.tencent.tmgp.speedmobile,{{ rule }} # QQ飞车
PROCESS-NAME,com.tencent.tmgp.srxs.wcqy,{{ rule }} # 王朝起源
PROCESS-NAME,com.tencent.tmgp.ssjj.gbws,{{ rule }} # 果宝无双
PROCESS-NAME,com.tencent.tmgp.ssjj.ghyj,{{ rule }} # 古荒遗迹
PROCESS-NAME,com.tencent.tmgp.ssjj.zmdld,{{ rule }} # 造梦大乱斗
PROCESS-NAME,com.tencent.tmgp.ssjj.zmws,{{ rule }} # 造梦无双
PROCESS-NAME,com.tencent.tmgp.sskgame,{{ rule }} # 圣斗士星矢-官方正版(腾讯)
PROCESS-NAME,com.tencent.tmgp.sssf37,{{ rule }} # 谁是首富
PROCESS-NAME,com.tencent.tmgp.sszg,{{ rule }} # 闪烁之光
PROCESS-NAME,com.tencent.tmgp.styjz,{{ rule }} # 隋唐英杰传
PROCESS-NAME,com.tencent.tmgp.stzb,{{ rule }} # 率土之滨
PROCESS-NAME,com.tencent.tmgp.supercell.boombeach,{{ rule }} # 海岛奇兵
PROCESS-NAME,com.tencent.tmgp.supercell.brawlstars,{{ rule }} # 荒野乱斗
PROCESS-NAME,com.tencent.tmgp.supercell.clashofclans,{{ rule }} # 部落冲突
PROCESS-NAME,com.tencent.tmgp.supercell.clashroyale,{{ rule }} # 皇室战争
PROCESS-NAME,com.tencent.tmgp.supercell.hayday,{{ rule }} # 卡通农场
PROCESS-NAME,com.tencent.tmgp.supertractor,{{ rule }} # 拖拉机升级
PROCESS-NAME,com.tencent.tmgp.survivedks,{{ rule }} # 活下去
PROCESS-NAME,com.tencent.tmgp.swzshg,{{ rule }} # 诸神皇冠
PROCESS-NAME,com.tencent.tmgp.sx6gm,{{ rule }} # 思仙
PROCESS-NAME,com.tencent.tmgp.sxddc,{{ rule }} # 神仙道高清重制版
PROCESS-NAME,com.tencent.tmgp.sxdthree,{{ rule }} # 神仙道3
PROCESS-NAME,com.tencent.tmgp.sylj,{{ rule }} # 亮剑
PROCESS-NAME,com.tencent.tmgp.sysgzhd,{{ rule }} # 时光杂货店
PROCESS-NAME,com.tencent.tmgp.syzshhzf,{{ rule }} # 诸神黄昏：征服
PROCESS-NAME,com.tencent.tmgp.szgd,{{ rule }} # 森之国度
PROCESS-NAME,com.tencent.tmgp.szh.xiaoyao,{{ rule }} # 小吆三打哈
PROCESS-NAME,com.tencent.tmgp.taiyouxi.tk2,{{ rule }} # 极无双2
PROCESS-NAME,com.tencent.tmgp.tata.wjhd,{{ rule }} # 无尽寒冬
PROCESS-NAME,com.tencent.tmgp.TCrossSGJQ,{{ rule }} # 腾讯天天军棋
PROCESS-NAME,com.tencent.tmgp.tdj,{{ rule }} # 天地劫：幽城再临
PROCESS-NAME,com.tencent.tmgp.tew,{{ rule }} # 变形金刚：地球之战
PROCESS-NAME,com.tencent.tmgp.tfjl,{{ rule }} # 塔防精灵
PROCESS-NAME,com.tencent.tmgp.tfxyj,{{ rule }} # 塔防西游记
PROCESS-NAME,com.tencent.tmgp.tfzhs.caohua,{{ rule }} # 塔防镇魂师
PROCESS-NAME,com.tencent.tmgp.tgfml2,{{ rule }} # 太古封魔录2
PROCESS-NAME,com.tencent.tmgp.tiancity.dom,{{ rule }} # 战争与文明
PROCESS-NAME,com.tencent.tmgp.tianmashikong.qj,{{ rule }} # 全民奇迹
PROCESS-NAME,com.tencent.tmgp.tigergame.fishing,{{ rule }} # 狂野钓鱼2-钓王荣耀
PROCESS-NAME,com.tencent.tmgp.tinghood.TpsForMobile.yyb3,{{ rule }} # 台球世界
PROCESS-NAME,com.tencent.tmgp.tjbkp,{{ rule }} # 天姬变
PROCESS-NAME,com.tencent.tmgp.tk2.x,{{ rule }} # 坦克争锋
PROCESS-NAME,com.tencent.tmgp.tkjz,{{ rule }} # 坦克大决战-战火重燃
PROCESS-NAME,com.tencent.tmgp.tmsk.qj2,{{ rule }} # 奇迹：觉醒
PROCESS-NAME,com.tencent.tmgp.tmsk.qj3,{{ rule }} # 全民奇迹2
PROCESS-NAME,com.tencent.tmgp.tmsk.zhzr,{{ rule }} # 真红之刃
PROCESS-NAME,com.tencent.tmgp.tmst,{{ rule }} # 同盟神探
PROCESS-NAME,com.tencent.tmgp.tom,{{ rule }} # 猫和老鼠（正版授权）
PROCESS-NAME,com.tencent.tmgp.tong.lcgame,{{ rule }} # 归龙潮
PROCESS-NAME,com.tencent.tmgp.tqbaohuang,{{ rule }} # 大眼保皇
PROCESS-NAME,com.tencent.tmgp.tqfuzhoumajiang,{{ rule }} # 福州麻将
PROCESS-NAME,com.tencent.tmgp.tqgouji,{{ rule }} # 大眼够级
PROCESS-NAME,com.tencent.tmgp.tqguandan,{{ rule }} # 大眼掼蛋
PROCESS-NAME,com.tencent.tmgp.tqshengji,{{ rule }} # 大眼升级
PROCESS-NAME,com.tencent.tmgp.tqshuangkou,{{ rule }} # 大眼双扣
PROCESS-NAME,com.tencent.tmgp.tqwzfx,{{ rule }} # 台球王者
PROCESS-NAME,com.tencent.tmgp.tqzhuojimajiang,{{ rule }} # 大眼捉鸡麻将
PROCESS-NAME,com.tencent.tmgp.trssj,{{ rule }} # 塔瑞斯世界
PROCESS-NAME,com.tencent.tmgp.tsjyyz,{{ rule }} # 天使纪元
PROCESS-NAME,com.tencent.tmgp.tssy,{{ rule }} # 塔防三国志II
PROCESS-NAME,com.tencent.tmgp.tstl,{{ rule }} # 天龙八部手游
PROCESS-NAME,com.tencent.tmgp.tszr.shengmiao,{{ rule }} # 吞食之刃
PROCESS-NAME,com.tencent.tmgp.tszz,{{ rule }} # 天使之战
PROCESS-NAME,com.tencent.tmgp.ttaxq,{{ rule }} # 天天爱象棋
PROCESS-NAME,com.tencent.tmgp.ttcz,{{ rule }} # 六龙争霸
PROCESS-NAME,com.tencent.tmgp.ttdg,{{ rule }} # 塔塔帝国
PROCESS-NAME,com.tencent.tmgp.ttgjtwo,{{ rule }} # 天天够级
PROCESS-NAME,com.tencent.tmgp.tthy.dtl,{{ rule }} # 大屠龙
PROCESS-NAME,com.tencent.tmgp.ttmj,{{ rule }} # 腾讯麻将来了（QQ麻将）
PROCESS-NAME,com.tencent.tmgp.tttq,{{ rule }} # 天天台球
PROCESS-NAME,com.tencent.tmgp.ttwgd,{{ rule }} # 天天玩掼蛋
PROCESS-NAME,com.tencent.tmgp.ttwq,{{ rule }} # 腾讯围棋
PROCESS-NAME,com.tencent.tmgp.twrxhjly,{{ rule }} # 热血合击
PROCESS-NAME,com.tencent.tmgp.twyscq,{{ rule }} # 原始传奇
PROCESS-NAME,com.tencent.tmgp.tx,{{ rule }} # 天下
PROCESS-NAME,com.tencent.tmgp.tydoudizhu,{{ rule }} # 途游斗地主（比赛版）
PROCESS-NAME,com.tencent.tmgp.tzyxmznew,{{ rule }} # 梦幻新诛仙
PROCESS-NAME,com.tencent.tmgp.tzyz.meng,{{ rule }} # 无尽梦回
PROCESS-NAME,com.tencent.tmgp.tzyz.pao,{{ rule }} # 超时空跑跑
PROCESS-NAME,com.tencent.tmgp.u1game.ptyj,{{ rule }} # 破天一剑
PROCESS-NAME,com.tencent.tmgp.ultraman,{{ rule }} # 奥特曼系列OL
PROCESS-NAME,com.tencent.tmgp.uniugame.xinw,{{ rule }} # 心舞
PROCESS-NAME,com.tencent.tmgp.universeatm,{{ rule }} # 奥特曼宇宙英雄
PROCESS-NAME,com.tencent.tmgp.uuapps.chinachess,{{ rule }} # 经典中国象棋
PROCESS-NAME,com.tencent.tmgp.uuapps.doudizhu,{{ rule }} # 经典单机斗地主
PROCESS-NAME,com.tencent.tmgp.uuapps.sichuan,{{ rule }} # 单机四川麻将
PROCESS-NAME,com.tencent.tmgp.uuappsmajiang,{{ rule }} # 经典单机麻将
PROCESS-NAME,com.tencent.tmgp.vlfcn,{{ rule }} # 绿茵信仰
PROCESS-NAME,com.tencent.tmgp.wafcncn.hwyad,{{ rule }} # 杜拉拉升职记
PROCESS-NAME,com.tencent.tmgp.wansuiye,{{ rule }} # 叫我万岁爷
PROCESS-NAME,com.tencent.tmgp.warofempire,{{ rule }} # 大帝国征服者
PROCESS-NAME,com.tencent.tmgp.wckj.zljz,{{ rule }} # 逐鹿九州
PROCESS-NAME,com.tencent.tmgp.wdqy,{{ rule }} # 我的起源
PROCESS-NAME,com.tencent.tmgp.wdsj666,{{ rule }} # 我的世界：移动版
PROCESS-NAME,com.tencent.tmgp.wdsm,{{ rule }} # 我的使命
PROCESS-NAME,com.tencent.tmgp.wdyjrj,{{ rule }} # 我的御剑日记
PROCESS-NAME,com.tencent.tmgp.wec,{{ rule }} # 乱世王者
PROCESS-NAME,com.tencent.tmgp.wegametk,{{ rule }} # 坦克无敌
PROCESS-NAME,com.tencent.tmgp.weile.doudizhu,{{ rule }} # 微乐斗地主移动版 V1.0.0
PROCESS-NAME,com.tencent.tmgp.weile.sichuanmj,{{ rule }} # 微乐四川麻将移动版
PROCESS-NAME,com.tencent.tmgp.WePop,{{ rule }} # 跑跑卡丁车官方竞速版
PROCESS-NAME,com.tencent.tmgp.werewolfbattle,{{ rule }} # 狼人对决
PROCESS-NAME,com.tencent.tmgp.whrhx,{{ rule }} # 无悔华夏
PROCESS-NAME,com.tencent.tmgp.wjmtgl,{{ rule }} # 我叫MT：归来
PROCESS-NAME,com.tencent.tmgp.wjxt,{{ rule }} # 无极仙途
PROCESS-NAME,com.tencent.tmgp.wkcsmj,{{ rule }} # 微壳长沙麻将
PROCESS-NAME,com.tencent.tmgp.wksdh,{{ rule }} # 微壳三打哈
PROCESS-NAME,com.tencent.tmgp.wkzbeqw,{{ rule }} # 微壳二七王
PROCESS-NAME,com.tencent.tmgp.wmsjjdb,{{ rule }} # 完美世界：诸神之战
PROCESS-NAME,com.tencent.tmgp.wodn,{{ rule }} # 龙之谷世界
PROCESS-NAME,com.tencent.tmgp.woobest.mysq,{{ rule }} # 命运圣契
PROCESS-NAME,com.tencent.tmgp.woobestsgwg,{{ rule }} # 上古王冠
PROCESS-NAME,com.tencent.tmgp.wooduan.ssjj,{{ rule }} # 生死狙击
PROCESS-NAME,com.tencent.tmgp.worldwarfare2,{{ rule }} # 二战风云2
PROCESS-NAME,com.tencent.tmgp.wpzz,{{ rule }} # 王牌战争
PROCESS-NAME,com.tencent.tmgp.wszg,{{ rule }} # 万乘之国
PROCESS-NAME,com.tencent.tmgp.wtcm.yzgame,{{ rule }} # 元尊
PROCESS-NAME,com.tencent.tmgp.wuxia,{{ rule }} # 天涯明月刀手游
PROCESS-NAME,com.tencent.tmgp.wxwy,{{ rule }} # 万象物语
PROCESS-NAME,com.tencent.tmgp.wzxx,{{ rule }} # 王者修仙
PROCESS-NAME,com.tencent.tmgp.wzyd.huiyue,{{ rule }} # 王者一刀
PROCESS-NAME,com.tencent.tmgp.xblr,{{ rule }} # 新不良人（第六季独家）
PROCESS-NAME,com.tencent.tmgp.xbxxz,{{ rule }} # 想不想修真
PROCESS-NAME,com.tencent.tmgp.xcdphz,{{ rule }} # 跑胡子
PROCESS-NAME,com.tencent.tmgp.xdsw.Aoe,{{ rule }} # 指尖帝国
PROCESS-NAME,com.tencent.tmgp.xianjianshijie.cmge,{{ rule }} # 仙剑世界
PROCESS-NAME,com.tencent.tmgp.xianlinwy,{{ rule }} # 仙灵物语
PROCESS-NAME,com.tencent.tmgp.ximi,{{ rule }} # 中职篮：全力以赴
PROCESS-NAME,com.tencent.tmgp.xishanju.mysy,{{ rule }} # 魔域手游
PROCESS-NAME,com.tencent.tmgp.xjqxz,{{ rule }} # 仙剑奇侠传：新的开始
PROCESS-NAME,com.tencent.tmgp.xkd.yzx,{{ rule }} # 侠客道
PROCESS-NAME,com.tencent.tmgp.xlwyln,{{ rule }} # 驯龙物语
PROCESS-NAME,com.tencent.tmgp.xmcm,{{ rule }} # 策马守天关
PROCESS-NAME,com.tencent.tmgp.xncp,{{ rule }} # 小南四川长牌
PROCESS-NAME,com.tencent.tmgp.xpdl,{{ rule }} # 西普大陆
PROCESS-NAME,com.tencent.tmgp.xsj.fbmy2,{{ rule }} # 风暴魔域2
PROCESS-NAME,com.tencent.tmgp.xsmdl,{{ rule }} # 新神魔大陆
PROCESS-NAME,com.tencent.tmgp.xtlbb,{{ rule }} # 新天龙八部
PROCESS-NAME,com.tencent.tmgp.xuezunew,{{ rule }} # 血族
PROCESS-NAME,com.tencent.tmgp.xunkaish.hhxxl,{{ rule }} # 洪荒西行录
PROCESS-NAME,com.tencent.tmgp.xunyou.xxzzmj,{{ rule }} # 八牛斗地主
PROCESS-NAME,com.tencent.tmgp.xxajh,{{ rule }} # 新笑傲江湖
PROCESS-NAME,com.tencent.tmgp.xxcz,{{ rule }} # 小小村长
PROCESS-NAME,com.tencent.tmgp.xxsy,{{ rule }} # 寻仙手游
PROCESS-NAME,com.tencent.tmgp.xxtjd,{{ rule }} # 小小突击队
PROCESS-NAME,com.tencent.tmgp.xxyg,{{ rule }} # 小小蚁国
PROCESS-NAME,com.tencent.tmgp.xxyymxj,{{ rule }} # 影业梦想家
PROCESS-NAME,com.tencent.tmgp.xxyz123,{{ rule }} # 小小勇者
PROCESS-NAME,com.tencent.tmgp.xymobile,{{ rule }} # 轩辕传奇手游
PROCESS-NAME,com.tencent.tmgp.xynegyz,{{ rule }} # 西游女儿国
PROCESS-NAME,com.tencent.tmgp.xztl,{{ rule }} # 血战屠龙
PROCESS-NAME,com.tencent.tmgp.ycdml,{{ rule }} # 异尘：达米拉
PROCESS-NAME,com.tencent.tmgp.ycxjjjc,{{ rule }} # 仙境竞技场
PROCESS-NAME,com.tencent.tmgp.ydcsly,{{ rule }} # 一刀传世
PROCESS-NAME,com.tencent.tmgp.ydgame.twzwtwo,{{ rule }} # 塔王之王2
PROCESS-NAME,com.tencent.tmgp.ydxh.cnchess,{{ rule }} # 象棋黄金版
PROCESS-NAME,com.tencent.tmgp.ydxh.superblock,{{ rule }} # 俄罗斯方块大战
PROCESS-NAME,com.tencent.tmgp.ygdhk,{{ rule }} # 勇敢的哈克
PROCESS-NAME,com.tencent.tmgp.yhhoa,{{ rule }} # 英魂之刃战略版
PROCESS-NAME,com.tencent.tmgp.yhzxtwzw,{{ rule }} # 塔王之王
PROCESS-NAME,com.tencent.tmgp.yhzz.huiyue,{{ rule }} # 永恒征战
PROCESS-NAME,com.tencent.tmgp.yinhan.skzh,{{ rule }} # 时空召唤
PROCESS-NAME,com.tencent.tmgp.yjqy,{{ rule }} # 御剑情缘
PROCESS-NAME,com.tencent.tmgp.ykdqddz,{{ rule }} # 真人天天斗地主
PROCESS-NAME,com.tencent.tmgp.ylandscn,{{ rule }} # 艾兰岛手游
PROCESS-NAME,com.tencent.tmgp.ylm,{{ rule }} # 御龙在天手游
PROCESS-NAME,com.tencent.tmgp.yndssy,{{ rule }} # 异能都市
PROCESS-NAME,com.tencent.tmgp.ynxy.fangzhou,{{ rule }} # 一念永恒：少年追梦
PROCESS-NAME,com.tencent.tmgp.yokaverse.zzxy,{{ rule }} # 自在西游
PROCESS-NAME,com.tencent.tmgp.yonghenglianmeng,{{ rule }} # 永恒联盟
PROCESS-NAME,com.tencent.tmgp.yongyong.clx,{{ rule }} # 一梦江湖
PROCESS-NAME,com.tencent.tmgp.yongyong.frxy,{{ rule }} # 非人学园
PROCESS-NAME,com.tencent.tmgp.yongyong.mrzh,{{ rule }} # 明日之后
PROCESS-NAME,com.tencent.tmgp.yongyong.skwzjj,{{ rule }} # 实况:王者集结
PROCESS-NAME,com.tencent.tmgp.yongyong.skzq,{{ rule }} # 实况足球
PROCESS-NAME,com.tencent.tmgp.yongyong.tksjsjz,{{ rule }} # 坦克世界闪击战
PROCESS-NAME,com.tencent.tmgp.yongyong.zjsjsjz,{{ rule }} # 战舰世界闪击战
PROCESS-NAME,com.tencent.tmgp.yoozoo.jgame,{{ rule }} # 绯色回响
PROCESS-NAME,com.tencent.tmgp.yoozoo.sgyml,{{ rule }} # 三国云梦录
PROCESS-NAME,com.tencent.tmgp.youzu.shjh2,{{ rule }} # 山海镜花
PROCESS-NAME,com.tencent.tmgp.youzu.slpk1,{{ rule }} # 少年西游记2
PROCESS-NAME,com.tencent.tmgp.youzu.snsgz2,{{ rule }} # 少年三国志2
PROCESS-NAME,com.tencent.tmgp.youzu.ss0,{{ rule }} # 少年三国志：零
PROCESS-NAME,com.tencent.tmgp.youzu.xdmbj,{{ rule }} # 新盗墓笔记
PROCESS-NAME,com.tencent.tmgp.yqqskp,{{ rule }} # 元气骑士
PROCESS-NAME,com.tencent.tmgp.yr.sgllk,{{ rule }} # 水果连连看单机游戏
PROCESS-NAME,com.tencent.tmgp.yr.snxxl,{{ rule }} # 收纳消消乐
PROCESS-NAME,com.tencent.tmgp.yr.starxxl,{{ rule }} # 星星消消乐单机游戏
PROCESS-NAME,com.tencent.tmgp.yr.tetris,{{ rule }} # 俄罗斯方块游戏
PROCESS-NAME,com.tencent.tmgp.ysdl,{{ rule }} # 云上大陆
PROCESS-NAME,com.tencent.tmgp.yslzm,{{ rule }} # 以闪亮之名
PROCESS-NAME,com.tencent.tmgp.ysymx,{{ rule }} # 勇士与冒险
PROCESS-NAME,com.tencent.tmgp.yttlj,{{ rule }} # 倚天屠龙记
PROCESS-NAME,com.tencent.tmgp.yttxky,{{ rule }} # 三国一统天下
PROCESS-NAME,com.tencent.tmgp.yulongzhanxian.shengdu,{{ rule }} # 御龙战仙
PROCESS-NAME,com.tencent.tmgp.yunbu.alicemergeland,{{ rule }} # 糖果精灵传奇
PROCESS-NAME,com.tencent.tmgp.yunbu.badmintonleague,{{ rule }} # 羽毛球高高手游戏软件 1.1.3023
PROCESS-NAME,com.tencent.tmgp.yunbu.nonogram,{{ rule }} # 数独趣味闯关
PROCESS-NAME,com.tencent.tmgp.yunbu.puppyblast,{{ rule }} # 甜点消消
PROCESS-NAME,com.tencent.tmgp.yunbu.sniperhonor,{{ rule }} # 千纹时空
PROCESS-NAME,com.tencent.tmgp.yuyoupoker101,{{ rule }} # 宇游麻将
PROCESS-NAME,com.tencent.tmgp.yxwdzzjy,{{ rule }} # 魔法门之英雄无敌：战争纪元
PROCESS-NAME,com.tencent.tmgp.yy.nbalqsj,{{ rule }} # 美职篮篮球世界
PROCESS-NAME,com.tencent.tmgp.yybdldlwhjx.qidian,{{ rule }} # 斗罗大陆：武魂觉醒
PROCESS-NAME,com.tencent.tmgp.yyhdyl.ddt,{{ rule }} # 斗斗堂
PROCESS-NAME,com.tencent.tmgp.yyjl,{{ rule }} # 永夜降临：复苏
PROCESS-NAME,com.tencent.tmgp.yys.zqb,{{ rule }} # 阴阳师
PROCESS-NAME,com.tencent.tmgp.yysbwp,{{ rule }} # 阴阳师：百闻牌
PROCESS-NAME,com.tencent.tmgp.yyslscn,{{ rule }} # 燕云十六声
PROCESS-NAME,com.tencent.tmgp.yyxx.qyj2,{{ rule }} # 青云诀2
PROCESS-NAME,com.tencent.tmgp.yyzy2,{{ rule }} # 月圆之夜
PROCESS-NAME,com.tencent.tmgp.yzg36,{{ rule }} # 三十六计
PROCESS-NAME,com.tencent.tmgp.yzjq,{{ rule }} # 蚁族崛起
PROCESS-NAME,com.tencent.tmgp.yzsnxyj,{{ rule }} # 少年西游记
PROCESS-NAME,com.tencent.tmgp.YZSY,{{ rule }} # 远征手游
PROCESS-NAME,com.tencent.tmgp.YZTWO,{{ rule }} # 远征2
PROCESS-NAME,com.tencent.tmgp.yzy_yzy,{{ rule }} # 源战役
PROCESS-NAME,com.tencent.tmgp.yzycj,{{ rule }} # 勇者养成记
PROCESS-NAME,com.tencent.tmgp.zawwshzh,{{ rule }} # 无双斩
PROCESS-NAME,com.tencent.tmgp.zbsmsy,{{ rule }} # 蜀门
PROCESS-NAME,com.tencent.tmgp.zbwlwz,{{ rule }} # 武林外传
PROCESS-NAME,com.tencent.tmgp.zdbjlbj,{{ rule }} # 战斗吧！精灵
PROCESS-NAME,com.tencent.tmgp.zdsd.emmj,{{ rule }} # 恶魔秘境
PROCESS-NAME,com.tencent.tmgp.zgjjhd,{{ rule }} # 最高警戒
PROCESS-NAME,com.tencent.tmgp.zgzz.jl,{{ rule }} # 止戈之战
PROCESS-NAME,com.tencent.tmgp.zhanjian2,{{ rule }} # 战舰少女
PROCESS-NAME,com.tencent.tmgp.zhanlangii.wuziqi,{{ rule }} # 五子棋对战
PROCESS-NAME,com.tencent.tmgp.zhanlangii.xqdz,{{ rule }} # 象棋对战
PROCESS-NAME,com.tencent.tmgp.zhaohe2,{{ rule }} # 召唤与合成2
PROCESS-NAME,com.tencent.tmgp.zhdysr,{{ rule }} # 最后的原始人
PROCESS-NAME,com.tencent.tmgp.zhmr,{{ rule }} # 战魂铭人
PROCESS-NAME,com.tencent.tmgp.zhuanzhuanmj,{{ rule }} # 转转麻将随便玩
PROCESS-NAME,com.tencent.tmgp.zhuxian,{{ rule }} # 诛仙
PROCESS-NAME,com.tencent.tmgp.zjls2017,{{ rule }} # 战舰猎手
PROCESS-NAME,com.tencent.tmgp.zjqx2020,{{ rule }} # 装甲前线
PROCESS-NAME,com.tencent.tmgp.zjscmj,{{ rule }} # 指尖四川麻将
PROCESS-NAME,com.tencent.tmgp.zjsesc,{{ rule }} # 紫禁十二时辰
PROCESS-NAME,com.tencent.tmgp.zlongame.cn.epicseven,{{ rule }} # 第七史诗
PROCESS-NAME,com.tencent.tmgp.zmcq.renyou,{{ rule }} # 祖玛传奇
PROCESS-NAME,com.tencent.tmgp.zmsy.zmxywz,{{ rule }} # 造梦西游外传
PROCESS-NAME,com.tencent.tmgp.zmxy,{{ rule }} # 造梦西游4
PROCESS-NAME,com.tencent.tmgp.zmxyol,{{ rule }} # 造梦西游OL
PROCESS-NAME,com.tencent.tmgp.zoxun.jjmj,{{ rule }} # 竞技麻将
PROCESS-NAME,com.tencent.tmgp.zqdwj,{{ rule }} # 足球大玩家
PROCESS-NAME,com.tencent.tmgp.ztgame.fir,{{ rule }} # 征途2
PROCESS-NAME,com.tencent.tmgp.ztgame.wzzt,{{ rule }} # 王者征途
PROCESS-NAME,com.tencent.tmgp.ztgame.yszt,{{ rule }} # 原始征途
PROCESS-NAME,com.tencent.tmgp.zulong.drc,{{ rule }} # 龙族：卡塞尔之门
PROCESS-NAME,com.tencent.tmgp.zushi,{{ rule }} # 最强祖师
PROCESS-NAME,com.tencent.tmgp.zvsa,{{ rule }} # 烈火星辰
PROCESS-NAME,com.tencent.tmgp.zy.ddzjdb,{{ rule }} # 斗地主经典版
PROCESS-NAME,com.tencent.tmpg.yzywl.hldjddz,{{ rule }} # 欢乐单机斗地主
PROCESS-NAME,com.tencent.toaa,{{ rule }} # 黎明觉醒：生机
PROCESS-NAME,com.tencent.WeFire,{{ rule }} # 全民突击
PROCESS-NAME,com.tencent.wmsj,{{ rule }} # 完美世界
PROCESS-NAME,com.tencent.wod,{{ rule }} # 龙之谷2
PROCESS-NAME,com.tencent.wok,{{ rule }} # 万王之王3D
PROCESS-NAME,com.tencent.woool3d,{{ rule }} # 传奇世界3D
PROCESS-NAME,com.tencent.xjcard,{{ rule }} # 仙剑奇侠传官方手游
PROCESS-NAME,com.tencent.YiRen,{{ rule }} # 一人之下
PROCESS-NAME,com.tencent.yoozoo.got.wintercoming,{{ rule }} # 权力的游戏凛冬将至
PROCESS-NAME,com.tencent.zgqyz,{{ rule }} # 鸿图之下
PROCESS-NAME,com.tencent.zhandiwujiang,{{ rule }} # 战地无疆
PROCESS-NAME,com.tencent.zqry2018,{{ rule }} # 全民冠军足球
PROCESS-NAME,com.tistar.ar.forest,{{ rule }} # 猫小智动物园AR探索恐龙海底森林的软件
PROCESS-NAME,com.tongzhuo.tongzhuogame,{{ rule }} # 同桌派对
PROCESS-NAME,com.touchtech.bbword,{{ rule }} # 儿童脑筋急转弯
PROCESS-NAME,com.touchtech.etpintu,{{ rule }} # 宝宝儿童来拼图
PROCESS-NAME,com.touchtech.klCake,{{ rule }} # 宝宝过生日
PROCESS-NAME,com.ubestkid.jigsawpuzzle.a,{{ rule }} # 贝乐虎拼图
PROCESS-NAME,com.ultron.crimaster,{{ rule }} # CRIMASTER侦探联盟
PROCESS-NAME,com.uqee.lying.maingame,{{ rule }} # 卧龙吟-手机版
PROCESS-NAME,com.ustwo.monumentvalleyzz,{{ rule }} # 纪念碑谷
PROCESS-NAME,com.wedobest.HD1010,{{ rule }} # 罗斯方块
PROCESS-NAME,com.wedobest.hdxy,{{ rule }} # 同桌大作战
PROCESS-NAME,com.wedobest.llk,{{ rule }} # 连连看
PROCESS-NAME,com.wedobest.piano,{{ rule }} # 白块儿达人
PROCESS-NAME,com.wedobest.puzzlebubble,{{ rule }} # 泡泡射手
PROCESS-NAME,com.wedobest.shudu,{{ rule }} # 数独
PROCESS-NAME,com.wedobest.szhrd,{{ rule }} # 数字华容道
PROCESS-NAME,com.wedobest.xiangqi,{{ rule }} # 象棋
PROCESS-NAME,com.wepie.snake.tencent,{{ rule }} # 贪吃蛇大作战
PROCESS-NAME,com.wepie.werewolfkill,{{ rule }} # 微派狼人
PROCESS-NAME,com.wepie.wespy,{{ rule }} # 我是卧底
PROCESS-NAME,com.wodidashi.paint,{{ rule }} # 你画我猜
PROCESS-NAME,com.wordtiger.cargame,{{ rule }} # 儿童宝宝汽车拼图
PROCESS-NAME,com.wordtiger.flygame,{{ rule }} # 儿童飞机拼图
PROCESS-NAME,com.worldyy.qq.app,{{ rule }} # 世界Online
PROCESS-NAME,com.wp.sjh.yyb,{{ rule }} # 三剑豪
PROCESS-NAME,com.wushuang.landlord.kxlandlord,{{ rule }} # 开心斗地主
PROCESS-NAME,com.wzf.fan,{{ rule }} # 我是谜
PROCESS-NAME,com.xhtt.app.fzjh.test,{{ rule }} # 放置江湖
PROCESS-NAME,com.xingluo.gncolor,{{ rule }} # 涂色小画家
PROCESS-NAME,com.xueba.play,{{ rule }} # 做题软件
PROCESS-NAME,com.xzbig.idiom,{{ rule }} # 成语大接龙
PROCESS-NAME,com.xzidiom.stay,{{ rule }} # 成语小秀才
PROCESS-NAME,com.yinhan.hunter.tx,{{ rule }} # 时空猎人
PROCESS-NAME,com.yodo1.rodeo.TXYYB,{{ rule }} # 疯狂动物园
PROCESS-NAME,com.yodo1.SkiSafari.TXYYB_01,{{ rule }} # 滑雪大冒险
PROCESS-NAME,com.yodo1tier1.ctr2.TXWXYY,{{ rule }} # 割绳子2
PROCESS-NAME,com.youlu.newapp,{{ rule }} # 解忧娃娃
PROCESS-NAME,com.youxi.drawingchainer,{{ rule }} # 画画接龙
PROCESS-NAME,com.yunbu.arcadepool.tencent,{{ rule }} # 街机台球大师游戏软件V1.0
PROCESS-NAME,com.yunbu.bubbleelfsaga1,{{ rule }} # 泡泡精灵传奇
PROCESS-NAME,com.zhuoyukid.math,{{ rule }} # 贝贝数学
PROCESS-NAME,e.room.Escape,{{ rule }} # 谜案馆
PROCESS-NAME,lqs.kaisi.kdlianliankan,{{ rule }} # 单机游戏连连看
PROCESS-NAME,mt.shadow,{{ rule }} # 魔塔50层勇者的试炼
PROCESS-NAME,newbee.wordplay.cn.mi,{{ rule }} # 文字大玩家
PROCESS-NAME,org.islq.move2048,{{ rule }} # 天天2048
PROCESS-NAME,xyz.ymyapp.xbw.nearme.gamecenter,{{ rule }} # 小霸王
{% endmacro %}