{% macro main(rule) %}
PROCESS-NAME,bf.sgs.hdexp,{{ rule }} # 三国杀
PROCESS-NAME,cn.apppk.apps.chessroad,{{ rule }} # 象棋公社
PROCESS-NAME,cn.flytalk.shudu,{{ rule }} # 全民数独
PROCESS-NAME,cn.izis.mygo.mplat,{{ rule }} # 隐智围棋
PROCESS-NAME,cn.jj,{{ rule }} # JJ斗地主
PROCESS-NAME,com.airmpoint.solitaire.yyb,{{ rule }} # 纸牌接龙经典
PROCESS-NAME,com.aswind.libdesktoppet,{{ rule }} # 桌面萌宠
PROCESS-NAME,com.axx.learning.market,{{ rule }} # 高豆豆
PROCESS-NAME,com.bbqstudio.bbqq.yyb,{{ rule }} # 野蛮人大作战
PROCESS-NAME,com.bdapps.slimesimulator,{{ rule }} # 史莱姆模拟器制作
PROCESS-NAME,com.bftuolaji.yyb,{{ rule }} # 边锋拖拉机精简版
PROCESS-NAME,com.brianbaek.popstar,{{ rule }} # 消灭星星全新版
PROCESS-NAME,com.bruce.bestidiom,{{ rule }} # 成语拼拼拼
PROCESS-NAME,com.bruce.idiomxxl,{{ rule }} # 成语消消
PROCESS-NAME,com.bruce.riddle,{{ rule }} # 谜语猜猜猜
PROCESS-NAME,com.c2vl.kgamebox,{{ rule }} # 狼人杀
PROCESS-NAME,com.carrot.carrotfantasy,{{ rule }} # 保卫萝卜
PROCESS-NAME,com.chrysler.ball,{{ rule }} # 七彩五子连珠
PROCESS-NAME,com.dda.yyb,{{ rule }} # 边锋打大A
PROCESS-NAME,com.dobest.new2048,{{ rule }} # 2048数字方块
PROCESS-NAME,com.ea.simcitymobile.tx,{{ rule }} # 模拟城市：我是市长
PROCESS-NAME,com.emo.studio.magicparticle,{{ rule }} # 我的粒子世界
PROCESS-NAME,com.fengguo.wpjz.yingyongbao,{{ rule }} # 王牌机战
PROCESS-NAME,com.fengyun.qiqijww,{{ rule }} # 奇奇抓娃娃
PROCESS-NAME,com.fingersoft.hcr2.cn.tencent,{{ rule }} # 登山赛车2
PROCESS-NAME,com.fingersoft.hillclimb,{{ rule }} # 登山赛车
PROCESS-NAME,com.fingertip.saolei,{{ rule }} # 扫雷世界
PROCESS-NAME,com.fourddz.yyb,{{ rule }} # 边锋四人斗地主精简版
PROCESS-NAME,com.gamebox.king,{{ rule }} # 帝王·三国
PROCESS-NAME,com.gdczu.memory,{{ rule }} # C族记忆宫殿
PROCESS-NAME,com.girl.chesstwo,{{ rule }} # 经典象棋单机版
PROCESS-NAME,com.golaxy.mobile,{{ rule }} # 星阵围棋
PROCESS-NAME,com.guandan.yybtest,{{ rule }} # 掼蛋
PROCESS-NAME,com.happyelements.AndroidAnimal.qq,{{ rule }} # 开心消消乐
PROCESS-NAME,com.happyelements.AndroidClover.www,{{ rule }} # 海滨消消乐
PROCESS-NAME,com.hottagames.yh.laohu,{{ rule }} # 异环
PROCESS-NAME,com.htwoplayers.srjjc,{{ rule }} # 双人竞技场
PROCESS-NAME,com.huabang.golf,{{ rule }} # 小白球
PROCESS-NAME,com.hypergryph.arknights,{{ rule }} # 明日方舟
PROCESS-NAME,com.hypergryph.endfield,{{ rule }} # 明日方舟：终末地
PROCESS-NAME,com.hytc.hxsg2,{{ rule }} # 汉风幻想三国OL
PROCESS-NAME,com.hzdx.fkzdx,{{ rule }} # 疯狂找东西
PROCESS-NAME,com.imangi.templerun2,{{ rule }} # 神庙逃亡2
PROCESS-NAME,com.indeed.golinks,{{ rule }} # 弈客围棋
PROCESS-NAME,com.jichuang.iq.client,{{ rule }} # 33IQ
PROCESS-NAME,com.jiumijoy.simuniversity,{{ rule }} # 我的大学
PROCESS-NAME,com.joym.armorbear.yyb,{{ rule }} # 熊出没之机甲熊大
PROCESS-NAME,com.joym.bearfarm.yingyongbao,{{ rule }} # 熊出没之熊大农场
PROCESS-NAME,com.joym.legendhero.yyb,{{ rule }} # 奥特曼传奇英雄
PROCESS-NAME,com.joym.xiongdakuaipao.yyb,{{ rule }} # 熊出没之熊大快跑
PROCESS-NAME,com.jucai.happygo,{{ rule }} # 一起学围棋
PROCESS-NAME,com.kid58.lianyong.agriculturalvehicle,{{ rule }} # 奇妙小镇农场
PROCESS-NAME,com.kidcastle.kidapp.plus,{{ rule }} # 奇趣 Plus
PROCESS-NAME,com.kiloo.subwaysurf,{{ rule }} # 地铁跑酷
PROCESS-NAME,com.KingOfTank.tkqx,{{ rule }} # 坦克前线
PROCESS-NAME,com.kuniu.mota,{{ rule }} # 魔塔
PROCESS-NAME,com.kurogame.mingchao,{{ rule }} # 鸣潮
PROCESS-NAME,com.leiting.jmzy,{{ rule }} # 九牧之野
PROCESS-NAME,com.leiting.wjcs.android,{{ rule }} # 问剑长生
PROCESS-NAME,com.leiting.zjcs,{{ rule }} # 杖剑传说
PROCESS-NAME,com.liaoyanxuan.jeweldropdom,{{ rule }} # 方块宝石滑消消
PROCESS-NAME,com.liaoyanxuan.sudoku,{{ rule }} # 数独玩家
PROCESS-NAME,com.lilith.palmon.android.cn,{{ rule }} # 帕萌战斗日记
PROCESS-NAME,com.lilithgame.igame.android.cn,{{ rule }} # 剑与远征：启程
PROCESS-NAME,com.lilithgame.wgame.android.cn,{{ rule }} # 战火勋章
PROCESS-NAME,com.lilithgames.rok.offical.cn,{{ rule }} # 万国觉醒
PROCESS-NAME,com.lilithgames.samo.android.cn,{{ rule }} # 万龙觉醒
PROCESS-NAME,com.lilithgames.solarland.android.cn,{{ rule }} # 远光84
PROCESS-NAME,com.lilithgames.xgame.android.cn,{{ rule }} # 众神派对
PROCESS-NAME,com.longtu.oao,{{ rule }} # 海龟汤
PROCESS-NAME,com.magene.onelapMatch,{{ rule }} # 顽鹿竞技-国内首个3D虚拟骑行运动平台
PROCESS-NAME,com.magicflute.renjuworld,{{ rule }} # 五林五子棋
PROCESS-NAME,com.martian.taochuhaidaochuan.tx,{{ rule }} # 密室逃脱绝境系列2海盗船
PROCESS-NAME,com.mfp.jelly.yingyongbao,{{ rule }} # 宾果消消消
PROCESS-NAME,com.miHoYo.hkrpg,{{ rule }} # 崩坏：星穹铁道
PROCESS-NAME,com.miHoYo.HSoDv22144.tencent,{{ rule }} # 崩坏学园2
PROCESS-NAME,com.miHoYo.Nap,{{ rule }} # 绝区零
PROCESS-NAME,com.mindblocks.blocks.tencent,{{ rule }} # 被尘封的故事
PROCESS-NAME,com.mizhongtech.qief,{{ rule }} # 儿童益智切水果
PROCESS-NAME,com.molehole.zaiwanyiguan.yyb,{{ rule }} # 再玩亿关
PROCESS-NAME,com.mszmapp.detective,{{ rule }} # 百变大侦探
PROCESS-NAME,com.n1studio.empress,{{ rule }} # 盛世天下-女帝篇
PROCESS-NAME,com.netease.dhxy,{{ rule }} # 大话西游
PROCESS-NAME,com.netease.lrs,{{ rule }} # 狼人杀
PROCESS-NAME,com.no.color.cn,{{ rule }} # 草莓涂涂
PROCESS-NAME,com.ntsqsoft.junqivip,{{ rule }} # 元游军棋
PROCESS-NAME,com.og.danjiddz,{{ rule }} # 单机斗地主（开心版）
PROCESS-NAME,com.ourgame.mahjong.danji,{{ rule }} # 单机麻将-开心版
PROCESS-NAME,com.outfit7.mytalkingtomfree,{{ rule }} # 我的汤姆猫
PROCESS-NAME,com.papegames.infinitynikki,{{ rule }} # 无限暖暖
PROCESS-NAME,com.papegames.lysk.cn,{{ rule }} # 恋与深空
PROCESS-NAME,com.pdragon.HD1010,{{ rule }} # 方块合合乐
PROCESS-NAME,com.pdragon.junqi,{{ rule }} # 军棋
PROCESS-NAME,com.pi.czrxdfirst,{{ rule }} # 超自然行动组
PROCESS-NAME,com.poem.qaguess,{{ rule }} # 诗词猜猜猜
PROCESS-NAME,com.qileyx.ddz.yyb,{{ rule }} # 欢喜斗地主
PROCESS-NAME,com.qqgame.happymj,{{ rule }} # 欢乐麻将
PROCESS-NAME,com.qqgame.hlddz,{{ rule }} # 欢乐斗地主
PROCESS-NAME,com.qqgame.mic,{{ rule }} # 英雄杀
PROCESS-NAME,com.ryqj.gdt01,{{ rule }} # 英雄大对决
PROCESS-NAME,com.sdbean.werewolf,{{ rule }} # 天天狼人
PROCESS-NAME,com.shengji.yyb,{{ rule }} # 升级80分
PROCESS-NAME,com.shoukai,{{ rule }} # 手开
PROCESS-NAME,com.sincetimes.fknsg,{{ rule }} # 放开那三国
PROCESS-NAME,com.sincetimes.games.worldship,{{ rule }} # 战舰帝国
PROCESS-NAME,com.sinyee.babybus.adventure,{{ rule }} # 奇妙逻辑启蒙
PROCESS-NAME,com.sinyee.babybus.bumpercars,{{ rule }} # 奇妙碰碰车
PROCESS-NAME,com.sinyee.babybus.cake,{{ rule }} # 奇妙蛋糕店
PROCESS-NAME,com.sinyee.babybus.careII,{{ rule }} # 照顾甜心妹妹
PROCESS-NAME,com.sinyee.babybus.chef,{{ rule }} # 宝宝小厨房
PROCESS-NAME,com.sinyee.babybus.coffee,{{ rule }} # 奇妙咖啡餐厅
PROCESS-NAME,com.sinyee.babybus.cultivation,{{ rule }} # 宝宝小牧场
PROCESS-NAME,com.sinyee.babybus.delicacy,{{ rule }} # 奇妙世界美食
PROCESS-NAME,com.sinyee.babybus.diner,{{ rule }} # 宝宝早餐车
PROCESS-NAME,com.sinyee.babybus.dinosaurIII,{{ rule }} # 奇妙恐龙科普
PROCESS-NAME,com.sinyee.babybus.factory,{{ rule }} # 宝宝冰淇淋工厂
PROCESS-NAME,com.sinyee.babybus.findCha,{{ rule }} # 宝宝来找茬
PROCESS-NAME,com.sinyee.babybus.foodstreetII,{{ rule }} # 奇妙美味日记
PROCESS-NAME,com.sinyee.babybus.grove,{{ rule }} # 宝宝森林美食
PROCESS-NAME,com.sinyee.babybus.icecream,{{ rule }} # 雪糕工厂
PROCESS-NAME,com.sinyee.babybus.kitchen,{{ rule }} # 宝宝神奇厨房
PROCESS-NAME,com.sinyee.babybus.manor,{{ rule }} # 宝宝庄园
PROCESS-NAME,com.sinyee.babybus.princess,{{ rule }} # 奇妙的专注力
PROCESS-NAME,com.sinyee.babybus.restaurant,{{ rule }} # 奇妙料理餐厅
PROCESS-NAME,com.sinyee.babybus.snacks,{{ rule }} # 宝宝手工零食
PROCESS-NAME,com.sinyee.babybus.soda,{{ rule }} # 宝宝果汁商店
PROCESS-NAME,com.sinyee.babybus.splice,{{ rule }} # 奇妙拼图世界
PROCESS-NAME,com.tencent.af,{{ rule }} # 王牌战士
PROCESS-NAME,com.tencent.cookie,{{ rule }} # 冲呀！饼干人：王国
PROCESS-NAME,com.tencent.cqsj,{{ rule }} # 传奇世界
PROCESS-NAME,com.tencent.czn,{{ rule }} # 卡厄思梦境
PROCESS-NAME,com.tencent.dhm1,{{ rule }} # 群星纪元
PROCESS-NAME,com.tencent.dm,{{ rule }} # 数码宝贝：新世纪
PROCESS-NAME,com.tencent.dragoncn,{{ rule }} # 龙息：神寂
PROCESS-NAME,com.tencent.egame,{{ rule }} # 英雄联盟电竞经理
PROCESS-NAME,com.tencent.feiji,{{ rule }} # 全民飞机大战
PROCESS-NAME,com.tencent.fifa4m,{{ rule }} # 足球在线4移动版
PROCESS-NAME,com.tencent.fifamobile,{{ rule }} # FC足球世界
PROCESS-NAME,com.tencent.fiftyone.yc,{{ rule }} # 桃源深处有人家
PROCESS-NAME,com.tencent.game.rhythmmaster,{{ rule }} # 节奏大师
PROCESS-NAME,com.tencent.game.VXDGame,{{ rule }} # 天天炫斗-经典重燃
PROCESS-NAME,com.tencent.gate,{{ rule }} # 白荆回廊——古剑奇谭
PROCESS-NAME,com.tencent.gnyx.ttd,{{ rule }} # 碳碳岛
PROCESS-NAME,com.tencent.guandansy,{{ rule }} # 大掼蛋（腾讯）
PROCESS-NAME,com.tencent.gwgo,{{ rule }} # 一起来捉妖
PROCESS-NAME,com.tencent.hhw,{{ rule }} # 航海王：壮志雄心
PROCESS-NAME,com.tencent.hxgame,{{ rule }} # 华夏
PROCESS-NAME,com.tencent.hyrzol,{{ rule }} # 火影忍者：忍者新世代
PROCESS-NAME,com.tencent.jkchess,{{ rule }} # 金铲铲之战
PROCESS-NAME,com.tencent.JWX,{{ rule }} # 傲世西游
PROCESS-NAME,com.tencent.KiHan,{{ rule }} # 火影忍者
PROCESS-NAME,com.tencent.lastblade,{{ rule }} # 末刀
PROCESS-NAME,com.tencent.letsgo,{{ rule }} # 元梦之星-探灵实录
PROCESS-NAME,com.tencent.lolm,{{ rule }} # 英雄联盟手游
PROCESS-NAME,com.tencent.lszz,{{ rule }} # 龙石战争
PROCESS-NAME,com.tencent.lzhx,{{ rule }} # 龙族幻想
PROCESS-NAME,com.tencent.mergemansion,{{ rule }} # 庄园合合
PROCESS-NAME,com.tencent.mf.uam,{{ rule }} # 暗区突围-军港风暴返场
PROCESS-NAME,com.tencent.msgame,{{ rule }} # 合金弹头：觉醒
PROCESS-NAME,com.tencent.Mtown,{{ rule }} # 全民小镇
PROCESS-NAME,com.tencent.nba2kx,{{ rule }} # 美职篮全明星
PROCESS-NAME,com.tencent.nfsonline,{{ rule }} # 极品飞车：集结
PROCESS-NAME,com.tencent.ngr,{{ rule }} # 王者荣耀世界
PROCESS-NAME,com.tencent.nikke,{{ rule }} # 胜利女神：新的希望
PROCESS-NAME,com.tencent.nrc,{{ rule }} # 洛克王国：世界
PROCESS-NAME,com.tencent.pao,{{ rule }} # 天天酷跑
PROCESS-NAME,com.tencent.peng,{{ rule }} # 天天爱消除
PROCESS-NAME,com.tencent.pocket,{{ rule }} # 腾讯桌球
PROCESS-NAME,com.tencent.pokemonunite.cn,{{ rule }} # 宝可梦大集结
PROCESS-NAME,com.tencent.pqsn,{{ rule }} # 排球少年：新的征程
PROCESS-NAME,com.tencent.Q108,{{ rule }} # 全民水浒
PROCESS-NAME,com.tencent.Qfarm,{{ rule }} # 全民农场
PROCESS-NAME,com.tencent.qmxjx,{{ rule }} # 全明星觉醒
PROCESS-NAME,com.tencent.qqfarm,{{ rule }} # QQ农场
PROCESS-NAME,com.tencent.qqgame.qqhlupwvga,{{ rule }} # 欢乐升级
PROCESS-NAME,com.tencent.qqgame.xq,{{ rule }} # 天天象棋
PROCESS-NAME,com.tencent.ro,{{ rule }} # 仙境传说：爱如初见
PROCESS-NAME,com.tencent.ryxsg,{{ rule }} # 荣耀新三国
PROCESS-NAME,com.tencent.sgzywl,{{ rule }} # 三国志异闻录
PROCESS-NAME,com.tencent.shootgame,{{ rule }} # 魂斗罗：归来
PROCESS-NAME,com.tencent.sqsd,{{ rule }} # 石器时代：觉醒
PROCESS-NAME,com.tencent.supernba2024,{{ rule }} # 热血美职篮-每周送球星
PROCESS-NAME,com.tencent.tig,{{ rule }} # 隐形守护者
PROCESS-NAME,com.tencent.tmaoe,{{ rule }} # 重返帝国
PROCESS-NAME,com.tencent.tmgp.aceracer,{{ rule }} # 王牌竞速
PROCESS-NAME,com.tencent.tmgp.afshqz,{{ rule }} # 水浒Q传手游
PROCESS-NAME,com.tencent.tmgp.ahlhsyjy,{{ rule }} # 神域纪元
PROCESS-NAME,com.tencent.tmgp.ahsqdhzq,{{ rule }} # 足球大人物
PROCESS-NAME,com.tencent.tmgp.ahsqdldllhsj,{{ rule }} # 斗罗大陆：猎魂世界
PROCESS-NAME,com.tencent.tmgp.ahsqdszc,{{ rule }} # 斗兽战场
PROCESS-NAME,com.tencent.tmgp.aligames.kybc,{{ rule }} # 狂野飙车9：竞速传奇
PROCESS-NAME,com.tencent.tmgp.aligames.sgzhxdl,{{ rule }} # 三国志幻想大陆
PROCESS-NAME,com.tencent.tmgp.android.ANMP.GloftDLCN,{{ rule }} # 萌龙大乱斗
PROCESS-NAME,com.tencent.tmgp.angellegion,{{ rule }} # 女神星球
PROCESS-NAME,com.tencent.tmgp.aoshilongcheng,{{ rule }} # 傲世龙城
PROCESS-NAME,com.tencent.tmgp.aotu,{{ rule }} # 凹凸世界
PROCESS-NAME,com.tencent.tmgp.aresvirus2,{{ rule }} # 阿瑞斯病毒2
PROCESS-NAME,com.tencent.tmgp.arrowio,{{ rule }} # 弓箭手大作战
PROCESS-NAME,com.tencent.tmgp.astx.chenjue,{{ rule }} # 傲视天下
PROCESS-NAME,com.tencent.tmgp.atm2,{{ rule }} # 奥特曼系列：对决
PROCESS-NAME,com.tencent.tmgp.atmlegend2,{{ rule }} # 奥特曼传奇英雄2
PROCESS-NAME,com.tencent.tmgp.awlzw,{{ rule }} # 阿瓦隆之王
PROCESS-NAME,com.tencent.tmgp.bairimeng.dmmdzz,{{ rule }} # 逃跑吧！少年
PROCESS-NAME,com.tencent.tmgp.bairimeng.snake,{{ rule }} # 蛇蛇争霸
PROCESS-NAME,com.tencent.tmgp.baitian.alx,{{ rule }} # 奥拉星
PROCESS-NAME,com.tencent.tmgp.baitian.aobi.czs,{{ rule }} # 奥比岛：梦想国度
PROCESS-NAME,com.tencent.tmgp.baitian.aqcs.aqcssy,{{ rule }} # 奥奇传说
PROCESS-NAME,com.tencent.tmgp.baitian.color,{{ rule }} # 乱涂彩世界
PROCESS-NAME,com.tencent.tmgp.basecity.game.hjd,{{ rule }} # 黄金岛在线游戏软件
PROCESS-NAME,com.tencent.tmgp.bbqstudio.bbq2,{{ rule }} # 野蛮人大作战2
PROCESS-NAME,com.tencent.tmgp.bd1117,{{ rule }} # 九界问仙
PROCESS-NAME,com.tencent.tmgp.bdxj,{{ rule }} # 捕盗行纪
PROCESS-NAME,com.tencent.tmgp.bekko.yld,{{ rule }} # 我有一座育龙岛
PROCESS-NAME,com.tencent.tmgp.bgame,{{ rule }} # 热血街篮
PROCESS-NAME,com.tencent.tmgp.bh3,{{ rule }} # 崩坏3
PROCESS-NAME,com.tencent.tmgp.bilibili.asharms,{{ rule }} # 灰烬战线
PROCESS-NAME,com.tencent.tmgp.bilibili.bangdream,{{ rule }} # 梦想协奏曲！少女乐团派对！
PROCESS-NAME,com.tencent.tmgp.bilibili.blhx,{{ rule }} # 碧蓝航线
PROCESS-NAME,com.tencent.tmgp.bilibili.deadcells.mobile,{{ rule }} # 重生细胞
PROCESS-NAME,com.tencent.tmgp.bilibili.excalibur,{{ rule }} # 依露希尔：星晓
PROCESS-NAME,com.tencent.tmgp.bilibili.mfgy,{{ rule }} # 魔法工艺
PROCESS-NAME,com.tencent.tmgp.bilibili.nslg,{{ rule }} # 三国：谋定天下
PROCESS-NAME,com.tencent.tmgp.bilibili.priconne,{{ rule }} # 公主连结
PROCESS-NAME,com.tencent.tmgp.bilibili.snake,{{ rule }} # 坎特伯雷公主与骑士唤醒冠军之剑的奇幻冒险
PROCESS-NAME,com.tencent.tmgp.bilibili.umamusu,{{ rule }} # 闪耀！优俊少女
PROCESS-NAME,com.tencent.tmgp.bilibili.warmsnow,{{ rule }} # 暖雪
PROCESS-NAME,com.tencent.tmgp.bkddz,{{ rule }} # 波克斗地主
PROCESS-NAME,com.tencent.tmgp.blackclove,{{ rule }} # 黑色四叶草 魔法帝之道
PROCESS-NAME,com.tencent.tmgp.blhdx,{{ rule }} # 北凉悍刀行
PROCESS-NAME,com.tencent.tmgp.blr3,{{ rule }} # 不良人3
PROCESS-NAME,com.tencent.tmgp.blrpj.hnhy,{{ rule }} # 不良人：破局
PROCESS-NAME,com.tencent.tmgp.bqsd,{{ rule }} # 冰汽时代：最后的家园
PROCESS-NAME,com.tencent.tmgp.brdz67,{{ rule }} # 兵人大战
PROCESS-NAME,com.tencent.tmgp.breezegirl,{{ rule }} # 神行少女
PROCESS-NAME,com.tencent.tmgp.budapp,{{ rule }} # 碧优蒂的世界
PROCESS-NAME,com.tencent.tmgp.cahxxc,{{ rule }} # 长安幻想
PROCESS-NAME,com.tencent.tmgp.caohua.dgqzywm,{{ rule }} # 帝国：权杖与文明
PROCESS-NAME,com.tencent.tmgp.carrot2,{{ rule }} # 保卫萝卜2
PROCESS-NAME,com.tencent.tmgp.carrot3dj,{{ rule }} # 保卫萝卜3
PROCESS-NAME,com.tencent.tmgp.catstudio.nekostory,{{ rule }} # 萌猫物语
PROCESS-NAME,com.tencent.tmgp.cdfml,{{ rule }} # 伏魔录
PROCESS-NAME,com.tencent.tmgp.cf,{{ rule }} # 穿越火线-枪战王者
PROCESS-NAME,com.tencent.tmgp.cfwzzs,{{ rule }} # 王者之师
PROCESS-NAME,com.tencent.tmgp.cfxf,{{ rule }} # 超凡先锋
PROCESS-NAME,com.tencent.tmgp.chaowu10003,{{ rule }} # 大武道
PROCESS-NAME,com.tencent.tmgp.chcyyb,{{ rule }} # 彩虹橙
PROCESS-NAME,com.tencent.tmgp.chengzhu.zcydtz,{{ rule }} # 这城有良田
PROCESS-NAME,com.tencent.tmgp.chudustar.gdmj2,{{ rule }} # 星辰广东麻将
PROCESS-NAME,com.tencent.tmgp.chudustar.herbmj,{{ rule }} # 星辰哈尔滨麻将
PROCESS-NAME,com.tencent.tmgp.chudustar.kwxmj,{{ rule }} # 星辰卡五星
PROCESS-NAME,com.tencent.tmgp.chudustar.sxmj,{{ rule }} # 星辰陕西麻将
PROCESS-NAME,com.tencent.tmgp.cig.themonsterchef,{{ rule }} # 黑暗料理王
PROCESS-NAME,com.tencent.tmgp.cjhwy,{{ rule }} # 超进化物语
PROCESS-NAME,com.tencent.tmgp.cjjd,{{ rule }} # 超级舰队
PROCESS-NAME,com.tencent.tmgp.cjqyz.kkk5,{{ rule }} # 超级群英传
PROCESS-NAME,com.tencent.tmgp.clgame.cs2,{{ rule }} # 火线出击
PROCESS-NAME,com.tencent.tmgp.cly.fkzz,{{ rule }} # 疯狂征战
PROCESS-NAME,com.tencent.tmgp.cly.txyx,{{ rule }} # 天选英雄
PROCESS-NAME,com.tencent.tmgp.cmcm.zmjjkillshotbravo,{{ rule }} # 狙神荣耀
PROCESS-NAME,com.tencent.tmgp.cmge.dldllove,{{ rule }} # 斗罗大陆：逆转时空
PROCESS-NAME,com.tencent.tmgp.cmge.gathering,{{ rule }} # 斗罗大陆：史莱克学院
PROCESS-NAME,com.tencent.tmgp.cmge.ssjd,{{ rule }} # 境界-死神激斗
PROCESS-NAME,com.tencent.tmgp.cmge.xxjhjwq,{{ rule }} # 新仙剑奇侠传之挥剑问情
PROCESS-NAME,com.tencent.tmgp.cmge.zsgwsb,{{ rule }} # 真•三国无双 霸
PROCESS-NAME,com.tencent.tmgp.cn.jj.chess2,{{ rule }} # JJ象棋
PROCESS-NAME,com.tencent.tmgp.cn.jj.log,{{ rule }} # 曙光英雄
PROCESS-NAME,com.tencent.tmgp.cn.phoenix,{{ rule }} # 龙魂旅人
PROCESS-NAME,com.tencent.tmgp.cn.ro,{{ rule }} # 仙境传说：新启航
PROCESS-NAME,com.tencent.tmgp.co.zjhy,{{ rule }} # 创世战车
PROCESS-NAME,com.tencent.tmgp.cod,{{ rule }} # 使命召唤手游
PROCESS-NAME,com.tencent.tmgp.codev,{{ rule }} # 无畏契约：源能行动
PROCESS-NAME,com.tencent.tmgp.cokqq,{{ rule }} # 列王的纷争
PROCESS-NAME,com.tencent.tmgp.cokutau.jls,{{ rule }} # 将灵说
PROCESS-NAME,com.tencent.tmgp.com.chorusworldwide.theroomone,{{ rule }} # 未上锁的房间
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.bn.cn,{{ rule }} # 明日边境
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.jsfb.cn,{{ rule }} # 僵尸风暴
PROCESS-NAME,com.tencent.tmgp.com.feelingtouch.zfsniper.cn,{{ rule }} # 僵尸前线3D
PROCESS-NAME,com.tencent.tmgp.com.hanjiasongshu.jianghux2,{{ rule }} # 汉家江湖
PROCESS-NAME,com.tencent.tmgp.com.outfit7.talkingtomgoldrun,{{ rule }} # 汤姆猫跑酷
PROCESS-NAME,com.tencent.tmgp.com.sdgs.yyb,{{ rule }} # 商道高手
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.bog2,{{ rule }} # 古魂
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.jsqq.alsp,{{ rule }} # 爱琳诗篇
PROCESS-NAME,com.tencent.tmgp.com.tencent.tmgp.yunbu.pool3,{{ rule }} # 台球风云游戏软件 V1.0.0
PROCESS-NAME,com.tencent.tmgp.combatman,{{ rule }} # 奥特曼之格斗超人
PROCESS-NAME,com.tencent.tmgp.coslegend,{{ rule }} # 英魂之刃
PROCESS-NAME,com.tencent.tmgp.cqytj,{{ rule }} # 从前有条街
PROCESS-NAME,com.tencent.tmgp.cqzy.shengmiao,{{ rule }} # 传奇之业
PROCESS-NAME,com.tencent.tmgp.croak,{{ rule }} # 旅行青蛙·中国之旅
PROCESS-NAME,com.tencent.tmgp.crossgate.ks,{{ rule }} # 魔力宝贝：旅人
PROCESS-NAME,com.tencent.tmgp.crownddz,{{ rule }} # 皇冠斗地主
PROCESS-NAME,com.tencent.tmgp.crownworld.dianfengddz,{{ rule }} # 巅峰斗地主
PROCESS-NAME,com.tencent.tmgp.ctycj,{{ rule }} # 餐厅养成记
PROCESS-NAME,com.tencent.tmgp.cx.pzys,{{ rule }} # 破阵勇士
PROCESS-NAME,com.tencent.tmgp.cxswz,{{ rule }} # 潮汐守望者
PROCESS-NAME,com.tencent.tmgp.cyddztwo,{{ rule }} # 禅游斗地主
PROCESS-NAME,com.tencent.tmgp.cykj.kdzz,{{ rule }} # 口袋战争
PROCESS-NAME,com.tencent.tmgp.daluandou,{{ rule }} # 奇葩战斗家
PROCESS-NAME,com.tencent.tmgp.dancingline,{{ rule }} # 跳舞的线
PROCESS-NAME,com.tencent.tmgp.daqing,{{ rule }} # 我在大清当皇帝
PROCESS-NAME,com.tencent.tmgp.darkestcastle,{{ rule }} # 黑暗城堡
PROCESS-NAME,com.tencent.tmgp.dartouPoker,{{ rule }} # 开心十三张
PROCESS-NAME,com.tencent.tmgp.DDD2,{{ rule }} # 弹弹岛2
PROCESS-NAME,com.tencent.tmgp.ddianle.lovedance,{{ rule }} # 恋舞OL
PROCESS-NAME,com.tencent.tmgp.ddtank,{{ rule }} # 弹弹堂
PROCESS-NAME,com.tencent.tmgp.ddxt,{{ rule }} # 大道仙途
PROCESS-NAME,com.tencent.tmgp.ddzbsdj,{{ rule }} # 斗地主比赛
PROCESS-NAME,com.tencent.tmgp.dfjs,{{ rule }} # 巅峰极速
PROCESS-NAME,com.tencent.tmgp.dfm,{{ rule }} # 三角洲行动
PROCESS-NAME,com.tencent.tmgp.dftkzjzg,{{ rule }} # 巅峰坦克
PROCESS-NAME,com.tencent.tmgp.dfzj,{{ rule }} # 巅峰战舰
PROCESS-NAME,com.tencent.tmgp.dhad,{{ rule }} # 放置奇兵
PROCESS-NAME,com.tencent.tmgp.djddzhlbtwo,{{ rule }} # 单机斗地主（欢乐版）
PROCESS-NAME,com.tencent.tmgp.djsy,{{ rule }} # 妄想山海
PROCESS-NAME,com.tencent.tmgp.dldl.qidian,{{ rule }} # 新斗罗大陆
PROCESS-NAME,com.tencent.tmgp.dldlhsdjsy,{{ rule }} # 斗罗大陆：魂师对决
PROCESS-NAME,com.tencent.tmgp.dldlwyly,{{ rule }} # 斗罗大陆
PROCESS-NAME,com.tencent.tmgp.dnf,{{ rule }} # 地下城与勇士：起源
PROCESS-NAME,com.tencent.tmgp.dodjoy.hlwdzz,{{ rule }} # 葫芦娃大作战
PROCESS-NAME,com.tencent.tmgp.doupokap,{{ rule }} # 斗破苍穹-少年崛起
PROCESS-NAME,com.tencent.tmgp.douposnzy,{{ rule }} # 斗破苍穹：三年之约
PROCESS-NAME,com.tencent.tmgp.douyurxjhgl,{{ rule }} # 热血江湖：归来
PROCESS-NAME,com.tencent.tmgp.dpcq,{{ rule }} # 斗破苍穹：异火重燃
PROCESS-NAME,com.tencent.tmgp.dpdj,{{ rule }} # 斗破苍穹：巅峰对决
PROCESS-NAME,com.tencent.tmgp.dqdgxxhd,{{ rule }} # 大秦帝国之帝国烽烟
PROCESS-NAME,com.tencent.tmgp.dragonball,{{ rule }} # 龙珠激斗
PROCESS-NAME,com.tencent.tmgp.dreamfarm,{{ rule }} # 梦想农场
PROCESS-NAME,com.tencent.tmgp.dssgame.jianzhong,{{ rule }} # 剑中
PROCESS-NAME,com.tencent.tmgp.dtszj,{{ rule }} # 永恒纪元
PROCESS-NAME,com.tencent.tmgp.dtszjkhd,{{ rule }} # 精灵盛典：黎明
PROCESS-NAME,com.tencent.tmgp.duige.hzw,{{ rule }} # 花之舞
PROCESS-NAME,com.tencent.tmgp.dungeon22,{{ rule }} # 地下城堡2：黑暗觉醒
PROCESS-NAME,com.tencent.tmgp.dungeon4,{{ rule }} # 地下城堡4：骑士与破碎编年史
PROCESS-NAME,com.tencent.tmgp.duole.chinachesshd,{{ rule }} # 多乐中国象棋
PROCESS-NAME,com.tencent.tmgp.duole.duolemjhd,{{ rule }} # 多乐麻将
PROCESS-NAME,com.tencent.tmgp.duoshuai,{{ rule }} # 夺帅
PROCESS-NAME,com.tencent.tmgp.dustglobal.jianghu,{{ rule }} # 这就是江湖
PROCESS-NAME,com.tencent.tmgp.dwct,{{ rule }} # 动物餐厅
PROCESS-NAME,com.tencent.tmgp.dwelst,{{ rule }} # 我的休闲时光
PROCESS-NAME,com.tencent.tmgp.dwrg,{{ rule }} # 第五人格
PROCESS-NAME,com.tencent.tmgp.dxphzhj,{{ rule }} # 跑胡子（字牌）合集
PROCESS-NAME,com.tencent.tmgp.dyqlb,{{ rule }} # 道友请留步
PROCESS-NAME,com.tencent.tmgp.dzxyzq,{{ rule }} # 队长小翼：最强十一人
PROCESS-NAME,com.tencent.tmgp.eden,{{ rule }} # 世界启元
PROCESS-NAME,com.tencent.tmgp.ef3,{{ rule }} # 现代空战3D
PROCESS-NAME,com.tencent.tmgp.ef5,{{ rule }} # 空战争锋
PROCESS-NAME,com.tencent.tmgp.eight.ball.live,{{ rule }} # 超凡台球
PROCESS-NAME,com.tencent.tmgp.elex.ctw,{{ rule }} # 列王的纷争：西部大陆
PROCESS-NAME,com.tencent.tmgp.enjoymisgzj,{{ rule }} # 三国战纪：风云再起
PROCESS-NAME,com.tencent.tmgp.es2boy,{{ rule }} # 偶像梦幻祭2
PROCESS-NAME,com.tencent.tmgp.evol,{{ rule }} # 恋与制作人
PROCESS-NAME,com.tencent.tmgp.ew5s,{{ rule }} # 欧陆战争5：帝国
PROCESS-NAME,com.tencent.tmgp.eyou.eygy,{{ rule }} # 光·遇
PROCESS-NAME,com.tencent.tmgp.eyou.tiyu,{{ rule }} # 天谕
PROCESS-NAME,com.tencent.tmgp.eyou.yjsh,{{ rule }} # 遇见逆水寒
PROCESS-NAME,com.tencent.tmgp.eyou.yqyn,{{ rule }} # 一起优诺
PROCESS-NAME,com.tencent.tmgp.fdd.yzcs,{{ rule }} # 远征传说
PROCESS-NAME,com.tencent.tmgp.fengbaotts,{{ rule }} # 风暴天堂
PROCESS-NAME,com.tencent.tmgp.fengchi.ldjx,{{ rule }} # 雷电：觉醒
PROCESS-NAME,com.tencent.tmgp.ffom,{{ rule }} # 自由幻想
PROCESS-NAME,com.tencent.tmgp.fgo,{{ rule }} # 命运-冠位指定
PROCESS-NAME,com.tencent.tmgp.fhmj,{{ rule }} # 富豪麻将
PROCESS-NAME,com.tencent.tmgp.fjdz2,{{ rule }} # 飞机大战之全民雷电
PROCESS-NAME,com.tencent.tmgp.fknsg2,{{ rule }} # 放开那三国2
PROCESS-NAME,com.tencent.tmgp.fknyg,{{ rule }} # 放开那妖怪
PROCESS-NAME,com.tencent.tmgp.fksss.hardtime,{{ rule }} # 疯狂神射手
PROCESS-NAME,com.tencent.tmgp.fmgame,{{ rule }} # 最终幻想14：水晶世界
PROCESS-NAME,com.tencent.tmgp.forgame.mmxd,{{ rule }} # 美美小店
PROCESS-NAME,com.tencent.tmgp.freeking,{{ rule }} # 空当接龙
PROCESS-NAME,com.tencent.tmgp.frxxzrjp,{{ rule }} # 凡人修仙传：人界篇
PROCESS-NAME,com.tencent.tmgp.fssd123,{{ rule }} # 繁盛时代
PROCESS-NAME,com.tencent.tmgp.fszn2.huiyue,{{ rule }} # 封神之怒
PROCESS-NAME,com.tencent.tmgp.ftf,{{ rule }} # 战就战
PROCESS-NAME,com.tencent.tmgp.funntcp,{{ rule }} # 欢乐南通长牌
PROCESS-NAME,com.tencent.tmgp.fxbp,{{ rule }} # 放学别跑
PROCESS-NAME,com.tencent.tmgp.fxyx.mzc,{{ rule }} # 猫之城
PROCESS-NAME,com.tencent.tmgp.fxyx.qnzl,{{ rule }} # 千年之旅
PROCESS-NAME,com.tencent.tmgp.fzdl,{{ rule }} # 风之大陆
PROCESS-NAME,com.tencent.tmgp.fzgd.ssfh,{{ rule }} # 盛世芳华
PROCESS-NAME,com.tencent.tmgp.fzyzh.yzx,{{ rule }} # 放置与召唤
PROCESS-NAME,com.tencent.tmgp.g12000128,{{ rule }} # 航海王-启航
PROCESS-NAME,com.tencent.tmgp.g13001230,{{ rule }} # 敢达决战
PROCESS-NAME,com.tencent.tmgp.g13002010,{{ rule }} # 灌篮高手 正版授权手游
PROCESS-NAME,com.tencent.tmgp.g15002011,{{ rule }} # 圣斗士星矢：重生2
PROCESS-NAME,com.tencent.tmgp.g67,{{ rule }} # 暗黑破坏神：不朽
PROCESS-NAME,com.tencent.tmgp.galasports.basketball,{{ rule }} # 美职篮篮球大师
PROCESS-NAME,com.tencent.tmgp.galasports.championsfc,{{ rule }} # 最佳11人
PROCESS-NAME,com.tencent.tmgp.galasports.operablebasketball,{{ rule }} # 美职篮巅峰对决
PROCESS-NAME,com.tencent.tmgp.galasports.totalfootball,{{ rule }} # 最佳球会
PROCESS-NAME,com.tencent.tmgp.game.xiaoyaojiugexing,{{ rule }} # 逍遥九歌行
PROCESS-NAME,com.tencent.tmgp.game.zjjy.cmzq,{{ rule }} # 超迷足球
PROCESS-NAME,com.tencent.tmgp.gamecomb.dxc,{{ rule }} # 超简单的地下城
PROCESS-NAME,com.tencent.tmgp.gbits.atm,{{ rule }} # 问道
PROCESS-NAME,com.tencent.tmgp.gcsgzh5,{{ rule }} # 攻城三国志
PROCESS-NAME,com.tencent.tmgp.gg.lostword,{{ rule }} # 东方归言录
PROCESS-NAME,com.tencent.tmgp.glzp,{{ rule }} # 桂林字牌手机版
PROCESS-NAME,com.tencent.tmgp.gm.hs,{{ rule }} # 魂色
PROCESS-NAME,com.tencent.tmgp.gmhsqs,{{ rule }} # 黑石启示
PROCESS-NAME,com.tencent.tmgp.gnyx,{{ rule }} # 高能英雄
PROCESS-NAME,com.tencent.tmgp.gs.hlgd,{{ rule }} # 幻灵格斗
PROCESS-NAME,com.tencent.tmgp.guaji,{{ rule }} # 传世挂机
PROCESS-NAME,com.tencent.tmgp.gumballs2,{{ rule }} # 不思议迷宫
PROCESS-NAME,com.tencent.tmgp.gundambattle,{{ rule }} # 敢达 争锋对决
PROCESS-NAME,com.tencent.tmgp.gw,{{ rule }} # 口袋进化
PROCESS-NAME,com.tencent.tmgp.gzhgsgwdsh,{{ rule }} # 三国：问鼎山河
PROCESS-NAME,com.tencent.tmgp.gzjw.pxdsg,{{ rule }} # 破晓的曙光
PROCESS-NAME,com.tencent.tmgp.gzlcddxe,{{ rule }} # 大店小二
PROCESS-NAME,com.tencent.tmgp.gzlcscssst,{{ rule }} # 生存33天
PROCESS-NAME,com.tencent.tmgp.gzqhzjxsc,{{ rule }} # 指尖像素城
PROCESS-NAME,com.tencent.tmgp.habby.archeroii,{{ rule }} # 弓箭传说2
PROCESS-NAME,com.tencent.tmgp.habby.cnarchero.qq,{{ rule }} # 弓箭传说
PROCESS-NAME,com.tencent.tmgp.habby.danke,{{ rule }} # 弹壳特攻队
PROCESS-NAME,com.tencent.tmgp.harrypotter,{{ rule }} # 哈利波特：魔法觉醒
PROCESS-NAME,com.tencent.tmgp.hchess,{{ rule }} # 全民象棋
PROCESS-NAME,com.tencent.tmgp.hcr2,{{ rule }} # 火柴人联盟2
PROCESS-NAME,com.tencent.tmgp.hcr3.qcjs,{{ rule }} # 火柴人联盟3
PROCESS-NAME,com.tencent.tmgp.hdczjh2,{{ rule }} # 皇帝成长计划2
PROCESS-NAME,com.tencent.tmgp.hdyxnbhx,{{ rule }} # 全民养成之女皇陛下
PROCESS-NAME,com.tencent.tmgp.hermes.blade,{{ rule }} # 境·界 刀鸣
PROCESS-NAME,com.tencent.tmgp.hero.lszt,{{ rule }} # 绿色征途
PROCESS-NAME,com.tencent.tmgp.hhw,{{ rule }} # 航海王强者之路
PROCESS-NAME,com.tencent.tmgp.hhwrxhx,{{ rule }} # 航海王热血航线
PROCESS-NAME,com.tencent.tmgp.hhxy,{{ rule }} # 洪荒仙韵
PROCESS-NAME,com.tencent.tmgp.hhymjj,{{ rule }} # 花花与幕间剧
PROCESS-NAME,com.tencent.tmgp.hhz,{{ rule }} # 神雕侠侣2
PROCESS-NAME,com.tencent.tmgp.hi4fun.ldsg,{{ rule }} # 零度曙光
PROCESS-NAME,com.tencent.tmgp.hi4fun.txcs,{{ rule }} # 天墟传说
PROCESS-NAME,com.tencent.tmgp.hjczjh,{{ rule }} # 豪杰成长计划
PROCESS-NAME,com.tencent.tmgp.hjol,{{ rule }} # 红警OL
PROCESS-NAME,com.tencent.tmgp.hlsgs,{{ rule }} # 欢乐三国杀
PROCESS-NAME,com.tencent.tmgp.hmrj,{{ rule }} # 绘梦日记
PROCESS-NAME,com.tencent.tmgp.hmzqfy,{{ rule }} # 豪门足球风云
PROCESS-NAME,com.tencent.tmgp.hntx.gransaga,{{ rule }} # 剑与骑士团
PROCESS-NAME,com.tencent.tmgp.hnty.tfjy,{{ rule }} # 塔防纪元
PROCESS-NAME,com.tencent.tmgp.hnyj.jxlmt,{{ rule }} # 见习猎魔团
PROCESS-NAME,com.tencent.tmgp.hnyy.xn,{{ rule }} # 仙逆H5
PROCESS-NAME,com.tencent.tmgp.holidayandroid,{{ rule }} # 假日乐消消
PROCESS-NAME,com.tencent.tmgp.home.hxqq,{{ rule }} # 华夏千秋
PROCESS-NAME,com.tencent.tmgp.hometownbuilder,{{ rule }} # 兔小萌世界
PROCESS-NAME,com.tencent.tmgp.hongguaiwan,{{ rule }} # 随便玩红拐弯
PROCESS-NAME,com.tencent.tmgp.hotta,{{ rule }} # 幻塔
PROCESS-NAME,com.tencent.tmgp.hqxy,{{ rule }} # 魂器学院
PROCESS-NAME,com.tencent.tmgp.hsahc,{{ rule }} # 幻兽爱合成
PROCESS-NAME,com.tencent.tmgp.hse,{{ rule }} # 饥饿鲨：进化
PROCESS-NAME,com.tencent.tmgp.hsw,{{ rule }} # 饥饿鲨：世界
PROCESS-NAME,com.tencent.tmgp.ht1117,{{ rule }} # 名扬天下
PROCESS-NAME,com.tencent.tmgp.htgl,{{ rule }} # 鸿图归来
PROCESS-NAME,com.tencent.tmgp.htsk,{{ rule }} # 千变双扣
PROCESS-NAME,com.tencent.tmgp.huahusy,{{ rule }} # 画狐
PROCESS-NAME,com.tencent.tmgp.hungrydragon,{{ rule }} # 饥饿龙
PROCESS-NAME,com.tencent.tmgp.huopinsk,{{ rule }} # 火拼双扣
PROCESS-NAME,com.tencent.tmgp.huoyu.spidersolitaireclassic,{{ rule }} # 经典蜘蛛纸牌
PROCESS-NAME,com.tencent.tmgp.hxjysy,{{ rule }} # 火线精英
PROCESS-NAME,com.tencent.tmgp.hxmjl,{{ rule }} # 幻想名将录
PROCESS-NAME,com.tencent.tmgp.hy.hbmnq,{{ rule }} # 滑板模拟器
PROCESS-NAME,com.tencent.tmgp.hy.hcrdj,{{ rule }} # 火柴人对决
PROCESS-NAME,com.tencent.tmgp.hymc,{{ rule }} # 荒野迷城
PROCESS-NAME,com.tencent.tmgp.hyrj,{{ rule }} # 荒野日记
PROCESS-NAME,com.tencent.tmgp.hyrjgd,{{ rule }} # 荒野日记：孤岛
PROCESS-NAME,com.tencent.tmgp.hyxcbgl,{{ rule }} # 星辰变：归来
PROCESS-NAME,com.tencent.tmgp.hztf,{{ rule }} # 守塔不能停
PROCESS-NAME,com.tencent.tmgp.idol2,{{ rule }} # 绝对演绎
PROCESS-NAME,com.tencent.tmgp.ifsanguo,{{ rule }} # 极无双
PROCESS-NAME,com.tencent.tmgp.jbycbmnq,{{ rule }} # 吃模拟器
PROCESS-NAME,com.tencent.tmgp.jbyhbzc,{{ rule }} # 滑板之城
PROCESS-NAME,com.tencent.tmgp.jbyhcrdz,{{ rule }} # 火柴人大战3
PROCESS-NAME,com.tencent.tmgp.jhyywx,{{ rule }} # 江湖悠悠
PROCESS-NAME,com.tencent.tmgp.jjxm,{{ rule }} # 新仙魔九界
PROCESS-NAME,com.tencent.tmgp.jjzd,{{ rule }} # 机甲战队
PROCESS-NAME,com.tencent.tmgp.jltx,{{ rule }} # 逐鹿三国之君临天下
PROCESS-NAME,com.tencent.tmgp.jnbg2,{{ rule }} # 纪念碑谷2
PROCESS-NAME,com.tencent.tmgp.jpzmg,{{ rule }} # 极品芝麻官
PROCESS-NAME,com.tencent.tmgp.jsxwsy,{{ rule }} # 绝世仙王
PROCESS-NAME,com.tencent.tmgp.jszc,{{ rule }} # 巨兽战场
PROCESS-NAME,com.tencent.tmgp.jumpw,{{ rule }} # 300大作战
PROCESS-NAME,com.tencent.tmgp.junhai.shjhxl,{{ rule }} # 山海经幻想录
PROCESS-NAME,com.tencent.tmgp.jwdzg,{{ rule }} # 叫我大掌柜
PROCESS-NAME,com.tencent.tmgp.jx3m,{{ rule }} # 剑网3指尖江湖
PROCESS-NAME,com.tencent.tmgp.jxpd.feimo,{{ rule }} # 吉星派对
PROCESS-NAME,com.tencent.tmgp.jxqy,{{ rule }} # 新剑侠情缘
PROCESS-NAME,com.tencent.tmgp.kaayou.daye,{{ rule }} # 大冶打拱
PROCESS-NAME,com.tencent.tmgp.kaayou.ezhou,{{ rule }} # 鄂州五十K
PROCESS-NAME,com.tencent.tmgp.kaayou.qichun,{{ rule }} # 蕲春打拱
PROCESS-NAME,com.tencent.tmgp.kaopu.jzpaj,{{ rule }} # 决战！平安京
PROCESS-NAME,com.tencent.tmgp.kaopu.zdjs,{{ rule }} # 朕的江山
PROCESS-NAME,com.tencent.tmgp.kddouluo,{{ rule }} # 口袋斗罗大陆
PROCESS-NAME,com.tencent.tmgp.kgame.catssoup,{{ rule }} # 猫咪和汤
PROCESS-NAME,com.tencent.tmgp.kjfzd,{{ rule }} # 开间服装店
PROCESS-NAME,com.tencent.tmgp.klbqm,{{ rule }} # 卡拉彼丘
PROCESS-NAME,com.tencent.tmgp.kn.zdfz,{{ rule }} # 战斗法则
PROCESS-NAME,com.tencent.tmgp.kof97,{{ rule }} # 拳皇97OL
PROCESS-NAME,com.tencent.tmgp.kof98,{{ rule }} # 拳皇98终极之战OL
PROCESS-NAME,com.tencent.tmgp.kuangbaochuanqi,{{ rule }} # 狂暴传奇
PROCESS-NAME,com.tencent.tmgp.kurogame.haru,{{ rule }} # 战双帕弥什
PROCESS-NAME,com.tencent.tmgp.kuroko,{{ rule }} # 黑子的篮球：街头对决
PROCESS-NAME,com.tencent.tmgp.kxtf,{{ rule }} # 开心塔防
PROCESS-NAME,com.tencent.tmgp.kyruanjian.gwlmlg,{{ rule }} # 怪物联萌
PROCESS-NAME,com.tencent.tmgp.kzysqh,{{ rule }} # 空之要塞：启航
PROCESS-NAME,com.tencent.tmgp.l10,{{ rule }} # 倩女幽魂
PROCESS-NAME,com.tencent.tmgp.lanjing.yanyu,{{ rule }} # 烟雨江湖
PROCESS-NAME,com.tencent.tmgp.ledou.mhhy,{{ rule }} # 梦幻花园
PROCESS-NAME,com.tencent.tmgp.ledou.mhjy,{{ rule }} # 梦幻家园
PROCESS-NAME,com.tencent.tmgp.leiting.chaojinhua,{{ rule }} # 超进化物语2
PROCESS-NAME,com.tencent.tmgp.leiting.dragonraider,{{ rule }} # 飞吧龙骑士
PROCESS-NAME,com.tencent.tmgp.leiting.dungeon3,{{ rule }} # 地下城堡3：魂之诗
PROCESS-NAME,com.tencent.tmgp.leiyan.mdjl,{{ rule }} # 锚点降临
PROCESS-NAME,com.tencent.tmgp.leshu.snakeonline,{{ rule }} # 贪吃蛇在线
PROCESS-NAME,com.tencent.tmgp.leting.picatown,{{ rule }} # 皮卡堂之梦想起源
PROCESS-NAME,com.tencent.tmgp.lfcs,{{ rule }} # 猎风传说
PROCESS-NAME,com.tencent.tmgp.liehuoyidao.shengmiao,{{ rule }} # 烈火一刀
PROCESS-NAME,com.tencent.tmgp.lilithgame.sgame,{{ rule }} # 剑与家园
PROCESS-NAME,com.tencent.tmgp.lilithgames.afk,{{ rule }} # 剑与远征
PROCESS-NAME,com.tencent.tmgp.limboworks.honorofcup,{{ rule }} # 足球大师黄金一代
PROCESS-NAME,com.tencent.tmgp.lingxigames.sh2xzg,{{ rule }} # 三国志幻想大陆2：枭之歌
PROCESS-NAME,com.tencent.tmgp.locojoy,{{ rule }} # 我叫MT
PROCESS-NAME,com.tencent.tmgp.lostinblue,{{ rule }} # 迷失蔚蓝
PROCESS-NAME,com.tencent.tmgp.ltgame.atmcard,{{ rule }} # 奥特曼王者传奇
PROCESS-NAME,com.tencent.tmgp.ltxfd.yyb,{{ rule }} # 雷霆小分队
PROCESS-NAME,com.tencent.tmgp.ltzs.tuantuan,{{ rule }} # 雷霆战神
PROCESS-NAME,com.tencent.tmgp.luobo4,{{ rule }} # 保卫萝卜4
PROCESS-NAME,com.tencent.tmgp.luoliye,{{ rule }} # 叶罗丽
PROCESS-NAME,com.tencent.tmgp.lv,{{ rule }} # 光与夜之恋
PROCESS-NAME,com.tencent.tmgp.LWSY,{{ rule }} # 龙武
PROCESS-NAME,com.tencent.tmgp.lwyqqsqz,{{ rule }} # 元气骑士前传
PROCESS-NAME,com.tencent.tmgp.lxdqy,{{ rule }} # 卢希达：起源
PROCESS-NAME,com.tencent.tmgp.lxwz,{{ rule }} # 篮下王者
PROCESS-NAME,com.tencent.tmgp.lyjleniu,{{ rule }} # 灵妖劫
PROCESS-NAME,com.tencent.tmgp.lyjzchqsy,{{ rule }} # 传奇岁月
PROCESS-NAME,com.tencent.tmgp.lyjzljtx,{{ rule }} # 灵决天下
PROCESS-NAME,com.tencent.tmgp.lywlfrcs,{{ rule }} # 凡人传说
PROCESS-NAME,com.tencent.tmgp.lzjxmb,{{ rule }} # 龙之觉醒
PROCESS-NAME,com.tencent.tmgp.m3gsy,{{ rule }} # 梦三国
PROCESS-NAME,com.tencent.tmgp.madhero,{{ rule }} # 暴走英雄坛游戏软件V1.0
PROCESS-NAME,com.tencent.tmgp.majiangall,{{ rule }} # 全番单机麻将
PROCESS-NAME,com.tencent.tmgp.manggo.xwdsh,{{ rule }} # 向往的生活
PROCESS-NAME,com.tencent.tmgp.maobu.gdzz2unity,{{ rule }} # 最后的勇者
PROCESS-NAME,com.tencent.tmgp.maplem,{{ rule }} # 冒险岛：枫之传说
PROCESS-NAME,com.tencent.tmgp.matrix,{{ rule }} # 盲盒派对
PROCESS-NAME,com.tencent.tmgp.mds,{{ rule }} # 真三国快打
PROCESS-NAME,com.tencent.tmgp.mduel,{{ rule }} # 漫威对决
PROCESS-NAME,com.tencent.tmgp.mecharashi,{{ rule }} # 钢岚
PROCESS-NAME,com.tencent.tmgp.meet,{{ rule }} # 遇见
PROCESS-NAME,com.tencent.tmgp.meng,{{ rule }} # 梦王国与沉睡的100王子
PROCESS-NAME,com.tencent.tmgp.mgddz,{{ rule }} # 芒果斗地主
PROCESS-NAME,com.tencent.tmgp.mhlz,{{ rule }} # 蛮荒领主
PROCESS-NAME,com.tencent.tmgp.mhmfw,{{ rule }} # 梦幻魔法屋
PROCESS-NAME,com.tencent.tmgp.mhmnz,{{ rule }} # 梦幻模拟战
PROCESS-NAME,com.tencent.tmgp.mhtgame.wxr,{{ rule }} # 走开外星人
PROCESS-NAME,com.tencent.tmgp.mhxy.sqsy,{{ rule }} # 梦幻西游
PROCESS-NAME,com.tencent.tmgp.mhzxsy,{{ rule }} # 梦幻诛仙
PROCESS-NAME,com.tencent.tmgp.migu.mgxlzl,{{ rule }} # 驯龙之旅
PROCESS-NAME,com.tencent.tmgp.minitech.miniworld,{{ rule }} # 迷你世界
PROCESS-NAME,com.tencent.tmgp.miniworldroyale,{{ rule }} # 迷你枪战精英
PROCESS-NAME,com.tencent.tmgp.mjwy,{{ rule }} # 魔镜物语
PROCESS-NAME,com.tencent.tmgp.mkcncn.hwyad,{{ rule }} # 暴吵萌厨
PROCESS-NAME,com.tencent.tmgp.MMHD,{{ rule }} # 魔法门之英雄无敌：王朝
PROCESS-NAME,com.tencent.tmgp.mmsrmlhd,{{ rule }} # 萌萌四人斗地主
PROCESS-NAME,com.tencent.tmgp.modernship2,{{ rule }} # 现代海战
PROCESS-NAME,com.tencent.tmgp.molenew,{{ rule }} # 摩尔庄园
PROCESS-NAME,com.tencent.tmgp.moto,{{ rule }} # 黎明飞驰
PROCESS-NAME,com.tencent.tmgp.mozhigu,{{ rule }} # 魔之谷游戏软件V1.0
PROCESS-NAME,com.tencent.tmgp.mqwgctx,{{ rule }} # 攻城天下
PROCESS-NAME,com.tencent.tmgp.mqwsgzz,{{ rule }} # 三国战争
PROCESS-NAME,com.tencent.tmgp.ms,{{ rule }} # 漫威终极逆转
PROCESS-NAME,com.tencent.tmgp.ms.yxgz,{{ rule }} # 英雄攻战
PROCESS-NAME,com.tencent.tmgp.mt2r,{{ rule }} # 我叫MT2
PROCESS-NAME,com.tencent.tmgp.mt4,{{ rule }} # 我叫MT4
PROCESS-NAME,com.tencent.tmgp.mtdl,{{ rule }} # 谜题大陆
PROCESS-NAME,com.tencent.tmgp.mtjkp,{{ rule }} # 魔天记游戏软件V1.0
PROCESS-NAME,com.tencent.tmgp.mtlbb,{{ rule }} # 天龙3D
PROCESS-NAME,com.tencent.tmgp.mw,{{ rule }} # 现代战舰
PROCESS-NAME,com.tencent.tmgp.mwr,{{ rule }} # 小小军团
PROCESS-NAME,com.tencent.tmgp.mxdlmdyz,{{ rule }} # 冒险岛：联盟的意志
PROCESS-NAME,com.tencent.tmgp.mxxfd,{{ rule }} # 冒险小分队
PROCESS-NAME,com.tencent.tmgp.my.yyb,{{ rule }} # 魔域口袋版
PROCESS-NAME,com.tencent.tmgp.my.zqwz,{{ rule }} # 最强武装
PROCESS-NAME,com.tencent.tmgp.myhero,{{ rule }} # 我的勇者
PROCESS-NAME,com.tencent.tmgp.myshzg,{{ rule }} # 云上城之歌
PROCESS-NAME,com.tencent.tmgp.mytalkingtom2,{{ rule }} # 我的汤姆猫2
PROCESS-NAME,com.tencent.tmgp.nanchangmajiang,{{ rule }} # 随便玩南昌麻将
PROCESS-NAME,com.tencent.tmgp.nanningmj,{{ rule }} # 南宁麻将
PROCESS-NAME,com.tencent.tmgp.NBA,{{ rule }} # 最强美职篮
PROCESS-NAME,com.tencent.tmgp.Nekootan.kfkj.yhlm,{{ rule }} # 开放空间
PROCESS-NAME,com.tencent.tmgp.netcraftyouyi,{{ rule }} # 奶块
PROCESS-NAME,com.tencent.tmgp.ninefun.ark,{{ rule }} # 仙国志
PROCESS-NAME,com.tencent.tmgp.nn4,{{ rule }} # 闪耀暖暖
PROCESS-NAME,com.tencent.tmgp.nomoga.fsandroid,{{ rule }} # 封神幻想世界
PROCESS-NAME,com.tencent.tmgp.nshm,{{ rule }} # 逆水寒
PROCESS-NAME,com.tencent.tmgp.nsn592.bubblefish,{{ rule }} # 萌鱼泡泡
PROCESS-NAME,com.tencent.tmgp.nysgs2,{{ rule }} # 怒焰三国杀
PROCESS-NAME,com.tencent.tmgp.nz,{{ rule }} # 逆战：未来
PROCESS-NAME,com.tencent.tmgp.oasis.jlcq,{{ rule }} # 君临传奇
PROCESS-NAME,com.tencent.tmgp.oasis.ynjg,{{ rule }} # 一念剑歌
PROCESS-NAME,com.tencent.tmgp.oceantradekings,{{ rule }} # 航海霸业
PROCESS-NAME,com.tencent.tmgp.onektower.mhcs,{{ rule }} # 梦幻传说
PROCESS-NAME,com.tencent.tmgp.p16s,{{ rule }} # 银河战舰
PROCESS-NAME,com.tencent.tmgp.p31,{{ rule }} # 朕的江山2
PROCESS-NAME,com.tencent.tmgp.p5x,{{ rule }} # 女神异闻录：夜幕魅影
PROCESS-NAME,com.tencent.tmgp.p6cncn.hwyad,{{ rule }} # 浮生忆玲珑
PROCESS-NAME,com.tencent.tmgp.p7mj,{{ rule }} # 开运麻将
PROCESS-NAME,com.tencent.tmgp.PalaceM2cncn,{{ rule }} # 熹妃传
PROCESS-NAME,com.tencent.tmgp.pandadastudio.ninja3,{{ rule }} # 忍者必须死3
PROCESS-NAME,com.tencent.tmgp.paoyao33,{{ rule }} # 刨幺
PROCESS-NAME,com.tencent.tmgp.party,{{ rule }} # 蛋仔派对
PROCESS-NAME,com.tencent.tmgp.pdkhj,{{ rule }} # 跑得快合集
PROCESS-NAME,com.tencent.tmgp.pisces,{{ rule }} # 桃花源记
PROCESS-NAME,com.tencent.tmgp.pkwan.op,{{ rule }} # 航海王：燃烧意志
PROCESS-NAME,com.tencent.tmgp.plantsvszombies3.mengxing,{{ rule }} # 植物大战僵尸3
PROCESS-NAME,com.tencent.tmgp.playcrab.kos,{{ rule }} # 一拳超人：最强之男
PROCESS-NAME,com.tencent.tmgp.playrix.township.chukong,{{ rule }} # 梦想城镇
PROCESS-NAME,com.tencent.tmgp.pocketworld,{{ rule }} # 我爱拼模型
PROCESS-NAME,com.tencent.tmgp.pook.foodgame,{{ rule }} # 爆炒江湖
PROCESS-NAME,com.tencent.tmgp.projectsnow,{{ rule }} # 尘白禁区
PROCESS-NAME,com.tencent.tmgp.projectt,{{ rule }} # 天龙八部2：飞龙战天
PROCESS-NAME,com.tencent.tmgp.pubgmhd,{{ rule }} # 和平精英
PROCESS-NAME,com.tencent.tmgp.pvz2hdtxyyb,{{ rule }} # 植物大战僵尸2
PROCESS-NAME,com.tencent.tmgp.pygame.zipai,{{ rule }} # 同城字牌
PROCESS-NAME,com.tencent.tmgp.qblykilltext,{{ rule }} # 谁是卧底移动版
PROCESS-NAME,com.tencent.tmgp.qiannianxx,{{ rule }} # 千年寻仙
PROCESS-NAME,com.tencent.tmgp.qilong.warship,{{ rule }} # 战舰冲突
PROCESS-NAME,com.tencent.tmgp.qinsmoon,{{ rule }} # 秦时明月卡牌版
PROCESS-NAME,com.tencent.tmgp.qita,{{ rule }} # 七塔
PROCESS-NAME,com.tencent.tmgp.qiwanhh,{{ rule }} # 航海纷争
PROCESS-NAME,com.tencent.tmgp.qjnn,{{ rule }} # 奇迹暖暖
PROCESS-NAME,com.tencent.tmgp.qjsjqy,{{ rule }} # 奇迹世界：起源
PROCESS-NAME,com.tencent.tmgp.qlbt.cly,{{ rule }} # 器灵宝塔
PROCESS-NAME,com.tencent.tmgp.qmqz2022,{{ rule }} # 全民枪战2
PROCESS-NAME,com.tencent.tmgp.qqx5,{{ rule }} # QQ炫舞
PROCESS-NAME,com.tencent.tmgp.qqyx,{{ rule }} # 球球英雄
PROCESS-NAME,com.tencent.tmgp.qrsj,{{ rule }} # 七日世界
PROCESS-NAME,com.tencent.tmgp.qsroom1,{{ rule }} # 密室逃脱求生系列1极地冒险
PROCESS-NAME,com.tencent.tmgp.qszc,{{ rule }} # 求生之城
PROCESS-NAME,com.tencent.tmgp.qtdl3d,{{ rule }} # 抢滩登陆3D
PROCESS-NAME,com.tencent.tmgp.qxxy.cookingcity,{{ rule }} # 小镇大厨
PROCESS-NAME,com.tencent.tmgp.qyfhl,{{ rule }} # 群英风华录
PROCESS-NAME,com.tencent.tmgp.qygames.mddqz,{{ rule }} # 梦的第七章
PROCESS-NAME,com.tencent.tmgp.qyj,{{ rule }} # 青云诀
PROCESS-NAME,com.tencent.tmgp.qznbp.jy,{{ rule }} # 酋长你别跑
PROCESS-NAME,com.tencent.tmgp.qzxy,{{ rule }} # 葫芦兄弟：七子降妖
PROCESS-NAME,com.tencent.tmgp.reagamezg2,{{ rule }} # 战国
PROCESS-NAME,com.tencent.tmgp.reflash,{{ rule }} # 镭明闪击
PROCESS-NAME,com.tencent.tmgp.rk.wjhj,{{ rule }} # 无尽花界
PROCESS-NAME,com.tencent.tmgp.road7.ddtdmxandroid,{{ rule }} # 弹弹堂大冒险
PROCESS-NAME,com.tencent.tmgp.road7.sqh5,{{ rule }} # 神曲H5
PROCESS-NAME,com.tencent.tmgp.rollingsky,{{ rule }} # 滚动的天空
PROCESS-NAME,com.tencent.tmgp.rome,{{ rule }} # 帝国军团罗马
PROCESS-NAME,com.tencent.tmgp.room2,{{ rule }} # 密室逃脱古堡迷城2
PROCESS-NAME,com.tencent.tmgp.room4,{{ rule }} # 密室逃脱影城之谜4
PROCESS-NAME,com.tencent.tmgp.rshytycq,{{ rule }} # 天羽传奇
PROCESS-NAME,com.tencent.tmgp.rshyzncq,{{ rule }} # 真牛传奇
PROCESS-NAME,com.tencent.tmgp.rxcq,{{ rule }} # 热血传奇
PROCESS-NAME,com.tencent.tmgp.rxjhbj,{{ rule }} # 热血江湖手游
PROCESS-NAME,com.tencent.tmgp.rxr,{{ rule }} # 溯回青空
PROCESS-NAME,com.tencent.tmgp.rxsc.chenyou,{{ rule }} # 热血沙城
PROCESS-NAME,com.tencent.tmgp.rydajiuzhilu,{{ rule }} # 搭救之路
PROCESS-NAME,com.tencent.tmgp.rydts,{{ rule }} # 荣耀大天使
PROCESS-NAME,com.tencent.tmgp.s3.sgzzlb,{{ rule }} # 三国志·战略版
PROCESS-NAME,com.tencent.tmgp.samurai,{{ rule }} # 侍魂-胧月传说
PROCESS-NAME,com.tencent.tmgp.sanguobt,{{ rule }} # 《攻城掠地》手机游戏软件（移动）
PROCESS-NAME,com.tencent.tmgp.sanguosha.mjz,{{ rule }} # 三国杀名将传
PROCESS-NAME,com.tencent.tmgp.sanweiapp.bubble,{{ rule }} # 千关泡泡龙单机游戏
PROCESS-NAME,com.tencent.tmgp.sbcsmj,{{ rule }} # 随便玩长沙麻将
PROCESS-NAME,com.tencent.tmgp.sbphz,{{ rule }} # 随便跑胡子
PROCESS-NAME,com.tencent.tmgp.sbsdh,{{ rule }} # 三打哈
PROCESS-NAME,com.tencent.tmgp.sbwpdk,{{ rule }} # 随便跑得快
PROCESS-NAME,com.tencent.tmgp.sbwwaihuzi,{{ rule }} # 随便玩歪胡子
PROCESS-NAME,com.tencent.tmgp.sbzp,{{ rule }} # 随便字牌
PROCESS-NAME,com.tencent.tmgp.scmjxzddnew,{{ rule }} # 四川麻将（血战到底）
PROCESS-NAME,com.tencent.tmgp.scqmjhly,{{ rule }} # 全民江湖
PROCESS-NAME,com.tencent.tmgp.sds,{{ rule }} # 圣斗士星矢：重生
PROCESS-NAME,com.tencent.tmgp.sdxl,{{ rule }} # 神雕侠侣
PROCESS-NAME,com.tencent.tmgp.sdyxz,{{ rule }} # 射雕英雄传手游
PROCESS-NAME,com.tencent.tmgp.seal,{{ rule }} # 征途
PROCESS-NAME,com.tencent.tmgp.seasun.jxqy0,{{ rule }} # 剑侠情缘·零
PROCESS-NAME,com.tencent.tmgp.seasun.jxsj3,{{ rule }} # 剑侠世界3
PROCESS-NAME,com.tencent.tmgp.seasun.jxsjorg,{{ rule }} # 剑侠世界：起源
PROCESS-NAME,com.tencent.tmgp.seayoo.ggd,{{ rule }} # 鹅鸭杀
PROCESS-NAME,com.tencent.tmgp.seayoo.jxfs,{{ rule }} # 封神再临
PROCESS-NAME,com.tencent.tmgp.seayoo.zero,{{ rule }} # 不朽箴言
PROCESS-NAME,com.tencent.tmgp.secret,{{ rule }} # 黑猫奇闻社
PROCESS-NAME,com.tencent.tmgp.SeerInfiniteUniverse,{{ rule }} # 赛尔号星球大战
PROCESS-NAME,com.tencent.tmgp.sf3,{{ rule }} # 暗影格斗3
PROCESS-NAME,com.tencent.tmgp.sg3,{{ rule }} # 放开那三国3
PROCESS-NAME,com.tencent.tmgp.sgame,{{ rule }} # 王者荣耀
PROCESS-NAME,com.tencent.tmgp.sgfx,{{ rule }} # 曙光防线
PROCESS-NAME,com.tencent.tmgp.sgqyz,{{ rule }} # 三国群英传-霸王之业
PROCESS-NAME,com.tencent.tmgp.sgqyzhhby,{{ rule }} # 三国群英传：鸿鹄霸业
PROCESS-NAME,com.tencent.tmgp.sgs.x,{{ rule }} # 三国杀：一将成名
PROCESS-NAME,com.tencent.tmgp.sgspad.yyb,{{ rule }} # 三国杀OL互通版
PROCESS-NAME,com.tencent.tmgp.sgz2017,{{ rule }} # 三国志2017
PROCESS-NAME,com.tencent.tmgp.sgzj2,{{ rule }} # 欢动三国战纪2
PROCESS-NAME,com.tencent.tmgp.sgzzqb,{{ rule }} # 三国志·战棋版
PROCESS-NAME,com.tencent.tmgp.sh.cly,{{ rule }} # 山河
PROCESS-NAME,com.tencent.tmgp.shanggqg,{{ rule }} # 上古情歌
PROCESS-NAME,com.tencent.tmgp.shangguxiux,{{ rule }} # 上古修仙
PROCESS-NAME,com.tencent.tmgp.shddz17dp,{{ rule }} # 上海斗地主
PROCESS-NAME,com.tencent.tmgp.shdlln,{{ rule }} # 神火大陆
PROCESS-NAME,com.tencent.tmgp.shelter,{{ rule }} # 辐射：避难所Online
PROCESS-NAME,com.tencent.tmgp.shenghewzcq,{{ rule }} # 王者传奇
PROCESS-NAME,com.tencent.tmgp.shenghuawc1,{{ rule }} # 生化围城
PROCESS-NAME,com.tencent.tmgp.shoptitans,{{ rule }} # 传奇商店：经营与打造
PROCESS-NAME,com.tencent.tmgp.shyyl,{{ rule }} # 山海与妖灵
PROCESS-NAME,com.tencent.tmgp.shzshx.atm,{{ rule }} # 奥特曼：超时空英雄
PROCESS-NAME,com.tencent.tmgp.sichuan,{{ rule }} # 蜀山四川麻将
PROCESS-NAME,com.tencent.tmgp.sim,{{ rule }} # 珍珠海大冒险
PROCESS-NAME,com.tencent.tmgp.sjffcf,{{ rule }} # 飞飞：重逢
PROCESS-NAME,com.tencent.tmgp.sjsgfx,{{ rule }} # 神将三国
PROCESS-NAME,com.tencent.tmgp.skysgame.xyqy,{{ rule }} # 逍遥情缘
PROCESS-NAME,com.tencent.tmgp.slqjwjws,{{ rule }} # 武将无双
PROCESS-NAME,com.tencent.tmgp.sm,{{ rule }} # 创造与魔法
PROCESS-NAME,com.tencent.tmgp.sm2022zq,{{ rule }} # 梦幻足球世界
PROCESS-NAME,com.tencent.tmgp.smdl.qy,{{ rule }} # 神魔大陆
PROCESS-NAME,com.tencent.tmgp.sngxfhxy,{{ rule }} # 少年歌行：风花雪月
PROCESS-NAME,com.tencent.tmgp.sniper3dv2,{{ rule }} # 狙击行动：代号猎鹰
PROCESS-NAME,com.tencent.tmgp.snk.kofworld,{{ rule }} # 拳皇世界
PROCESS-NAME,com.tencent.tmgp.snsgz,{{ rule }} # 少年三国志
PROCESS-NAME,com.tencent.tmgp.snxjz,{{ rule }} # 少年仙界传
PROCESS-NAME,com.tencent.tmgp.sparrowkwx2dx.maijie,{{ rule }} # 楚天优游卡五星麻将
PROCESS-NAME,com.tencent.tmgp.speedmobile,{{ rule }} # QQ飞车
PROCESS-NAME,com.tencent.tmgp.sqcdjz,{{ rule }} # 三国群英传：策定九州
PROCESS-NAME,com.tencent.tmgp.ssjj.gbws,{{ rule }} # 果宝无双
PROCESS-NAME,com.tencent.tmgp.ssjj.zmws,{{ rule }} # 造梦无双
PROCESS-NAME,com.tencent.tmgp.sskgame,{{ rule }} # 圣斗士星矢-官方正版(腾讯)
PROCESS-NAME,com.tencent.tmgp.sszg,{{ rule }} # 闪烁之光
PROCESS-NAME,com.tencent.tmgp.stgsl,{{ rule }} # 神探诡事录
PROCESS-NAME,com.tencent.tmgp.studio27.MelonPlayground,{{ rule }} # 甜瓜沙盒
PROCESS-NAME,com.tencent.tmgp.styjz,{{ rule }} # 隋唐英杰传
PROCESS-NAME,com.tencent.tmgp.stzb,{{ rule }} # 率土之滨
PROCESS-NAME,com.tencent.tmgp.supercell.boombeach,{{ rule }} # 海岛奇兵
PROCESS-NAME,com.tencent.tmgp.supercell.brawlstars,{{ rule }} # 荒野乱斗
PROCESS-NAME,com.tencent.tmgp.supercell.clashofclans,{{ rule }} # 部落冲突
PROCESS-NAME,com.tencent.tmgp.supercell.clashroyale,{{ rule }} # 部落冲突：皇室战争
PROCESS-NAME,com.tencent.tmgp.supercell.hayday,{{ rule }} # 卡通农场
PROCESS-NAME,com.tencent.tmgp.survivedks,{{ rule }} # 活下去
PROCESS-NAME,com.tencent.tmgp.sxddc,{{ rule }} # 《神仙道》高清重制版
PROCESS-NAME,com.tencent.tmgp.sxdthree,{{ rule }} # 神仙道3
PROCESS-NAME,com.tencent.tmgp.sylj,{{ rule }} # 亮剑
PROCESS-NAME,com.tencent.tmgp.sylqsxy,{{ rule }} # 龙骑士学园
PROCESS-NAME,com.tencent.tmgp.sysgzhd,{{ rule }} # 时光杂货店
PROCESS-NAME,com.tencent.tmgp.szgd,{{ rule }} # 森之国度
PROCESS-NAME,com.tencent.tmgp.taiyouxi.tk2,{{ rule }} # 极无双2
PROCESS-NAME,com.tencent.tmgp.tbggalaxyreavers,{{ rule }} # 银河掠夺者
PROCESS-NAME,com.tencent.tmgp.TCrossSGJQ,{{ rule }} # 腾讯天天军棋
PROCESS-NAME,com.tencent.tmgp.tdj,{{ rule }} # 天地劫：幽城再临
PROCESS-NAME,com.tencent.tmgp.tew,{{ rule }} # 变形金刚：地球之战
PROCESS-NAME,com.tencent.tmgp.tfjl,{{ rule }} # 塔防精灵
PROCESS-NAME,com.tencent.tmgp.tfxyj,{{ rule }} # 塔防西游记
PROCESS-NAME,com.tencent.tmgp.tgsgsy,{{ rule }} # 铁杆三国
PROCESS-NAME,com.tencent.tmgp.tiancity.dom,{{ rule }} # 战争与文明
PROCESS-NAME,com.tencent.tmgp.tianmashikong.qj,{{ rule }} # 全民奇迹
PROCESS-NAME,com.tencent.tmgp.tinghood.TpsForMobile.yyb3,{{ rule }} # 台球世界
PROCESS-NAME,com.tencent.tmgp.tk2.x,{{ rule }} # 坦克争锋
PROCESS-NAME,com.tencent.tmgp.tkxs,{{ rule }} # 坦克雄师
PROCESS-NAME,com.tencent.tmgp.tlsy2.huiyue,{{ rule }} # 屠龙圣域
PROCESS-NAME,com.tencent.tmgp.tmsk.qj2,{{ rule }} # 奇迹：觉醒
PROCESS-NAME,com.tencent.tmgp.tmsk.qj3,{{ rule }} # 全民奇迹2
PROCESS-NAME,com.tencent.tmgp.tmst,{{ rule }} # 同盟神探
PROCESS-NAME,com.tencent.tmgp.tom,{{ rule }} # 猫和老鼠
PROCESS-NAME,com.tencent.tmgp.totnew,{{ rule }} # 旅人日记
PROCESS-NAME,com.tencent.tmgp.tqbaohuang,{{ rule }} # 大眼保皇
PROCESS-NAME,com.tencent.tmgp.tqguandan,{{ rule }} # 大眼掼蛋
PROCESS-NAME,com.tencent.tmgp.tqshuangkou,{{ rule }} # 大眼双扣
PROCESS-NAME,com.tencent.tmgp.tqwzfx,{{ rule }} # 台球王者
PROCESS-NAME,com.tencent.tmgp.trunknaruto,{{ rule }} # 火影忍者：木叶高手
PROCESS-NAME,com.tencent.tmgp.tsjyyz,{{ rule }} # 天使纪元
PROCESS-NAME,com.tencent.tmgp.tssy,{{ rule }} # 塔防三国志II
PROCESS-NAME,com.tencent.tmgp.tstl,{{ rule }} # 天龙八部手游
PROCESS-NAME,com.tencent.tmgp.tszr.shengmiao,{{ rule }} # 吞食之刃
PROCESS-NAME,com.tencent.tmgp.tszz,{{ rule }} # 天使之战
PROCESS-NAME,com.tencent.tmgp.ttcz,{{ rule }} # 六龙争霸
PROCESS-NAME,com.tencent.tmgp.tthy.dtl,{{ rule }} # 大屠龙
PROCESS-NAME,com.tencent.tmgp.ttigd2.android,{{ rule }} # 天天爱掼蛋
PROCESS-NAME,com.tencent.tmgp.ttmj,{{ rule }} # 麻将来了
PROCESS-NAME,com.tencent.tmgp.tttq,{{ rule }} # 天天台球
PROCESS-NAME,com.tencent.tmgp.ttwq,{{ rule }} # 腾讯围棋
PROCESS-NAME,com.tencent.tmgp.turnipboy,{{ rule }} # 大头菜菜历险记
PROCESS-NAME,com.tencent.tmgp.twrxhjly,{{ rule }} # 热血合击
PROCESS-NAME,com.tencent.tmgp.twyscq,{{ rule }} # 原始传奇
PROCESS-NAME,com.tencent.tmgp.twzzjhly,{{ rule }} # 自在江湖
PROCESS-NAME,com.tencent.tmgp.tx,{{ rule }} # 天下
PROCESS-NAME,com.tencent.tmgp.txgxxy2024,{{ rule }} # 三国：天下归心
PROCESS-NAME,com.tencent.tmgp.txsgsj,{{ rule }} # 三国世界
PROCESS-NAME,com.tencent.tmgp.tydoudizhu,{{ rule }} # 途游斗地主（比赛版）
PROCESS-NAME,com.tencent.tmgp.tzyxmznew,{{ rule }} # 梦幻新诛仙
PROCESS-NAME,com.tencent.tmgp.tzyz.meng,{{ rule }} # 无尽梦回
PROCESS-NAME,com.tencent.tmgp.tzyz.pao,{{ rule }} # 超时空跑跑
PROCESS-NAME,com.tencent.tmgp.tzyz.sgwsz,{{ rule }} # 三国望神州
PROCESS-NAME,com.tencent.tmgp.u1game.ptyj,{{ rule }} # 破天一剑
PROCESS-NAME,com.tencent.tmgp.ultralisk.gameapp.game37,{{ rule }} # 叶罗丽美颜公主
PROCESS-NAME,com.tencent.tmgp.ultraman,{{ rule }} # 奥特曼系列OL
PROCESS-NAME,com.tencent.tmgp.uniugame.xinw,{{ rule }} # 心舞
PROCESS-NAME,com.tencent.tmgp.universeatm,{{ rule }} # 奥特曼宇宙英雄
PROCESS-NAME,com.tencent.tmgp.uuapps.chinachess,{{ rule }} # 经典中国象棋
PROCESS-NAME,com.tencent.tmgp.uuapps.sichuan,{{ rule }} # 单机四川麻将
PROCESS-NAME,com.tencent.tmgp.uuappsmajiang,{{ rule }} # 经典单机麻将
PROCESS-NAME,com.tencent.tmgp.vlfcn,{{ rule }} # 绿茵信仰
PROCESS-NAME,com.tencent.tmgp.wali.jianxiashijie3D,{{ rule }} # 剑侠世界
PROCESS-NAME,com.tencent.tmgp.wansuiye,{{ rule }} # 叫我万岁爷
PROCESS-NAME,com.tencent.tmgp.wanyu.clqx,{{ rule }} # 苍蓝前线
PROCESS-NAME,com.tencent.tmgp.wdry.hegsbl,{{ rule }} # 我的荣耀
PROCESS-NAME,com.tencent.tmgp.wdsm,{{ rule }} # 我的使命
PROCESS-NAME,com.tencent.tmgp.wdyjrj,{{ rule }} # 我的御剑日记
PROCESS-NAME,com.tencent.tmgp.wec,{{ rule }} # 乱世王者
PROCESS-NAME,com.tencent.tmgp.weflycn,{{ rule }} # 发条总动员
PROCESS-NAME,com.tencent.tmgp.wegametk,{{ rule }} # 坦克无敌
PROCESS-NAME,com.tencent.tmgp.weile.doudizhu,{{ rule }} # 微乐斗地主移动版 V1.0.0
PROCESS-NAME,com.tencent.tmgp.weile.sichuanmj,{{ rule }} # 微乐四川麻将移动版
PROCESS-NAME,com.tencent.tmgp.WePop,{{ rule }} # 跑跑卡丁车官方竞速版
PROCESS-NAME,com.tencent.tmgp.wereviz.inlchina,{{ rule }} # 村落人生
PROCESS-NAME,com.tencent.tmgp.werewolfbattle,{{ rule }} # 狼人对决
PROCESS-NAME,com.tencent.tmgp.whrhx,{{ rule }} # 无悔华夏
PROCESS-NAME,com.tencent.tmgp.wjfz,{{ rule }} # 无尽纷争
PROCESS-NAME,com.tencent.tmgp.wjmtgl,{{ rule }} # 我叫MT：归来
PROCESS-NAME,com.tencent.tmgp.wjxt,{{ rule }} # 无极仙途
PROCESS-NAME,com.tencent.tmgp.wkzbeqw,{{ rule }} # 微壳二七王
PROCESS-NAME,com.tencent.tmgp.wmsjjdb,{{ rule }} # 完美世界：诸神之战
PROCESS-NAME,com.tencent.tmgp.wodn,{{ rule }} # 龙之谷世界
PROCESS-NAME,com.tencent.tmgp.woobest.mysq,{{ rule }} # 命运圣契
PROCESS-NAME,com.tencent.tmgp.wooduan.ssjj,{{ rule }} # 生死狙击
PROCESS-NAME,com.tencent.tmgp.wpzz,{{ rule }} # 王牌战争
PROCESS-NAME,com.tencent.tmgp.wsyxyyb,{{ rule }} # 顽石英雄
PROCESS-NAME,com.tencent.tmgp.wuxia,{{ rule }} # 天涯明月刀·世界
PROCESS-NAME,com.tencent.tmgp.wwguandanall,{{ rule }} # 一起玩掼蛋
PROCESS-NAME,com.tencent.tmgp.wxbz.lyjx,{{ rule }} # 烈焰觉醒
PROCESS-NAME,com.tencent.tmgp.wxbz.sjjx,{{ rule }} # 神迹觉醒
PROCESS-NAME,com.tencent.tmgp.wxmj,{{ rule }} # 无限梦境
PROCESS-NAME,com.tencent.tmgp.wzxx,{{ rule }} # 王者修仙
PROCESS-NAME,com.tencent.tmgp.xblr,{{ rule }} # 新不良人
PROCESS-NAME,com.tencent.tmgp.xbxxz,{{ rule }} # 想不想修真
PROCESS-NAME,com.tencent.tmgp.xcdphz,{{ rule }} # 跑胡子
PROCESS-NAME,com.tencent.tmgp.xdsw.Aoe,{{ rule }} # 指尖帝国
PROCESS-NAME,com.tencent.tmgp.xianjianshijie.cmge,{{ rule }} # 仙剑世界
PROCESS-NAME,com.tencent.tmgp.xianlinwy,{{ rule }} # 仙灵物语
PROCESS-NAME,com.tencent.tmgp.xiaoyss,{{ rule }} # 逍遥蜀山
PROCESS-NAME,com.tencent.tmgp.xinhuluwa,{{ rule }} # 葫芦娃
PROCESS-NAME,com.tencent.tmgp.xishanju.mysy,{{ rule }} # 魔域手游
PROCESS-NAME,com.tencent.tmgp.xjcspx,{{ rule }} # 仙境传说：破晓
PROCESS-NAME,com.tencent.tmgp.xjqxz,{{ rule }} # 仙剑奇侠传：新的开始
PROCESS-NAME,com.tencent.tmgp.xlwyln,{{ rule }} # 驯龙物语
PROCESS-NAME,com.tencent.tmgp.xmsl,{{ rule }} # 寻梦丝路
PROCESS-NAME,com.tencent.tmgp.xncp,{{ rule }} # 小南四川长牌
PROCESS-NAME,com.tencent.tmgp.xpdl,{{ rule }} # 西普大陆
PROCESS-NAME,com.tencent.tmgp.xsgzccz,{{ rule }} # 新三国志曹操传
PROCESS-NAME,com.tencent.tmgp.xsj.moyu2,{{ rule }} # 魔域手游2
PROCESS-NAME,com.tencent.tmgp.xsjyln,{{ rule }} # 星神纪元
PROCESS-NAME,com.tencent.tmgp.xtlbb,{{ rule }} # 新天龙八部
PROCESS-NAME,com.tencent.tmgp.xuanying,{{ rule }} # 玄影
PROCESS-NAME,com.tencent.tmgp.xuezunew,{{ rule }} # 血族
PROCESS-NAME,com.tencent.tmgp.xxajh,{{ rule }} # 新笑傲江湖
PROCESS-NAME,com.tencent.tmgp.xxcz,{{ rule }} # 小小村长
PROCESS-NAME,com.tencent.tmgp.xxsk.zqdw,{{ rule }} # 最强斗王
PROCESS-NAME,com.tencent.tmgp.xxsy,{{ rule }} # 寻仙
PROCESS-NAME,com.tencent.tmgp.xxtjd,{{ rule }} # 小小突击队
PROCESS-NAME,com.tencent.tmgp.xxyg,{{ rule }} # 小小蚁国
PROCESS-NAME,com.tencent.tmgp.xyhq,{{ rule }} # 爱玩信阳黑七
PROCESS-NAME,com.tencent.tmgp.xykp,{{ rule }} # 小鱼快跑
PROCESS-NAME,com.tencent.tmgp.xymobile,{{ rule }} # 轩辕传奇手游
PROCESS-NAME,com.tencent.tmgp.xynegyz,{{ rule }} # 西游女儿国
PROCESS-NAME,com.tencent.tmgp.ycf.herosland,{{ rule }} # 英勇之地
PROCESS-NAME,com.tencent.tmgp.ydcsly,{{ rule }} # 一刀传世
PROCESS-NAME,com.tencent.tmgp.ydgame.twzwtwo,{{ rule }} # 塔王之王2
PROCESS-NAME,com.tencent.tmgp.ydxh.cnchess,{{ rule }} # 象棋黄金版
PROCESS-NAME,com.tencent.tmgp.ydxh.gomoku,{{ rule }} # 五子棋大战
PROCESS-NAME,com.tencent.tmgp.ydxh.ludo,{{ rule }} # 飞行棋黄金版
PROCESS-NAME,com.tencent.tmgp.ydxh.nummerge,{{ rule }} # 数字大合成
PROCESS-NAME,com.tencent.tmgp.ydyaocuotu,{{ rule }} # 妖错图
PROCESS-NAME,com.tencent.tmgp.yhhoa,{{ rule }} # 英魂之刃战略版
PROCESS-NAME,com.tencent.tmgp.yhzxtwzw,{{ rule }} # 塔王之王
PROCESS-NAME,com.tencent.tmgp.yhzz.huiyue,{{ rule }} # 永恒征战
PROCESS-NAME,com.tencent.tmgp.yjqy,{{ rule }} # 御剑情缘
PROCESS-NAME,com.tencent.tmgp.ykdqddz,{{ rule }} # 真人天天斗地主
PROCESS-NAME,com.tencent.tmgp.ylm,{{ rule }} # 御龙在天手游
PROCESS-NAME,com.tencent.tmgp.yokaverse.zzxy,{{ rule }} # 自在西游
PROCESS-NAME,com.tencent.tmgp.yongyong.clx,{{ rule }} # 一梦江湖
PROCESS-NAME,com.tencent.tmgp.yongyong.mrzh,{{ rule }} # 明日之后
PROCESS-NAME,com.tencent.tmgp.yongyong.skwzjj,{{ rule }} # 实况:王者集结
PROCESS-NAME,com.tencent.tmgp.yongyong.skzq,{{ rule }} # 实况足球
PROCESS-NAME,com.tencent.tmgp.yongyong.tksjsjz,{{ rule }} # 坦克世界闪击战
PROCESS-NAME,com.tencent.tmgp.yongyong.zjsjsjz,{{ rule }} # 战舰世界闪击战
PROCESS-NAME,com.tencent.tmgp.yoozoo.jgame,{{ rule }} # 绯色回响
PROCESS-NAME,com.tencent.tmgp.yoozoo.sgyml,{{ rule }} # 三国云梦录
PROCESS-NAME,com.tencent.tmgp.youzu.slpk1,{{ rule }} # 少年西游记2
PROCESS-NAME,com.tencent.tmgp.youzu.snsgz2,{{ rule }} # 少年三国志2
PROCESS-NAME,com.tencent.tmgp.youzu.ss0,{{ rule }} # 少年三国志：零
PROCESS-NAME,com.tencent.tmgp.youzu.xdmbj,{{ rule }} # 新盗墓笔记
PROCESS-NAME,com.tencent.tmgp.yqklnw,{{ rule }} # 一千克拉女王
PROCESS-NAME,com.tencent.tmgp.yqqskp,{{ rule }} # 元气骑士
PROCESS-NAME,com.tencent.tmgp.yqw.xjsw,{{ rule }} # 小鸡守卫
PROCESS-NAME,com.tencent.tmgp.ysljln,{{ rule }} # 异兽灵境
PROCESS-NAME,com.tencent.tmgp.yslzm,{{ rule }} # 以闪亮之名
PROCESS-NAME,com.tencent.tmgp.ysymx,{{ rule }} # 勇士与冒险
PROCESS-NAME,com.tencent.tmgp.yttlj,{{ rule }} # 倚天屠龙记
PROCESS-NAME,com.tencent.tmgp.yttxky,{{ rule }} # 三国一统天下
PROCESS-NAME,com.tencent.tmgp.yunbu.nonogram,{{ rule }} # 数独趣味闯关
PROCESS-NAME,com.tencent.tmgp.yunbu.puppyblast,{{ rule }} # 甜点消消
PROCESS-NAME,com.tencent.tmgp.yuyoupoker101,{{ rule }} # 宇游麻将
PROCESS-NAME,com.tencent.tmgp.ywgn.myc,{{ rule }} # 亿万光年
PROCESS-NAME,com.tencent.tmgp.yx.sjcs,{{ rule }} # 神将传说
PROCESS-NAME,com.tencent.tmgp.yxwdzzjy,{{ rule }} # 魔法门之英雄无敌：战争纪元
PROCESS-NAME,com.tencent.tmgp.yxzs,{{ rule }} # 英雄之时
PROCESS-NAME,com.tencent.tmgp.yybdldlwhjx.qidian,{{ rule }} # 斗罗大陆：武魂觉醒
PROCESS-NAME,com.tencent.tmgp.yyhdyl.ddt,{{ rule }} # 斗斗堂
PROCESS-NAME,com.tencent.tmgp.yyjl,{{ rule }} # 永夜降临：复苏
PROCESS-NAME,com.tencent.tmgp.yys.zqb,{{ rule }} # 阴阳师
PROCESS-NAME,com.tencent.tmgp.yysbwp,{{ rule }} # 阴阳师：百闻牌
PROCESS-NAME,com.tencent.tmgp.yyslscn,{{ rule }} # 燕云十六声
PROCESS-NAME,com.tencent.tmgp.yyxx.qyj2,{{ rule }} # 青云诀2
PROCESS-NAME,com.tencent.tmgp.yyzy2,{{ rule }} # 月圆之夜
PROCESS-NAME,com.tencent.tmgp.yzg36,{{ rule }} # 三十六计
PROCESS-NAME,com.tencent.tmgp.yzhslln,{{ rule }} # 勇者幻兽录
PROCESS-NAME,com.tencent.tmgp.yzmj.cn,{{ rule }} # 勇者秘境
PROCESS-NAME,com.tencent.tmgp.yzsc,{{ rule }} # 约战沙城
PROCESS-NAME,com.tencent.tmgp.yzsnxyj,{{ rule }} # 少年西游记
PROCESS-NAME,com.tencent.tmgp.YZSY,{{ rule }} # 远征手游
PROCESS-NAME,com.tencent.tmgp.YZTWO,{{ rule }} # 远征2
PROCESS-NAME,com.tencent.tmgp.yzy_yzy,{{ rule }} # 源战役
PROCESS-NAME,com.tencent.tmgp.zanbuwyym,{{ rule }} # 未央一梦
PROCESS-NAME,com.tencent.tmgp.zawwshzh,{{ rule }} # 无双斩
PROCESS-NAME,com.tencent.tmgp.zbsmsy,{{ rule }} # 蜀门
PROCESS-NAME,com.tencent.tmgp.zbwlwz,{{ rule }} # 武林外传
PROCESS-NAME,com.tencent.tmgp.zd.ultraman,{{ rule }} # 奥特曼：光之战士
PROCESS-NAME,com.tencent.tmgp.zdbjlbj,{{ rule }} # 战斗吧！精灵
PROCESS-NAME,com.tencent.tmgp.zdsd.emmj,{{ rule }} # 恶魔秘境
PROCESS-NAME,com.tencent.tmgp.zgjjhd,{{ rule }} # 最高警戒
PROCESS-NAME,com.tencent.tmgp.zhangxinmj,{{ rule }} # 掌心全民麻将游戏软件v1.0
PROCESS-NAME,com.tencent.tmgp.zhanjian2,{{ rule }} # 战舰少女
PROCESS-NAME,com.tencent.tmgp.zhanlangii.wuziqi,{{ rule }} # 五子棋对战
PROCESS-NAME,com.tencent.tmgp.zhanlangii.xqdz,{{ rule }} # 象棋对战
PROCESS-NAME,com.tencent.tmgp.zhanling,{{ rule }} # 战灵
PROCESS-NAME,com.tencent.tmgp.zhaohe2,{{ rule }} # 召唤与合成2
PROCESS-NAME,com.tencent.tmgp.zhdysr,{{ rule }} # 最后的原始人
PROCESS-NAME,com.tencent.tmgp.zhetian,{{ rule }} # 遮天：凡尘一叶
PROCESS-NAME,com.tencent.tmgp.zhmr,{{ rule }} # 战魂铭人
PROCESS-NAME,com.tencent.tmgp.zhuanzhuanmj,{{ rule }} # 转转麻将随便玩
PROCESS-NAME,com.tencent.tmgp.zhuxian,{{ rule }} # 诛仙
PROCESS-NAME,com.tencent.tmgp.zjjhyyb,{{ rule }} # 再见江湖
PROCESS-NAME,com.tencent.tmgp.zjls2017,{{ rule }} # 战舰猎手
PROCESS-NAME,com.tencent.tmgp.zjqx2020,{{ rule }} # 装甲前线
PROCESS-NAME,com.tencent.tmgp.zjscmj,{{ rule }} # 指尖四川麻将
PROCESS-NAME,com.tencent.tmgp.zjsh,{{ rule }} # 指间山海
PROCESS-NAME,com.tencent.tmgp.zljjt,{{ rule }} # 侏罗纪军团
PROCESS-NAME,com.tencent.tmgp.zlongame.cn.epicseven,{{ rule }} # 第七史诗
PROCESS-NAME,com.tencent.tmgp.zlongame.eversoul,{{ rule }} # 空灵诗篇
PROCESS-NAME,com.tencent.tmgp.zmsy.zmxywz,{{ rule }} # 造梦西游外传
PROCESS-NAME,com.tencent.tmgp.zmxy,{{ rule }} # 造梦西游4
PROCESS-NAME,com.tencent.tmgp.zmxyol,{{ rule }} # 造梦西游OL
PROCESS-NAME,com.tencent.tmgp.zoxun.jjmj,{{ rule }} # 竞技麻将
PROCESS-NAME,com.tencent.tmgp.zqdwj,{{ rule }} # 足球大玩家
PROCESS-NAME,com.tencent.tmgp.zsjjc,{{ rule }} # 诸神竞技场
PROCESS-NAME,com.tencent.tmgp.zszs,{{ rule }} # 宗师之上
PROCESS-NAME,com.tencent.tmgp.zt.hsyl,{{ rule }} # 遮天：帝路争锋
PROCESS-NAME,com.tencent.tmgp.ztgame.fir,{{ rule }} # 征途2
PROCESS-NAME,com.tencent.tmgp.ztgame.wzzt,{{ rule }} # 王者征途
PROCESS-NAME,com.tencent.tmgp.ztgame.yszt,{{ rule }} # 原始征途
PROCESS-NAME,com.tencent.tmgp.zulong.drc,{{ rule }} # 龙族：卡塞尔之门
PROCESS-NAME,com.tencent.tmgp.zushi,{{ rule }} # 最强祖师
PROCESS-NAME,com.tencent.tmgp.zw.night,{{ rule }} # 黑夜传奇
PROCESS-NAME,com.tencent.tmgp.zx2,{{ rule }} # 诛仙2
PROCESS-NAME,com.tencent.tmgp.zzbw.chenjue,{{ rule }} # 至尊兵王
PROCESS-NAME,com.tencent.toaa,{{ rule }} # 黎明觉醒：生机
PROCESS-NAME,com.tencent.WeFire,{{ rule }} # 全民突击
PROCESS-NAME,com.tencent.wlfz,{{ rule }} # 星痕共鸣
PROCESS-NAME,com.tencent.wmsj,{{ rule }} # 完美世界
PROCESS-NAME,com.tencent.wok,{{ rule }} # 万王之王3D
PROCESS-NAME,com.tencent.woool3d,{{ rule }} # 传奇世界3D
PROCESS-NAME,com.tencent.xjcard,{{ rule }} # 仙剑奇侠传官方手游
PROCESS-NAME,com.tencent.YiRen,{{ rule }} # 一人之下
PROCESS-NAME,com.tencent.yoozoo.got.wintercoming,{{ rule }} # 权力的游戏凛冬将至
PROCESS-NAME,com.tencent.zd,{{ rule }} # 偃武
PROCESS-NAME,com.tencent.zgqyz,{{ rule }} # 鸿图之下
PROCESS-NAME,com.tencent.zhandiwujiang,{{ rule }} # 战地无疆
PROCESS-NAME,com.tencent.zqry2018,{{ rule }} # 全民冠军足球
PROCESS-NAME,com.touchtech.bbword,{{ rule }} # 儿童脑筋急转弯
PROCESS-NAME,com.touchtech.etpintu,{{ rule }} # 宝宝儿童来拼图
PROCESS-NAME,com.ubestkid.jigsawpuzzle.a,{{ rule }} # 贝乐虎拼图
PROCESS-NAME,com.uqee.lying.maingame,{{ rule }} # 卧龙吟-手机版
PROCESS-NAME,com.ustwo.monumentvalleyzz,{{ rule }} # 纪念碑谷
PROCESS-NAME,com.wedobest.HD1010,{{ rule }} # 罗斯方块
PROCESS-NAME,com.wedobest.llk,{{ rule }} # 连连看
PROCESS-NAME,com.wedobest.piano,{{ rule }} # 白块儿达人
PROCESS-NAME,com.wedobest.shudu,{{ rule }} # 数独
PROCESS-NAME,com.wedobest.szhrd,{{ rule }} # 数字华容道
PROCESS-NAME,com.wedobest.xiangqi,{{ rule }} # 象棋
PROCESS-NAME,com.wepie.snake.tencent,{{ rule }} # 贪吃蛇大作战
PROCESS-NAME,com.wepie.werewolfkill,{{ rule }} # 微派狼人
PROCESS-NAME,com.wepie.wespy,{{ rule }} # 我是卧底
PROCESS-NAME,com.wodidashi.paint,{{ rule }} # 你画我猜
PROCESS-NAME,com.wordtiger.cargame,{{ rule }} # 儿童宝宝汽车拼图
PROCESS-NAME,com.worldyy.qq.app,{{ rule }} # 世界Online
PROCESS-NAME,com.wp.sjh.yyb,{{ rule }} # 三剑豪
PROCESS-NAME,com.wushuang.landlord.kxlandlord,{{ rule }} # 开心斗地主
PROCESS-NAME,com.wxfg.cgjnz,{{ rule }} # 猜歌巨能赚
PROCESS-NAME,com.wzf.fan,{{ rule }} # 我是谜
PROCESS-NAME,com.xianyud.qs.cn,{{ rule }} # 仙遇
PROCESS-NAME,com.xueba.play,{{ rule }} # 做题软件
PROCESS-NAME,com.xzbig.idiom,{{ rule }} # 成语大接龙
PROCESS-NAME,com.xzidiom.stay,{{ rule }} # 成语小秀才
PROCESS-NAME,com.yinhan.hunter.tx,{{ rule }} # 时空猎人
PROCESS-NAME,com.yodo1.rodeo.TXYYB,{{ rule }} # 疯狂动物园
PROCESS-NAME,com.yodo1.SkiSafari.TXYYB_01,{{ rule }} # 滑雪大冒险
PROCESS-NAME,com.yshb.rrquestion,{{ rule }} # 人人答题
PROCESS-NAME,com.yshb.zhaocha,{{ rule }} # 找不同找茬
PROCESS-NAME,com.yunbu.bubbleelfsaga1,{{ rule }} # 泡泡精灵传奇
PROCESS-NAME,com.yxjj.sjtc.tc,{{ rule }} # 远星集结
PROCESS-NAME,com.zy.wqmt.cn,{{ rule }} # 无期迷途
PROCESS-NAME,e.room.Escape,{{ rule }} # 谜案馆
PROCESS-NAME,newbee.wordplay.cn.mi,{{ rule }} # 文字大玩家
PROCESS-NAME,org.islq.move2048,{{ rule }} # 天天2048
{% endmacro %}