{% macro main(rule) %}
PROCESS-NAME,air.com.bbfriend.ddsz,{{ rule }} # 哆哆识字
PROCESS-NAME,air.tv.douyu.android,{{ rule }} # 斗鱼
PROCESS-NAME,alook.browser,{{ rule }} # Alook浏览器
PROCESS-NAME,android.translate.xuedianba,{{ rule }} # 同声翻译超级版
PROCESS-NAME,android.zhibo8,{{ rule }} # 直播吧
PROCESS-NAME,app.Artronauction,{{ rule }} # 雅昌拍卖图录
PROCESS-NAME,app.yhyh.com,{{ rule }} # YHYH通信集成云厅
PROCESS-NAME,az.studio.gkztc,{{ rule }} # 高考直通车
PROCESS-NAME,bj.wanquan.hanfeislidecompact,{{ rule }} # 汉飞滑动输入法大屏手机版
PROCESS-NAME,bubei.tingshu,{{ rule }} # 懒人听书
PROCESS-NAME,bzjh.three.com,{{ rule }} # 神图壁纸
PROCESS-NAME,cc.fotoplace.app,{{ rule }} # 足记
PROCESS-NAME,cld.navi.mainframe,{{ rule }} # 凯立德导航
PROCESS-NAME,cmccwm.mobilemusic,{{ rule }} # 咪咕音乐
PROCESS-NAME,cn.amazon.mShop.android,{{ rule }} # 亚马逊购物
PROCESS-NAME,cn.banshenggua.aichang,{{ rule }} # 爱唱
PROCESS-NAME,cn.bdqn.pictureview,{{ rule }} # 手机图库
PROCESS-NAME,cn.buding.martin,{{ rule }} # 微车
PROCESS-NAME,cn.chinabus.main,{{ rule }} # 8684实时公交
PROCESS-NAME,cn.cj.pe,{{ rule }} # 139邮箱
PROCESS-NAME,cn.cntv,{{ rule }} # 央视影音
PROCESS-NAME,cn.cntvhd,{{ rule }} # 央视影音HD-新闻体育人文影视高清
PROCESS-NAME,cn.cntvnews,{{ rule }} # 央视新闻
PROCESS-NAME,cn.co.toyota_ms.smartGLINK,{{ rule }} # eLexusClub
PROCESS-NAME,cn.colorv,{{ rule }} # 彩视
PROCESS-NAME,cn.com.enorth.jinyun,{{ rule }} # 津云
PROCESS-NAME,cn.com.gjzq.yjb.kh,{{ rule }} # 佣金宝开户
PROCESS-NAME,cn.com.gxrb.client,{{ rule }} # 广西云
PROCESS-NAME,cn.com.lzb.mobilebank.per,{{ rule }} # 兰州银行
PROCESS-NAME,cn.com.modernmedia.businessweek,{{ rule }} # iBloomberg i商周
PROCESS-NAME,cn.com.modernmedia.modernlady,{{ rule }} # InStyle iLady
PROCESS-NAME,cn.com.nbd.nbdmobile,{{ rule }} # 每日经济新闻
PROCESS-NAME,cn.com.open.mooc,{{ rule }} # 慕课网
PROCESS-NAME,cn.com.pcauto.android.browser,{{ rule }} # 太平洋汽车
PROCESS-NAME,cn.com.pcgroup.magazine,{{ rule }} # 太平洋家居
PROCESS-NAME,cn.com.pconline.android.browser,{{ rule }} # 太平洋科技
PROCESS-NAME,cn.com.qlwb.qiluyidian,{{ rule }} # 齐鲁壹点
PROCESS-NAME,cn.com.shbank.mper,{{ rule }} # 上海银行
PROCESS-NAME,cn.com.sina.finance,{{ rule }} # 新浪财经
PROCESS-NAME,cn.com.sina.sports,{{ rule }} # 新浪体育
PROCESS-NAME,cn.com.spdb.mobilebank.per,{{ rule }} # 浦发银行
PROCESS-NAME,cn.com.tx.chat.android,{{ rule }} # 天下网
PROCESS-NAME,cn.com.wiisoft.contacts,{{ rule }} # 灵动来电海报
PROCESS-NAME,cn.com.wiisoft.skin,{{ rule }} # 灵动主题皮肤
PROCESS-NAME,cn.dahebao,{{ rule }} # 顶端新闻
PROCESS-NAME,cn.damai,{{ rule }} # 大麦
PROCESS-NAME,cn.dict.android.pro,{{ rule }} # 海词词典
PROCESS-NAME,cn.dxy.idxyer,{{ rule }} # 丁香园
PROCESS-NAME,cn.dxy.medicinehelper,{{ rule }} # 用药助手
PROCESS-NAME,cn.eclicks.drivingtest,{{ rule }} # 车轮驾考通
PROCESS-NAME,cn.eclicks.wzsearch,{{ rule }} # 车轮
PROCESS-NAME,cn.ecook,{{ rule }} # 网上厨房
PROCESS-NAME,cn.edu.zjicm.wordsnet_d,{{ rule }} # 知米背单词
PROCESS-NAME,cn.emagsoftware.gamehall,{{ rule }} # 咪咕快游
PROCESS-NAME,cn.emoney.level2,{{ rule }} # 益盟操盘手经典版
PROCESS-NAME,cn.etouch.ecalendar,{{ rule }} # 中华万年历
PROCESS-NAME,cn.fmsyjhgb,{{ rule }} # FM收音机广播-广播电台
PROCESS-NAME,cn.ghac.gha,{{ rule }} # 广汽本田
PROCESS-NAME,cn.gogocity.suibian,{{ rule }} # 随便走
PROCESS-NAME,cn.gzmovement,{{ rule }} # 动静新闻
PROCESS-NAME,cn.ibabyzone.music,{{ rule }} # 胎教盒子
PROCESS-NAME,cn.itheme.tech,{{ rule }} # 手机主题
PROCESS-NAME,cn.jingling.motu.photowonder,{{ rule }} # 魔图精灵
PROCESS-NAME,cn.jjpengcheng.wallpaper,{{ rule }} # 安卓动态壁纸
PROCESS-NAME,cn.jsb.china,{{ rule }} # 江苏银行
PROCESS-NAME,cn.kaoshi100.view,{{ rule }} # 考试100
PROCESS-NAME,cn.kuwo.kwmusichd,{{ rule }} # 酷我音乐HD
PROCESS-NAME,cn.kuwo.player,{{ rule }} # 酷我音乐
PROCESS-NAME,cn.kuwo.tingshu,{{ rule }} # 酷我听书
PROCESS-NAME,cn.ledongli.ldl,{{ rule }} # 乐动力
PROCESS-NAME,cn.longmaster.pengpeng,{{ rule }} # 语玩
PROCESS-NAME,cn.lrapps.changliaocall,{{ rule }} # 畅聊网络电话
PROCESS-NAME,cn.lrapps.yitongcall,{{ rule }} # 易通网络电话
PROCESS-NAME,cn.mama.activity,{{ rule }} # 妈妈网轻聊
PROCESS-NAME,cn.mchina.mbrowser,{{ rule }} # 移联浏览器
PROCESS-NAME,cn.mopon.film.xflh,{{ rule }} # 幸福看
PROCESS-NAME,cn.myhug.baobao,{{ rule }} # 抱抱直播
PROCESS-NAME,cn.nanjingshuoyu.iclock,{{ rule }} # 一键锁屏iclock主题-应用锁
PROCESS-NAME,cn.okek.chexingwuyou,{{ rule }} # 车行无忧
PROCESS-NAME,cn.opda.a.phonoalbumshoushou,{{ rule }} # 百度手机卫士
PROCESS-NAME,cn.poco.jane,{{ rule }} # 简拼
PROCESS-NAME,cn.samsclub.app,{{ rule }} # 山姆会员商店
PROCESS-NAME,cn.shengmimi.callshow,{{ rule }} # 视频铃声
PROCESS-NAME,cn.shengmitech.intelllock,{{ rule }} # 锁屏
PROCESS-NAME,cn.shijihaiwaitech.hunli,{{ rule }} # 婚礼邀请函
PROCESS-NAME,cn.shuangshuangfei,{{ rule }} # 找对象
PROCESS-NAME,cn.sqcat.jwcamera,{{ rule }} # 经纬
PROCESS-NAME,cn.tianya.light,{{ rule }} # 天涯社区
PROCESS-NAME,cn.vcinema.cinema,{{ rule }} # 南瓜电影
PROCESS-NAME,cn.weixiaowenghua.Polaroid,{{ rule }} # 拍立得
PROCESS-NAME,cn.weli.sweet,{{ rule }} # CUCU
PROCESS-NAME,cn.wondershare.filmorago,{{ rule }} # 万兴喵影
PROCESS-NAME,cn.wps.moffice_eng,{{ rule }} # WPS Office
PROCESS-NAME,cn.xiaochuankeji.tieba,{{ rule }} # 最右
PROCESS-NAME,cn.xmcall.haige,{{ rule }} # 嗨鸽
PROCESS-NAME,cn.xuexi.android,{{ rule }} # 学习强国
PROCESS-NAME,cn.youth.news,{{ rule }} # 中青看点
PROCESS-NAME,cn.zepeto.main,{{ rule }} # 崽崽ZEPETO
PROCESS-NAME,cn.zhangyoukeji.browser.jisou,{{ rule }} # 极搜浏览器
PROCESS-NAME,cn.zymk.comic,{{ rule }} # 知音漫客
PROCESS-NAME,com.achievo.vipshop,{{ rule }} # 唯品会
PROCESS-NAME,com.actionsmicro.ezcast,{{ rule }} # EZCast
PROCESS-NAME,com.ada.desks,{{ rule }} # 安卓桌面
PROCESS-NAME,com.admin.dingdongphone,{{ rule }} # 叮咚网络电话-虚拟电话软件
PROCESS-NAME,com.admin.youyouphone,{{ rule }} # 优优电话-免费电话
PROCESS-NAME,com.adnonstop.mancamera2017,{{ rule }} # 型影
PROCESS-NAME,com.advasoft.touchretouch,{{ rule }} # TouchRetouch
PROCESS-NAME,com.afar.eleass,{{ rule }} # 电工专家
PROCESS-NAME,com.aheading.news.lanzhourb,{{ rule }} # 奔流新闻
PROCESS-NAME,com.ahnews.newsclient,{{ rule }} # 中安新闻
PROCESS-NAME,com.ainemo.dragoon,{{ rule }} # 小鱼易连
PROCESS-NAME,com.aipai.android,{{ rule }} # 爱拍
PROCESS-NAME,com.aipai.paidashi,{{ rule }} # 拍大师
PROCESS-NAME,com.alensw.PhoneArea,{{ rule }} # QC 归属地
PROCESS-NAME,com.alibaba.android.rimet,{{ rule }} # 钉钉
PROCESS-NAME,com.alibaba.intl.android.apps.poseidon,{{ rule }} # Alibaba.com
PROCESS-NAME,com.alibaba.wireless,{{ rule }} # 阿里巴巴
PROCESS-NAME,com.alicom.smartdail,{{ rule }} # 阿里小号
PROCESS-NAME,com.alimama.moon,{{ rule }} # 淘宝联盟
PROCESS-NAME,com.android.app.quanmama,{{ rule }} # 券妈妈优惠券
PROCESS-NAME,com.android.autoAirPlaneMode,{{ rule }} # 自动飞行模式
PROCESS-NAME,com.android.bankabc,{{ rule }} # 中国农业银行
PROCESS-NAME,com.android.clock.sd,{{ rule }} # 山东农信
PROCESS-NAME,com.android.dazhihui,{{ rule }} # 大智慧
PROCESS-NAME,com.android.tiancity.mobilesecurity,{{ rule }} # 天成账号管家
PROCESS-NAME,com.android36kr.app,{{ rule }} # 36氪
PROCESS-NAME,com.Android56,{{ rule }} # 56视频
PROCESS-NAME,com.androidesk,{{ rule }} # 安卓壁纸
PROCESS-NAME,com.androidesk.livewallpaper,{{ rule }} # 安卓动态壁纸
PROCESS-NAME,com.anhuioss.simpleime,{{ rule }} # Simple IME
PROCESS-NAME,com.ants360.yicamera,{{ rule }} # 小蚁摄像机
PROCESS-NAME,com.antutu.ABenchMark,{{ rule }} # 安兔兔评测
PROCESS-NAME,com.apa.callshow,{{ rule }} # 嗨来电秀
PROCESS-NAME,com.app.dzy.btchat,{{ rule }} # 蓝牙闲聊
PROCESS-NAME,com.app.hero.ui,{{ rule }} # K歌达人
PROCESS-NAME,com.app.meiyue,{{ rule }} # 魅约
PROCESS-NAME,com.app.ymqzy,{{ rule }} # 动态壁纸秀场
PROCESS-NAME,com.app.yujiasuxingji,{{ rule }} # 壁纸图片大师
PROCESS-NAME,com.appbyme.app71974,{{ rule }} # 编织人生论坛
PROCESS-NAME,com.appchina.anpai.2019071601,{{ rule }} # 鸟类壁纸
PROCESS-NAME,com.appchina.anpai.2020052601,{{ rule }} # Gear浏览器
PROCESS-NAME,com.appchina.anpai.20210203002,{{ rule }} # 什么时辰 - 生辰文字时钟小组件Widgets
PROCESS-NAME,com.appchina.anpai.20210203003,{{ rule }} # 什么时间 - 翻转时钟桌面小组件Widget
PROCESS-NAME,com.appchina.anpai.2021100803,{{ rule }} # 猫咪锁屏提醒-每天将待办任务展示到壁纸上
PROCESS-NAME,com.appcina.anpai.2019080818,{{ rule }} # 克拉壁纸
PROCESS-NAME,com.appcina.anpai.2019090601,{{ rule }} # 壁纸制作:Livfe - 动态壁纸制作&视频壁纸
PROCESS-NAME,com.appcina.anpai.2019092705,{{ rule }} # 星座运势-十二星座每日运势小组件
PROCESS-NAME,com.appcina.anpai.2019092707,{{ rule }} # PixHall-高清可商用图片壁纸库
PROCESS-NAME,com.appcina.anpai.2019092902,{{ rule }} # 落格输入法
PROCESS-NAME,com.appcina.anpai.2019101103,{{ rule }} # 滑一滑相册视频
PROCESS-NAME,com.appcina.anpai.2019112101,{{ rule }} # Artpaper：有 1,300 多张艺术画壁纸可每日更换
PROCESS-NAME,com.appcina.anpai.2019112901,{{ rule }} # Hola Px - 我的专属精选壁纸专家
PROCESS-NAME,com.appcina.anpai.2019112915,{{ rule }} # OnlyTalk - 语音对讲
PROCESS-NAME,com.appcina.anpai.2019122013,{{ rule }} # WLPPR - background wallpapers
PROCESS-NAME,com.appcina.anpai.2019122604,{{ rule }} # LiveFun - 自定义动态壁纸
PROCESS-NAME,com.appcina.anpai.2020010306,{{ rule }} # 无相 - 原生化浏览器
PROCESS-NAME,com.appcina.anpai.2020011202,{{ rule }} # Berkanan Messenger
PROCESS-NAME,com.appcina.anpai.2020011602,{{ rule }} # 我的同事-职场熟人社交
PROCESS-NAME,com.appshare.android.ilisten,{{ rule }} # 口袋故事
PROCESS-NAME,com.appshare.android.ilisten.hd,{{ rule }} # 口袋故事HD
PROCESS-NAME,com.appsino.bingluo.fycz,{{ rule }} # 移动公证
PROCESS-NAME,com.appstarry.beauty.widget,{{ rule }} # 小组件桌面美化
PROCESS-NAME,com.astonievanesc.affinit,{{ rule }} # 怦然来电
PROCESS-NAME,com.autohome.usedcar,{{ rule }} # 二手车之家
PROCESS-NAME,com.autonavi.minimap,{{ rule }} # 高德地图
PROCESS-NAME,com.avatar.kungfufinance,{{ rule }} # 功夫财经
PROCESS-NAME,com.babytree.apps.lama,{{ rule }} # 宝宝树小时光
PROCESS-NAME,com.babytree.apps.pregnancy,{{ rule }} # 宝宝树孕育
PROCESS-NAME,com.baidu.BaiduMap,{{ rule }} # 百度地图
PROCESS-NAME,com.baidu.baidutranslate,{{ rule }} # 百度翻译
PROCESS-NAME,com.baidu.browser.apps,{{ rule }} # 百度浏览器
PROCESS-NAME,com.baidu.hao123,{{ rule }} # 上网导航
PROCESS-NAME,com.baidu.haokan,{{ rule }} # 好看视频
PROCESS-NAME,com.baidu.hi,{{ rule }} # 如流
PROCESS-NAME,com.baidu.homework,{{ rule }} # 作业帮
PROCESS-NAME,com.baidu.iknow,{{ rule }} # 百度知道
PROCESS-NAME,com.baidu.input,{{ rule }} # 百度输入法
PROCESS-NAME,com.baidu.input_mi,{{ rule }} # 百度输入法小米版
PROCESS-NAME,com.baidu.lbs.crowdapp,{{ rule }} # 地图淘金
PROCESS-NAME,com.baidu.netdisk,{{ rule }} # 百度网盘
PROCESS-NAME,com.baidu.news,{{ rule }} # 百度新闻
PROCESS-NAME,com.baidu.searchbox,{{ rule }} # 百度
PROCESS-NAME,com.baidu.searchbox.lite,{{ rule }} # 百度极速版
PROCESS-NAME,com.baidu.searchbox.senior,{{ rule }} # 百度关怀版
PROCESS-NAME,com.baidu.searchcraft,{{ rule }} # 简单搜索
PROCESS-NAME,com.baidu.tieba,{{ rule }} # 百度贴吧
PROCESS-NAME,com.baidu.video,{{ rule }} # 百搜视频
PROCESS-NAME,com.baidu.video.pad,{{ rule }} # 百搜视频HD
PROCESS-NAME,com.baidu.wenku,{{ rule }} # 百度文库
PROCESS-NAME,com.baidu.youavideo,{{ rule }} # 一刻相册
PROCESS-NAME,com.baidu.yuedu,{{ rule }} # 百度阅读
PROCESS-NAME,com.baihe,{{ rule }} # 百合网
PROCESS-NAME,com.baijiu.bizhi.sjbixiaz,{{ rule }} # Wallpaper
PROCESS-NAME,com.baijiu.bizhi.zhutidaq,{{ rule }} # 主题
PROCESS-NAME,com.bank,{{ rule }} # 黄河银行
PROCESS-NAME,com.baoear.baoer,{{ rule }} # 宝耳
PROCESS-NAME,com.baoruan.a.theme.nmbfoacffRZoLNxYKVq,{{ rule }} # 科技之光-宝软3D主题
PROCESS-NAME,com.baoruan.theme.mhczpffedYqofhovJAD,{{ rule }} # 古剑奇谭之风晴雪-3D桌面主题
PROCESS-NAME,com.baoruan.theme.ngbipabffBUHJYlMxjk,{{ rule }} # 假装自己能忘记-宝软3D主题
PROCESS-NAME,com.baoruan.theme.ngbznegecClKxGwPhol,{{ rule }} # 阿里巴巴大盗奇兵-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nibzpezehhOtmKEOjRO,{{ rule }} # 偶像来了-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nicaoaiacBRvWyrigGY,{{ rule }} # 十二道锋味-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nicazaebaXgOPvDEIUI,{{ rule }} # 么么哒小鹿先生-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nlbglcefeBEfUwqRwZG,{{ rule }} # 爱是心灵的交流-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nmczieafirKJYCtjYiX,{{ rule }} # 天边最亮的星-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nmdaneeebWKQxeDBSBV,{{ rule }} # 回忆飘散の时光-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nzacpcdcUntIsxoVVv,{{ rule }} # 小黄人大眼萌-宝软3D主题
PROCESS-NAME,com.baoruan.theme.nzcdieefhPEFnNNEaFM,{{ rule }} # 兔子兔子-宝软3D主题
PROCESS-NAME,com.baoruan.vmiic,{{ rule }} # 主题商店
PROCESS-NAME,com.baoruan.wallpaper.lmaczcgcdjTJGknirRd,{{ rule }} # 绚丽水晶-桌面壁纸
PROCESS-NAME,com.bayupay.zhbqb,{{ rule }} # 最火表情包
PROCESS-NAME,com.bbbao.shop.client.android.activity,{{ rule }} # 比比宝
PROCESS-NAME,com.bbqk.quietlycall,{{ rule }} # 免费电话宝
PROCESS-NAME,com.bcxgps.baidumap,{{ rule }} # 伴车星
PROCESS-NAME,com.bdatu.geography,{{ rule }} # 每日精选
PROCESS-NAME,com.bench.yylc,{{ rule }} # 盈盈
PROCESS-NAME,com.benqu.wuta,{{ rule }} # 无他相机
PROCESS-NAME,com.bigwinepot.nwdn,{{ rule }} # 你我当年AI照片修复
PROCESS-NAME,com.bilibili.studio,{{ rule }} # 必剪
PROCESS-NAME,com.biligyar.izdax,{{ rule }} # izdax翻译
PROCESS-NAME,com.bizhi.picturexx,{{ rule }} # 花瓣壁纸
PROCESS-NAME,com.bizhijuhe.lj,{{ rule }} # 克拉壁纸
PROCESS-NAME,com.bjbyhd.voiceback,{{ rule }} # 保益悦听
PROCESS-NAME,com.bjsy.xiangsubz,{{ rule }} # 像素壁纸
PROCESS-NAME,com.blink.academy.nomo,{{ rule }} # NOMO CAM
PROCESS-NAME,com.boohee.one,{{ rule }} # 薄荷健康
PROCESS-NAME,com.bp.androidesk,{{ rule }} # 主题壁纸
PROCESS-NAME,com.brains.byzmnew,{{ rule }} # 益智脑筋急转弯大全
PROCESS-NAME,com.brid.wallpaper.two,{{ rule }} # 小鸟壁纸
PROCESS-NAME,com.browser2345,{{ rule }} # 2345浏览器
PROCESS-NAME,com.budejie.www,{{ rule }} # 百思漂流瓶
PROCESS-NAME,com.businessvalue.android.app,{{ rule }} # 钛媒体
PROCESS-NAME,com.by.butter.camera,{{ rule }} # 黄油相机
PROCESS-NAME,com.bz.xiu,{{ rule }} # 壁纸秀秀
PROCESS-NAME,com.bz.ziti.diy,{{ rule }} # wallpaper壁纸大全
PROCESS-NAME,com.caijing,{{ rule }} # 财经杂志
PROCESS-NAME,com.caing.news,{{ rule }} # 财新
PROCESS-NAME,com.caishi.cronus,{{ rule }} # 唔哩头条
PROCESS-NAME,com.camera.retroarg,{{ rule }} # Dazz复古相机拍照
PROCESS-NAME,com.campmobile.snowcamera,{{ rule }} # B612咔叽
PROCESS-NAME,com.capelabs.leyou,{{ rule }} # 乐友
PROCESS-NAME,com.cat.readall,{{ rule }} # 悟空浏览器
PROCESS-NAME,com.cbnweekly,{{ rule }} # 第一财经杂志
PROCESS-NAME,com.ccgs.sms,{{ rule }} # 短信群发助手
PROCESS-NAME,com.cdcd.milv,{{ rule }} # 觅侣-语音视频恋爱交友
PROCESS-NAME,com.cdtv.app,{{ rule }} # 看度新闻
PROCESS-NAME,com.ceic.app,{{ rule }} # 地震速报
PROCESS-NAME,com.chan.cwallpaper,{{ rule }} # 图凌
PROCESS-NAME,com.changba,{{ rule }} # 唱吧
PROCESS-NAME,com.changshuo.ui,{{ rule }} # 畅说108
PROCESS-NAME,com.chaozh.iReaderFree,{{ rule }} # 掌阅
PROCESS-NAME,com.chaozh.iReaderFree15,{{ rule }} # 爱读掌阅
PROCESS-NAME,com.chenai.eyes,{{ rule }} # 夜间模式
PROCESS-NAME,com.chinaamc.MainActivityAMC,{{ rule }} # 华夏基金管家
PROCESS-NAME,com.chinaamc.mfbh.amcActivity,{{ rule }} # 华夏活期通
PROCESS-NAME,com.chinablue.tv,{{ rule }} # Z视介
PROCESS-NAME,com.chinaideal.bkclient.tabmain,{{ rule }} # 你我嘉选
PROCESS-NAME,com.chinamobile.contacts.im,{{ rule }} # 和通讯录
PROCESS-NAME,com.chinamobile.mcloud,{{ rule }} # 中国移动云盘
PROCESS-NAME,com.chinamworld.bocmbci,{{ rule }} # 中国银行
PROCESS-NAME,com.chinamworld.main,{{ rule }} # 中国建设银行
PROCESS-NAME,com.chinasoft.mall,{{ rule }} # 好享购物
PROCESS-NAME,com.chinatelecom.bestpayclient,{{ rule }} # 翼支付
PROCESS-NAME,com.chineseall.reader,{{ rule }} # 17K小说
PROCESS-NAME,com.chineseall.singlebook,{{ rule }} # 中文书城
PROCESS-NAME,com.ci123.pregnancy,{{ rule }} # 孕育提醒
PROCESS-NAME,com.ci123.pregnancywap,{{ rule }} # 妈妈社区
PROCESS-NAME,com.cio.project,{{ rule }} # 通信助手
PROCESS-NAME,com.citiccard.mobilebank,{{ rule }} # 动卡空间
PROCESS-NAME,com.cleanmaster.mguard_cn,{{ rule }} # 猎豹清理大师
PROCESS-NAME,com.cmbchina.ccd.pluto.cmbActivity,{{ rule }} # 掌上生活
PROCESS-NAME,com.cmcm.cfwallpaper,{{ rule }} # 元气桌面壁纸
PROCESS-NAME,com.cmri.universalapp,{{ rule }} # 移动爱家
PROCESS-NAME,com.cmstop.zswz,{{ rule }} # 掌上温州
PROCESS-NAME,com.cn21.ecloud,{{ rule }} # 天翼云盘
PROCESS-NAME,com.cnbizmedia.shangjie,{{ rule }} # 商界
PROCESS-NAME,com.cns.mc.activity,{{ rule }} # 中国新闻网
PROCESS-NAME,com.codoon.gps,{{ rule }} # 咕咚
PROCESS-NAME,com.color.by.coloring.wallpaper.android,{{ rule }} # 涂个壁纸
PROCESS-NAME,com.corp21cn.mail189,{{ rule }} # 189邮箱
PROCESS-NAME,com.csii_qzbank,{{ rule }} # 泉州银行
PROCESS-NAME,com.csii.hkb,{{ rule }} # 汉口银行
PROCESS-NAME,com.csii.tianjin.mobilebank,{{ rule }} # 天津银行
PROCESS-NAME,com.cssq.wallpaper,{{ rule }} # 最美免费壁纸
PROCESS-NAME,com.ct.client,{{ rule }} # 中国电信
PROCESS-NAME,com.cubic.autohome,{{ rule }} # 汽车之家
PROCESS-NAME,com.cutv.mobile.zsntclient,{{ rule }} # 掌上南通
PROCESS-NAME,com.czbank.mbank,{{ rule }} # 浙商银行
PROCESS-NAME,com.dachen.medicalcircle,{{ rule }} # 医生圈
PROCESS-NAME,com.dada.kdb123,{{ rule }} # 快递短信宝
PROCESS-NAME,com.dangdang.buy2,{{ rule }} # 当当
PROCESS-NAME,com.dangdang.reader,{{ rule }} # 当当云阅读
PROCESS-NAME,com.danielstudio.app.wowtu,{{ rule }} # 煎蛋
PROCESS-NAME,com.daofeng.zuhaowan,{{ rule }} # 租号玩
PROCESS-NAME,com.daqo.wallpaper,{{ rule }} # 酷划壁纸大全
PROCESS-NAME,com.ddmh.livewallpaper,{{ rule }} # 动态壁纸秀
PROCESS-NAME,com.ddsm.didu,{{ rule }} # Didu
PROCESS-NAME,com.ddwallpaperang.wallpaper,{{ rule }} # 图图乐
PROCESS-NAME,com.dealmoon.android,{{ rule }} # 北美省钱快报
PROCESS-NAME,com.desktop.pendant,{{ rule }} # 银河壁纸多多
PROCESS-NAME,com.devuni.flashlight,{{ rule }} # 超级手电筒
PROCESS-NAME,com.dewmobile.kuaiya,{{ rule }} # 快牙
PROCESS-NAME,com.deyi.client,{{ rule }} # 得意生活
PROCESS-NAME,com.DHgate.seller.android,{{ rule }} # 敦煌网商户
PROCESS-NAME,com.dianping.v1,{{ rule }} # 大众点评
PROCESS-NAME,com.diershoubing.erbing,{{ rule }} # 二柄
PROCESS-NAME,com.dingniu.wallpaper,{{ rule }} # 4k动态壁纸
PROCESS-NAME,com.dingYZ.dingyzwater,{{ rule }} # 微脉水印相机
PROCESS-NAME,com.dipiapp.pcall,{{ rule }} # 嘀嗒网络电话
PROCESS-NAME,com.djbox.product,{{ rule }} # DJ音乐盒
PROCESS-NAME,com.docin.zlibrary.ui.android,{{ rule }} # 豆丁书房
PROCESS-NAME,com.dongqiudi.news,{{ rule }} # 懂球帝
PROCESS-NAME,com.dotamax.app,{{ rule }} # Max+
PROCESS-NAME,com.douban.book.reader,{{ rule }} # 豆瓣阅读
PROCESS-NAME,com.douban.radio,{{ rule }} # 豆瓣FM
PROCESS-NAME,com.douguo.recipe,{{ rule }} # 豆果美食
PROCESS-NAME,com.dp.android.elong,{{ rule }} # 艺龙旅行
PROCESS-NAME,com.dragon.read,{{ rule }} # 番茄免费小说
PROCESS-NAME,com.dragonfly.wallpaper,{{ rule }} # 蜻蜓壁纸
PROCESS-NAME,com.droidpiggy.weiqi,{{ rule }} # 围棋宝典
PROCESS-NAME,com.duitang.main,{{ rule }} # 堆糖
PROCESS-NAME,com.duoduo.cailing,{{ rule }} # 彩铃多多
PROCESS-NAME,com.duoduo.child.story,{{ rule }} # 儿歌多多
PROCESS-NAME,com.duokan.phone.remotecontroller,{{ rule }} # 万能遥控
PROCESS-NAME,com.duokan.reader,{{ rule }} # 多看
PROCESS-NAME,com.duolingo,{{ rule }} # 多邻国
PROCESS-NAME,com.duowan.kiwi,{{ rule }} # 虎牙直播
PROCESS-NAME,com.duowan.mobile,{{ rule }} # YY
PROCESS-NAME,com.dx.x1myapplication,{{ rule }} # 电销外呼电话
PROCESS-NAME,com.dzwww.sd.android,{{ rule }} # 海报新闻
PROCESS-NAME,com.eastday.listen_news,{{ rule }} # 翱翔
PROCESS-NAME,com.eastmoney.android.berlin,{{ rule }} # 东方财富
PROCESS-NAME,com.eastmoney.android.fund,{{ rule }} # 天天基金
PROCESS-NAME,com.eastmoney.android.tokyo,{{ rule }} # 财经圈子
PROCESS-NAME,com.easy.wallpaper,{{ rule }} # 番茄动态壁纸
PROCESS-NAME,com.ebnews,{{ rule }} # 亿邦
PROCESS-NAME,com.eg.android.AlipayGphone,{{ rule }} # 支付宝
PROCESS-NAME,com.ell.wallpaperell,{{ rule }} # 主题商店免费
PROCESS-NAME,com.eno.android,{{ rule }} # 国海金探号
PROCESS-NAME,com.eno.android.cj.page,{{ rule }} # 长江e号
PROCESS-NAME,com.eno.xyzq.page,{{ rule }} # 兴业证券优理宝
PROCESS-NAME,com.enotary.cloud,{{ rule }} # 公证云
PROCESS-NAME,com.esbook.reader,{{ rule }} # 宜搜小说
PROCESS-NAME,com.estrongs.android.pop,{{ rule }} # ES文件浏览器
PROCESS-NAME,com.eusoft.eudic,{{ rule }} # 欧路词典
PROCESS-NAME,com.eusoft.frhelper,{{ rule }} # 法语助手
PROCESS-NAME,com.eusoft.ting.en,{{ rule }} # 每日英语听力
PROCESS-NAME,com.evaair.android,{{ rule }} # 长荣航空
PROCESS-NAME,com.everimaging.photoeffectstudio,{{ rule }} # Fotor
PROCESS-NAME,com.example.administrator.searchpicturetool,{{ rule }} # 搜图神器
PROCESS-NAME,com.example.mp3editor,{{ rule }} # MP3剪辑器
PROCESS-NAME,com.example.raccoon.dialogwidget,{{ rule }} # 万象小组件
PROCESS-NAME,com.ezen.ehshig,{{ rule }} # egshig
PROCESS-NAME,com.faloo.BookReader4Android,{{ rule }} # 飞卢小说
PROCESS-NAME,com.fanghe.makepaper,{{ rule }} # 桌面时钟锁屏
PROCESS-NAME,com.fanghuoyun.im,{{ rule }} # 防火云
PROCESS-NAME,com.fanhuan,{{ rule }} # 返还网
PROCESS-NAME,com.fanli.android.apps,{{ rule }} # 返利
PROCESS-NAME,com.fbx.handwriteime,{{ rule }} # 手写输入法
PROCESS-NAME,com.feiteng.lieyou,{{ rule }} # 猎游
PROCESS-NAME,com.felink.foregroundpaper,{{ rule }} # 羞兔全局壁纸
PROCESS-NAME,com.fenbi.android.gaozhong,{{ rule }} # 猿题库
PROCESS-NAME,com.fenqile.fenqile,{{ rule }} # 分期乐
PROCESS-NAME,com.fimo.camera,{{ rule }} # FIMO
PROCESS-NAME,com.finals.finalsflash,{{ rule }} # 来电闪光灯
PROCESS-NAME,com.flightmanager.view,{{ rule }} # 航班管家
PROCESS-NAME,com.fn.android,{{ rule }} # 蜂鸟摄影
PROCESS-NAME,com.fombo.wallpaper,{{ rule }} # 高清动态壁纸大全
PROCESS-NAME,com.font,{{ rule }} # 写字先生
PROCESS-NAME,com.founder.qujing,{{ rule }} # 掌上曲靖
PROCESS-NAME,com.founder.zhanjiang,{{ rule }} # 湛江云媒
PROCESS-NAME,com.fq.wallpaper,{{ rule }} # 飞火动态壁纸-超清主题桌面大全
PROCESS-NAME,com.freebird.zsp.DailyAccounting,{{ rule }} # 日常记账
PROCESS-NAME,com.frozenape.tempo,{{ rule }} # 移动节拍器 Metronome Tempo
PROCESS-NAME,com.fullgoal.android,{{ rule }} # 富国富钱包
PROCESS-NAME,com.funinput.digit,{{ rule }} # 数字尾巴
PROCESS-NAME,com.funshion.video.mobile,{{ rule }} # 风行视频
PROCESS-NAME,com.fx678.finace,{{ rule }} # 汇通财经
PROCESS-NAME,com.galaxy.metawp,{{ rule }} # 元壁纸
PROCESS-NAME,com.galaxy.stock,{{ rule }} # 中国银河证券
PROCESS-NAME,com.gamestar.perfectpiano,{{ rule }} # 完美钢琴
PROCESS-NAME,com.gamestar.pianoperfect,{{ rule }} # 随身乐队
PROCESS-NAME,com.ganji.android,{{ rule }} # 赶集直招
PROCESS-NAME,com.gaoping.makewallpaper,{{ rule }} # 动态壁纸制作
PROCESS-NAME,com.gau.go.launcherex.theme.droidglass,{{ rule }} # 玻璃主题包
PROCESS-NAME,com.gbcom.gwifi.school,{{ rule }} # GiWiFi校园助手
PROCESS-NAME,com.geihui,{{ rule }} # 给惠网
PROCESS-NAME,com.gem.tastyfood,{{ rule }} # 食行生鲜
PROCESS-NAME,com.ggeye.jiakao.api,{{ rule }} # 驾考通驾照考试宝典
PROCESS-NAME,com.gifshow.kuaishou.bamboo,{{ rule }} # 快手创作者版
PROCESS-NAME,com.glodon.drawingexplorer,{{ rule }} # CAD快速看图
PROCESS-NAME,com.gongyinruixin,{{ rule }} # 工银瑞信基金
PROCESS-NAME,com.gonlan.iplaymtg,{{ rule }} # 旅法师营地
PROCESS-NAME,com.goodluck.qianming,{{ rule }} # 一句心情签名
PROCESS-NAME,com.gopro.smarty,{{ rule }} # GoPro Quik
PROCESS-NAME,com.gorgeous.lite,{{ rule }} # 轻颜
PROCESS-NAME,com.goseet.VidTrim,{{ rule }} # 视频剪辑
PROCESS-NAME,com.gozap.chouti,{{ rule }} # 抽屉
PROCESS-NAME,com.gpslh.baidumap,{{ rule }} # 物联在线
PROCESS-NAME,com.greenpoint.android.mc10086.activity,{{ rule }} # 中国移动
PROCESS-NAME,com.gtdev5.caller_flashover,{{ rule }} # 来电闪
PROCESS-NAME,com.gtgj.view,{{ rule }} # 高铁管家
PROCESS-NAME,com.guosen.android,{{ rule }} # 国信金太阳
PROCESS-NAME,com.gwdang.app,{{ rule }} # 购物党
PROCESS-NAME,com.gwsoft.imusic.controller,{{ rule }} # 爱音乐
PROCESS-NAME,com.gzrcb.mobilebank,{{ rule }} # 广州农商银行
PROCESS-NAME,com.haidilao,{{ rule }} # 海底捞
PROCESS-NAME,com.haitao,{{ rule }} # 55海淘
PROCESS-NAME,com.hangzhoucaimi.financial,{{ rule }} # 挖财宝
PROCESS-NAME,com.hanvon.inputmethod.hanvonime,{{ rule }} # 汉王行云输入法
PROCESS-NAME,com.hanweb.android.sdzwfw.activity,{{ rule }} # 爱山东
PROCESS-NAME,com.haowan.huabar,{{ rule }} # 画吧
PROCESS-NAME,com.hapingbizhiang.bizhi,{{ rule }} # 哈屏壁纸
PROCESS-NAME,com.happigo.activity,{{ rule }} # 快乐购
PROCESS-NAME,com.happylife.multimedia.image,{{ rule }} # 相片集
PROCESS-NAME,com.happyteam.dubbingshow,{{ rule }} # 配音秀
PROCESS-NAME,com.heiyan.reader,{{ rule }} # 黑岩阅读
PROCESS-NAME,com.hellotalk,{{ rule }} # HelloTalk
PROCESS-NAME,com.hexin.android.bank,{{ rule }} # 同花顺爱基金
PROCESS-NAME,com.hexin.android.stockassistant,{{ rule }} # i问财
PROCESS-NAME,com.hexin.ifind.android,{{ rule }} # 同花顺iFinD
PROCESS-NAME,com.hexin.plat.android,{{ rule }} # 同花顺
PROCESS-NAME,com.hexin.plat.android.GuoJinZXGSecurity,{{ rule }} # 全能行
PROCESS-NAME,com.hexin.plat.android.ZhongyuanSecurity,{{ rule }} # 中原证券
PROCESS-NAME,com.hexun.news,{{ rule }} # 和讯财经
PROCESS-NAME,com.hf,{{ rule }} # 中国天气
PROCESS-NAME,com.hh.wallpaper.a,{{ rule }} # 全民免费壁纸
PROCESS-NAME,com.hipu.yidian,{{ rule }} # 一点资讯
PROCESS-NAME,com.hjkj66.fakecall,{{ rule }} # 虚拟电话
PROCESS-NAME,com.hjwordgames,{{ rule }} # 沪江开心词场
PROCESS-NAME,com.hkairlines.apps,{{ rule }} # 香港航空
PROCESS-NAME,com.hkx.youandme,{{ rule }} # 情侣我和你
PROCESS-NAME,com.hlg.daydaytobusiness,{{ rule }} # 稿定设计
PROCESS-NAME,com.hmkx.zgjkj,{{ rule }} # 健康界
PROCESS-NAME,com.hnzx.hnrb,{{ rule }} # 河南日报
PROCESS-NAME,com.hoge.android.chinablue,{{ rule }} # 中国蓝新闻
PROCESS-NAME,com.hoge.android.wuhan,{{ rule }} # 掌上武汉
PROCESS-NAME,com.hoge.android.wuxiwireless,{{ rule }} # 无锡博报
PROCESS-NAME,com.honeymoon.stone.jean.poweredit,{{ rule }} # 图片编辑工具
PROCESS-NAME,com.honghesoft.calligrapher,{{ rule }} # 大书法家
PROCESS-NAME,com.hongxiu.app,{{ rule }} # 红袖读书
PROCESS-NAME,com.hoo.mood.wallpaper,{{ rule }} # 免费壁纸王
PROCESS-NAME,com.hqf.app.yuanqi,{{ rule }} # 趣玩桌面壁纸
PROCESS-NAME,com.hsbank.mobilebank,{{ rule }} # 徽商银行
PROCESS-NAME,com.htffund.mobile.ec.ui,{{ rule }} # 汇添富现金宝
PROCESS-NAME,com.htinns,{{ rule }} # 华住会
PROCESS-NAME,com.huaban.android,{{ rule }} # 花瓣
PROCESS-NAME,com.huajiao,{{ rule }} # 花椒直播
PROCESS-NAME,com.hualongxiang,{{ rule }} # 化龙巷
PROCESS-NAME,com.huankaifa.tpjwz,{{ rule }} # 图片加文字
PROCESS-NAME,com.huanqiu.news,{{ rule }} # 环球时报
PROCESS-NAME,com.huanyukeji.xiaohong,{{ rule }} # 配角
PROCESS-NAME,com.huawei.hwid,{{ rule }} # HMS Core
PROCESS-NAME,com.huawei.KoBackup,{{ rule }} # 备份
PROCESS-NAME,com.huimai365,{{ rule }} # 惠买
PROCESS-NAME,com.hujiang.dict,{{ rule }} # 沪江小D词典
PROCESS-NAME,com.hujiang.hjclass,{{ rule }} # 沪江网校
PROCESS-NAME,com.hunantv.imgo.activity,{{ rule }} # 芒果TV
PROCESS-NAME,com.hundsun.winner.pazq,{{ rule }} # 平安证券
PROCESS-NAME,com.hupu.games,{{ rule }} # 虎扑
PROCESS-NAME,com.hupu.shihuo,{{ rule }} # 识货
PROCESS-NAME,com.huxiu,{{ rule }} # 虎嗅
PROCESS-NAME,com.hyhy.view,{{ rule }} # 掌上天津
PROCESS-NAME,com.ibox.flashlight,{{ rule }} # 多多手电筒
PROCESS-NAME,com.iboxpay.minicashbox,{{ rule }} # 钱盒商户通
PROCESS-NAME,com.icbc,{{ rule }} # 中国工商银行
PROCESS-NAME,com.icbc.emallmobile,{{ rule }} # 融e购
PROCESS-NAME,com.ichano.athome.avs,{{ rule }} # 掌上看家采集端
PROCESS-NAME,com.ichano.athome.camera,{{ rule }} # 掌上看家
PROCESS-NAME,com.iCitySuzhou.suzhou001,{{ rule }} # 引力播
PROCESS-NAME,com.icoolme.android.weather,{{ rule }} # 最美天气
PROCESS-NAME,com.id10000,{{ rule }} # ID
PROCESS-NAME,com.ifanr.activitys,{{ rule }} # 爱范儿
PROCESS-NAME,com.ifeimo.videoeditor,{{ rule }} # 视频剪辑大师
PROCESS-NAME,com.ifeng.fhdt,{{ rule }} # 凤凰FM
PROCESS-NAME,com.ifeng.news2,{{ rule }} # 凤凰新闻
PROCESS-NAME,com.ifeng.newvideo,{{ rule }} # 凤凰视频
PROCESS-NAME,com.ifext.news,{{ rule }} # 凤凰新闻极速版
PROCESS-NAME,com.iflytek.inputmethod,{{ rule }} # 讯飞输入法
PROCESS-NAME,com.iflytek.womusicclient,{{ rule }} # 联通视频彩铃
PROCESS-NAME,com.ifreetalk.ftalk,{{ rule }} # 派派
PROCESS-NAME,com.ihg.apps.android,{{ rule }} # IHG洲际酒店集团及优悦会
PROCESS-NAME,com.ihope.hbdt,{{ rule }} # 冀时
PROCESS-NAME,com.imgo.pad,{{ rule }} # 芒果TV HD
PROCESS-NAME,com.immomo.momo,{{ rule }} # MOMO陌陌
PROCESS-NAME,com.imusic.iting,{{ rule }} # 爱听
PROCESS-NAME,com.inditex.zara,{{ rule }} # ZARA
PROCESS-NAME,com.intel.voice,{{ rule }} # 超级声音表情
PROCESS-NAME,com.intsig.BizCardReader,{{ rule }} # 名片全能王
PROCESS-NAME,com.intsig.camscanner,{{ rule }} # 扫描全能王
PROCESS-NAME,com.irongroup,{{ rule }} # 电话时间统计
PROCESS-NAME,com.iss.dongyingbank,{{ rule }} # 东营银行
PROCESS-NAME,com.iss.taianbank,{{ rule }} # 泰安银行
PROCESS-NAME,com.istone.activity,{{ rule }} # 邦购商城
PROCESS-NAME,com.iyuba.AE,{{ rule }} # 美语怎么说
PROCESS-NAME,com.iyuba.cet4,{{ rule }} # 英语四级听力
PROCESS-NAME,com.iyuba.CSvoa,{{ rule }} # VOA英语听力
PROCESS-NAME,com.iyuba.music,{{ rule }} # 听歌学英语
PROCESS-NAME,com.iyuba.voa,{{ rule }} # VOA慢速英语
PROCESS-NAME,com.jecelyin.editor,{{ rule }} # JecEditor 文本编辑器
PROCESS-NAME,com.jeejen.family,{{ rule }} # 极简桌面
PROCESS-NAME,com.jesson.meishi,{{ rule }} # 美食杰
PROCESS-NAME,com.jhdapp.xhbycm,{{ rule }} # 交汇点新闻
PROCESS-NAME,com.jhss.youguu,{{ rule }} # 优顾炒股
PROCESS-NAME,com.jiayuan,{{ rule }} # 世纪佳缘
PROCESS-NAME,com.jie.lockscreen,{{ rule }} # 锁屏大全
PROCESS-NAME,com.jiemian.news,{{ rule }} # 界面新闻
PROCESS-NAME,com.jifen.qukan,{{ rule }} # 趣头条
PROCESS-NAME,com.jingdong.app.mall,{{ rule }} # 京东
PROCESS-NAME,com.jingzhou,{{ rule }} # 荆州社区
PROCESS-NAME,com.jinying.mobile,{{ rule }} # 金鹰生活
PROCESS-NAME,com.jiongji.andriod.card,{{ rule }} # 百词斩
PROCESS-NAME,com.jiuxianapk.ui,{{ rule }} # 酒仙
PROCESS-NAME,com.jiuyan.infashion,{{ rule }} # in
PROCESS-NAME,com.jlzb.android,{{ rule }} # 找帮手机定位
PROCESS-NAME,com.jm.android.jumei,{{ rule }} # 聚美
PROCESS-NAME,com.jm.fxw,{{ rule }} # 发型屋
PROCESS-NAME,com.job.android,{{ rule }} # 前程无忧51Job
PROCESS-NAME,com.jovetech.CloudSee.temp,{{ rule }} # 云视通
PROCESS-NAME,com.joygo,{{ rule }} # 忘忧围棋
PROCESS-NAME,com.joyintech.wise.seller,{{ rule }} # 智慧商贸进销存
PROCESS-NAME,com.jsbc.lznews,{{ rule }} # 荔枝新闻
PROCESS-NAME,com.jsmcc,{{ rule }} # 中国移动江苏
PROCESS-NAME,com.jtjsb.ldb,{{ rule }} # 来电宝软件
PROCESS-NAME,com.jtjsb.yymms,{{ rule }} # 智能应用密码锁
PROCESS-NAME,com.julanling.app,{{ rule }} # 安心记加班
PROCESS-NAME,com.jx.fastbrowser,{{ rule }} # 高速浏览器
PROCESS-NAME,com.jx.minibrowser,{{ rule }} # 极速浏览器
PROCESS-NAME,com.jx.safebrowser,{{ rule }} # 安全浏览器
PROCESS-NAME,com.jxedt,{{ rule }} # 驾校一点通
PROCESS-NAME,com.kankanews.kankanxinwen,{{ rule }} # 看看新闻
PROCESS-NAME,com.kaola,{{ rule }} # 考拉海购
PROCESS-NAME,com.kdbzyjz20,{{ rule }} # 口袋壁纸
PROCESS-NAME,com.kevinstudio.test,{{ rule }} # 转盘做决定
PROCESS-NAME,com.Kingdee.Express,{{ rule }} # 快递100
PROCESS-NAME,com.kingsoft,{{ rule }} # 金山词霸
PROCESS-NAME,com.kingsoft.android.cat,{{ rule }} # 玲珑密保锁
PROCESS-NAME,com.kkycs.component,{{ rule }} # 美化小组件
PROCESS-NAME,com.kmxs.reader,{{ rule }} # 七猫免费小说
PROCESS-NAME,com.komoxo.octopusime,{{ rule }} # 章鱼输入法
PROCESS-NAME,com.koudai.weishop,{{ rule }} # 微店店长版
PROCESS-NAME,com.kuaikan.comic,{{ rule }} # 快看漫画
PROCESS-NAME,com.kuangxiang.novel,{{ rule }} # 欢乐书客
PROCESS-NAME,com.kugou.android,{{ rule }} # 酷狗音乐
PROCESS-NAME,com.kugou.android.ringtone,{{ rule }} # 酷狗铃声
PROCESS-NAME,com.kugou.fanxing,{{ rule }} # 酷狗直播
PROCESS-NAME,com.kunpeng.babyting,{{ rule }} # 宝贝听听-睡前故事
PROCESS-NAME,com.kunpeng.bluefont,{{ rule }} # 字体下载极速版
PROCESS-NAME,com.kwai.m2u,{{ rule }} # 一甜相机
PROCESS-NAME,com.kwai.videoeditor,{{ rule }} # 快影
PROCESS-NAME,com.lakala.android,{{ rule }} # 拉卡拉易分期
PROCESS-NAME,com.lanjinger.choiassociatedpress,{{ rule }} # 财联社
PROCESS-NAME,com.lazymc.smstoemail,{{ rule }} # 我的信
PROCESS-NAME,com.lcworld.haiwainet,{{ rule }} # 海客新闻
PROCESS-NAME,com.ledu.ebrowser,{{ rule }} # e浏览器
PROCESS-NAME,com.ledu.wbrowser,{{ rule }} # w浏览器
PROCESS-NAME,com.leisu.sports,{{ rule }} # 雷速体育
PROCESS-NAME,com.leixun.taofen8,{{ rule }} # 淘粉吧
PROCESS-NAME,com.lemon.faceu,{{ rule }} # Faceu激萌
PROCESS-NAME,com.lenovo.leos.cloud.sync,{{ rule }} # 云服务(原乐同步)
PROCESS-NAME,com.leqi.idpicture,{{ rule }} # 智能证件照
PROCESS-NAME,com.letv.android.client,{{ rule }} # 乐视视频
PROCESS-NAME,com.letv.android.client.pad,{{ rule }} # 乐视视频Pad
PROCESS-NAME,com.letv.letvshop,{{ rule }} # 乐视商城
PROCESS-NAME,com.lezhi.mythcall,{{ rule }} # 北瓜电话
PROCESS-NAME,com.lianaibiji.dev,{{ rule }} # 恋爱记
PROCESS-NAME,com.liba.android,{{ rule }} # 篱笆社区
PROCESS-NAME,com.linecorp.foodcamcn.android,{{ rule }} # Foodie
PROCESS-NAME,com.lingan.seeyou,{{ rule }} # 美柚
PROCESS-NAME,com.linkiing.show,{{ rule }} # 联客show
PROCESS-NAME,com.liulishuo.engzo,{{ rule }} # 流利说-英语
PROCESS-NAME,com.liuzb.moodiary,{{ rule }} # 心情日记本
PROCESS-NAME,com.ljmobile.zlj.rom.release,{{ rule }} # 授权管理软件搬家
PROCESS-NAME,com.llspace.pupu,{{ rule }} # 平行世界
PROCESS-NAME,com.lltskb.lltskb,{{ rule }} # 路路通
PROCESS-NAME,com.lofter.android,{{ rule }} # 网易LOFTER
PROCESS-NAME,com.lokinfo.android.gamemarket.mmshow,{{ rule }} # 95秀
PROCESS-NAME,com.lolaage.tbulu.tools,{{ rule }} # 两步路户外助手
PROCESS-NAME,com.lovebizhi.wallpaper,{{ rule }} # 爱壁纸_桌面锁屏
PROCESS-NAME,com.lqh.love.comic,{{ rule }} # 爱动漫壁纸
PROCESS-NAME,com.ls.sjdtbz,{{ rule }} # 手机动态壁纸
PROCESS-NAME,com.lt.lighting,{{ rule }} # 来电闪光
PROCESS-NAME,com.ludashi.benchmark,{{ rule }} # 鲁大师
PROCESS-NAME,com.lufax.android,{{ rule }} # 陆基金
PROCESS-NAME,com.lyh.talkphoto,{{ rule }} # 让照片会说话
PROCESS-NAME,com.lyx.piano,{{ rule }} # 钢琴节奏键盘大师
PROCESS-NAME,com.lz.mycall,{{ rule }} # 千千电话
PROCESS-NAME,com.magicalstory.search,{{ rule }} # 奇妙搜索
PROCESS-NAME,com.marqio.widget.keeplighting,{{ rule }} # 屏幕常亮
PROCESS-NAME,com.meelive.ingkee,{{ rule }} # 映客直播
PROCESS-NAME,com.meet.pianolearn,{{ rule }} # 钢琴教练
PROCESS-NAME,com.meetstudio.app.Zither,{{ rule }} # 古筝
PROCESS-NAME,com.meitu.makeup,{{ rule }} # 美妆相机
PROCESS-NAME,com.meitu.meipaimv,{{ rule }} # 美拍
PROCESS-NAME,com.meitu.meiyancamera,{{ rule }} # 美颜相机
PROCESS-NAME,com.meitu.poster,{{ rule }} # 美图设计室
PROCESS-NAME,com.meitu.wheecam,{{ rule }} # 潮自拍
PROCESS-NAME,com.meitu.wink,{{ rule }} # Meitu Wink
PROCESS-NAME,com.meixun.wnpet,{{ rule }} # 蜗牛桌宠- 桌面小组件
PROCESS-NAME,com.meizu.flyme.find,{{ rule }} # 查找手机
PROCESS-NAME,com.melot.meshow,{{ rule }} # KK
PROCESS-NAME,com.memory.me,{{ rule }} # 英语魔方秀
PROCESS-NAME,com.mendon.riza,{{ rule }} # 日杂相机
PROCESS-NAME,com.mengtuiapp.mall,{{ rule }} # 萌推
PROCESS-NAME,com.messi.languagehelper,{{ rule }} # 中英互译
PROCESS-NAME,com.mfw.roadbook,{{ rule }} # 马蜂窝
PROCESS-NAME,com.mgyun.rootmaster,{{ rule }} # ROOT大师
PROCESS-NAME,com.microsoft.emmx,{{ rule }} # Edge
PROCESS-NAME,com.microsoft.office.officehub,{{ rule }} # Microsoft 365 (Office)
PROCESS-NAME,com.microsoft.skydrive,{{ rule }} # OneDrive
PROCESS-NAME,com.miercnnew.app,{{ rule }} # 米尔军事
PROCESS-NAME,com.mimikko.mimikkoui,{{ rule }} # 兽耳助手
PROCESS-NAME,com.minitools.miniwidget,{{ rule }} # 心动主题壁纸
PROCESS-NAME,com.mishangwo,{{ rule }} # 迷上我
PROCESS-NAME,com.miui.video,{{ rule }} # 小米视频
PROCESS-NAME,com.mmbox.xbrowser.pro,{{ rule }} # X浏览器
PROCESS-NAME,com.mmote.play,{{ rule }} # 买萌陪玩
PROCESS-NAME,com.mobile.myeye,{{ rule }} # 监控眼
PROCESS-NAME,com.MobileTicket,{{ rule }} # 铁路12306
PROCESS-NAME,com.mobvoi.baiding,{{ rule }} # 出门问问
PROCESS-NAME,com.mogujie,{{ rule }} # 蘑菇街
PROCESS-NAME,com.moji.mjweather,{{ rule }} # 墨迹天气
PROCESS-NAME,com.moneywise.mhmoney,{{ rule }} # 财智快账
PROCESS-NAME,com.moonlight.huatu,{{ rule }} # 画画图
PROCESS-NAME,com.mp.qcoperate,{{ rule }} # 红旗e岗通
PROCESS-NAME,com.mrkj.sm,{{ rule }} # 知命
PROCESS-NAME,com.msg.schedule,{{ rule }} # 定时信息
PROCESS-NAME,com.mt.mtxx.mtxx,{{ rule }} # 美图秀秀
PROCESS-NAME,com.mtime,{{ rule }} # 时光网
PROCESS-NAME,com.mx.browser,{{ rule }} # 傲游浏览器
PROCESS-NAME,com.mxr.dreambook,{{ rule }} # 4D书城
PROCESS-NAME,com.mxtech.videoplayer.ad,{{ rule }} # MX 播放器
PROCESS-NAME,com.my.browserplus,{{ rule }} # 浏览器加
PROCESS-NAME,com.mygolbs.mybus,{{ rule }} # 掌上公交
PROCESS-NAME,com.mymoney,{{ rule }} # 随手记
PROCESS-NAME,com.mymoney.sms,{{ rule }} # 卡牛信用管家
PROCESS-NAME,com.myzaker.ZAKER_Phone,{{ rule }} # ZAKER
PROCESS-NAME,com.naiyoubz.main,{{ rule }} # 奶油桌面
PROCESS-NAME,com.nbbank,{{ rule }} # 宁波银行
PROCESS-NAME,com.ncpaclassic,{{ rule }} # 大剧院·古典
PROCESS-NAME,com.nd.android.pandahome2,{{ rule }} # 91桌面
PROCESS-NAME,com.nd.android.pandareader,{{ rule }} # 熊猫看书
PROCESS-NAME,com.neil,{{ rule }} # 返利助手
PROCESS-NAME,com.net263.ecm.display,{{ rule }} # 263移动会议
PROCESS-NAME,com.netease.cc,{{ rule }} # CC直播
PROCESS-NAME,com.netease.cloudmusic,{{ rule }} # 网易云音乐
PROCESS-NAME,com.netease.epay,{{ rule }} # 网易支付
PROCESS-NAME,com.netease.huatian,{{ rule }} # 网易花田
PROCESS-NAME,com.netease.mail,{{ rule }} # 网易邮箱大师
PROCESS-NAME,com.netease.mkey,{{ rule }} # 网易将军令
PROCESS-NAME,com.netease.mobimail,{{ rule }} # 网易邮箱
PROCESS-NAME,com.netease.newsreader.activity,{{ rule }} # 网易新闻
PROCESS-NAME,com.netease.pris,{{ rule }} # 网易云阅读
PROCESS-NAME,com.netease.vopen,{{ rule }} # 网易公开课
PROCESS-NAME,com.netease.xyqcbg,{{ rule }} # 梦幻藏宝阁
PROCESS-NAME,com.new_qdqss.activity,{{ rule }} # 掌上青岛
PROCESS-NAME,com.newstar.zybbname,{{ rule }} # 宝宝生辰起名取名
PROCESS-NAME,com.nfdaily.nfplus,{{ rule }} # 南方Plus
PROCESS-NAME,com.nice.main,{{ rule }} # nice
PROCESS-NAME,com.nineteenlou.nineteenlou,{{ rule }} # 19楼
PROCESS-NAME,com.ninexiu.sixninexiu,{{ rule }} # 九秀直播
PROCESS-NAME,com.niuguwang.stock,{{ rule }} # 牛股王股票
PROCESS-NAME,com.njmizhilan.wallpaper,{{ rule }} # 动态壁纸
PROCESS-NAME,com.njwry.zhuochong,{{ rule }} # 桌面宠物多多
PROCESS-NAME,com.novv.resshare,{{ rule }} # 光点视频壁纸
PROCESS-NAME,com.ocj.oms.mobile,{{ rule }} # 东方购物
PROCESS-NAME,com.octinn.birthdayplus,{{ rule }} # 生日管家
PROCESS-NAME,com.oda_cad,{{ rule }} # CAD迷你看图
PROCESS-NAME,com.oeiskd.easysoftkey,{{ rule }} # 小白点虚拟按键
PROCESS-NAME,com.offcn.android.offcn,{{ rule }} # 中公教育
PROCESS-NAME,com.ophone.reader.ui,{{ rule }} # 咪咕阅读
PROCESS-NAME,com.oray.sunlogin,{{ rule }} # 向日葵远程控制
PROCESS-NAME,com.oupeng.browser,{{ rule }} # 欧朋浏览器极速版
PROCESS-NAME,com.oupeng.mini.android,{{ rule }} # 欧朋浏览器
PROCESS-NAME,com.p1.mobile.putong,{{ rule }} # 探探
PROCESS-NAME,com.paic.zhifu.wallet.activity,{{ rule }} # 壹钱包
PROCESS-NAME,com.pcpop.popapk,{{ rule }} # hao网址大全
PROCESS-NAME,com.peopledailychina.activity,{{ rule }} # 人民日报
PROCESS-NAME,com.perracolabs.tcc,{{ rule }} # Tiny Call Confirm
PROCESS-NAME,com.pingdiguo.tuner,{{ rule }} # 乐器调音器
PROCESS-NAME,com.pinguo.edit.sdk,{{ rule }} # MIX滤镜大师
PROCESS-NAME,com.pplive.androidphone,{{ rule }} # PP视频
PROCESS-NAME,com.pplive.androidphone.sport,{{ rule }} # PP体育
PROCESS-NAME,com.prinics.kodak.photoprinter,{{ rule }} # KODAK Photo Printer
PROCESS-NAME,com.qdnews.qd,{{ rule }} # 青岛新闻
PROCESS-NAME,com.qiaola.desktop,{{ rule }} # 动态壁纸精灵
PROCESS-NAME,com.qidian.QDReader,{{ rule }} # 起点读书
PROCESS-NAME,com.qihoo.appstore,{{ rule }} # 360手机助手
PROCESS-NAME,com.qihoo.browser,{{ rule }} # 360浏览器
PROCESS-NAME,com.qihoo.camera,{{ rule }} # 360摄像机
PROCESS-NAME,com.qihoo.cleandroid_cn,{{ rule }} # 360清理大师
PROCESS-NAME,com.qihoo.contents,{{ rule }} # 360极速浏览器
PROCESS-NAME,com.qihoo.qeditor,{{ rule }} # 快剪辑
PROCESS-NAME,com.qihoo360.mobilesafe,{{ rule }} # 360手机卫士
PROCESS-NAME,com.qilesoft.en.eights,{{ rule }} # 英语口语8000句
PROCESS-NAME,com.qima.kdt,{{ rule }} # 有赞微商城
PROCESS-NAME,com.qisi.freepaper,{{ rule }} # 免费壁纸大全
PROCESS-NAME,com.qisi.wallpaper,{{ rule }} # 壁纸主题大全
PROCESS-NAME,com.qiyi.video,{{ rule }} # 爱奇艺
PROCESS-NAME,com.qiyi.video.pad,{{ rule }} # 爱奇艺PAD
PROCESS-NAME,com.qnap.qremote,{{ rule }} # Qremote
PROCESS-NAME,com.qq.ac.android,{{ rule }} # 腾讯动漫
PROCESS-NAME,com.qq.qcloud,{{ rule }} # 腾讯微云
PROCESS-NAME,com.qq.reader,{{ rule }} # QQ阅读
PROCESS-NAME,com.quanleimu.activity,{{ rule }} # 百姓网
PROCESS-NAME,com.quark.browser,{{ rule }} # 夸克
PROCESS-NAME,com.Qunar,{{ rule }} # 去哪儿旅行
PROCESS-NAME,com.quvideo.slideplus,{{ rule }} # 小影记
PROCESS-NAME,com.quvideo.xiaoying,{{ rule }} # 小影
PROCESS-NAME,com.qzone,{{ rule }} # QQ空间
PROCESS-NAME,com.raiyi.wxcs,{{ rule }} # 流量掌厅
PROCESS-NAME,com.rakutec.android.iweekly,{{ rule }} # iWeekly 周末画报
PROCESS-NAME,com.rarlab.rar,{{ rule }} # 万能RAR解压缩软件
PROCESS-NAME,com.rd.kx,{{ rule }} # 星剪
PROCESS-NAME,com.redrcd.ylxf,{{ rule }} # 云岭先锋
PROCESS-NAME,com.renren.mobile.android,{{ rule }} # 人人直播
PROCESS-NAME,com.ruanmei.ithome,{{ rule }} # IT之家
PROCESS-NAME,com.rumtel.mobiletv,{{ rule }} # 影视大全看看
PROCESS-NAME,com.saida.sjkd.xk,{{ rule }} # 享看
PROCESS-NAME,com.sand.airdroid,{{ rule }} # AirDroid
PROCESS-NAME,com.sangdh,{{ rule }} # 3G网络电话
PROCESS-NAME,com.sankuai.meituan,{{ rule }} # 美团
PROCESS-NAME,com.sankuai.movie,{{ rule }} # 猫眼
PROCESS-NAME,com.sanya.xinxiulive,{{ rule }} # Bei贝
PROCESS-NAME,com.scanning,{{ rule }} # 二维码与条形码
PROCESS-NAME,com.sdu.didi.psnger,{{ rule }} # 滴滴出行
PROCESS-NAME,com.sec.android.easyMover,{{ rule }} # S 换机助手
PROCESS-NAME,com.secoo,{{ rule }} # 寺库
PROCESS-NAME,com.seetong.app.seetong,{{ rule }} # Seetong
PROCESS-NAME,com.sevenmmobile,{{ rule }} # 7M足球实时比分
PROCESS-NAME,com.shanbay.sentence,{{ rule }} # 扇贝单词英语版
PROCESS-NAME,com.shangc.tiennews,{{ rule }} # 石榴云
PROCESS-NAME,com.shanhu.wallpaper,{{ rule }} # 小鸟壁纸
PROCESS-NAME,com.shenyuan.militarynews,{{ rule }} # 环球新军事
PROCESS-NAME,com.shinyv.cnr,{{ rule }} # 云听
PROCESS-NAME,com.shizhuang.duapp,{{ rule }} # 得物
PROCESS-NAME,com.shoujiduoduo.ringtone,{{ rule }} # 铃声多多
PROCESS-NAME,com.shoujiduoduo.wallpaper,{{ rule }} # 壁纸多多
PROCESS-NAME,com.shuqi.controller,{{ rule }} # 书旗小说
PROCESS-NAME,com.shyltts,{{ rule }} # 读短信来电报姓名
PROCESS-NAME,com.si.wallpapersi,{{ rule }} # 最美免费壁纸秀
PROCESS-NAME,com.sina.news,{{ rule }} # 新浪新闻
PROCESS-NAME,com.sina.VDisk,{{ rule }} # 新浪微盘
PROCESS-NAME,com.sina.weibo,{{ rule }} # 微博
PROCESS-NAME,com.sina.weibog3,{{ rule }} # 微博移动版
PROCESS-NAME,com.sing.client,{{ rule }} # 5sing音乐
PROCESS-NAME,com.sinovatech.gxmobile.ui,{{ rule }} # 中国移动广西
PROCESS-NAME,com.sinovatech.unicom.ui,{{ rule }} # 中国联通
PROCESS-NAME,com.sinovoice.hcicloudinput,{{ rule }} # 灵云智能输入法
PROCESS-NAME,com.sinyee.babybus.abc,{{ rule }} # 宝宝巴士ABC
PROCESS-NAME,com.sinyee.babybus.babydrawing,{{ rule }} # 宝宝画妈妈猜
PROCESS-NAME,com.sinyee.babybus.chef,{{ rule }} # 宝宝小厨房
PROCESS-NAME,com.sinyee.babybus.dailycommodities,{{ rule }} # 宝宝认日用品
PROCESS-NAME,com.sinyee.babybus.farm,{{ rule }} # 奇妙数字农场
PROCESS-NAME,com.sinyee.babybus.foodstreet,{{ rule }} # 宝宝美食街
PROCESS-NAME,com.sinyee.babybus.lovehealthy,{{ rule }} # 宝宝爱卫生
PROCESS-NAME,com.sinyee.babybus.magichouse,{{ rule }} # 宝宝调色屋
PROCESS-NAME,com.sinyee.babybus.number,{{ rule }} # 宝宝玩数字
PROCESS-NAME,com.sinyee.babybus.organized,{{ rule }} # 宝宝大扫除
PROCESS-NAME,com.sinyee.babybus.puzzle,{{ rule }} # 宝宝认知大全
PROCESS-NAME,com.sinyee.babybus.season,{{ rule }} # 宝宝缤纷四季
PROCESS-NAME,com.sinyee.babybus.seaworld,{{ rule }} # 宝宝钓鱼
PROCESS-NAME,com.sinyee.babybus.show,{{ rule }} # 宝宝服装秀
PROCESS-NAME,com.sinyee.babybus.toilet,{{ rule }} # 宝宝上厕所
PROCESS-NAME,com.sinyee.babybus.travelsafety,{{ rule }} # 宝宝出行安全
PROCESS-NAME,com.sitech.rhtx,{{ rule }} # 易信
PROCESS-NAME,com.sjz.cl.smspopup,{{ rule }} # 短信弹窗
PROCESS-NAME,com.skp.adf.photopunch,{{ rule }} # 抠图神手
PROCESS-NAME,com.slanissue.apps.mobile.erge,{{ rule }} # 贝瓦儿歌
PROCESS-NAME,com.sloth.removelogo,{{ rule }} # 视频去水印
PROCESS-NAME,com.smile.gifmaker,{{ rule }} # 快手
PROCESS-NAME,com.smzdm.client.android,{{ rule }} # 什么值得买
PROCESS-NAME,com.snda.wifilocating,{{ rule }} # WiFi万能钥匙
PROCESS-NAME,com.soft.blued,{{ rule }} # Blued
PROCESS-NAME,com.sohu.inputmethod.sogou,{{ rule }} # 搜狗输入法
PROCESS-NAME,com.sohu.mail.client.cordova,{{ rule }} # 搜狐闪电邮
PROCESS-NAME,com.sohu.newsclient,{{ rule }} # 搜狐新闻
PROCESS-NAME,com.sohu.sohuvideo,{{ rule }} # 搜狐视频
PROCESS-NAME,com.sohu.tv,{{ rule }} # 搜狐视频HD
PROCESS-NAME,com.sony.store.china,{{ rule }} # 索尼中国
PROCESS-NAME,com.soohoot.ptest,{{ rule }} # 普通话发音测试
PROCESS-NAME,com.soufun.app,{{ rule }} # 房天下
PROCESS-NAME,com.ss.android.article.lite,{{ rule }} # 今日头条极速版
PROCESS-NAME,com.ss.android.article.news,{{ rule }} # 今日头条
PROCESS-NAME,com.ss.android.tuchong,{{ rule }} # 图虫
PROCESS-NAME,com.sskj.flashlight,{{ rule }} # 随手电筒
PROCESS-NAME,com.ssports.mobile.video,{{ rule }} # 爱奇艺体育
PROCESS-NAME,com.starbucks.cn,{{ rule }} # 星巴克
PROCESS-NAME,com.starsidea.vigorousicon,{{ rule }} # 元气图标
PROCESS-NAME,com.stkj.dadieji,{{ rule }} # 音乐节奏大师
PROCESS-NAME,com.storychina,{{ rule }} # 故事会
PROCESS-NAME,com.strawberry.cmbz,{{ rule }} # 草莓壁纸
PROCESS-NAME,com.sun.quickpay,{{ rule }} # 神奇小部件
PROCESS-NAME,com.suning.mobile.ebuy,{{ rule }} # 苏宁易购
PROCESS-NAME,com.suning.mobile.epa,{{ rule }} # 星图金融
PROCESS-NAME,com.sunying.booster,{{ rule }} # 光影
PROCESS-NAME,com.superlib,{{ rule }} # 超星移动图书馆
PROCESS-NAME,com.swlvrm.anwsi,{{ rule }} # 蜜桃主题壁纸
PROCESS-NAME,com.sywg.stock,{{ rule }} # 申万宏源高端
PROCESS-NAME,com.szeureka.camerasrc,{{ rule }} # 联趣拍摄遥控器
PROCESS-NAME,com.szqd.dialer,{{ rule }} # 神指拨号
PROCESS-NAME,com.tal.kaoyan,{{ rule }} # 考研帮
PROCESS-NAME,com.talicai.timiclient,{{ rule }} # Timi记账
PROCESS-NAME,com.taobao.etao,{{ rule }} # 一淘
PROCESS-NAME,com.taobao.idlefish,{{ rule }} # 闲鱼
PROCESS-NAME,com.taobao.litetao,{{ rule }} # 淘宝特价版
PROCESS-NAME,com.taobao.qianniu,{{ rule }} # 千牛
PROCESS-NAME,com.taobao.taobao,{{ rule }} # 淘宝
PROCESS-NAME,com.taobao.trip,{{ rule }} # 飞猪旅行
PROCESS-NAME,com.taoche.qctt,{{ rule }} # 汽车头条
PROCESS-NAME,com.taoguba.app,{{ rule }} # 淘股吧
PROCESS-NAME,com.taou.maimai,{{ rule }} # 脉脉
PROCESS-NAME,com.telecom.video,{{ rule }} # 天翼超高清
PROCESS-NAME,com.tencent.androidqqmail,{{ rule }} # QQ邮箱
PROCESS-NAME,com.tencent.gallerymanager,{{ rule }} # 相册管家
PROCESS-NAME,com.tencent.gamehelper.smoba,{{ rule }} # 王者营地
PROCESS-NAME,com.tencent.map,{{ rule }} # 腾讯地图
PROCESS-NAME,com.tencent.mm,{{ rule }} # 微信
PROCESS-NAME,com.tencent.mobileqq,{{ rule }} # QQ
PROCESS-NAME,com.tencent.mtt,{{ rule }} # QQ浏览器
PROCESS-NAME,com.tencent.news,{{ rule }} # 腾讯新闻
PROCESS-NAME,com.tencent.portfolio,{{ rule }} # 腾讯自选股
PROCESS-NAME,com.tencent.qqlive,{{ rule }} # 腾讯视频
PROCESS-NAME,com.tencent.qqmusic,{{ rule }} # QQ音乐
PROCESS-NAME,com.tencent.qqmusicpad,{{ rule }} # QQ音乐HD
PROCESS-NAME,com.tencent.qqpim,{{ rule }} # QQ同步助手
PROCESS-NAME,com.tencent.qqpimsecure,{{ rule }} # 腾讯手机管家
PROCESS-NAME,com.tencent.qqpinyin,{{ rule }} # QQ输入法
PROCESS-NAME,com.tencent.qqsports,{{ rule }} # 腾讯体育
PROCESS-NAME,com.tencent.qt.qtl,{{ rule }} # 掌上英雄联盟
PROCESS-NAME,com.tencent.token,{{ rule }} # QQ安全中心
PROCESS-NAME,com.tencent.ttpic,{{ rule }} # 天天P图
PROCESS-NAME,com.tencent.weishi,{{ rule }} # 腾讯微视
PROCESS-NAME,com.tencent.zebra,{{ rule }} # 水印相机
PROCESS-NAME,com.tgry.j7yr.rqtko,{{ rule }} # 壁纸素材库-壁纸
PROCESS-NAME,com.themewallpaper.douping,{{ rule }} # 主题动态壁纸
PROCESS-NAME,com.theotino.chinadaily,{{ rule }} # China Daily
PROCESS-NAME,com.theotino.sztv,{{ rule }} # 无线苏州
PROCESS-NAME,com.thestore.main,{{ rule }} # 1号会员店
PROCESS-NAME,com.thinkyeah.galleryvault,{{ rule }} # 照片保险箱
PROCESS-NAME,com.tianxingjian.screenshot,{{ rule }} # 超级截图录屏大师
PROCESS-NAME,com.tieyou.train.ark,{{ rule }} # 铁友火车票
PROCESS-NAME,com.ting.mp3.android,{{ rule }} # 千千音乐
PROCESS-NAME,com.tiqiaa.icontrol,{{ rule }} # 遥控精灵
PROCESS-NAME,com.tmall.wireless,{{ rule }} # 天猫
PROCESS-NAME,com.tom.ule.ui,{{ rule }} # 邮乐
PROCESS-NAME,com.tongcheng.android,{{ rule }} # 同程旅行
PROCESS-NAME,com.topgether.sixfoot,{{ rule }} # 六只脚
PROCESS-NAME,com.towords,{{ rule }} # 拓词
PROCESS-NAME,com.traffic.handtrafficbible,{{ rule }} # 四川电信
PROCESS-NAME,com.trantor.genesis,{{ rule }} # 维迈通多多
PROCESS-NAME,com.tripadvisor.tripadvisor.daodao,{{ rule }} # Tripadvisor猫途鹰
PROCESS-NAME,com.truckhome.bbs,{{ rule }} # 卡车之家
PROCESS-NAME,com.tsf.shell.widget.message,{{ rule }} # TSF 信息小部件
PROCESS-NAME,com.tudou.android,{{ rule }} # 土豆
PROCESS-NAME,com.tujia.hotel,{{ rule }} # 途家民宿
PROCESS-NAME,com.tuniu.app.ui,{{ rule }} # 途牛旅游
PROCESS-NAME,com.tuoniu.pingmuezuo,{{ rule }} # 屏幕恶作剧
PROCESS-NAME,com.tuyang.global.trans,{{ rule }} # 全局透明壁纸
PROCESS-NAME,com.tvunetworks.android.anywhere,{{ rule }} # TVU Anywhere
PROCESS-NAME,com.twentyfirstcbh.epaper,{{ rule }} # 21财经
PROCESS-NAME,com.tydic.app.hh,{{ rule }} # 海航信息
PROCESS-NAME,com.ucar.app,{{ rule }} # 淘车车
PROCESS-NAME,com.UCMobile,{{ rule }} # UC浏览器
PROCESS-NAME,com.ucmobile.lite,{{ rule }} # UC浏览器极速版
PROCESS-NAME,com.umaman.laiyifen,{{ rule }} # 来伊份社区购
PROCESS-NAME,com.ume.browser,{{ rule }} # 微米浏览器
PROCESS-NAME,com.umetrip.android.msky.app,{{ rule }} # 航旅纵横
PROCESS-NAME,com.unicom.gudong.client,{{ rule }} # 蓝信
PROCESS-NAME,com.unicom.wopay,{{ rule }} # 沃钱包
PROCESS-NAME,com.unicom.zworeader.ui,{{ rule }} # 联通爱听
PROCESS-NAME,com.unionpay,{{ rule }} # 云闪付
PROCESS-NAME,com.unionpay.chsp,{{ rule }} # 银联钱包
PROCESS-NAME,com.ushaqi.zhuishushenqi,{{ rule }} # 追书神器
PROCESS-NAME,com.ushaqi.zhuishushenqi.adfree,{{ rule }} # 追书神器免费版
PROCESS-NAME,com.uu,{{ rule }} # UU电话-UU网络电话
PROCESS-NAME,com.versa,{{ rule }} # 马卡龙玩图
PROCESS-NAME,com.video.link.heart,{{ rule }} # 心心相印
PROCESS-NAME,com.videogo,{{ rule }} # 萤石云视频
PROCESS-NAME,com.voibook.voicebook,{{ rule }} # 音书
PROCESS-NAME,com.wa.wallpaperon,{{ rule }} # 手机主题多多
PROCESS-NAME,com.wacai365,{{ rule }} # 挖财记账
PROCESS-NAME,com.wallstreetcn.news,{{ rule }} # 华尔街见闻
PROCESS-NAME,com.wandafilm.app,{{ rule }} # 万达电影
PROCESS-NAME,com.wander.android.wallpaper,{{ rule }} # 元气壁纸
PROCESS-NAME,com.wangdou.prettygirls.dress,{{ rule }} # 装扮次元手帐
PROCESS-NAME,com.wangyin.payment,{{ rule }} # 京东钱包
PROCESS-NAME,com.waterfall.metronome,{{ rule }} # 节拍器
PROCESS-NAME,com.welove520.welove,{{ rule }} # 微爱
PROCESS-NAME,com.wenhua.bamboo,{{ rule }} # 随身行
PROCESS-NAME,com.wenhui.ebook,{{ rule }} # 文汇
PROCESS-NAME,com.when.coco,{{ rule }} # 365日历
PROCESS-NAME,com.whizen.iptv.activity,{{ rule }} # 万视达
PROCESS-NAME,com.wlstock.fund,{{ rule }} # 持股帮
PROCESS-NAME,com.wole56.ishow,{{ rule }} # 我秀
PROCESS-NAME,com.womai,{{ rule }} # 中粮我买网
PROCESS-NAME,com.wondertek.paper,{{ rule }} # 澎湃新闻
PROCESS-NAME,com.wuba,{{ rule }} # 58同城
PROCESS-NAME,com.wuba.zhuanzhuan,{{ rule }} # 转转
PROCESS-NAME,com.xcar.activity,{{ rule }} # 爱卡汽车
PROCESS-NAME,com.xdf.recite,{{ rule }} # 新东方乐词
PROCESS-NAME,com.xdtech.news.greatriver,{{ rule }} # 江西新闻
PROCESS-NAME,com.xfplay.play,{{ rule }} # 影音先锋
PROCESS-NAME,com.xhey.xcamera,{{ rule }} # 今日水印相机
PROCESS-NAME,com.xiachufang,{{ rule }} # 下厨房
PROCESS-NAME,com.xiaobanlong.main,{{ rule }} # 小伴龙
PROCESS-NAME,com.xiaoenai.app,{{ rule }} # 小恩爱
PROCESS-NAME,com.xiaomi.gamecenter.sdk.service,{{ rule }} # 游戏服务
PROCESS-NAME,com.xiaomi.router,{{ rule }} # 小米WiFi
PROCESS-NAME,com.xiaomi.shop,{{ rule }} # 小米商城
PROCESS-NAME,com.ximalaya.ting.android,{{ rule }} # 喜马拉雅
PROCESS-NAME,com.xingin.xhs,{{ rule }} # 小红书
PROCESS-NAME,com.xingluo.mpa,{{ rule }} # 魔力相册
PROCESS-NAME,com.xingzhicheng2024.bizhi,{{ rule }} # 超高清壁纸
PROCESS-NAME,com.xinhang.mobileclient,{{ rule }} # 中国移动河南
PROCESS-NAME,com.xinli.fm,{{ rule }} # 心理Fm
PROCESS-NAME,com.xinshuru.inputmethod,{{ rule }} # 手心输入法
PROCESS-NAME,com.xinyu210.enchdictionary,{{ rule }} # 英汉词典
PROCESS-NAME,com.xnbzxbk,{{ rule }} # 仙女壁纸
PROCESS-NAME,com.xs.fm,{{ rule }} # 番茄畅听
PROCESS-NAME,com.xt.retouch,{{ rule }} # 醒图
PROCESS-NAME,com.xtuone.android.syllabus,{{ rule }} # 超级课程表
PROCESS-NAME,com.xuanyou2022.bizhi,{{ rule }} # 手机壁纸
PROCESS-NAME,com.xueqiu.android,{{ rule }} # 雪球
PROCESS-NAME,com.xuexiang.myring,{{ rule }} # 炫铃声
PROCESS-NAME,com.xunlei.browser,{{ rule }} # 迅雷浏览器
PROCESS-NAME,com.xunlei.downloadprovider,{{ rule }} # 迅雷
PROCESS-NAME,com.xunruifairy.wallpaper,{{ rule }} # 壁纸精灵
PROCESS-NAME,com.xvideostudio.videoeditor,{{ rule }} # 乐秀视频剪辑视频编辑
PROCESS-NAME,com.xyhui,{{ rule }} # PU口袋校园
PROCESS-NAME,com.ybws.ucast,{{ rule }} # Ucast
PROCESS-NAME,com.ydtx.camera,{{ rule }} # 元道经纬相机
PROCESS-NAME,com.yeahka.mach.android.openpos,{{ rule }} # 乐刷商务版
PROCESS-NAME,com.yek.android.game5173,{{ rule }} # 5173
PROCESS-NAME,com.yek.android.kfc.activitys,{{ rule }} # 肯德基
PROCESS-NAME,com.yek.android.uniqlo,{{ rule }} # 优衣库
PROCESS-NAME,com.ygkj.chelaile.standard,{{ rule }} # 车来了
PROCESS-NAME,com.yibasan.lizhifm,{{ rule }} # 荔枝
PROCESS-NAME,com.yicai.news,{{ rule }} # 第一财经
PROCESS-NAME,com.yiche.autoeasy,{{ rule }} # 易车
PROCESS-NAME,com.yiche.price,{{ rule }} # 易车汽车报价
PROCESS-NAME,com.yidian.xiaomi,{{ rule }} # 一点新闻资讯
PROCESS-NAME,com.yigequanquanqq.app,{{ rule }} # 一个圈圈
PROCESS-NAME,com.yinliang.simple_desktop,{{ rule }} # 超极简桌面
PROCESS-NAME,com.yipiao,{{ rule }} # 智行火车票
PROCESS-NAME,com.yiruike.sodacn.android,{{ rule }} # 甜盐相机
PROCESS-NAME,com.yitong.mbank,{{ rule }} # 江苏·农商行
PROCESS-NAME,com.yiwugou.yiwukan,{{ rule }} # 义乌购
PROCESS-NAME,com.yixia.videoeditor,{{ rule }} # 秒拍
PROCESS-NAME,com.ylmf.androidclient,{{ rule }} # 115生活
PROCESS-NAME,com.ymatou.seller,{{ rule }} # 洋码头扫货神器买手版
PROCESS-NAME,com.ymatou.shop,{{ rule }} # 洋码头
PROCESS-NAME,com.yoho,{{ rule }} # YOHO有货
PROCESS-NAME,com.yoloho.dayima,{{ rule }} # 大姨妈
PROCESS-NAME,com.yoosee,{{ rule }} # 有看头
PROCESS-NAME,com.youba.barcode,{{ rule }} # 二维码扫描
PROCESS-NAME,com.youdao.dict,{{ rule }} # 网易有道词典
PROCESS-NAME,com.youdao.note,{{ rule }} # 有道云笔记
PROCESS-NAME,com.yougou,{{ rule }} # 优购时尚商城
PROCESS-NAME,com.youku.crazytogether,{{ rule }} # 来疯
PROCESS-NAME,com.youku.phone,{{ rule }} # 优酷视频
PROCESS-NAME,com.youloft.calendar,{{ rule }} # 万年历
PROCESS-NAME,com.yuanli.wallpapermaster,{{ rule }} # 手机壁纸大师
PROCESS-NAME,com.yuanlue.chongwu,{{ rule }} # 互动桌面宠物
PROCESS-NAME,com.yuedong.browser,{{ rule }} # 悦动浏览器
PROCESS-NAME,com.yuexiang.wallpaper,{{ rule }} # 悦享动态壁纸
PROCESS-NAME,com.yumei.game.engine.ui.client,{{ rule }} # 玩股成金
PROCESS-NAME,com.yunlan.unlock.dewdropunlock,{{ rule }} # 3D水滴-随变锁屏
PROCESS-NAME,com.yunlian.wewe,{{ rule }} # 微微电话
PROCESS-NAME,com.ywallpaper.ddztbz,{{ rule }} # 多多主题壁纸
PROCESS-NAME,com.yx,{{ rule }} # 有信
PROCESS-NAME,com.yy.android.udbsec,{{ rule }} # YY安全中心
PROCESS-NAME,com.yyyfs.wallpaper,{{ rule }} # 元宇宙壁纸
PROCESS-NAME,com.zbx.ct.tvzhibo,{{ rule }} # 手机电视高清直播
PROCESS-NAME,com.zd.meta,{{ rule }} # 元气桌面宠物
PROCESS-NAME,com.zerone.hidesktop,{{ rule }} # 我的桌面iScreen
PROCESS-NAME,com.zhangdan.app,{{ rule }} # 51信用卡管家
PROCESS-NAME,com.zhanlang.dailyscreen,{{ rule }} # 天天录屏
PROCESS-NAME,com.zhaopin.social,{{ rule }} # 智联招聘
PROCESS-NAME,com.zhenai.android,{{ rule }} # 珍爱
PROCESS-NAME,com.zhianxiaoyuan.app,{{ rule }} # 智安校园
PROCESS-NAME,com.zhihu.android,{{ rule }} # 知乎
PROCESS-NAME,com.zhihu.daily.android,{{ rule }} # 知乎日报
PROCESS-NAME,com.zhubajie.client,{{ rule }} # 猪八戒
PROCESS-NAME,com.ziipin.softkeyboard,{{ rule }} # Badam维语输入法
PROCESS-NAME,com.ziipin.softkeyboard.kazakh,{{ rule }} # Kazakhsha Kirgizwshi
PROCESS-NAME,com.zol.android,{{ rule }} # 中关村在线
PROCESS-NAME,com.zongheng.reader,{{ rule }} # 纵横小说
PROCESS-NAME,com.zsyj.trans,{{ rule }} # 全局透明壁纸
PROCESS-NAME,com.zsyj.wallpaper,{{ rule }} # 熊猫动态壁纸
PROCESS-NAME,com.zydsoft.acuherb,{{ rule }} # 中医辨证云
PROCESS-NAME,com.zzu.sxm.chemical,{{ rule }} # 化学方程式
PROCESS-NAME,ctrip.android.view,{{ rule }} # 携程旅行
PROCESS-NAME,cuuca.sendfiles.Activity,{{ rule }} # 汇分享
PROCESS-NAME,dongzheng.szkingdom.android.phone,{{ rule }} # 掌证宝
PROCESS-NAME,droom.sleepIfUCan,{{ rule }} # 使命闹钟Alarmy
PROCESS-NAME,dttp.com.tupian.djg,{{ rule }} # 动态壁纸
PROCESS-NAME,epson.print,{{ rule }} # Epson iPrint
PROCESS-NAME,flipboard.cn,{{ rule }} # 红板报
PROCESS-NAME,fm.qingting.qtradio,{{ rule }} # 蜻蜓FM
PROCESS-NAME,hbyc.china.medical.view,{{ rule }} # 壹生
PROCESS-NAME,howbuy.android.palmfund,{{ rule }} # 好买基金
PROCESS-NAME,howbuy.android.piggy,{{ rule }} # 储蓄罐
PROCESS-NAME,im.weshine.keyboard,{{ rule }} # KK键盘
PROCESS-NAME,im.yixin,{{ rule }} # 易信
PROCESS-NAME,insigma.waybook.jinan,{{ rule }} # 369出行
PROCESS-NAME,io.iftech.android.box,{{ rule }} # 小组件盒子
PROCESS-NAME,io.wallpaperengine.weclient,{{ rule }} # 壁纸引擎
PROCESS-NAME,jp.ne.neko.freewing.JapaneseKeyboard,{{ rule }} # 简易的日语输入 日文输入法 五十音图 虚拟键盘方式
PROCESS-NAME,jp.ne.neko.freewing.OpenWnn136Plus,{{ rule }} # 日文輸入法 OpenWnn136加强版
PROCESS-NAME,jp.ne.neko.freewing.PinYinImePlus,{{ rule }} # 中文拼音输入法 加强版
PROCESS-NAME,jyeoo.app.ystudy,{{ rule }} # 菁优网
PROCESS-NAME,lf.example.wubi,{{ rule }} # 五笔反查
PROCESS-NAME,lhypg.bnq.zbnh,{{ rule }} # 包子漫画
PROCESS-NAME,long.xian.wallpaper,{{ rule }} # 免费主题商店
PROCESS-NAME,longbin.helloworld,{{ rule }} # 计算管家
PROCESS-NAME,mark.via,{{ rule }} # Via
PROCESS-NAME,me.chunyu.ChunyuDoctor,{{ rule }} # 春雨医生
PROCESS-NAME,me.iweek.rili,{{ rule }} # 生活日历
PROCESS-NAME,me.yidui,{{ rule }} # 伊对
PROCESS-NAME,music.f2bcutter.mp3editor,{{ rule }} # 音乐音频剪辑
PROCESS-NAME,my.beautyCamera,{{ rule }} # 美人相机
PROCESS-NAME,my.PCamera,{{ rule }} # POCO相机
PROCESS-NAME,net.ask123.mima96,{{ rule }} # 密码酷
PROCESS-NAME,net.bontec.wxqd.activity,{{ rule }} # 爱青岛
PROCESS-NAME,net.cmoaciopm.sgsdict,{{ rule }} # 三国杀大典
PROCESS-NAME,net.hua.hua.a3dlivewallpaper,{{ rule }} # 4D动态壁纸
PROCESS-NAME,net.joydao.radio,{{ rule }} # 听听广播
PROCESS-NAME,net.kdnet.club,{{ rule }} # 凯迪网
PROCESS-NAME,net.pchome.kds,{{ rule }} # kds宽带山
PROCESS-NAME,net.qihoo.launcher.widget.clockweather,{{ rule }} # 360天气
PROCESS-NAME,net.xinhuamm.mainclient,{{ rule }} # 新华社
PROCESS-NAME,net.yyasp.clothing,{{ rule }} # 虚拟试衣间
PROCESS-NAME,net.zdsoft.zerobook_android,{{ rule }} # 智人播客
PROCESS-NAME,ning.zuo.diyzhuti,{{ rule }} # DIY主题组件库
PROCESS-NAME,oms.mmc.app.almanac_inland,{{ rule }} # 老黄历万年历顺历
PROCESS-NAME,oms.mmc.fortunetelling,{{ rule }} # 灵机
PROCESS-NAME,one.hh.oneclient,{{ rule }} # 一个
PROCESS-NAME,org.fungo.fungolive,{{ rule }} # 天天电视直播
PROCESS-NAME,org.mozilla.fennec_mylinux,{{ rule }} # 蚂蚁浏览器
PROCESS-NAME,org.sojex.finance,{{ rule }} # 口袋贵金属
PROCESS-NAME,org.sunapp.wenote,{{ rule }} # 微鹏
PROCESS-NAME,org.thinkinbunny.autoanswer,{{ rule }} # 自动应答
PROCESS-NAME,org.zywx.wbpalmstar.widgetone.uex10075364,{{ rule }} # 经管之家
PROCESS-NAME,org.zywx.wbpalmstar.widgetone.uexaaagg10013,{{ rule }} # 关爱守护
PROCESS-NAME,paint.by.number.pixel.art.coloring.drawing.puzzle,{{ rule }} # 乐涂数字填色
PROCESS-NAME,pet.desktop.elf,{{ rule }} # 图图宠物
PROCESS-NAME,photo.editor.polarr,{{ rule }} # 泼辣修图
PROCESS-NAME,pinkdiary.xiaoxiaotu.com,{{ rule }} # 粉粉日记
PROCESS-NAME,predictor.ui,{{ rule }} # 灵占算命八字星座
PROCESS-NAME,qianlong.qlmobile,{{ rule }} # 钱龙
PROCESS-NAME,ru.zdevs.zarchiver,{{ rule }} # ZArchiver解压缩工具
PROCESS-NAME,sina.mobile.tianqitong,{{ rule }} # 天气通
PROCESS-NAME,sl.mySms,{{ rule }} # Q信
PROCESS-NAME,smskb.com,{{ rule }} # 盛名时刻表
PROCESS-NAME,sogou.mobile.explorer,{{ rule }} # 搜狗浏览器极速版
PROCESS-NAME,sr.daiv.alls.ko,{{ rule }} # 基础韩语口语
PROCESS-NAME,ssdk.xkbz.gzgy,{{ rule }} # 星空壁纸
PROCESS-NAME,tool.music.ringtonemaker,{{ rule }} # 铃声制作MP3编辑器
PROCESS-NAME,ts.NetTraffic,{{ rule }} # 网速流量监测
PROCESS-NAME,tt.lt.tt,{{ rule }} # 聊天漂流瓶
PROCESS-NAME,tv.acfundanmaku.video,{{ rule }} # AcFun
PROCESS-NAME,tv.danmaku.bili,{{ rule }} # 哔哩哔哩
PROCESS-NAME,tv.pps.mobile,{{ rule }} # 爱奇艺随刻
PROCESS-NAME,us.pinguo.april_collage,{{ rule }} # 拼图酱
PROCESS-NAME,vStudio.Android.Camera360,{{ rule }} # 相机360
PROCESS-NAME,vz.com,{{ rule }} # 飞常准
PROCESS-NAME,wind.deposit,{{ rule }} # 万得基金
PROCESS-NAME,windinfo.android,{{ rule }} # Wind金融终端
PROCESS-NAME,ysykzheng.hotlauncher,{{ rule }} # 热门启动器
PROCESS-NAME,yyc.xk,{{ rule }} # 星空视频壁纸
PROCESS-NAME,zuo.sai.che,{{ rule }} # 全民跑车
{% endmacro %}