{% macro main(rule) %}
PROCESS-NAME,ACloud.MindMap,{{ rule }} # 3A思维导图
PROCESS-NAME,air.com.A3aapp.fyp,{{ rule }} # 法语入门基础
PROCESS-NAME,air.com.bbfriend.ddsz,{{ rule }} # 哆哆识字
PROCESS-NAME,air.com.gongfubb.wksz,{{ rule }} # 悟空识字
PROCESS-NAME,air.common.android.A123qibu.com,{{ rule }} # 熊猫识字
PROCESS-NAME,air.tv.douyu.android,{{ rule }} # 斗鱼
PROCESS-NAME,all.parttimeguidesystem,{{ rule }} # 兼职猫-同城找工作求职招聘平台
PROCESS-NAME,android.translate.xuedianba,{{ rule }} # 同声翻译超级版
PROCESS-NAME,android.zhibo8,{{ rule }} # 直播吧
PROCESS-NAME,az.studio.gaokaowidget,{{ rule }} # 新高考倒计时
PROCESS-NAME,az.studio.gkztc,{{ rule }} # 高考直通车
PROCESS-NAME,battymole.trainticket,{{ rule }} # 买火车票
PROCESS-NAME,bj.wanquan.hanfeislidecompact,{{ rule }} # 汉飞滑动输入法大屏手机版
PROCESS-NAME,bubei.tingshu,{{ rule }} # 懒人听书
PROCESS-NAME,c39dotcn.creader,{{ rule }} # 图创建筑规范
PROCESS-NAME,cld.navi.mainframe,{{ rule }} # 凯立德导航
PROCESS-NAME,cmccwm.mobilemusic,{{ rule }} # 咪咕音乐
PROCESS-NAME,cn.amazon.mShop.android,{{ rule }} # 亚马逊购物
PROCESS-NAME,cn.banshenggua.aichang,{{ rule }} # 爱唱
PROCESS-NAME,cn.bdqn.pictureview,{{ rule }} # 手机图库
PROCESS-NAME,cn.beekee.zhongtong,{{ rule }} # 中通快递
PROCESS-NAME,cn.bluecrane.album,{{ rule }} # 相册管家
PROCESS-NAME,cn.bluecrane.calendar,{{ rule }} # 万年历黄历
PROCESS-NAME,cn.buding.martin,{{ rule }} # 微车
PROCESS-NAME,cn.cityhouse.fytpersonal,{{ rule }} # 房产管家
PROCESS-NAME,cn.cj.pe,{{ rule }} # 139邮箱
PROCESS-NAME,cn.cntv,{{ rule }} # 央视影音
PROCESS-NAME,cn.cntvhd,{{ rule }} # 央视影音HD
PROCESS-NAME,cn.cntvnews,{{ rule }} # 央视新闻
PROCESS-NAME,cn.colorv,{{ rule }} # 彩视
PROCESS-NAME,cn.com.gjzq.yjb.kh,{{ rule }} # 佣金宝开户
PROCESS-NAME,cn.com.hkgt.gasapp,{{ rule }} # 易捷加油
PROCESS-NAME,cn.com.igimu.qianyi,{{ rule }} # 千亿词霸俄语词典
PROCESS-NAME,cn.com.larry.compass,{{ rule }} # 精准罗盘
PROCESS-NAME,cn.com.modernmedia.businessweek,{{ rule }} # iBloomberg i商周
PROCESS-NAME,cn.com.modernmedia.modernlady,{{ rule }} # InStyle iLady
PROCESS-NAME,cn.com.nbd.nbdmobile,{{ rule }} # 每日经济新闻
PROCESS-NAME,cn.com.open.mooc,{{ rule }} # 慕课网
PROCESS-NAME,cn.com.pcauto.android.browser,{{ rule }} # 太平洋汽车
PROCESS-NAME,cn.com.pcgroup.magazine,{{ rule }} # PChouse太平洋家居
PROCESS-NAME,cn.com.pconline.android.browser,{{ rule }} # 太平洋科技
PROCESS-NAME,cn.com.shbank.mper,{{ rule }} # 上海银行
PROCESS-NAME,cn.com.sina.finance,{{ rule }} # 新浪财经
PROCESS-NAME,cn.com.sina.sports,{{ rule }} # 新浪体育
PROCESS-NAME,cn.com.spdb.mobilebank.per,{{ rule }} # 浦发银行
PROCESS-NAME,cn.com.taximeter,{{ rule }} # 出租车计价器
PROCESS-NAME,cn.dahebao,{{ rule }} # 顶端新闻
PROCESS-NAME,cn.damai,{{ rule }} # 大麦
PROCESS-NAME,cn.dict.android.pro,{{ rule }} # 海词词典
PROCESS-NAME,cn.dictcn.android.digitize.sw_gjcydcd_10011,{{ rule }} # 成语大词典
PROCESS-NAME,cn.dictcn.android.digitize.wys_japan,{{ rule }} # 外研社大家的日语
PROCESS-NAME,cn.dictcn.android.digitize.wys_korean,{{ rule }} # 外研社韩语
PROCESS-NAME,cn.dictcn.android.digitize.wys_modern_german,{{ rule }} # 外研社德语
PROCESS-NAME,cn.dictcn.android.digitize.wys_modern_russian,{{ rule }} # 外研社俄语
PROCESS-NAME,cn.dictcn.android.digitize.wys_spain,{{ rule }} # 外研社西班牙语
PROCESS-NAME,cn.dxy.android.aspirin,{{ rule }} # 丁香医生
PROCESS-NAME,cn.dxy.idxyer,{{ rule }} # 丁香园
PROCESS-NAME,cn.dxy.inderal,{{ rule }} # 丁香医考
PROCESS-NAME,cn.dxy.medicinehelper,{{ rule }} # 用药助手
PROCESS-NAME,cn.eclicks.drivingtest,{{ rule }} # 车轮驾考通
PROCESS-NAME,cn.eclicks.wzsearch,{{ rule }} # 车轮
PROCESS-NAME,cn.ecook,{{ rule }} # 网上厨房
PROCESS-NAME,cn.edaijia.android.client,{{ rule }} # e代驾
PROCESS-NAME,cn.edu.zjicm.wordsnet_d,{{ rule }} # 知米背单词
PROCESS-NAME,cn.emagsoftware.gamehall,{{ rule }} # 咪咕快游
PROCESS-NAME,cn.emoney.level2,{{ rule }} # 益盟操盘手经典版
PROCESS-NAME,cn.etouch.ecalendar,{{ rule }} # 中华万年历
PROCESS-NAME,cn.etouch.ecalendar.longshi,{{ rule }} # 微鲤天气
PROCESS-NAME,cn.gogocity.suibian,{{ rule }} # 随便走
PROCESS-NAME,cn.ibabyzone.music,{{ rule }} # 胎教盒子
PROCESS-NAME,cn.ishansong,{{ rule }} # 闪送
PROCESS-NAME,cn.jingling.motu.photowonder,{{ rule }} # 魔图精灵
PROCESS-NAME,cn.jsb.china,{{ rule }} # 江苏银行
PROCESS-NAME,cn.kaoshi100.view,{{ rule }} # 考试100
PROCESS-NAME,cn.kidyn.qdmedical160,{{ rule }} # 健康160
PROCESS-NAME,cn.kuwo.kwmusichd,{{ rule }} # 酷我音乐HD
PROCESS-NAME,cn.kuwo.player,{{ rule }} # 酷我音乐
PROCESS-NAME,cn.kuwo.tingshu,{{ rule }} # 酷我畅听
PROCESS-NAME,cn.ledongli.ldl,{{ rule }} # 乐动力
PROCESS-NAME,cn.longmaster.pengpeng,{{ rule }} # 语玩
PROCESS-NAME,cn.mama.activity,{{ rule }} # 妈妈网轻聊
PROCESS-NAME,cn.mama.pregnant,{{ rule }} # 妈妈网孕育
PROCESS-NAME,cn.mchina.mbrowser,{{ rule }} # 移联浏览器
PROCESS-NAME,cn.medlive.android,{{ rule }} # 医脉通
PROCESS-NAME,cn.medlive.guideline.android,{{ rule }} # 临床指南
PROCESS-NAME,cn.mopon.film.xflh,{{ rule }} # 幸福看
PROCESS-NAME,cn.mucang.drunkremind.android,{{ rule }} # 小猪二手车
PROCESS-NAME,cn.myhug.baobao,{{ rule }} # 抱抱直播
PROCESS-NAME,cn.opda.a.phonoalbumshoushou,{{ rule }} # 百度手机卫士
PROCESS-NAME,cn.samsclub.app,{{ rule }} # 山姆会员商店
PROCESS-NAME,cn.shuangshuangfei,{{ rule }} # 找对象
PROCESS-NAME,cn.tianya.light,{{ rule }} # 天涯社区
PROCESS-NAME,cn.wiz.note,{{ rule }} # 为知笔记
PROCESS-NAME,cn.wps.moffice_eng,{{ rule }} # WPS Office
PROCESS-NAME,cn.zhimawu,{{ rule }} # 河狸家
PROCESS-NAME,cn.zymk.comic,{{ rule }} # 知音漫客
PROCESS-NAME,co.jp.realsys.pinyin,{{ rule }} # 我爱拼音
PROCESS-NAME,co.runner.app,{{ rule }} # 悦跑圈
PROCESS-NAME,com.achievo.vipshop,{{ rule }} # 唯品会
PROCESS-NAME,com.actionsmicro.ezcast,{{ rule }} # EZCast
PROCESS-NAME,com.ada.desks,{{ rule }} # 安卓桌面
PROCESS-NAME,com.advasoft.touchretouch,{{ rule }} # TouchRetouch
PROCESS-NAME,com.afar.machinedesignhandbook,{{ rule }} # 机械设计手册
PROCESS-NAME,com.agoda.mobile.consumer,{{ rule }} # Agoda安可达
PROCESS-NAME,com.air.sz,{{ rule }} # 深圳航空
PROCESS-NAME,com.airbnb.android,{{ rule }} # 爱彼迎
PROCESS-NAME,com.alensw.PhoneArea,{{ rule }} # QC 归属地
PROCESS-NAME,com.alex.e,{{ rule }} # 绍兴E网
PROCESS-NAME,com.alibaba.icbu.app.aliexpress.seller,{{ rule }} # 速卖通卖家
PROCESS-NAME,com.alibaba.icbu.app.seller,{{ rule }} # 阿里卖家
PROCESS-NAME,com.alibaba.intl.android.apps.poseidon,{{ rule }} # Alibaba.com
PROCESS-NAME,com.alibaba.wireless,{{ rule }} # 阿里巴巴
PROCESS-NAME,com.alimama.moon,{{ rule }} # 淘宝联盟
PROCESS-NAME,com.alipay.m.portal,{{ rule }} # 阿里本地通
PROCESS-NAME,com.android.app.quanmama,{{ rule }} # 券妈妈优惠券
PROCESS-NAME,com.android.bankabc,{{ rule }} # 中国农业银行
PROCESS-NAME,com.android.clock.sd,{{ rule }} # 山东农信
PROCESS-NAME,com.android.dazhihui,{{ rule }} # 大智慧
PROCESS-NAME,com.android.tiancity.mobilesecurity,{{ rule }} # 天成账号管家
PROCESS-NAME,com.android36kr.app,{{ rule }} # 36氪
PROCESS-NAME,com.Android56,{{ rule }} # 56视频
PROCESS-NAME,com.androidesk,{{ rule }} # 安卓壁纸
PROCESS-NAME,com.androidesk.livewallpaper,{{ rule }} # 安卓动态壁纸
PROCESS-NAME,com.anjuke.android.app,{{ rule }} # 安居客
PROCESS-NAME,com.anjuke.android.newbroker,{{ rule }} # 移动经纪人
PROCESS-NAME,com.antutu.ABenchMark,{{ rule }} # 安兔兔评测
PROCESS-NAME,com.app.hero.ui,{{ rule }} # K歌达人
PROCESS-NAME,com.apprush.game.chinesechar,{{ rule }} # 汉语字典
PROCESS-NAME,com.appshare.android.ilisten,{{ rule }} # 口袋故事
PROCESS-NAME,com.appshare.android.ilisten.hd,{{ rule }} # 口袋故事HD
PROCESS-NAME,com.appsino.bingluo.fycz,{{ rule }} # 移动公证
PROCESS-NAME,com.Apricotforest_epocket,{{ rule }} # 医口袋
PROCESS-NAME,com.apricotforest.dossier,{{ rule }} # 病历夹经典版
PROCESS-NAME,com.arivoc.kouyu,{{ rule }} # 口语100
PROCESS-NAME,com.ataaw.tianyi,{{ rule }} # 天翼生活
PROCESS-NAME,com.autohome.usedcar,{{ rule }} # 二手车之家
PROCESS-NAME,com.autonavi.minimap,{{ rule }} # 高德地图
PROCESS-NAME,com.Autoyol.auto,{{ rule }} # 凹凸租车
PROCESS-NAME,com.ayibang.ayb,{{ rule }} # 阿姨帮
PROCESS-NAME,com.babytree.apps.lama,{{ rule }} # 宝宝树小时光
PROCESS-NAME,com.babytree.apps.pregnancy,{{ rule }} # 宝宝树孕育
PROCESS-NAME,com.bai.doctorpda,{{ rule }} # 掌上医讯
PROCESS-NAME,com.baidu.BaiduMap,{{ rule }} # 百度地图
PROCESS-NAME,com.baidu.baidutranslate,{{ rule }} # 百度翻译
PROCESS-NAME,com.baidu.browser.apps,{{ rule }} # 百度浏览器
PROCESS-NAME,com.baidu.fengchao.ui,{{ rule }} # 百度营销
PROCESS-NAME,com.baidu.hi,{{ rule }} # 如流
PROCESS-NAME,com.baidu.homework,{{ rule }} # 作业帮
PROCESS-NAME,com.baidu.iknow,{{ rule }} # 百度知道
PROCESS-NAME,com.baidu.input,{{ rule }} # 百度输入法
PROCESS-NAME,com.baidu.input_mi,{{ rule }} # 百度输入法小米版
PROCESS-NAME,com.baidu.lbs.crowdapp,{{ rule }} # 地图淘金
PROCESS-NAME,com.baidu.netdisk,{{ rule }} # 百度网盘
PROCESS-NAME,com.baidu.news,{{ rule }} # 百度新闻
PROCESS-NAME,com.baidu.searchbox,{{ rule }} # 百度
PROCESS-NAME,com.baidu.tieba,{{ rule }} # 百度贴吧
PROCESS-NAME,com.baidu.video,{{ rule }} # 百搜视频
PROCESS-NAME,com.baidu.video.pad,{{ rule }} # 百搜视频HD
PROCESS-NAME,com.baidu.wenku,{{ rule }} # 百度文库
PROCESS-NAME,com.baidu.yuedu,{{ rule }} # 百度阅读
PROCESS-NAME,com.baihe,{{ rule }} # 百合网
PROCESS-NAME,com.bamboo.ibike,{{ rule }} # 黑鸟单车
PROCESS-NAME,com.baoruan.wallpaper.lmaczcgcdjTJGknirRd,{{ rule }} # 绚丽水晶-桌面壁纸
PROCESS-NAME,com.bbbao.shop.client.android.activity,{{ rule }} # 比比宝
PROCESS-NAME,com.bdatu.geography,{{ rule }} # 每日精选
PROCESS-NAME,com.bench.yylc,{{ rule }} # 盈盈
PROCESS-NAME,com.besttone.exchange2,{{ rule }} # 总机服务
PROCESS-NAME,com.biligyar.izdax,{{ rule }} # izdax翻译
PROCESS-NAME,com.bjbyhd.voiceback,{{ rule }} # 保益悦听
PROCESS-NAME,com.bjcsxq.chat.carfriend,{{ rule }} # 学车不
PROCESS-NAME,com.boohee.one,{{ rule }} # 薄荷健康
PROCESS-NAME,com.booking,{{ rule }} # Booking.com缤客
PROCESS-NAME,com.bozhong.crazy,{{ rule }} # 疯狂造人-播种网备孕怀孕
PROCESS-NAME,com.brains.byzmnew,{{ rule }} # 益智脑筋急转弯大全
PROCESS-NAME,com.browser2345,{{ rule }} # 2345浏览器
PROCESS-NAME,com.budejie.www,{{ rule }} # 百思漂流瓶
PROCESS-NAME,com.buick,{{ rule }} # iBuick
PROCESS-NAME,com.buloo,{{ rule }} # 旅行者导航地图
PROCESS-NAME,com.businessvalue.android.app,{{ rule }} # 钛媒体
PROCESS-NAME,com.bw30.zsch,{{ rule }} # 四川航空
PROCESS-NAME,com.bycookie.schurter,{{ rule }} # 注意力训练
PROCESS-NAME,com.byd.aeri.caranywhere,{{ rule }} # 比亚迪
PROCESS-NAME,com.caijing,{{ rule }} # 财经杂志
PROCESS-NAME,com.caing.news,{{ rule }} # 财新
PROCESS-NAME,com.capelabs.leyou,{{ rule }} # 乐友
PROCESS-NAME,com.cbnweekly,{{ rule }} # 第一财经杂志
PROCESS-NAME,com.cdtv.app,{{ rule }} # 看度新闻
PROCESS-NAME,com.ceic.app,{{ rule }} # 地震速报
PROCESS-NAME,com.changba,{{ rule }} # 唱吧
PROCESS-NAME,com.changshuo.ui,{{ rule }} # 畅说108
PROCESS-NAME,com.chaozh.iReaderFree,{{ rule }} # 掌阅
PROCESS-NAME,com.chaozh.iReaderFree15,{{ rule }} # 油梨
PROCESS-NAME,com.chediandian.app,{{ rule }} # 车点点
PROCESS-NAME,com.chen.zhi.activity,{{ rule }} # C语言宝典
PROCESS-NAME,com.chenai.eyes,{{ rule }} # 夜间模式
PROCESS-NAME,com.china3s.android,{{ rule }} # 春秋航空
PROCESS-NAME,com.china3s.strip,{{ rule }} # 春秋旅游
PROCESS-NAME,com.chinaamc.MainActivityAMC,{{ rule }} # 华夏基金管家
PROCESS-NAME,com.chinaamc.mfbh.amcActivity,{{ rule }} # 华夏活期通
PROCESS-NAME,com.chinaideal.bkclient.tabmain,{{ rule }} # 你我嘉选
PROCESS-NAME,com.chinamobile.mcloud,{{ rule }} # 中国移动云盘
PROCESS-NAME,com.chinamworld.bocmbci,{{ rule }} # 中国银行
PROCESS-NAME,com.chinamworld.main,{{ rule }} # 中国建设银行
PROCESS-NAME,com.chinasoft.mall,{{ rule }} # 好享购物
PROCESS-NAME,com.chinatelecom.bestpayclient,{{ rule }} # 翼支付
PROCESS-NAME,com.chineseall.reader,{{ rule }} # 17K小说
PROCESS-NAME,com.chineseall.singlebook,{{ rule }} # 中文书城
PROCESS-NAME,com.ci123.pregnancywap,{{ rule }} # 妈妈社区
PROCESS-NAME,com.citywithincity.ecard,{{ rule }} # e通卡
PROCESS-NAME,com.cleanmaster.mguard_cn,{{ rule }} # 猎豹清理大师
PROCESS-NAME,com.cloudpower.netsale.activity,{{ rule }} # 中国人保
PROCESS-NAME,com.cmbchina.ccd.pluto.cmbActivity,{{ rule }} # 掌上生活
PROCESS-NAME,com.cnki.client,{{ rule }} # 手机知网
PROCESS-NAME,com.cns.mc.activity,{{ rule }} # 中国新闻网
PROCESS-NAME,com.codoon.gps,{{ rule }} # 咕咚
PROCESS-NAME,com.com1010jz,{{ rule }} # 1010兼职网
PROCESS-NAME,com.comit.gooddriver,{{ rule }} # 优驾
PROCESS-NAME,com.concur.breeze,{{ rule }} # SAP Concur
PROCESS-NAME,com.coomix.app.car,{{ rule }} # 汽车在线
PROCESS-NAME,com.cqmc.client,{{ rule }} # 中国移动重庆
PROCESS-NAME,com.cs090.android,{{ rule }} # 常熟零距离
PROCESS-NAME,com.csair.mbp,{{ rule }} # 南方航空
PROCESS-NAME,com.csii_qzbank,{{ rule }} # 泉州银行
PROCESS-NAME,com.css.bj.css,{{ rule }} # 爱课程
PROCESS-NAME,com.ct.client,{{ rule }} # 中国电信
PROCESS-NAME,com.cubic.autohome,{{ rule }} # 汽车之家
PROCESS-NAME,com.cubic.choosecar,{{ rule }} # 汽车报价
PROCESS-NAME,com.czbank.mbank,{{ rule }} # 浙商银行
PROCESS-NAME,com.dailyyoga.cn,{{ rule }} # 每日瑜伽
PROCESS-NAME,com.dangdang.buy2,{{ rule }} # 当当
PROCESS-NAME,com.dangdang.reader,{{ rule }} # 当当云阅读
PROCESS-NAME,com.danielstudio.app.wowtu,{{ rule }} # 煎蛋
PROCESS-NAME,com.ddcinemaapp,{{ rule }} # 大地影院
PROCESS-NAME,com.dealmoon.android,{{ rule }} # 北美省钱快报
PROCESS-NAME,com.devuni.flashlight,{{ rule }} # 超级手电筒
PROCESS-NAME,com.dewmobile.kuaiya,{{ rule }} # 快牙
PROCESS-NAME,com.deyi.client,{{ rule }} # 得意生活
PROCESS-NAME,com.dianping.v1,{{ rule }} # 大众点评
PROCESS-NAME,com.diershoubing.erbing,{{ rule }} # 二柄
PROCESS-NAME,com.digienginetek.rccsec,{{ rule }} # 汽车保姆
PROCESS-NAME,com.djbox.product,{{ rule }} # DJ音乐盒
PROCESS-NAME,com.doc360.client,{{ rule }} # 个人图书馆
PROCESS-NAME,com.docin.zlibrary.ui.android,{{ rule }} # 豆丁书房
PROCESS-NAME,com.dongqiudi.news,{{ rule }} # 懂球帝
PROCESS-NAME,com.douban.book.reader,{{ rule }} # 豆瓣阅读
PROCESS-NAME,com.douban.radio,{{ rule }} # 豆瓣FM
PROCESS-NAME,com.douguo.recipe,{{ rule }} # 豆果美食
PROCESS-NAME,com.dp.android.elong,{{ rule }} # 艺龙旅行
PROCESS-NAME,com.dragonpass.activity,{{ rule }} # 龙腾出行
PROCESS-NAME,com.droidpiggy.weiqi,{{ rule }} # 围棋宝典
PROCESS-NAME,com.duitang.main,{{ rule }} # 堆糖
PROCESS-NAME,com.duoduo.cailing,{{ rule }} # 彩铃多多
PROCESS-NAME,com.duoduo.child.story,{{ rule }} # 儿歌多多
PROCESS-NAME,com.duokan.phone.remotecontroller,{{ rule }} # 万能遥控
PROCESS-NAME,com.duokan.reader,{{ rule }} # 多看
PROCESS-NAME,com.duolingo,{{ rule }} # 多邻国
PROCESS-NAME,com.duowan.kiwi,{{ rule }} # 虎牙直播
PROCESS-NAME,com.duowan.mobile,{{ rule }} # YY
PROCESS-NAME,com.dw.btime,{{ rule }} # 亲宝宝
PROCESS-NAME,com.eastday.listen_news,{{ rule }} # 翱翔
PROCESS-NAME,com.eastmoney.android.berlin,{{ rule }} # 东方财富
PROCESS-NAME,com.eastmoney.android.fund,{{ rule }} # 天天基金
PROCESS-NAME,com.eastmoney.android.tokyo,{{ rule }} # AI妙想炒股
PROCESS-NAME,com.ebnews,{{ rule }} # 亿邦
PROCESS-NAME,com.eg.android.AlipayGphone,{{ rule }} # 支付宝
PROCESS-NAME,com.ehai,{{ rule }} # 一嗨租车
PROCESS-NAME,com.eno.android.cj.page,{{ rule }} # 长江e号
PROCESS-NAME,com.eno.xyzq.page,{{ rule }} # 兴业证券优理宝
PROCESS-NAME,com.esbook.reader,{{ rule }} # 宜搜小说
PROCESS-NAME,com.eshore.efilm,{{ rule }} # 院线通电影票
PROCESS-NAME,com.espring.index,{{ rule }} # 安利益之源
PROCESS-NAME,com.estrongs.android.pop,{{ rule }} # ES文件浏览器
PROCESS-NAME,com.eusoft.dehelper,{{ rule }} # 德语助手
PROCESS-NAME,com.eusoft.eshelper,{{ rule }} # 西语助手
PROCESS-NAME,com.eusoft.eudic,{{ rule }} # 欧路词典
PROCESS-NAME,com.eusoft.frhelper,{{ rule }} # 法语助手
PROCESS-NAME,com.eusoft.ting.de,{{ rule }} # 每日德语听力
PROCESS-NAME,com.eusoft.ting.en,{{ rule }} # 每日英语听力
PROCESS-NAME,com.eusoft.ting.fr,{{ rule }} # 每日法语听力
PROCESS-NAME,com.everimaging.photoeffectstudio,{{ rule }} # Fotor
PROCESS-NAME,com.exam8.mideconomist,{{ rule }} # 经济师万题库
PROCESS-NAME,com.exam8.twojian,{{ rule }} # 二建万题库
PROCESS-NAME,com.exam8.yijian,{{ rule }} # 一建万题库
PROCESS-NAME,com.example.bihua,{{ rule }} # 汉字笔画
PROCESS-NAME,com.example.mp3editor,{{ rule }} # MP3剪辑器
PROCESS-NAME,com.ezen.ehshig,{{ rule }} # egshig
PROCESS-NAME,com.facishare.fs,{{ rule }} # 纷享销客CRM
PROCESS-NAME,com.faloo.BookReader4Android,{{ rule }} # 飞卢小说
PROCESS-NAME,com.fanhuan,{{ rule }} # 返还网
PROCESS-NAME,com.fanli.android.apps,{{ rule }} # 返利
PROCESS-NAME,com.fenbi.android.gaozhong,{{ rule }} # 猿题库
PROCESS-NAME,com.fenbi.android.kyzz,{{ rule }} # 粉笔考研
PROCESS-NAME,com.fenbi.android.servant,{{ rule }} # 粉笔
PROCESS-NAME,com.fenbi.android.sikao,{{ rule }} # 粉笔法考
PROCESS-NAME,com.fiberhome.waiqin365.client,{{ rule }} # 勤策
PROCESS-NAME,com.fiistudio.fiinote,{{ rule }} # 随手写
PROCESS-NAME,com.firebear.androil,{{ rule }} # 小熊油耗
PROCESS-NAME,com.flightmanager.view,{{ rule }} # 航班管家
PROCESS-NAME,com.fn.android,{{ rule }} # 蜂鸟摄影
PROCESS-NAME,com.font,{{ rule }} # 写字先生
PROCESS-NAME,com.founder.qujing,{{ rule }} # 掌上曲靖
PROCESS-NAME,com.foxit.mobile.pdf.lite,{{ rule }} # 福昕PDF阅读器
PROCESS-NAME,com.freebird.zsp.DailyAccounting,{{ rule }} # 日常记账
PROCESS-NAME,com.freshideas.airindex,{{ rule }} # 在意空气
PROCESS-NAME,com.fullgoal.android,{{ rule }} # 富国富钱包
PROCESS-NAME,com.funinput.digit,{{ rule }} # 数字尾巴
PROCESS-NAME,com.funshion.video.mobile,{{ rule }} # 风行视频
PROCESS-NAME,com.futurefleet.pandabus.ui,{{ rule }} # 熊猫出行
PROCESS-NAME,com.fx678.finace,{{ rule }} # 汇通财经
PROCESS-NAME,com.galaxy.stock,{{ rule }} # 中国银河证券
PROCESS-NAME,com.gamestar.perfectpiano,{{ rule }} # 完美钢琴
PROCESS-NAME,com.gamestar.pianoperfect,{{ rule }} # 随身乐队
PROCESS-NAME,com.ganji.android,{{ rule }} # 赶集招聘
PROCESS-NAME,com.garmin.android.apps.connectmobile,{{ rule }} # Garmin Connect
PROCESS-NAME,com.gau.go.launcherex.theme.droidglass,{{ rule }} # 玻璃主题包
PROCESS-NAME,com.gdcn.sport,{{ rule }} # 群体通
PROCESS-NAME,com.geihui,{{ rule }} # 给惠网
PROCESS-NAME,com.gem.tastyfood,{{ rule }} # 食行生鲜
PROCESS-NAME,com.gewara,{{ rule }} # 格瓦拉生活
PROCESS-NAME,com.ggeye.jiakao.api,{{ rule }} # 驾考通驾照考试
PROCESS-NAME,com.ggeye.kaoshi.kjcj,{{ rule }} # 初级会计考试
PROCESS-NAME,com.gift.android,{{ rule }} # 驴妈妈旅游
PROCESS-NAME,com.glodon.drawingexplorer,{{ rule }} # CAD快速看图
PROCESS-NAME,com.gongyinruixin,{{ rule }} # 工银瑞信基金
PROCESS-NAME,com.gonlan.iplaymtg,{{ rule }} # 旅法师营地
PROCESS-NAME,com.goodluck.qianming,{{ rule }} # 一句心情签名
PROCESS-NAME,com.gopro.smarty,{{ rule }} # GoPro Quik
PROCESS-NAME,com.goseet.VidTrim,{{ rule }} # 视频剪辑
PROCESS-NAME,com.gozap.chouti,{{ rule }} # 抽屉
PROCESS-NAME,com.greenline.guahao,{{ rule }} # 微医
PROCESS-NAME,com.greenpoint.android.mc10086.activity,{{ rule }} # 中国移动
PROCESS-NAME,com.greentree.android,{{ rule }} # 格林
PROCESS-NAME,com.gstarmc.android,{{ rule }} # CAD看图王
PROCESS-NAME,com.gtgj.view,{{ rule }} # 高铁管家
PROCESS-NAME,com.guosen.android,{{ rule }} # 国信金太阳
PROCESS-NAME,com.gwdang.app,{{ rule }} # 购物党
PROCESS-NAME,com.gwsoft.imusic.controller,{{ rule }} # 爱音乐
PROCESS-NAME,com.gzrcb.mobilebank,{{ rule }} # 广州农商银行
PROCESS-NAME,com.haidilao,{{ rule }} # 海底捞
PROCESS-NAME,com.haitao,{{ rule }} # 55海淘
PROCESS-NAME,com.hangzhoucaimi.financial,{{ rule }} # 挖财宝
PROCESS-NAME,com.hanvon.inputmethod.hanvonime,{{ rule }} # 汉王行云输入法
PROCESS-NAME,com.haodf.android,{{ rule }} # 好大夫在线
PROCESS-NAME,com.haodf.android.doctor,{{ rule }} # 好大夫医生版
PROCESS-NAME,com.haofang.hftsoftapp,{{ rule }} # 掌上好房通
PROCESS-NAME,com.happigo.activity,{{ rule }} # 快乐购
PROCESS-NAME,com.happylife.multimedia.image,{{ rule }} # 相片集
PROCESS-NAME,com.happyteam.dubbingshow,{{ rule }} # 配音秀
PROCESS-NAME,com.heiyan.reader,{{ rule }} # 黑岩阅读
PROCESS-NAME,com.hellotalk,{{ rule }} # HelloTalk
PROCESS-NAME,com.hesh.five,{{ rule }} # 365小时光
PROCESS-NAME,com.hexin.android.bank,{{ rule }} # 同花顺爱基金
PROCESS-NAME,com.hexin.android.stockassistant,{{ rule }} # 同花顺i问财
PROCESS-NAME,com.hexin.ifind.android,{{ rule }} # 同花顺iFinD
PROCESS-NAME,com.hexin.plat.android,{{ rule }} # 同花顺
PROCESS-NAME,com.hexin.plat.android.GuoJinZXGSecurity,{{ rule }} # 全能行
PROCESS-NAME,com.hexin.plat.android.ZhongyuanSecurity,{{ rule }} # 中原证券
PROCESS-NAME,com.hexun.news,{{ rule }} # 和讯财经
PROCESS-NAME,com.hf,{{ rule }} # 中国天气
PROCESS-NAME,com.hipu.yidian,{{ rule }} # 一点资讯
PROCESS-NAME,com.hjwordgames,{{ rule }} # 沪江开心词场
PROCESS-NAME,com.hkx.youandme,{{ rule }} # 情侣我和你
PROCESS-NAME,com.hmkx.zgjkj,{{ rule }} # 健康界
PROCESS-NAME,com.hoge.android.wuhan,{{ rule }} # 掌上武汉
PROCESS-NAME,com.hoge.android.wuxiwireless,{{ rule }} # 无锡博报
PROCESS-NAME,com.hoge.android.xuzhou,{{ rule }} # 无线徐州
PROCESS-NAME,com.homelink.android,{{ rule }} # 链家
PROCESS-NAME,com.honghesoft.calligrapher,{{ rule }} # 大书法家
PROCESS-NAME,com.honghesoft.travelenglish,{{ rule }} # 出国旅游英语
PROCESS-NAME,com.hongxiu.app,{{ rule }} # 红袖读书
PROCESS-NAME,com.house365.newhouse,{{ rule }} # 365淘房
PROCESS-NAME,com.hp.android.printservice,{{ rule }} # HP 打印服务插件
PROCESS-NAME,com.hp.marykay,{{ rule }} # 玫琳凯之窗
PROCESS-NAME,com.hr.ui,{{ rule }} # 行业找工作
PROCESS-NAME,com.hsj.calorie,{{ rule }} # 卡路里减肥助手
PROCESS-NAME,com.htffund.mobile.ec.ui,{{ rule }} # 汇添富现金宝
PROCESS-NAME,com.htinns,{{ rule }} # 华住会
PROCESS-NAME,com.huaban.android,{{ rule }} # 花瓣
PROCESS-NAME,com.hualongxiang,{{ rule }} # 化龙巷
PROCESS-NAME,com.huania.earthquakewarning,{{ rule }} # 地震预警
PROCESS-NAME,com.huanqiu.news,{{ rule }} # 环球时报
PROCESS-NAME,com.huawei.hwid,{{ rule }} # HMS Core
PROCESS-NAME,com.huicent,{{ rule }} # 山东航空
PROCESS-NAME,com.huimai365,{{ rule }} # 惠买
PROCESS-NAME,com.hujiang.cctalk,{{ rule }} # CCtalk
PROCESS-NAME,com.hujiang.dict,{{ rule }} # 沪江小D词典
PROCESS-NAME,com.hujiang.hjclass,{{ rule }} # 沪江网校
PROCESS-NAME,com.hunantv.imgo.activity,{{ rule }} # 芒果TV
PROCESS-NAME,com.hundsun.winner.pazq,{{ rule }} # 平安证券
PROCESS-NAME,com.huofar,{{ rule }} # 过日子
PROCESS-NAME,com.huofar.ylyh,{{ rule }} # 月来越好
PROCESS-NAME,com.hupu.shihuo,{{ rule }} # 识货
PROCESS-NAME,com.huxiu,{{ rule }} # 虎嗅
PROCESS-NAME,com.hyhy.view,{{ rule }} # 掌上天津
PROCESS-NAME,com.hyx.maizuo.main,{{ rule }} # 卖座电影
PROCESS-NAME,com.ibox.flashlight,{{ rule }} # 多多手电筒
PROCESS-NAME,com.iboxpay.minicashbox,{{ rule }} # 钱盒商户通
PROCESS-NAME,com.icbc,{{ rule }} # 中国工商银行
PROCESS-NAME,com.icbc.emallmobile,{{ rule }} # 融e购
PROCESS-NAME,com.ichano.athome.avs,{{ rule }} # 掌上看家采集端
PROCESS-NAME,com.ichano.athome.camera,{{ rule }} # 掌上看家
PROCESS-NAME,com.icoolme.android.weather,{{ rule }} # 最美天气
PROCESS-NAME,com.ifanr.activitys,{{ rule }} # 爱范儿
PROCESS-NAME,com.ifeng.fhdt,{{ rule }} # 凤凰FM
PROCESS-NAME,com.ifeng.news2,{{ rule }} # 凤凰新闻
PROCESS-NAME,com.ifeng.newvideo,{{ rule }} # 凤凰视频
PROCESS-NAME,com.iflytek.inputmethod,{{ rule }} # 讯飞输入法
PROCESS-NAME,com.iflytek.womusicclient,{{ rule }} # 联通视频彩铃
PROCESS-NAME,com.ifreetalk.ftalk,{{ rule }} # 派派
PROCESS-NAME,com.ihope.hbdt,{{ rule }} # 冀时新闻
PROCESS-NAME,com.imgo.pad,{{ rule }} # 芒果TV HD
PROCESS-NAME,com.immomo.momo,{{ rule }} # MOMO陌陌
PROCESS-NAME,com.imusic.iting,{{ rule }} # 爱听
PROCESS-NAME,com.inditex.zara,{{ rule }} # ZARA
PROCESS-NAME,com.infothinker.gzmetro,{{ rule }} # 广州地铁
PROCESS-NAME,com.intsig.BizCardReader,{{ rule }} # 名片全能王
PROCESS-NAME,com.intsig.camscanner,{{ rule }} # 扫描全能王
PROCESS-NAME,com.iqinbao.android.songs,{{ rule }} # 亲宝儿歌
PROCESS-NAME,com.istone.activity,{{ rule }} # 邦购商城
PROCESS-NAME,com.ithink.activity,{{ rule }} # 手立视
PROCESS-NAME,com.iwxlh.pta,{{ rule }} # 交广领航
PROCESS-NAME,com.iyuba.AE,{{ rule }} # 美语怎么说
PROCESS-NAME,com.iyuba.bbcinone,{{ rule }} # 爱语吧英语
PROCESS-NAME,com.iyuba.cet4,{{ rule }} # 英语四级听力
PROCESS-NAME,com.iyuba.cet6,{{ rule }} # 英语六级听力
PROCESS-NAME,com.iyuba.CSvoa,{{ rule }} # VOA常速英语
PROCESS-NAME,com.iyuba.music,{{ rule }} # 听歌学英语
PROCESS-NAME,com.iyuba.toeiclistening,{{ rule }} # 托业听力
PROCESS-NAME,com.iyuba.toelflistening,{{ rule }} # 托福听力
PROCESS-NAME,com.iyuba.voa,{{ rule }} # VOA慢速英语
PROCESS-NAME,com.iyuba.VoaVideo,{{ rule }} # VOA英语视频
PROCESS-NAME,com.jecelyin.editor,{{ rule }} # JecEditor 文本编辑器
PROCESS-NAME,com.jeejen.family,{{ rule }} # 极简桌面
PROCESS-NAME,com.jesson.meishi,{{ rule }} # 美食杰
PROCESS-NAME,com.jhss.youguu,{{ rule }} # 优顾炒股
PROCESS-NAME,com.jianke.doctor,{{ rule }} # 健客医生
PROCESS-NAME,com.jiaxun.acupoint,{{ rule }} # 经络穴位图解
PROCESS-NAME,com.jiayuan,{{ rule }} # 世纪佳缘
PROCESS-NAME,com.jingdian.tianxiameishi.android,{{ rule }} # 美食天下
PROCESS-NAME,com.jingdong.app.mall,{{ rule }} # 京东
PROCESS-NAME,com.jiongji.andriod.card,{{ rule }} # 百词斩
PROCESS-NAME,com.jiuxianapk.ui,{{ rule }} # 酒仙
PROCESS-NAME,com.jiuyan.infashion,{{ rule }} # in
PROCESS-NAME,com.jlzb.android,{{ rule }} # 找帮手机定位
PROCESS-NAME,com.jm.android.jumei,{{ rule }} # 聚美
PROCESS-NAME,com.jm.fxw,{{ rule }} # 发型屋
PROCESS-NAME,com.job.android,{{ rule }} # 前程无忧51Job
PROCESS-NAME,com.jootun.hudongba,{{ rule }} # 互动吧
PROCESS-NAME,com.jorny.expcla,{{ rule }} # 语音计算器
PROCESS-NAME,com.jovetech.CloudSee.temp,{{ rule }} # 云视通
PROCESS-NAME,com.joygo,{{ rule }} # 忘忧围棋
PROCESS-NAME,com.joyintech.wise.seller,{{ rule }} # 智慧商贸进销存
PROCESS-NAME,com.jsbc.lznews,{{ rule }} # 荔枝新闻
PROCESS-NAME,com.jsmcc,{{ rule }} # 中国移动江苏
PROCESS-NAME,com.julanling.app,{{ rule }} # 安心记加班
PROCESS-NAME,com.jw.iworker,{{ rule }} # 工作家
PROCESS-NAME,com.jxedt,{{ rule }} # 驾校一点通
PROCESS-NAME,com.kdweibo.client,{{ rule }} # 云之家
PROCESS-NAME,com.kehu51,{{ rule }} # 客户无忧
PROCESS-NAME,com.kekeclient_,{{ rule }} # 可可英语
PROCESS-NAME,com.kevinstudio.test,{{ rule }} # 转盘做决定
PROCESS-NAME,com.Kingdee.Express,{{ rule }} # 快递100
PROCESS-NAME,com.kingpoint.gmcchh,{{ rule }} # 中国移动广东
PROCESS-NAME,com.kingsoft,{{ rule }} # 金山词霸
PROCESS-NAME,com.kingsoft.android.cat,{{ rule }} # 玲珑密保锁
PROCESS-NAME,com.komoxo.octopusime,{{ rule }} # 章鱼输入法
PROCESS-NAME,com.koolearn.android,{{ rule }} # 新东方在线
PROCESS-NAME,com.koudai.weishop,{{ rule }} # 微店店长版
PROCESS-NAME,com.kplus.car,{{ rule }} # 橙牛汽车管家
PROCESS-NAME,com.kuaibao.kuaidi,{{ rule }} # 微快递
PROCESS-NAME,com.kuaibao.skuaidi,{{ rule }} # 快宝快递员
PROCESS-NAME,com.kugou.android,{{ rule }} # 酷狗音乐
PROCESS-NAME,com.kugou.android.ringtone,{{ rule }} # 酷狗铃声
PROCESS-NAME,com.kugou.fanxing,{{ rule }} # 酷狗直播
PROCESS-NAME,com.kugou.playerHD,{{ rule }} # 酷狗音乐HD
PROCESS-NAME,com.kunpeng.babyting,{{ rule }} # 宝贝听听
PROCESS-NAME,com.kunshan.main,{{ rule }} # 智慧昆山
PROCESS-NAME,com.ky.medical.reference,{{ rule }} # 用药参考
PROCESS-NAME,com.laba.wcs,{{ rule }} # 微差事
PROCESS-NAME,com.lakala.android,{{ rule }} # 拉卡拉易分期
PROCESS-NAME,com.leduoworks.gpstoolbox,{{ rule }} # GPS工具箱
PROCESS-NAME,com.leixun.taofen8,{{ rule }} # 淘粉吧
PROCESS-NAME,com.leju.platform,{{ rule }} # 乐居买房
PROCESS-NAME,com.letv.android.client,{{ rule }} # 乐视视频
PROCESS-NAME,com.letv.android.client.pad,{{ rule }} # 乐视视频Pad
PROCESS-NAME,com.letv.letvshop,{{ rule }} # 乐视商城
PROCESS-NAME,com.lianaibiji.dev,{{ rule }} # 恋爱记
PROCESS-NAME,com.liba.android,{{ rule }} # 篱笆社区
PROCESS-NAME,com.lietou.mishu,{{ rule }} # 猎聘
PROCESS-NAME,com.lingan.seeyou,{{ rule }} # 美柚
PROCESS-NAME,com.liulishuo.engzo,{{ rule }} # 流利说-英语
PROCESS-NAME,com.liuzb.moodiary,{{ rule }} # 心情日记本
PROCESS-NAME,com.liveyap.timehut,{{ rule }} # 时光小屋
PROCESS-NAME,com.liwushuo.gifttalk,{{ rule }} # 礼物说
PROCESS-NAME,com.ljmobile.zlj.rom.release,{{ rule }} # 授权管理软件搬家
PROCESS-NAME,com.lltskb.lltskb,{{ rule }} # 路路通
PROCESS-NAME,com.lofter.android,{{ rule }} # 网易LOFTER
PROCESS-NAME,com.lolaage.tbulu.tools,{{ rule }} # 两步路户外助手
PROCESS-NAME,com.lovebizhi.wallpaper,{{ rule }} # 爱壁纸
PROCESS-NAME,com.lt.lighting,{{ rule }} # 来电闪光
PROCESS-NAME,com.ludashi.benchmark,{{ rule }} # 鲁大师
PROCESS-NAME,com.lufax.android,{{ rule }} # 陆基金
PROCESS-NAME,com.lujiaxing.disconnectpoweroff,{{ rule }} # 断电自动关机
PROCESS-NAME,com.lyh.talkphoto,{{ rule }} # 让照片会说话
PROCESS-NAME,com.manle.phone.android.yaodian,{{ rule }} # 掌上药店
PROCESS-NAME,com.maxxipoint.android,{{ rule }} # 集享联盟
PROCESS-NAME,com.medapp,{{ rule }} # 女性私人医生
PROCESS-NAME,com.medapp.man,{{ rule }} # 男性私人医生
PROCESS-NAME,com.meet.pianolearn,{{ rule }} # 钢琴教练
PROCESS-NAME,com.meetstudio.app.Zither,{{ rule }} # 魔幻古筝
PROCESS-NAME,com.meitu.meipaimv,{{ rule }} # 美拍
PROCESS-NAME,com.meitu.meiyancamera,{{ rule }} # 美颜相机
PROCESS-NAME,com.meitu.poster,{{ rule }} # 美图设计室
PROCESS-NAME,com.meizu.flyme.find,{{ rule }} # 查找手机
PROCESS-NAME,com.melot.meshow,{{ rule }} # KK
PROCESS-NAME,com.memory.me,{{ rule }} # 英语魔方秀
PROCESS-NAME,com.messi.cantonese.study,{{ rule }} # 粤语说
PROCESS-NAME,com.messi.languagehelper,{{ rule }} # 中英互译
PROCESS-NAME,com.mfw.roadbook,{{ rule }} # 马蜂窝
PROCESS-NAME,com.mgyun.rootmaster,{{ rule }} # ROOT大师
PROCESS-NAME,com.microsoft.bing,{{ rule }} # 微软必应
PROCESS-NAME,com.microsoft.office.officehub,{{ rule }} # Microsoft 365 Copilot
PROCESS-NAME,com.microsoft.office.onenote,{{ rule }} # OneNote
PROCESS-NAME,com.microsoft.skydrive,{{ rule }} # OneDrive
PROCESS-NAME,com.mingdao,{{ rule }} # 明道云
PROCESS-NAME,com.miui.video,{{ rule }} # 小米视频
PROCESS-NAME,com.mmc.fengshui.pass,{{ rule }} # 通易罗盘指南针
PROCESS-NAME,com.mobile.myeye,{{ rule }} # 监控眼
PROCESS-NAME,com.MobileTicket,{{ rule }} # 铁路12306
PROCESS-NAME,com.mobvoi.baiding,{{ rule }} # 出门问问
PROCESS-NAME,com.mogujie,{{ rule }} # 蘑菇街
PROCESS-NAME,com.moji.mjweather,{{ rule }} # 墨迹天气
PROCESS-NAME,com.moneywise.mhmoney,{{ rule }} # 财智快账
PROCESS-NAME,com.mrkj.sm,{{ rule }} # 知命
PROCESS-NAME,com.mt.mtxx.mtxx,{{ rule }} # 美图秀秀
PROCESS-NAME,com.mtime,{{ rule }} # 时光网
PROCESS-NAME,com.mw2c.guitartabsearch,{{ rule }} # 吉他谱搜索
PROCESS-NAME,com.mx.browser,{{ rule }} # 傲游浏览器
PROCESS-NAME,com.mxr.dreambook,{{ rule }} # 4D书城
PROCESS-NAME,com.mygolbs.mybus,{{ rule }} # 掌上公交
PROCESS-NAME,com.mymoney,{{ rule }} # 随手记
PROCESS-NAME,com.mymoney.sms,{{ rule }} # 卡牛信用管家
PROCESS-NAME,com.myzaker.ZAKER_Phone,{{ rule }} # ZAKER
PROCESS-NAME,com.nbbank,{{ rule }} # 宁波银行
PROCESS-NAME,com.ncpaclassic,{{ rule }} # 大剧院·古典
PROCESS-NAME,com.nd.android.pandareader,{{ rule }} # 熊猫看书
PROCESS-NAME,com.neil,{{ rule }} # 返利助手
PROCESS-NAME,com.netease.cc,{{ rule }} # CC直播
PROCESS-NAME,com.netease.cloudmusic,{{ rule }} # 网易云音乐
PROCESS-NAME,com.netease.epay,{{ rule }} # 网易支付
PROCESS-NAME,com.netease.huatian,{{ rule }} # 网易花田
PROCESS-NAME,com.netease.mail,{{ rule }} # 网易邮箱大师
PROCESS-NAME,com.netease.mkey,{{ rule }} # 网易将军令
PROCESS-NAME,com.netease.mobimail,{{ rule }} # 网易邮箱
PROCESS-NAME,com.netease.newsreader.activity,{{ rule }} # 网易新闻
PROCESS-NAME,com.netease.pris,{{ rule }} # 网易云阅读
PROCESS-NAME,com.netease.vopen,{{ rule }} # 网易公开课
PROCESS-NAME,com.netease.xyqcbg,{{ rule }} # 梦幻藏宝阁
PROCESS-NAME,com.netschool.main.ui,{{ rule }} # 华图在线题库
PROCESS-NAME,com.new_qdqss.activity,{{ rule }} # 掌上青岛
PROCESS-NAME,com.newstar.zybbname,{{ rule }} # 宝宝生辰起名取名
PROCESS-NAME,com.nice.main,{{ rule }} # nice
PROCESS-NAME,com.nineteenlou.nineteenlou,{{ rule }} # 19楼
PROCESS-NAME,com.ninexiu.sixninexiu,{{ rule }} # 九秀直播
PROCESS-NAME,com.niuguwang.stock,{{ rule }} # 牛股王股票
PROCESS-NAME,com.nowcasting.activity,{{ rule }} # 彩云天气
PROCESS-NAME,com.nxnresearch,{{ rule }} # 戒烟军团
PROCESS-NAME,com.ny.jiuyi160_doctor,{{ rule }} # 160医护
PROCESS-NAME,com.ocj.oms.mobile,{{ rule }} # 东方购物
PROCESS-NAME,com.octinn.birthdayplus,{{ rule }} # 生日管家
PROCESS-NAME,com.oda_cad,{{ rule }} # CAD迷你看图
PROCESS-NAME,com.offcn.android.offcn,{{ rule }} # 中公教育
PROCESS-NAME,com.onesoft.app.ExamCountDown,{{ rule }} # CPA 考试倒计时
PROCESS-NAME,com.onesoft.app.Tiiku.Duia.KJZ,{{ rule }} # 会计随身学
PROCESS-NAME,com.ophone.reader.ui,{{ rule }} # 咪咕悦看
PROCESS-NAME,com.oray.sunlogin,{{ rule }} # 向日葵远程控制
PROCESS-NAME,com.oupeng.browser,{{ rule }} # 欧朋浏览器极速版
PROCESS-NAME,com.oupeng.mini.android,{{ rule }} # 欧朋浏览器
PROCESS-NAME,com.ovital.ovitalMap,{{ rule }} # 奥维互动地图
PROCESS-NAME,com.p1.mobile.putong,{{ rule }} # 探探
PROCESS-NAME,com.paic.zhifu.wallet.activity,{{ rule }} # 壹钱包
PROCESS-NAME,com.pch.plan,{{ rule }} # 计划管理
PROCESS-NAME,com.pcs.knowing_weather,{{ rule }} # 知天气
PROCESS-NAME,com.pdswp.su.smartcalendar,{{ rule }} # 智能备忘录
PROCESS-NAME,com.peopledailychina.activity,{{ rule }} # 人民日报
PROCESS-NAME,com.picooc,{{ rule }} # PICOOC
PROCESS-NAME,com.pingan.lifeinsurance,{{ rule }} # 平安金管家
PROCESS-NAME,com.pplive.androidphone,{{ rule }} # PP视频
PROCESS-NAME,com.pplive.androidphone.sport,{{ rule }} # PP体育
PROCESS-NAME,com.puscene.client,{{ rule }} # 美味不用等
PROCESS-NAME,com.qdnews.qd,{{ rule }} # 青岛新闻
PROCESS-NAME,com.qidian.QDReader,{{ rule }} # 起点读书
PROCESS-NAME,com.qihoo.browser,{{ rule }} # 360浏览器
PROCESS-NAME,com.qihoo.cleandroid_cn,{{ rule }} # 360清理大师
PROCESS-NAME,com.qihoo360.antilostwatch,{{ rule }} # 360儿童卫士
PROCESS-NAME,com.qihoo360.mobilesafe,{{ rule }} # 360手机卫士
PROCESS-NAME,com.qilesoft.en.eights,{{ rule }} # 英语口语8000句
PROCESS-NAME,com.qima.kdt,{{ rule }} # 有赞微商城
PROCESS-NAME,com.qingdaonews.bus,{{ rule }} # 青岛公交查询
PROCESS-NAME,com.qiyi.video,{{ rule }} # 爱奇艺
PROCESS-NAME,com.qiyi.video.pad,{{ rule }} # 爱奇艺PAD
PROCESS-NAME,com.qq.ac.android,{{ rule }} # 腾讯动漫
PROCESS-NAME,com.qq.qcloud,{{ rule }} # 腾讯微云
PROCESS-NAME,com.qq.reader,{{ rule }} # QQ阅读
PROCESS-NAME,com.quanleimu.activity,{{ rule }} # 百姓网
PROCESS-NAME,com.Qunar,{{ rule }} # 去哪儿旅行
PROCESS-NAME,com.quvideo.xiaoying,{{ rule }} # 小影
PROCESS-NAME,com.qyer.android.jinnang,{{ rule }} # 穷游
PROCESS-NAME,com.qzone,{{ rule }} # QQ空间
PROCESS-NAME,com.raiyi.wxcs,{{ rule }} # 流量掌厅
PROCESS-NAME,com.rakutec.android.iweekly,{{ rule }} # iWeekly 周末画报
PROCESS-NAME,com.rarlab.rar,{{ rule }} # RAR
PROCESS-NAME,com.rd.kx,{{ rule }} # 星剪
PROCESS-NAME,com.renren.mobile.android,{{ rule }} # 人人直播
PROCESS-NAME,com.rkhd.ingage.app,{{ rule }} # 销售易CRM
PROCESS-NAME,com.roamingsoft.manager,{{ rule }} # WiFi连接管理器
PROCESS-NAME,com.ruanmei.ithome,{{ rule }} # IT之家
PROCESS-NAME,com.rumtel.mobiletv,{{ rule }} # 影视大全看看
PROCESS-NAME,com.rytong.airchina,{{ rule }} # 中国国航
PROCESS-NAME,com.rytong.ceair,{{ rule }} # 东方航空
PROCESS-NAME,com.rytong.hnair,{{ rule }} # 海南航空
PROCESS-NAME,com.saker.app.huhu,{{ rule }} # 呼呼收音机
PROCESS-NAME,com.saltchucker,{{ rule }} # 渔获
PROCESS-NAME,com.sand.airdroid,{{ rule }} # AirDroid
PROCESS-NAME,com.sangdh,{{ rule }} # 3G网络电话
PROCESS-NAME,com.sankuai.meituan,{{ rule }} # 美团
PROCESS-NAME,com.sankuai.meituan.merchant,{{ rule }} # 美团经营宝
PROCESS-NAME,com.sankuai.meituan.takeoutnew,{{ rule }} # 美团外卖
PROCESS-NAME,com.sankuai.movie,{{ rule }} # 猫眼
PROCESS-NAME,com.scanning,{{ rule }} # 二维码与条形码
PROCESS-NAME,com.sdu.didi.psnger,{{ rule }} # 滴滴出行
PROCESS-NAME,com.secoo,{{ rule }} # 寺库奢侈品
PROCESS-NAME,com.seetong.app.seetong,{{ rule }} # Seetong
PROCESS-NAME,com.sevenmmobile,{{ rule }} # 7M足球实时比分
PROCESS-NAME,com.sf.activity,{{ rule }} # 顺丰速运
PROCESS-NAME,com.shanbay.news,{{ rule }} # 扇贝阅读
PROCESS-NAME,com.shanbay.sentence,{{ rule }} # 扇贝单词英语版
PROCESS-NAME,com.shanghaionstar,{{ rule }} # 安吉星
PROCESS-NAME,com.shengcai,{{ rule }} # 圣才电子书
PROCESS-NAME,com.shengshi,{{ rule }} # 小鱼网
PROCESS-NAME,com.shenyuan.militarynews,{{ rule }} # 环球新军事
PROCESS-NAME,com.shinyv.cnr,{{ rule }} # 云听
PROCESS-NAME,com.shipxy.android,{{ rule }} # 船讯网
PROCESS-NAME,com.shoujiduoduo.ringtone,{{ rule }} # 铃声多多
PROCESS-NAME,com.shoujiduoduo.wallpaper,{{ rule }} # 壁纸多多
PROCESS-NAME,com.shuqi.controller,{{ rule }} # 书旗小说
PROCESS-NAME,com.shyl_weather,{{ rule }} # 天气预报播报员
PROCESS-NAME,com.shyl.train,{{ rule }} # 全国火车票实时查
PROCESS-NAME,com.shyltts,{{ rule }} # 读短信来电报姓名
PROCESS-NAME,com.sina.news,{{ rule }} # 新浪新闻
PROCESS-NAME,com.sina.VDisk,{{ rule }} # 微盘
PROCESS-NAME,com.sina.weibo,{{ rule }} # 微博
PROCESS-NAME,com.sina.weibog3,{{ rule }} # 微博移动版
PROCESS-NAME,com.sing.client,{{ rule }} # 5sing音乐
PROCESS-NAME,com.sinosoft.mobilebiz.chinalife,{{ rule }} # 中国人寿综合金融
PROCESS-NAME,com.sinovatech.gxmobile.ui,{{ rule }} # 中国移动广西
PROCESS-NAME,com.sinovatech.unicom.ui,{{ rule }} # 中国联通
PROCESS-NAME,com.sinyee.babybus.abc,{{ rule }} # 宝宝巴士英语
PROCESS-NAME,com.sinyee.babybus.animal,{{ rule }} # 动物乐园
PROCESS-NAME,com.sinyee.babybus.babydrawing,{{ rule }} # 宝宝画妈妈猜
PROCESS-NAME,com.sinyee.babybus.babyhospital,{{ rule }} # 宝宝医院
PROCESS-NAME,com.sinyee.babybus.behaviour,{{ rule }} # 宝宝行为认知
PROCESS-NAME,com.sinyee.babybus.birthdayparty,{{ rule }} # 宝宝生日派对
PROCESS-NAME,com.sinyee.babybus.chef,{{ rule }} # 宝宝小厨房
PROCESS-NAME,com.sinyee.babybus.concert,{{ rule }} # 宝宝音乐启蒙
PROCESS-NAME,com.sinyee.babybus.dailycommodities,{{ rule }} # 宝宝认日用品
PROCESS-NAME,com.sinyee.babybus.dayandnight,{{ rule }} # 白天黑夜
PROCESS-NAME,com.sinyee.babybus.drawing,{{ rule }} # 神奇的画笔
PROCESS-NAME,com.sinyee.babybus.duibi,{{ rule }} # 有趣的对比
PROCESS-NAME,com.sinyee.babybus.farm,{{ rule }} # 奇妙数字农场
PROCESS-NAME,com.sinyee.babybus.findCha,{{ rule }} # 宝宝来找茬
PROCESS-NAME,com.sinyee.babybus.findchaII,{{ rule }} # 猜猜哪不对
PROCESS-NAME,com.sinyee.babybus.findfriendsII,{{ rule }} # 宝宝玩配对
PROCESS-NAME,com.sinyee.babybus.findnumber,{{ rule }} # 宝宝欢乐数字
PROCESS-NAME,com.sinyee.babybus.fireman,{{ rule }} # 我是消防员
PROCESS-NAME,com.sinyee.babybus.foodstreet,{{ rule }} # 宝宝美食街
PROCESS-NAME,com.sinyee.babybus.garbage,{{ rule }} # 宝宝垃圾回收
PROCESS-NAME,com.sinyee.babybus.greenguard,{{ rule }} # 环保小宝宝
PROCESS-NAME,com.sinyee.babybus.homesafe,{{ rule }} # 宝宝居家安全
PROCESS-NAME,com.sinyee.babybus.kindergarten,{{ rule }} # 宝宝欢乐教室
PROCESS-NAME,com.sinyee.babybus.lovehealthy,{{ rule }} # 宝宝爱卫生
PROCESS-NAME,com.sinyee.babybus.magichouse,{{ rule }} # 宝宝调色屋
PROCESS-NAME,com.sinyee.babybus.newyear,{{ rule }} # 奇妙传统节日
PROCESS-NAME,com.sinyee.babybus.number,{{ rule }} # 宝宝玩数字
PROCESS-NAME,com.sinyee.babybus.numberconnect,{{ rule }} # 宝宝数字岛
PROCESS-NAME,com.sinyee.babybus.organized,{{ rule }} # 宝宝大扫除
PROCESS-NAME,com.sinyee.babybus.paintingII,{{ rule }} # 宝宝涂鸦
PROCESS-NAME,com.sinyee.babybus.puzzle,{{ rule }} # 宝宝认知大全
PROCESS-NAME,com.sinyee.babybus.season,{{ rule }} # 宝宝缤纷四季
PROCESS-NAME,com.sinyee.babybus.seaworld,{{ rule }} # 宝宝钓鱼
PROCESS-NAME,com.sinyee.babybus.show,{{ rule }} # 宝宝服装秀
PROCESS-NAME,com.sinyee.babybus.songIV,{{ rule }} # 宝宝乐器
PROCESS-NAME,com.sinyee.babybus.songV,{{ rule }} # 欢乐圣诞
PROCESS-NAME,com.sinyee.babybus.spell,{{ rule }} # 宝宝拼拼乐
PROCESS-NAME,com.sinyee.babybus.tadpole,{{ rule }} # 小蝌蚪历险记
PROCESS-NAME,com.sinyee.babybus.toilet,{{ rule }} # 宝宝上厕所
PROCESS-NAME,com.sinyee.babybus.travelsafety,{{ rule }} # 宝宝出行安全
PROCESS-NAME,com.sinyee.babybus.vegetable,{{ rule }} # 宝宝爱蔬菜
PROCESS-NAME,com.sinyee.education.color_new,{{ rule }} # 宝宝玩颜色
PROCESS-NAME,com.sinyee.education.shape,{{ rule }} # 宝宝玩形状
PROCESS-NAME,com.sinyee.fruit.activity,{{ rule }} # 宝宝爱水果
PROCESS-NAME,com.sitech.rhtx,{{ rule }} # 易信
PROCESS-NAME,com.sjz.cl.smspopup,{{ rule }} # 短信弹窗
PROCESS-NAME,com.skp.adf.photopunch,{{ rule }} # 抠图神手
PROCESS-NAME,com.slanissue.apps.mobile.erge,{{ rule }} # 贝瓦儿歌
PROCESS-NAME,com.smartisan.notes,{{ rule }} # 锤子便签
PROCESS-NAME,com.smile.gifmaker,{{ rule }} # 快手
PROCESS-NAME,com.smzdm.client.android,{{ rule }} # 什么值得买
PROCESS-NAME,com.snda.wifilocating,{{ rule }} # WiFi万能钥匙
PROCESS-NAME,com.sohu.inputmethod.sogou,{{ rule }} # 搜狗输入法
PROCESS-NAME,com.sohu.newsclient,{{ rule }} # 搜狐新闻
PROCESS-NAME,com.sohu.sohuvideo,{{ rule }} # 搜狐视频
PROCESS-NAME,com.sohu.tv,{{ rule }} # 搜狐视频Pad
PROCESS-NAME,com.sony.store.china,{{ rule }} # 索尼中国
PROCESS-NAME,com.soohoot.ptest,{{ rule }} # 普通话发音测试
PROCESS-NAME,com.soufun,{{ rule }} # 经纪云
PROCESS-NAME,com.soufun.app,{{ rule }} # 房天下
PROCESS-NAME,com.ss.android.article.news,{{ rule }} # 今日头条
PROCESS-NAME,com.sskj.flashlight,{{ rule }} # 随手电筒
PROCESS-NAME,com.starbucks.cn,{{ rule }} # 星巴克
PROCESS-NAME,com.storychina,{{ rule }} # 故事会纯阅版
PROCESS-NAME,com.suning.mobile.ebuy,{{ rule }} # 苏宁易购
PROCESS-NAME,com.suning.mobile.epa,{{ rule }} # 星图金融
PROCESS-NAME,com.sunrise.scmbhc,{{ rule }} # 中国移动四川
PROCESS-NAME,com.super8.android,{{ rule }} # 速8酒店
PROCESS-NAME,com.superlib,{{ rule }} # 移动图书馆
PROCESS-NAME,com.synology.DSfile,{{ rule }} # DS file
PROCESS-NAME,com.sywg.stock,{{ rule }} # 申万宏源高端
PROCESS-NAME,com.sz.china.mycityweather,{{ rule }} # 我的都市天气
PROCESS-NAME,com.sz.china.weather,{{ rule }} # 深圳天气
PROCESS-NAME,com.szchmtech.parkingfee,{{ rule }} # 宜停车
PROCESS-NAME,com.szzc,{{ rule }} # 神州租车
PROCESS-NAME,com.tal.kaoyan,{{ rule }} # 考研帮
PROCESS-NAME,com.talicai.timiclient,{{ rule }} # Timi记账
PROCESS-NAME,com.taobao.etao,{{ rule }} # 一淘
PROCESS-NAME,com.taobao.mobile.dipei,{{ rule }} # 口碑
PROCESS-NAME,com.taobao.movie.android,{{ rule }} # 淘票票
PROCESS-NAME,com.taobao.qianniu,{{ rule }} # 千牛
PROCESS-NAME,com.taobao.taobao,{{ rule }} # 淘宝
PROCESS-NAME,com.taobao.trip,{{ rule }} # 飞猪旅行
PROCESS-NAME,com.taoguba.app,{{ rule }} # 淘股吧
PROCESS-NAME,com.taou.maimai,{{ rule }} # 脉脉
PROCESS-NAME,com.tc.cm,{{ rule }} # 地铁通
PROCESS-NAME,com.tdx.AndroidNew,{{ rule }} # 通达信
PROCESS-NAME,com.teambition.teambition,{{ rule }} # Teambition
PROCESS-NAME,com.telecom.video,{{ rule }} # 天翼超高清
PROCESS-NAME,com.tencent.androidqqmail,{{ rule }} # QQ邮箱
PROCESS-NAME,com.tencent.gallerymanager,{{ rule }} # 腾讯相册管家
PROCESS-NAME,com.tencent.map,{{ rule }} # 腾讯地图
PROCESS-NAME,com.tencent.mm,{{ rule }} # 微信
PROCESS-NAME,com.tencent.mobileqq,{{ rule }} # QQ
PROCESS-NAME,com.tencent.mtt,{{ rule }} # QQ浏览器
PROCESS-NAME,com.tencent.news,{{ rule }} # 腾讯新闻
PROCESS-NAME,com.tencent.portfolio,{{ rule }} # 腾讯自选股
PROCESS-NAME,com.tencent.qqlive,{{ rule }} # 腾讯视频
PROCESS-NAME,com.tencent.qqmusic,{{ rule }} # QQ音乐
PROCESS-NAME,com.tencent.qqmusicpad,{{ rule }} # QQ音乐HD
PROCESS-NAME,com.tencent.qqpim,{{ rule }} # QQ同步助手
PROCESS-NAME,com.tencent.qqpimsecure,{{ rule }} # 腾讯手机管家
PROCESS-NAME,com.tencent.qqpinyin,{{ rule }} # QQ输入法
PROCESS-NAME,com.tencent.qqsports,{{ rule }} # 腾讯体育
PROCESS-NAME,com.tencent.qt.qtl,{{ rule }} # 掌上英雄联盟
PROCESS-NAME,com.tencent.token,{{ rule }} # QQ安全中心
PROCESS-NAME,com.tencent.transfer,{{ rule }} # 换机助手
PROCESS-NAME,com.tencent.ttpic,{{ rule }} # 天天P图
PROCESS-NAME,com.tencent.weishi,{{ rule }} # 腾讯微视
PROCESS-NAME,com.tencent.zebra,{{ rule }} # 水印相机
PROCESS-NAME,com.theotino.chinadaily,{{ rule }} # China Daily
PROCESS-NAME,com.theotino.sztv,{{ rule }} # 无线苏州
PROCESS-NAME,com.thestore.main,{{ rule }} # 1号会员店
PROCESS-NAME,com.thinkyeah.galleryvault,{{ rule }} # 照片保险箱
PROCESS-NAME,com.tianqi2345,{{ rule }} # 2345天气王
PROCESS-NAME,com.tieyou.train.ark,{{ rule }} # 铁友火车票
PROCESS-NAME,com.ting.mp3.android,{{ rule }} # 千千音乐
PROCESS-NAME,com.tiqiaa.icontrol,{{ rule }} # 遥控精灵
PROCESS-NAME,com.tmall.wireless,{{ rule }} # 天猫
PROCESS-NAME,com.to8to.assistant.activity,{{ rule }} # 土巴兔装修设计软件
PROCESS-NAME,com.to8to.tuku,{{ rule }} # 装修图库
PROCESS-NAME,com.to8to.zxtyg,{{ rule }} # 装修体验馆
PROCESS-NAME,com.tom.ule.ui,{{ rule }} # 邮乐
PROCESS-NAME,com.tongcheng.android,{{ rule }} # 同程旅行
PROCESS-NAME,com.topgether.sixfoot,{{ rule }} # 六只脚
PROCESS-NAME,com.topsky.kkol,{{ rule }} # 康康在线
PROCESS-NAME,com.towords,{{ rule }} # 拓词
PROCESS-NAME,com.tqkj.calculator,{{ rule }} # 神指计算器
PROCESS-NAME,com.travelsky.bluesky,{{ rule }} # 差旅随行
PROCESS-NAME,com.tripadvisor.tripadvisor.daodao,{{ rule }} # Tripadvisor猫途鹰
PROCESS-NAME,com.truckhome.bbs,{{ rule }} # 卡车之家
PROCESS-NAME,com.ts.zlzs,{{ rule }} # 诊疗助手
PROCESS-NAME,com.ts.zys,{{ rule }} # 快速问医生
PROCESS-NAME,com.tsf.shell.widget.message,{{ rule }} # TSF 信息小部件
PROCESS-NAME,com.ttxg.fruitday,{{ rule }} # 天天果园
PROCESS-NAME,com.tudou.android,{{ rule }} # 土豆
PROCESS-NAME,com.tujia.hotel,{{ rule }} # 途家民宿
PROCESS-NAME,com.tuniu.app.ui,{{ rule }} # 途牛旅游
PROCESS-NAME,com.ubivelox.bluelink_c,{{ rule }} # Bluelink
PROCESS-NAME,com.ubivelox.uvo_c,{{ rule }} # Kia Connect
PROCESS-NAME,com.ucar.app,{{ rule }} # 淘车车
PROCESS-NAME,com.UCMobile,{{ rule }} # UC浏览器
PROCESS-NAME,com.ume.browser,{{ rule }} # 微米浏览器
PROCESS-NAME,com.umetrip.android.msky.app,{{ rule }} # 航旅纵横
PROCESS-NAME,com.unicom.wopay,{{ rule }} # 沃钱包
PROCESS-NAME,com.unicom.zworeader.ui,{{ rule }} # 联通爱听
PROCESS-NAME,com.unionpay,{{ rule }} # 云闪付
PROCESS-NAME,com.ushaqi.zhuishushenqi,{{ rule }} # 追书神器
PROCESS-NAME,com.utooo.android.knife.free,{{ rule }} # UTOOO Knife
PROCESS-NAME,com.vertech.roadexame,{{ rule }} # 科目三语音助手
PROCESS-NAME,com.videogo,{{ rule }} # 萤石云视频
PROCESS-NAME,com.violationquery,{{ rule }} # 车行易查违章
PROCESS-NAME,com.vip186.neteye,{{ rule }} # 手机监控
PROCESS-NAME,com.wacai365,{{ rule }} # 挖财记账
PROCESS-NAME,com.wallstreetcn.news,{{ rule }} # 华尔街见闻
PROCESS-NAME,com.wandafilm.app,{{ rule }} # 万达电影
PROCESS-NAME,com.wangyin.payment,{{ rule }} # 京东钱包
PROCESS-NAME,com.wanmeizhensuo.zhensuo,{{ rule }} # 更美
PROCESS-NAME,com.waterfall.metronome,{{ rule }} # 节拍器
PROCESS-NAME,com.way.note,{{ rule }} # 九宫记事本
PROCESS-NAME,com.welove520.welove,{{ rule }} # 微爱
PROCESS-NAME,com.wenhua.bamboo,{{ rule }} # 随身行
PROCESS-NAME,com.Wf,{{ rule }} # 上海外服
PROCESS-NAME,com.when.coco,{{ rule }} # 365日历
PROCESS-NAME,com.whty.wicity.china,{{ rule }} # 和生活
PROCESS-NAME,com.wiseman.writing,{{ rule }} # 跟我学写汉字
PROCESS-NAME,com.wlqq4consignor,{{ rule }} # 货车帮货主
PROCESS-NAME,com.wlstock.fund,{{ rule }} # 持股帮
PROCESS-NAME,com.wole56.ishow,{{ rule }} # 我秀
PROCESS-NAME,com.womai,{{ rule }} # 中粮我买网
PROCESS-NAME,com.wondertek.paper,{{ rule }} # 澎湃新闻
PROCESS-NAME,com.wuba,{{ rule }} # 58同城
PROCESS-NAME,com.wutong.android,{{ rule }} # 物通网配货车主版
PROCESS-NAME,com.xcar.activity,{{ rule }} # 爱卡汽车
PROCESS-NAME,com.xdf.recite,{{ rule }} # 新东方乐词
PROCESS-NAME,com.xdtech.news.greatriver,{{ rule }} # 江西新闻
PROCESS-NAME,com.xes.jazhanghui.activity,{{ rule }} # 学而思
PROCESS-NAME,com.xfplay.play,{{ rule }} # 影音先锋
PROCESS-NAME,com.xfzd.client,{{ rule }} # AA出行
PROCESS-NAME,com.xiachufang,{{ rule }} # 下厨房
PROCESS-NAME,com.xiangha,{{ rule }} # 香哈菜谱
PROCESS-NAME,com.xianqing.driving3d,{{ rule }} # 驾考模拟3D
PROCESS-NAME,com.xiaobanlong.main,{{ rule }} # 小伴龙
PROCESS-NAME,com.xiaodao.jiemeng,{{ rule }} # 复真书法
PROCESS-NAME,com.xiaoenai.app,{{ rule }} # 小恩爱
PROCESS-NAME,com.xiaomi.gamecenter.sdk.service,{{ rule }} # 游戏服务
PROCESS-NAME,com.xiaomi.router,{{ rule }} # 小米WiFi
PROCESS-NAME,com.xiaomi.shop,{{ rule }} # 小米商城
PROCESS-NAME,com.ximalaya.ting.android,{{ rule }} # 喜马拉雅
PROCESS-NAME,com.xingyuanma.tangsengenglish,{{ rule }} # 唐僧英语
PROCESS-NAME,com.xinhang.mobileclient,{{ rule }} # 中国移动河南
PROCESS-NAME,com.xinli.fm,{{ rule }} # 心理Fm
PROCESS-NAME,com.xinyu210.enchdictionary,{{ rule }} # 英汉词典
PROCESS-NAME,com.xtuone.android.syllabus,{{ rule }} # 超级课程表
PROCESS-NAME,com.xueqiu.android,{{ rule }} # 雪球
PROCESS-NAME,com.xunlei.downloadprovider,{{ rule }} # 迅雷
PROCESS-NAME,com.xvideostudio.videoeditor,{{ rule }} # 乐秀视频剪辑视频编辑
PROCESS-NAME,com.yaochufa.app,{{ rule }} # 要出发周边游
PROCESS-NAME,com.yaoo.qlauncher,{{ rule }} # 如意老人桌面
PROCESS-NAME,com.yaya.zone,{{ rule }} # 叮咚买菜
PROCESS-NAME,com.yeahka.mach.android.openpos,{{ rule }} # 乐刷商务版
PROCESS-NAME,com.yek.android.game5173,{{ rule }} # 5173
PROCESS-NAME,com.yek.android.kfc.activitys,{{ rule }} # 肯德基
PROCESS-NAME,com.yek.android.uniqlo,{{ rule }} # 优衣库
PROCESS-NAME,com.yelong.baobaoshipu,{{ rule }} # 宝宝食谱
PROCESS-NAME,com.yelong.caipudaquan,{{ rule }} # 菜谱大全
PROCESS-NAME,com.yelong.safeperiod,{{ rule }} # 安全期
PROCESS-NAME,com.yelong.zhongyaodaquan,{{ rule }} # 中药大全
PROCESS-NAME,com.ygkj.chelaile.standard,{{ rule }} # 车来了
PROCESS-NAME,com.yibasan.lizhifm,{{ rule }} # 荔枝
PROCESS-NAME,com.yiche.autoeasy,{{ rule }} # 易车
PROCESS-NAME,com.yiche.price,{{ rule }} # 易车汽车报价
PROCESS-NAME,com.yihu.medical,{{ rule }} # 健康之路
PROCESS-NAME,com.yingsoft.ksbao.Activity,{{ rule }} # 考试宝典
PROCESS-NAME,com.yipiao,{{ rule }} # 智行火车票
PROCESS-NAME,com.yitong.mbank,{{ rule }} # 江苏·农商行
PROCESS-NAME,com.yiwang,{{ rule }} # 1药网
PROCESS-NAME,com.yiwugou.yiwukan,{{ rule }} # 义乌购
PROCESS-NAME,com.yixia.videoeditor,{{ rule }} # 秒拍
PROCESS-NAME,com.ylmf.androidclient,{{ rule }} # 115生活
PROCESS-NAME,com.ymatou.seller,{{ rule }} # 洋码头扫货神器买手版
PROCESS-NAME,com.ymatou.shop,{{ rule }} # 洋码头
PROCESS-NAME,com.yoho,{{ rule }} # Yoho!Buy有货
PROCESS-NAME,com.yoloho.dayima,{{ rule }} # 大姨妈
PROCESS-NAME,com.youba.barcode,{{ rule }} # 二维码扫描
PROCESS-NAME,com.youdao.dict,{{ rule }} # 网易有道词典
PROCESS-NAME,com.youdao.note,{{ rule }} # 有道云笔记
PROCESS-NAME,com.youdao.translator,{{ rule }} # 有道翻译官
PROCESS-NAME,com.yougou,{{ rule }} # 优购时尚商城
PROCESS-NAME,com.youinputmeread,{{ rule }} # 朗读大师
PROCESS-NAME,com.youku.phone,{{ rule }} # 优酷视频
PROCESS-NAME,com.youloft.calendar,{{ rule }} # 万年历
PROCESS-NAME,com.youxiang.soyoungapp,{{ rule }} # 新氧医美
PROCESS-NAME,com.yto.client.activity,{{ rule }} # 圆通速递
PROCESS-NAME,com.yuedong.browser,{{ rule }} # 悦动浏览器
PROCESS-NAME,com.yulore.yellowpage,{{ rule }} # 电话邦
PROCESS-NAME,com.yumei.game.engine.ui.client,{{ rule }} # 玩股成金
PROCESS-NAME,com.yunda.app,{{ rule }} # 韵达快递
PROCESS-NAME,com.yunlian.wewe,{{ rule }} # 微微网络电话
PROCESS-NAME,com.yunnfc.writer,{{ rule }} # NFC读写器
PROCESS-NAME,com.yx,{{ rule }} # 有信
PROCESS-NAME,com.yy.android.udbsec,{{ rule }} # YY安全中心
PROCESS-NAME,com.yy.huanju,{{ rule }} # Hello
PROCESS-NAME,com.zbx.ct.tvzhibo,{{ rule }} # 手机电视高清直播
PROCESS-NAME,com.zh.carbyticket,{{ rule }} # 团子出行
PROCESS-NAME,com.zhangdan.app,{{ rule }} # 51信用卡管家
PROCESS-NAME,com.zhaopin.social,{{ rule }} # 智联招聘
PROCESS-NAME,com.zhenai.android,{{ rule }} # 珍爱
PROCESS-NAME,com.zhihu.android,{{ rule }} # 知乎
PROCESS-NAME,com.zhihu.daily.android,{{ rule }} # 知乎日报
PROCESS-NAME,com.zhubajie.client,{{ rule }} # 猪八戒
PROCESS-NAME,com.ziipin.homeinn,{{ rule }} # 首旅如家
PROCESS-NAME,com.ziipin.softkeyboard,{{ rule }} # Badam维语输入法
PROCESS-NAME,com.zjrc.yygh,{{ rule }} # 浙江预约挂号
PROCESS-NAME,com.zjw.chehang168,{{ rule }} # 车行168
PROCESS-NAME,com.zol.android,{{ rule }} # 中关村在线
PROCESS-NAME,com.zongheng.reader,{{ rule }} # 纵横小说
PROCESS-NAME,com.zuzuChe,{{ rule }} # 租租车
PROCESS-NAME,com.zving.ipmph.app,{{ rule }} # 医考学堂
PROCESS-NAME,com.ZWSoft.ZWCAD,{{ rule }} # CAD看图大师
PROCESS-NAME,com.zydsoft.acuherb,{{ rule }} # 中医辨证云
PROCESS-NAME,com.zzu.sxm.chemical,{{ rule }} # 化学方程式
PROCESS-NAME,ctrip.android.view,{{ rule }} # 携程旅行
PROCESS-NAME,cuuca.sendfiles.Activity,{{ rule }} # 备份助手
PROCESS-NAME,doctorjob.com.cn,{{ rule }} # 医疗人才网
PROCESS-NAME,dongzheng.szkingdom.android.phone,{{ rule }} # 掌证宝
PROCESS-NAME,droom.sleepIfUCan,{{ rule }} # 使命闹钟Alarmy
PROCESS-NAME,dxwt.questionnaire.ui,{{ rule }} # 10000社区
PROCESS-NAME,epson.print,{{ rule }} # Epson iPrint
PROCESS-NAME,et.song.remotestar,{{ rule }} # 遥控之星
PROCESS-NAME,flipboard.cn,{{ rule }} # 红板报
PROCESS-NAME,fm.qingting.qtradio,{{ rule }} # 蜻蜓FM
PROCESS-NAME,gov.pianzong.androidnga,{{ rule }} # NGA玩家社区
PROCESS-NAME,gz.aas.calc2yi,{{ rule }} # 易爻
PROCESS-NAME,gz.aas.calc8words,{{ rule }} # 論八字
PROCESS-NAME,hotcard.doc.reader,{{ rule }} # 文档识别
PROCESS-NAME,howbuy.android.palmfund,{{ rule }} # 好买基金
PROCESS-NAME,howbuy.android.piggy,{{ rule }} # 储蓄罐
PROCESS-NAME,hugh.android.app.zidianadd,{{ rule }} # 新华字典补丁
PROCESS-NAME,icelamp.ConverCnToPinyin,{{ rule }} # 汉字转拼音
PROCESS-NAME,im.xingzhe,{{ rule }} # 行者
PROCESS-NAME,im.yixin,{{ rule }} # 易信
PROCESS-NAME,imoblife.brainwavestus,{{ rule }} # 神奇脑波
PROCESS-NAME,insigma.waybook.jinan,{{ rule }} # 369出行
PROCESS-NAME,jp.ne.neko.freewing.JapaneseKeyboard,{{ rule }} # 简易的日语输入 日文输入法 五十音图 虚拟键盘方式
PROCESS-NAME,jp.ne.neko.freewing.OpenWnn136Plus,{{ rule }} # 日文輸入法 OpenWnn136加强版
PROCESS-NAME,jp.ne.neko.freewing.PinYinImePlus,{{ rule }} # 中文拼音输入法 加强版
PROCESS-NAME,jyeoo.app.ystudy,{{ rule }} # 菁优网
PROCESS-NAME,lexue.mryyyd,{{ rule }} # 每日英语阅读
PROCESS-NAME,lf.example.wubi,{{ rule }} # 五笔反查
PROCESS-NAME,longbin.helloworld,{{ rule }} # 计算管家
PROCESS-NAME,luo.speedometergps,{{ rule }} # GPS仪表盘
PROCESS-NAME,mail139.launcher,{{ rule }} # 139邮箱轻量版
PROCESS-NAME,me.chunyu.ChunyuDoctor,{{ rule }} # 春雨医生
PROCESS-NAME,me.ele,{{ rule }} # 淘宝闪购
PROCESS-NAME,me.iweek.rili,{{ rule }} # 生活日历
PROCESS-NAME,me.iweek.wannianli,{{ rule }} # 小枣万年历
PROCESS-NAME,me.suncloud.marrymemo,{{ rule }} # 婚礼纪
PROCESS-NAME,mobi.w3studio.apps.android.shsmy.phone,{{ rule }} # 随申办市民云
PROCESS-NAME,my.beautyCamera,{{ rule }} # 美人相机
PROCESS-NAME,net.ask123.mima96,{{ rule }} # 密码酷
PROCESS-NAME,net.bontec.wxqd.activity,{{ rule }} # 爱青岛
PROCESS-NAME,net.cmoaciopm.sgsdict,{{ rule }} # 三国杀大典
PROCESS-NAME,net.kdnet.club,{{ rule }} # 凯迪网
PROCESS-NAME,net.qihoo.launcher.widget.clockweather,{{ rule }} # 360天气
PROCESS-NAME,net.unitepower.zhitong,{{ rule }} # 智通直聘
PROCESS-NAME,net.xinhuamm.mainclient,{{ rule }} # 新华社
PROCESS-NAME,oms.mmc.app.almanac_inland,{{ rule }} # 老黄历万年历顺历
PROCESS-NAME,oms.mmc.fortunetelling,{{ rule }} # 灵机
PROCESS-NAME,oms.mmc.fortunetelling.fate.ziwei,{{ rule }} # 灵动紫微
PROCESS-NAME,oms.mmc.fortunetelling.measuringtools.naming,{{ rule }} # 诗词起名
PROCESS-NAME,one.hh.oneclient,{{ rule }} # 一个
PROCESS-NAME,org.ccc.aa,{{ rule }} # 考勤助手
PROCESS-NAME,org.ccc.mm,{{ rule }} # 高效备忘录
PROCESS-NAME,org.ccc.tl,{{ rule }} # 高效待办清单
PROCESS-NAME,org.fungo.fungolive,{{ rule }} # 天天电视直播
PROCESS-NAME,org.moegirl.moegirlview,{{ rule }} # 萌娘百科
PROCESS-NAME,org.sojex.finance,{{ rule }} # 口袋贵金属
PROCESS-NAME,org.zywx.wbpalmstar.widgetone.uex10075364,{{ rule }} # 经管之家
PROCESS-NAME,pinkdiary.xiaoxiaotu.com,{{ rule }} # 粉粉日记
PROCESS-NAME,predictor.namer,{{ rule }} # 宝宝取名起名
PROCESS-NAME,predictor.ui,{{ rule }} # 灵占算命八字星座
PROCESS-NAME,qianlong.qlmobile,{{ rule }} # 钱龙
PROCESS-NAME,rocket.vehiclemgr.android.obd2,{{ rule }} # 车况检测大师
PROCESS-NAME,shanks.scgl,{{ rule }} # 诗词格律
PROCESS-NAME,shufa.cn,{{ rule }} # 书法辞典
PROCESS-NAME,sina.mobile.tianqitong,{{ rule }} # 天气通
PROCESS-NAME,sl.mySms,{{ rule }} # Q信
PROCESS-NAME,smskb.com,{{ rule }} # 盛名时刻表
PROCESS-NAME,sogou.mobile.explorer,{{ rule }} # 搜狗浏览器极速版
PROCESS-NAME,sr.daiv.alls.de,{{ rule }} # 基础德语口语
PROCESS-NAME,sr.daiv.alls.es,{{ rule }} # 基础西班牙语口语
PROCESS-NAME,sr.daiv.alls.fr,{{ rule }} # 基础法语口语
PROCESS-NAME,sr.daiv.alls.it,{{ rule }} # 基础意大利语口语
PROCESS-NAME,sr.daiv.alls.ja,{{ rule }} # 基础日语口语
PROCESS-NAME,sr.daiv.alls.ko,{{ rule }} # 基础韩语口语
PROCESS-NAME,ts.NetTraffic,{{ rule }} # 网速流量监测
PROCESS-NAME,tv.acfundanmaku.video,{{ rule }} # AcFun
PROCESS-NAME,tv.danmaku.bili,{{ rule }} # 哔哩哔哩
PROCESS-NAME,tv.pps.mobile,{{ rule }} # 爱奇艺随刻
PROCESS-NAME,vstc.vscam.client,{{ rule }} # Eye4
PROCESS-NAME,vStudio.Android.Camera360,{{ rule }} # 相机360
PROCESS-NAME,vz.com,{{ rule }} # 飞常准
PROCESS-NAME,wind.deposit,{{ rule }} # 万得基金
PROCESS-NAME,windinfo.android,{{ rule }} # Wind金融终端
PROCESS-NAME,yiqi.bazi,{{ rule }} # 易奇文化
PROCESS-NAME,ysykzheng.hotlauncher,{{ rule }} # 热门启动器
PROCESS-NAME,zjdf.zhaogongzuo,{{ rule }} # 最佳东方
{% endmacro %}